// 200 questions about admin.lume.uz (LUME Admin System).
// Each question has bilingual text (RU/UZ), 3-4 answer options, the index of
// the correct option, and an optional screenshot path (under /public/screenshots).
//
// The questions intentionally cover both surface-level UI knowledge (where
// things live, what colours/icons sections use) and deeper, more specific
// behavioural facts (KPIs shown on a page, columns in a table, the URL
// segment used by a section, what each section is for, etc.).

export type Question = {
  id: number;
  // category for analytics / future filters
  cat: string;
  // path to screenshot inside /public (omit leading slash)
  shot?: string;
  ru: { q: string; opts: string[] };
  uz: { q: string; opts: string[] };
  correct: number; // index 0..opts.length-1
};

// Helper to keep declaration tidy
const q = (
  id: number,
  cat: string,
  shot: string | undefined,
  ru: { q: string; opts: string[] },
  uz: { q: string; opts: string[] },
  correct: number,
): Question => ({ id, cat, shot, ru, uz, correct });

export const QUESTIONS: Question[] = [
  // ─────────────────────────  GENERAL / DASHBOARD  ─────────────────────────
  q(1, 'general', 'screenshots/dashboard.png',
    { q: 'Как называется система, скриншот которой показан?', opts: ['LUME ADMIN SYSTEM', 'Lume POS', 'Lume Cloud', 'Lume CRM'] },
    { q: 'Skrinshotda ko‘rsatilgan tizim nomi nima?', opts: ['LUME ADMIN SYSTEM', 'Lume POS', 'Lume Cloud', 'Lume CRM'] }, 0),
  q(2, 'general', 'screenshots/dashboard.png',
    { q: 'Сколько основных разделов в боковом меню?', opts: ['5', '6', '7', '8'] },
    { q: 'Yon menyuda nechta asosiy bo‘lim bor?', opts: ['5', '6', '7', '8'] }, 2),
  q(3, 'general', 'screenshots/dashboard.png',
    { q: 'Какой раздел подсвечен синим (активен) в боковом меню по умолчанию?', opts: ['Кабинет', 'Главная', 'Отчеты', 'Настройки'] },
    { q: 'Yon menyuda boshlanishida qaysi bo‘lim ko‘k rangda (faol) ko‘rinadi?', opts: ['Kabinet', 'Bosh sahifa (Главная)', 'Hisobotlar', 'Sozlamalar'] }, 1),
  q(4, 'general', 'screenshots/dashboard.png',
    { q: 'Какая сумма отображается на зелёной кнопке внизу левой панели?', opts: ['749 700 UZS', '500 000 UZS', '1 000 000 UZS', '102 000 000 UZS'] },
    { q: 'Chap panelning pastki qismidagi yashil tugmada qancha summa ko‘rsatilgan?', opts: ['749 700 UZS', '500 000 UZS', '1 000 000 UZS', '102 000 000 UZS'] }, 0),
  q(5, 'general', 'screenshots/dashboard.png',
    { q: 'Как назван первый блок разделов на главной?', opts: ['Меню', 'Старт', 'Начало работы', 'Главное'] },
    { q: 'Bosh sahifadagi birinchi bo‘limlar bloki qanday nomlangan?', opts: ['Menyu', 'Start', 'Начало работы (Ish boshlash)', 'Asosiy'] }, 2),
  q(6, 'general', 'screenshots/dashboard.png',
    { q: 'Какой логин (email) использовался при тестировании системы LUME?', opts: ['admin@lume.uz', 'point@indev.uz', 'test@lume.uz', 'demo@lume.uz'] },
    { q: 'LUME tizimini sinash uchun qaysi login (email) ishlatilgan?', opts: ['admin@lume.uz', 'point@indev.uz', 'test@lume.uz', 'demo@lume.uz'] }, 1),
  q(7, 'general', 'screenshots/dashboard.png',
    { q: 'Как называется пользователь под аватаром в левой панели?', opts: ['Admin User', 'Vendor User', 'Test User', 'Owner'] },
    { q: 'Chap paneldagi avatar ostidagi foydalanuvchi nomi qanday?', opts: ['Admin User', 'Vendor User', 'Test User', 'Owner'] }, 1),
  q(8, 'general', 'screenshots/dashboard.png',
    { q: 'Какой ID/номер пользователя показан под именем Vendor User?', opts: ['100000000', '990123456', '777771668', '909118811'] },
    { q: 'Vendor User ismi ostida qaysi ID/raqam ko‘rsatilgan?', opts: ['100000000', '990123456', '777771668', '909118811'] }, 1),
  q(9, 'general', 'screenshots/dashboard.png',
    { q: 'Сколько крупных групп карточек на дашборде (Главная)?', opts: ['4', '5', '6', '7'] },
    { q: 'Bosh sahifadagi kartalar guruhlari soni nechta?', opts: ['4', '5', '6', '7'] }, 2),
  q(10, 'general', 'screenshots/dashboard.png',
    { q: 'Какой стиль у цветовой схемы LUME в шапке?', opts: ['Чёрный + жёлтый', 'Тёмно-синий + белый', 'Красный + серый', 'Зелёный + чёрный'] },
    { q: 'LUME ning yuqori paneldagi rang sxemasi qanday?', opts: ['Qora + sariq', 'To‘q ko‘k + oq', 'Qizil + kulrang', 'Yashil + qora'] }, 1),

  // ──────────────────────────  СКЛАДСКИЕ ОПЕРАЦИИ  ──────────────────────────
  q(11, 'warehouse', 'screenshots/products.png',
    { q: 'Какая надпись на синей кнопке в правом верхнем углу страницы «Товары»?', opts: ['Создать', 'Добавить товар', 'Импорт', 'Новый товар'] },
    { q: '«Товары» sahifasining yuqori o‘ng burchagidagi ko‘k tugmadagi yozuv qanday?', opts: ['Yaratish', '+ Добавить товар (Mahsulot qo‘shish)', 'Import', 'Yangi mahsulot'] }, 1),
  q(12, 'warehouse', 'screenshots/products.png',
    { q: 'Сколько KPI-блоков сверху страницы «Товары» (Количество, Себестоимость и т.д.)?', opts: ['2', '3', '4', '5'] },
    { q: '«Mahsulotlar» sahifasi yuqorisida nechta KPI-blok bor (Miqdor, Tannarx va h.k.)?', opts: ['2', '3', '4', '5'] }, 2),
  q(13, 'warehouse', 'screenshots/products.png',
    { q: 'Какая цена продажи у товара Printer на скриншоте?', opts: ['250 000 UZS', '500 000 UZS', '330 000 UZS', '9 000 UZS'] },
    { q: 'Skrinshotdagi Printer mahsulotining sotuv narxi qancha?', opts: ['250 000 UZS', '500 000 UZS', '330 000 UZS', '9 000 UZS'] }, 1),
  q(14, 'warehouse', 'screenshots/products.png',
    { q: 'Какой плейсхолдер у поиска на странице товаров?', opts: ['«Поиск товара»', '«Что вы ищете "F4"»', '«Введите название»', '«Поиск...»'] },
    { q: 'Mahsulotlar sahifasidagi qidiruvning placeholder’i qanday?', opts: ['«Tovar qidirish»', '«Что вы ищете "F4"»', '«Nomini kiriting»', '«Поиск...»'] }, 1),
  q(15, 'warehouse', 'screenshots/products.png',
    { q: 'Какие колонки в таблице товаров (по порядку слева направо)?', opts: ['№, Цена, Остаток, Дата', '№, Наименование товара, Остаток, Себестоимость, Цена продажи', 'Код, Название, Цена', '№, Категория, Бренд, Цена'] },
    { q: 'Mahsulotlar jadvalida qaysi ustunlar (chapdan o‘ngga)?', opts: ['№, Narx, Qoldiq, Sana', '№, Tovar nomi, Qoldiq, Tannarx, Sotuv narxi', 'Kod, Nomi, Narx', '№, Kategoriya, Brend, Narx'] }, 1),
  q(16, 'warehouse', 'screenshots/products.png',
    { q: 'Что обозначает строка с красным фоном в списке товаров?', opts: ['Дорогой товар', 'Товар на распродаже', 'Отрицательный/проблемный остаток', 'Товар-новинка'] },
    { q: 'Mahsulotlar ro‘yxatidagi qizil fonli qator nimani anglatadi?', opts: ['Qimmat mahsulot', 'Aksiyadagi mahsulot', 'Manfiy/muammoli qoldiq', 'Yangi mahsulot'] }, 2),
  q(17, 'warehouse', 'screenshots/receipt.png',
    { q: 'Что оформляется на странице «Приход»?', opts: ['Возврат товара клиенту', 'Поступление товаров от поставщиков', 'Списание товаров', 'Перемещение между складами'] },
    { q: '«Приход» sahifasida nima rasmiylashtiriladi?', opts: ['Mijozga qaytarish', 'Yetkazib beruvchidan tovar qabul qilish', 'Hisobdan chiqarish', 'Omborlar orasida ko‘chirish'] }, 1),
  q(18, 'warehouse', 'screenshots/receipt_return.png',
    { q: 'Что делает раздел «Возврат прихода»?', opts: ['Возврат товара поставщикам', 'Возврат от клиента', 'Возврат денег на карту', 'Удаление прихода'] },
    { q: '«Возврат прихода» bo‘limi nima qiladi?', opts: ['Tovarlarni yetkazib beruvchiga qaytarish', 'Mijozdan qaytarish', 'Kartaga pulni qaytarish', 'Kirimni o‘chirish'] }, 0),
  q(19, 'warehouse', 'screenshots/transfer.png',
    { q: 'Что такое «Трансфер» в LUME Admin?', opts: ['Перевод денег', 'Перемещение товаров между складами и торговыми точками', 'Оплата картой', 'Отправка SMS'] },
    { q: 'LUME Admin’dagi «Transfer» nima?', opts: ['Pul o‘tkazmasi', 'Tovarlarni omborlar va savdo nuqtalari orasida ko‘chirish', 'Karta orqali to‘lov', 'SMS yuborish'] }, 1),
  q(20, 'warehouse', 'screenshots/realization.png',
    { q: 'Раздел «Реализация» предназначен для…', opts: ['Создание акций', 'Реализация (отгрузка/продажа) товаров', 'Возврат товаров', 'Печать ценников'] },
    { q: '«Реализация» bo‘limi … uchun mo‘ljallangan', opts: ['Aksiyalar yaratish', 'Tovarlarni realizatsiya qilish (jo‘natish/sotish)', 'Tovarni qaytarish', 'Narx yorliqlarini chop etish'] }, 1),
  q(21, 'warehouse', 'screenshots/reprice.png',
    { q: 'Что делает «Переоценка»?', opts: ['Печатает чеки', 'Массово изменяет цены на товары', 'Меняет валюту', 'Меняет курс UZS'] },
    { q: '«Переоценка» nima qiladi?', opts: ['Cheklar chop etadi', 'Tovarlarning narxlarini ommaviy o‘zgartiradi', 'Valyutani almashtiradi', 'UZS kursini o‘zgartiradi'] }, 1),
  q(22, 'warehouse', 'screenshots/inventory.png',
    { q: 'Что делает «Инвентаризация»?', opts: ['Сверяет фактическое наличие с учётными данными', 'Считает зарплату', 'Создает прайс-листы', 'Делает копии чеков'] },
    { q: '«Инвентаризация» nimani amalga oshiradi?', opts: ['Haqiqiy mavjudlikni hisob ma’lumotlari bilan solishtiradi', 'Oylik maoshni hisoblaydi', 'Narxlar ro‘yxatini yaratadi', 'Cheklar nusxasini chiqaradi'] }, 0),
  q(23, 'warehouse', 'screenshots/writeoff.png',
    { q: 'Что делает раздел «Списание»?', opts: ['Создаёт скидки', 'Удаляет испорченные или списанные товары', 'Удаляет пользователей', 'Печатает ценники'] },
    { q: '«Списание» bo‘limi nima qiladi?', opts: ['Chegirmalar yaratadi', 'Buzilgan yoki hisobdan chiqarilgan tovarlarni o‘chiradi', 'Foydalanuvchilarni o‘chiradi', 'Narx yorliqlarini chop etadi'] }, 1),
  q(24, 'warehouse', 'screenshots/grouping.png',
    { q: 'Что такое «Группировка» в складских операциях?', opts: ['Создание категорий', 'Объединение позиций для упрощения анализа', 'Группировка чеков', 'Группировка пользователей'] },
    { q: 'Ombor amallaridagi «Группировка» nima?', opts: ['Kategoriyalar yaratish', 'Tahlilni soddalashtirish uchun pozitsiyalarni birlashtirish', 'Cheklar guruhi', 'Foydalanuvchilarni guruhlash'] }, 1),
  q(25, 'warehouse', 'screenshots/weighted_products.png',
    { q: 'Раздел «Весовые товары» — для чего?', opts: ['Учёт и продажа товаров, реализуемых по весу', 'Печать наклеек', 'Доставка товара', 'Уценка товаров'] },
    { q: '«Весовые товары» bo‘limi nima uchun?', opts: ['Vaznga sotiladigan tovarlarni hisobga olish va sotish', 'Stikerlarni chop etish', 'Tovar yetkazib berish', 'Tovarlarni arzonlashtirish'] }, 0),
  q(26, 'warehouse', 'screenshots/import_products.png',
    { q: 'Что делает «Импорт товаров»?', opts: ['Создаёт акции', 'Загружает и обновляет данные из файлов или систем', 'Печатает ценники', 'Импортирует клиентов'] },
    { q: '«Импорт товаров» nima qiladi?', opts: ['Aksiyalar yaratadi', 'Fayllar yoki tizimlardan ma’lumotlarni yuklab oladi va yangilaydi', 'Narx yorliqlarini chop etadi', 'Mijozlarni import qiladi'] }, 1),
  q(27, 'warehouse', 'screenshots/tech_cards.png',
    { q: 'За что отвечают «Техкарты»?', opts: ['Печать чеков', 'Состав рецептур и калькуляция себестоимости', 'Доставка', 'Зарплата'] },
    { q: '«Техкарты» nimaga javob beradi?', opts: ['Cheklar chop etish', 'Retseptlar tarkibi va tannarx kalkulyatsiyasi', 'Yetkazib berish', 'Maosh'] }, 1),
  q(28, 'warehouse', 'screenshots/manufacturing_act.png',
    { q: 'Что фиксирует «Акт изготовления»?', opts: ['Возврат брака', 'Выпуск готовой продукции', 'Продажу', 'Поступление сырья'] },
    { q: '«Акт изготовления» nimani qayd etadi?', opts: ['Brak qaytarilishi', 'Tayyor mahsulot ishlab chiqarilishi', 'Sotuv', 'Xomashyo kirimi'] }, 1),
  q(29, 'warehouse', 'screenshots/favorite_products.png',
    { q: '«Избранные товары» позволяют…', opts: ['Скрывать товары', 'Выбирать и сохранять важные товары', 'Удалять товары', 'Снижать цены'] },
    { q: '«Избранные товары» qanday imkoniyat beradi?', opts: ['Tovarlarni yashirish', 'Muhim tovarlarni tanlash va saqlash', 'Tovarlarni o‘chirish', 'Narxlarni pasaytirish'] }, 1),
  q(30, 'warehouse', 'screenshots/products.png',
    { q: 'На скриншоте «Товары» какой суммарный показатель «Цена продажи»?', opts: ['-2 297 000.00 UZS', '-187 000.00 UZS', '0 UZS', '500 000 UZS'] },
    { q: 'Skrinshotdagi «Tovarlar» da umumiy «Sotuv narxi» qancha?', opts: ['-2 297 000.00 UZS', '-187 000.00 UZS', '0 UZS', '500 000 UZS'] }, 0),

  // ──────────────────────────  СПРАВОЧНИК  ──────────────────────────
  q(31, 'reference', 'screenshots/personnel.png',
    { q: 'Раздел «Персонал» нужен для…', opts: ['Учёта оборудования', 'Эффективного управления сотрудниками', 'Учёта поставщиков', 'Учёта клиентов'] },
    { q: '«Персонал» bo‘limi nima uchun?', opts: ['Uskunalar hisobi', 'Xodimlarni samarali boshqarish', 'Yetkazib beruvchilar hisobi', 'Mijozlar hisobi'] }, 1),
  q(32, 'reference', 'screenshots/drivers.png',
    { q: 'Где в системе ведётся учёт водителей?', opts: ['В «Персонал»', 'В «Водители»', 'В «Контрагенты»', 'В «Кабинет»'] },
    { q: 'Tizimda haydovchilar hisobi qayerda yuritiladi?', opts: ['«Персонал» da', '«Водители» da', '«Контрагенты» da', '«Кабинет» da'] }, 1),
  q(33, 'reference', 'screenshots/shifts.png',
    { q: 'Раздел «Смены» предназначен для…', opts: ['Контроля и ведения рабочих смен', 'Учёта товаров', 'Печати чеков', 'СМС-рассылки'] },
    { q: '«Смены» bo‘limi nima uchun?', opts: ['Ish smenalarini nazorat qilish va yuritish', 'Tovarlar hisobi', 'Cheklar chop etish', 'SMS yuborish'] }, 0),
  q(34, 'reference', 'screenshots/z_reports.png',
    { q: 'Что такое Z-отчёты в LUME?', opts: ['Отчёты, отправленные в ОФД', 'Отчёты по зарплате', 'Отчёты по складу', 'Отчёты по клиентам'] },
    { q: 'LUME’dagi Z-hisobotlar nima?', opts: ['OFD ga yuborilgan barcha hisobotlar haqida ma’lumot', 'Maosh hisobotlari', 'Ombor hisobotlari', 'Mijoz hisobotlari'] }, 0),
  q(35, 'reference', 'screenshots/print_pricetags.png',
    { q: '«Печать ценников» — это…', opts: ['Печать чеков', 'Быстрая генерация и печать ценников', 'Печать ярлыков сотрудников', 'Печать накладных'] },
    { q: '«Печать ценников» nima?', opts: ['Cheklar chop etish', 'Narx yorliqlarini tezkor yaratish va chop etish', 'Xodim badjlarini chop etish', 'Yo‘l varaqalarini chop etish'] }, 1),
  q(36, 'reference', 'screenshots/clients.png',
    { q: 'Сколько клиентов отображается в верхнем счётчике на скрине «Клиенты»?', opts: ['11', '23', '33', '50'] },
    { q: '«Клиенты» skrinshotidagi yuqori hisoblagichda nechta mijoz ko‘rsatilgan?', opts: ['11', '23', '33', '50'] }, 2),
  q(37, 'reference', 'screenshots/clients.png',
    { q: 'Какая «Сумма оплаты» показана на скриншоте «Клиенты»?', opts: ['613 500 UZS', '102 009 428 UZS', '4 867 000 UZS', '28 350 UZS'] },
    { q: '«Mijozlar» skrinshotidagi «To‘lov summasi» qancha?', opts: ['613 500 UZS', '102 009 428 UZS', '4 867 000 UZS', '28 350 UZS'] }, 1),
  q(38, 'reference', 'screenshots/clients.png',
    { q: 'Какие колонки видны в таблице «Клиенты»?', opts: ['№, Имя, Телефон, Количество, Сумма покупок, Дата регистрации, Текущий долг', '№, Имя, Адрес, Телефон', 'Имя, e-mail, адрес', 'Имя, Долг, Скидка'] },
    { q: '«Mijozlar» jadvalida qaysi ustunlar ko‘rinadi?', opts: ['№, Ism, Telefon, Miqdor, Xaridlar summasi, Ro‘yxatdan o‘tgan sana, Joriy qarz', '№, Ism, Manzil, Telefon', 'Ism, e-mail, manzil', 'Ism, Qarz, Chegirma'] }, 0),
  q(39, 'reference', 'screenshots/clients.png',
    { q: 'Какая «Сумма долга» по клиентам?', opts: ['0 UZS', '613 500 UZS', '4 867 000 UZS', '102 009 428 UZS'] },
    { q: 'Mijozlar bo‘yicha «Сумма долга» (qarz summasi) qancha?', opts: ['0 UZS', '613 500 UZS', '4 867 000 UZS', '102 009 428 UZS'] }, 1),
  q(40, 'reference', 'screenshots/clients.png',
    { q: 'Как зовут первого клиента в таблице?', opts: ['Suxrob', 'Aslan', 'Mirali', 'Shaxzod'] },
    { q: 'Jadvaldagi birinchi mijozning ismi qanday?', opts: ['Suxrob', 'Aslan', 'Mirali', 'Shaxzod'] }, 1),
  q(41, 'reference', 'screenshots/loyalty.png',
    { q: 'Что делает раздел «Лояльность»?', opts: ['Отправляет SMS', 'Настраивает программы поощрения постоянных клиентов', 'Считает зарплату', 'Меняет цены'] },
    { q: '«Лояльность» bo‘limi nima qiladi?', opts: ['SMS yuboradi', 'Doimiy mijozlarni rag‘batlantirish dasturlarini sozlaydi', 'Maosh hisoblaydi', 'Narxlarni o‘zgartiradi'] }, 1),
  q(42, 'reference', 'screenshots/contractors.png',
    { q: '«Контрагенты» — это учёт…', opts: ['Поставщиков, партнёров и организаций', 'Только клиентов', 'Сотрудников', 'Кассиров'] },
    { q: '«Контрагенты» kimlarni hisobga oladi?', opts: ['Yetkazib beruvchilar, hamkorlar va tashkilotlar', 'Faqat mijozlar', 'Xodimlar', 'Kassirlar'] }, 0),
  q(43, 'reference', 'screenshots/sms_blast.png',
    { q: 'Что такое «СМС рассылка»?', opts: ['Печать чеков', 'Массовая отправка клиентских смс-сообщений', 'Создание пользователей', 'Импорт товаров'] },
    { q: '«СМС рассылка» nima?', opts: ['Cheklar chop etish', 'Mijozlarga ommaviy SMS yuborish', 'Foydalanuvchilar yaratish', 'Mahsulot import qilish'] }, 1),
  q(44, 'reference', 'screenshots/sms_templates.png',
    { q: 'Где хранятся шаблоны SMS?', opts: ['В «Документы»', 'В «Шаблоны СМС»', 'В «СМС рассылка»', 'В «Параметры»'] },
    { q: 'SMS shablonlari qayerda saqlanadi?', opts: ['«Документы» da', '«Шаблоны СМС» da', '«СМС рассылка» da', '«Параметры» da'] }, 1),
  q(45, 'reference', 'screenshots/marking_audit.png',
    { q: 'Что проверяет «Аудит маркировок»?', opts: ['Качество фото', 'Точность и корректность маркировок', 'Зарплату', 'Налоги'] },
    { q: '«Аудит маркировок» nimani tekshiradi?', opts: ['Suratlar sifatini', 'Markirovkalarning aniqligi va to‘g‘riligini', 'Maoshni', 'Soliqlarni'] }, 1),
  q(46, 'reference', 'screenshots/edo.png',
    { q: 'Аббревиатура «ЭДО» в LUME означает…', opts: ['Эталон-доход', 'Электронный документооборот', 'Электронная декларация', 'Электронные деньги'] },
    { q: 'LUME’dagi «ЭДО» qisqartmasi nimani anglatadi?', opts: ['Etalon-daromad', 'Elektron hujjat aylanmasi', 'Elektron deklaratsiya', 'Elektron pul'] }, 1),
  q(47, 'reference', 'screenshots/promotions.png',
    { q: 'Что настраивается в разделе «Акции»?', opts: ['Скидочные кампании / возврат товаров клиентам или поставщикам', 'Создание чеков', 'Печать ценников', 'Импорт пользователей'] },
    { q: '«Акции» bo‘limida nima sozlanadi?', opts: ['Aksiya kampaniyalari / mijozlarga yoki yetkazib beruvchilarga qaytarish', 'Cheklar yaratish', 'Narx yorliqlarini chop etish', 'Foydalanuvchilarni import qilish'] }, 0),
  q(48, 'reference', 'screenshots/documents.png',
    { q: 'Раздел «Документы» нужен для…', opts: ['Хранения и работы с документами', 'Печати чеков', 'Печати ценников', 'Учёта товаров'] },
    { q: '«Документы» bo‘limi nima uchun?', opts: ['Hujjatlarni saqlash va ular bilan ishlash', 'Cheklar chop etish', 'Narx yorliqlarini chop etish', 'Tovarlar hisobi'] }, 0),
  q(49, 'reference', 'screenshots/clients.png',
    { q: 'Какой телефон у клиента «Aslan»?', opts: ['+998 909118811', '+998 777771668', '+998 944182882', '+998 901247931'] },
    { q: '«Aslan» mijozining telefoni qanday?', opts: ['+998 909118811', '+998 777771668', '+998 944182882', '+998 901247931'] }, 0),
  q(50, 'reference', 'screenshots/personnel.png',
    { q: 'Какая иконка использована для раздела «Персонал»?', opts: ['Корзина', 'Бейдж сотрудника', 'Машина', 'Календарь'] },
    { q: '«Персонал» bo‘limi uchun qanday belgi ishlatilgan?', opts: ['Savat', 'Xodim badji', 'Mashina', 'Kalendar'] }, 1),

  // ──────────────────────────  ФИНАНСОВЫЕ ОПЕРАЦИИ  ──────────────────────────
  q(51, 'finance', 'screenshots/sold_checks.png',
    { q: 'Что показывает раздел «Проданные чеки»?', opts: ['Список всех завершённых продаж', 'Список товаров', 'Список зарплат', 'Список клиентов'] },
    { q: '«Проданные чеки» bo‘limi nimani ko‘rsatadi?', opts: ['Yakunlangan sotuvlar ro‘yxati', 'Tovarlar ro‘yxati', 'Maoshlar ro‘yxati', 'Mijozlar ro‘yxati'] }, 0),
  q(52, 'finance', 'screenshots/check_returns.png',
    { q: 'Что обрабатывает «Возвраты чеков»?', opts: ['Возвраты по чекам клиентов', 'Возвраты от поставщиков', 'Скидки', 'Налоги'] },
    { q: '«Возвраты чеков» nima ustida ishlaydi?', opts: ['Mijoz cheklari bo‘yicha qaytarishlar', 'Yetkazib beruvchidan qaytarish', 'Chegirmalar', 'Soliqlar'] }, 0),
  q(53, 'finance', 'screenshots/deleted_checks.png',
    { q: '«Удалённые чеки» — это…', opts: ['Чеки в архиве', 'Чеки, в которых имеются удалённые товары', 'Заблокированные чеки', 'Возвращённые чеки'] },
    { q: '«Удалённые чеки» nima?', opts: ['Arxivdagi cheklar', 'O‘chirilgan tovarlar bo‘lgan cheklar', 'Bloklangan cheklar', 'Qaytarilgan cheklar'] }, 1),
  q(54, 'finance', 'screenshots/pending_checks.png',
    { q: '«Отложенные чеки» — это…', opts: ['Чеки прошедшие оплату', 'Сохранённые чеки, которые не прошли оплату', 'Чеки на возврат', 'Тестовые чеки'] },
    { q: '«Отложенные чеки» nima?', opts: ['To‘lov amalga oshirilgan cheklar', 'Saqlangan, lekin to‘lov o‘tmagan cheklar', 'Qaytarish cheklari', 'Sinov cheklari'] }, 1),
  q(55, 'finance', 'screenshots/mutual_settlements.png',
    { q: 'Что делает «Взаиморасчёт»?', opts: ['Контроль взаимных задолженностей и платежей', 'Печать чеков', 'СМС-рассылка', 'Зарплата'] },
    { q: '«Взаиморасчёт» nima qiladi?', opts: ['O‘zaro qarzlar va to‘lovlarni nazorat qilish', 'Cheklar chop etish', 'SMS yuborish', 'Maosh'] }, 0),
  q(56, 'finance', 'screenshots/accounts.png',
    { q: 'Раздел «Счета» — это…', opts: ['Создание, ведение и оплата счетов', 'Список товаров', 'Печать ценников', 'Журнал смен'] },
    { q: '«Счета» bo‘limi nima?', opts: ['Hisob-fakturalar yaratish, yuritish va to‘lash', 'Tovarlar ro‘yxati', 'Narx yorliqlarini chop etish', 'Smenalar jurnali'] }, 0),
  q(57, 'finance', 'screenshots/salary.png',
    { q: 'Раздел «Зарплата» предназначен для…', opts: ['Расчёта и управления выплатой зарплат', 'Учёта налогов', 'Печати чеков', 'Импорта товаров'] },
    { q: '«Зарплата» bo‘limi nima uchun?', opts: ['Maoshni hisoblash va to‘lashni boshqarish', 'Soliqlar hisobi', 'Cheklar chop etish', 'Tovar import qilish'] }, 0),
  q(58, 'finance', 'screenshots/sold_checks.png',
    { q: 'Раздел «Проданные чеки» относится к группе…', opts: ['Складские операции', 'Финансовые операции', 'Отчеты', 'Кабинет'] },
    { q: '«Проданные чеки» qaysi guruhga tegishli?', opts: ['Ombor amallari', 'Moliyaviy amallar', 'Hisobotlar', 'Kabinet'] }, 1),
  q(59, 'finance', 'screenshots/sold_checks.png',
    { q: 'Какой иконкой обозначен раздел «Проданные чеки»?', opts: ['Зелёная корзина', 'Коричневая корзина', 'Жёлтая стрелка', 'Синий человечек'] },
    { q: '«Проданные чеки» qanday belgi bilan ko‘rsatilgan?', opts: ['Yashil savat', 'Jigarrang savat', 'Sariq strelka', 'Ko‘k odam'] }, 1),
  q(60, 'finance', 'screenshots/check_returns.png',
    { q: 'Какой подзаголовок у карточки «Возвраты чеков» на дашборде?', opts: ['Учёт и обработка возвратных чеков', 'Печать чеков', 'Список возвратов', 'Возврат денег'] },
    { q: 'Bosh sahifadagi «Возвраты чеков» kartochkasining quyi sarlavhasi qanday?', opts: ['Qaytarilgan cheklarni hisobga olish va qayta ishlash', 'Cheklar chop etish', 'Qaytarishlar ro‘yxati', 'Pulni qaytarish'] }, 0),

  // ──────────────────────────  ОТЧЁТЫ  ──────────────────────────
  q(61, 'reports', 'screenshots/sales_report.png',
    { q: 'Какие 4 KPI-блока в «Отчёт о продаже»?', opts: ['Продажи, Возвраты, Скидка, Конечный итог', 'Продажи, Зарплата, Налог, Долг', 'Касса, Карта, Терминал, Долг', 'День, Неделя, Месяц, Год'] },
    { q: '«Отчёт о продаже» dagi 4 KPI-blok qanday?', opts: ['Sotuvlar, Qaytarishlar, Chegirma, Yakuniy natija', 'Sotuvlar, Maosh, Soliq, Qarz', 'Kassa, Karta, Terminal, Qarz', 'Kun, Hafta, Oy, Yil'] }, 0),
  q(62, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой блок-график в нижней части отчёта о продаже?', opts: ['Структура платежей', 'Контрагенты', 'Себестоимость', 'Налоги'] },
    { q: 'Sotuv hisobotining quyi qismidagi blok-grafik nomi?', opts: ['To‘lovlar tuzilishi', 'Kontragentlar', 'Tannarx', 'Soliqlar'] }, 0),
  q(63, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой формат периода используется в правом верхнем углу отчёта?', opts: ['DD.MM.YYYY', 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM', 'YYYY/MM/DD', 'MM/DD/YYYY'] },
    { q: 'Hisobotning yuqori o‘ng burchagidagi davr formati qanday?', opts: ['DD.MM.YYYY', 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM', 'YYYY/MM/DD', 'MM/DD/YYYY'] }, 1),
  q(64, 'reports', 'screenshots/top_sales.png',
    { q: 'Что показывает «Топ продаж»?', opts: ['Лучших клиентов', 'Список самых продаваемых товаров', 'Лучшие смены', 'Лучшие зарплаты'] },
    { q: '«Топ продаж» nimani ko‘rsatadi?', opts: ['Eng yaxshi mijozlar', 'Eng ko‘p sotilgan tovarlar ro‘yxati', 'Eng yaxshi smenalar', 'Eng yuqori maoshlar'] }, 1),
  q(65, 'reports', 'screenshots/pl_report.png',
    { q: 'Что показывает P&L отчёт?', opts: ['Доходы, расходы, прибыль', 'Список товаров', 'Учёт сотрудников', 'Печать ценников'] },
    { q: 'P&L hisoboti nimani ko‘rsatadi?', opts: ['Daromad, xarajat, foyda', 'Tovarlar ro‘yxati', 'Xodimlar hisobi', 'Narx yorliqlarini chop etish'] }, 0),
  q(66, 'reports', 'screenshots/balance.png',
    { q: 'Раздел «Салдо» отслеживает…', opts: ['Остатки и балансы', 'Зарплаты', 'Налоги', 'Импорт товара'] },
    { q: '«Салдо» bo‘limi nimani kuzatadi?', opts: ['Qoldiqlar va balanslarni', 'Maoshlarni', 'Soliqlarni', 'Tovar importini'] }, 0),
  q(67, 'reports', 'screenshots/abc_report.png',
    { q: 'Что показывает «Отчёт ABC»?', opts: ['Стабильность спроса', 'Отслеживание остатка с учётом всех движений', 'Зарплату', 'Структуру налогов'] },
    { q: '«Отчёт ABC» nimani ko‘rsatadi?', opts: ['Talab barqarorligini', 'Barcha harakatlarni hisobga olib qoldiqni kuzatish', 'Maoshni', 'Soliq tuzilishini'] }, 1),
  q(68, 'reports', 'screenshots/xyz_report.png',
    { q: '«Отчёт XYZ» — это анализ…', opts: ['Стабильности спроса товаров', 'Расхода топлива', 'Налогов', 'Курсов валют'] },
    { q: '«Отчёт XYZ» nimaning tahlili?', opts: ['Tovarlarga talabning barqarorligini', 'Yoqilg‘i sarfini', 'Soliqlarni', 'Valyuta kurslarini'] }, 0),
  q(69, 'reports', 'screenshots/abc_xyz_report.png',
    { q: 'Что отчёт ABC/XYZ показывает?', opts: ['Отчёт по значимости опирающийся на стабильность товара', 'Отчёт по выручке кассиров', 'Отчёт по зарплате', 'Отчёт по налогам'] },
    { q: 'ABC/XYZ hisobot nimani ko‘rsatadi?', opts: ['Tovarning ahamiyati va barqarorligini bog‘lab beruvchi hisobot', 'Kassirlar daromadi', 'Maosh hisoboti', 'Soliq hisoboti'] }, 0),
  q(70, 'reports', 'screenshots/material_report.png',
    { q: '«Материальный отчёт» — это…', opts: ['Отчёт по сотрудникам', 'Отчёт по материальным ценностям/движениям', 'Отчёт по налогам', 'Отчёт по СМС'] },
    { q: '«Материальный отчёт» nima?', opts: ['Xodimlar bo‘yicha hisobot', 'Moddiy boyliklar/harakatlar bo‘yicha hisobot', 'Soliq hisoboti', 'SMS hisoboti'] }, 1),
  q(71, 'reports', 'screenshots/params_report.png',
    { q: '«Отчёт по параметрам» — это…', opts: ['Формирование отчёта по параметрам', 'Только демонстрация графиков', 'Печать чеков', 'СМС-отчёт'] },
    { q: '«Отчёт по параметрам» nima?', opts: ['Parametrlar bo‘yicha hisobot shakllantirish', 'Faqat grafiklar namoyishi', 'Cheklar chop etish', 'SMS hisoboti'] }, 0),
  q(72, 'reports', 'screenshots/product_report.png',
    { q: 'Что показывает «Товарный отчёт»?', opts: ['Общий отчёт товарных движений', 'Список клиентов', 'Налоговую декларацию', 'Зарплату'] },
    { q: '«Товарный отчёт» nimani ko‘rsatadi?', opts: ['Tovar harakatlarining umumiy hisoboti', 'Mijozlar ro‘yxati', 'Soliq deklaratsiyasi', 'Maosh'] }, 0),
  q(73, 'reports', 'screenshots/no_movement.png',
    { q: 'Что показывает «Товары без движения»?', opts: ['Список товаров без движения за период', 'Список новых товаров', 'Список акций', 'Список клиентов'] },
    { q: '«Товары без движения» nimani ko‘rsatadi?', opts: ['Davr ichida harakatsiz tovarlar ro‘yxati', 'Yangi tovarlar ro‘yxati', 'Aksiyalar ro‘yxati', 'Mijozlar ro‘yxati'] }, 0),
  q(74, 'reports', 'screenshots/sales_report.png',
    { q: 'Какие методы оплаты обычно есть в структуре платежей отчёта о продаже?', opts: ['Только наличные', 'Наличные и Карта', 'Криптовалюта и USDT', 'Только смс-эквайринг'] },
    { q: 'Sotuv hisobotidagi to‘lov tuzilishida odatda qaysi to‘lov usullari bo‘ladi?', opts: ['Faqat naqd', 'Naqd va Karta', 'Kripto va USDT', 'Faqat SMS-ekvayring'] }, 1),
  q(75, 'reports', 'screenshots/pl_report.png',
    { q: 'P&L расшифровывается как…', opts: ['Pay & Loan', 'Profit & Loss (Прибыль и убыток)', 'Plan & Limit', 'Profit & Limit'] },
    { q: 'P&L qisqartmasi nimani anglatadi?', opts: ['Pay & Loan', 'Profit & Loss (Foyda va zarar)', 'Plan & Limit', 'Profit & Limit'] }, 1),

  // ──────────────────────────  НАСТРОЙКИ  ──────────────────────────
  q(76, 'settings', 'screenshots/payment_methods.png',
    { q: '«Методы оплаты» — это…', opts: ['Способы приёма платежей', 'Налоговые ставки', 'Список банков Узбекистана', 'Виды доставки'] },
    { q: '«Методы оплаты» nima?', opts: ['To‘lovlarni qabul qilish usullari', 'Soliq stavkalari', 'O‘zbekiston banklari ro‘yxati', 'Yetkazib berish turlari'] }, 0),
  q(77, 'settings', 'screenshots/pricetags.png',
    { q: '«Ценники» — это…', opts: ['Шаблоны и печать ценников', 'Прайс-лист', 'Расчёт цены', 'Налоговые наклейки'] },
    { q: '«Ценники» nima?', opts: ['Narx yorliqlari shablonlari va chop etish', 'Narxlar ro‘yxati', 'Narx hisoblash', 'Soliq stikerlari'] }, 0),
  q(78, 'settings', 'screenshots/checks_settings.png',
    { q: '«Чеки» в Настройках задают…', opts: ['Параметры печати кассовых чеков', 'Импорт чеков', 'Возврат чеков', 'Архив чеков'] },
    { q: 'Sozlamalardagi «Чеки» nima?', opts: ['Kassa cheklarini chop etish parametrlari', 'Cheklarni import', 'Cheklarni qaytarish', 'Cheklar arxivi'] }, 0),
  q(79, 'settings', 'screenshots/devices.png',
    { q: 'Раздел «Устройства» нужен для…', opts: ['Подключения оборудования', 'Печати ценников', 'Учёта водителей', 'Учёта клиентов'] },
    { q: '«Устройства» bo‘limi nima uchun?', opts: ['Uskunalarni ulash', 'Narx yorliqlarini chop etish', 'Haydovchilar hisobi', 'Mijozlar hisobi'] }, 0),
  q(80, 'settings', 'screenshots/pricing.png',
    { q: '«Ценообразование» — это…', opts: ['Правила формирования цен', 'Налоговая ставка', 'Список валют', 'Зарплата'] },
    { q: '«Ценообразование» nima?', opts: ['Narxlarni shakllantirish qoidalari', 'Soliq stavkasi', 'Valyutalar ro‘yxati', 'Maosh'] }, 0),
  q(81, 'settings', 'screenshots/parameters.png',
    { q: '«Параметры» в настройках задают…', opts: ['Способы приёма платежей', 'Технические параметры приёма платежей', 'Параметры товаров', 'Параметры пользователей'] },
    { q: 'Sozlamalardagi «Параметры» nima?', opts: ['To‘lovlarni qabul qilish usullari', 'To‘lovlarni qabul qilishning texnik parametrlari', 'Tovarlar parametrlari', 'Foydalanuvchilar parametrlari'] }, 1),
  q(82, 'settings', 'screenshots/tags.png',
    { q: 'Что делают «Теги»?', opts: ['Сортируют товары по тегам и формируют отчёт', 'Выдают зарплату', 'Печатают чеки', 'Хранят пароли'] },
    { q: '«Теги» nima qiladi?', opts: ['Tovarlarni teglar bo‘yicha tartiblaydi va hisobot beradi', 'Maosh beradi', 'Cheklar chop etadi', 'Parollarni saqlaydi'] }, 0),
  q(83, 'settings', 'screenshots/interface.png',
    { q: 'Раздел «Интерфейс» отвечает за…', opts: ['Настройки внешнего вида интерфейса', 'Импорт товаров', 'Зарплату', 'Список клиентов'] },
    { q: '«Интерфейс» bo‘limi nima uchun?', opts: ['Interfeys ko‘rinishini sozlash', 'Tovar import', 'Maosh', 'Mijozlar ro‘yxati'] }, 0),
  q(84, 'settings', 'screenshots/telegram_bot.png',
    { q: 'Что делает «Телеграм бот»?', opts: ['Будьте в курсе обо всём что происходит в кассе', 'Печатает чеки', 'Считает зарплату', 'Создаёт пользователей'] },
    { q: '«Телеграм бот» nima qiladi?', opts: ['Kassada bo‘layotgan barcha narsalardan xabardor bo‘lish', 'Cheklar chop etadi', 'Maosh hisoblaydi', 'Foydalanuvchilar yaratadi'] }, 0),
  q(85, 'settings', 'screenshots/tariffs.png',
    { q: 'Где смотрят «Текущий тариф и условия»?', opts: ['В разделе «Тарифы» (Кабинет)', 'В «Настройки → Чеки»', 'В «Отчёты»', 'В «Складские операции»'] },
    { q: '«Joriy tarif va shartlar» qayerda ko‘riladi?', opts: ['«Тарифы» (Kabinet) bo‘limida', '«Sozlamalar → Cheklar» da', '«Hisobotlar» da', '«Ombor amallari» da'] }, 0),

  // ──────────────────────────  КАБИНЕТ  ──────────────────────────
  q(86, 'cabinet', 'screenshots/subscriptions.png',
    { q: 'Раздел «Подписки» нужен для…', opts: ['Управления активными подписками', 'Учёта клиентов', 'Печати чеков', 'Импорта товаров'] },
    { q: '«Подписки» bo‘limi nima uchun?', opts: ['Faol obunalarni boshqarish', 'Mijozlar hisobi', 'Cheklar chop etish', 'Tovar import'] }, 0),
  q(87, 'cabinet', 'screenshots/cash_registers.png',
    { q: 'Раздел «Кассы» — это…', opts: ['Список кассовых аппаратов', 'Список товаров', 'Список клиентов', 'Список зарплат'] },
    { q: '«Кассы» bo‘limi nima?', opts: ['Kassa apparatlari ro‘yxati', 'Tovarlar ro‘yxati', 'Mijozlar ro‘yxati', 'Maoshlar ro‘yxati'] }, 0),
  q(88, 'cabinet', 'screenshots/company_data.png',
    { q: '«Данные» в Кабинете — это…', opts: ['Сведения о компании и реквизитах', 'Список клиентов', 'Прайс-лист', 'Список устройств'] },
    { q: 'Kabinetdagi «Данные» nima?', opts: ['Kompaniya haqida ma’lumotlar va rekvizitlar', 'Mijozlar ro‘yxati', 'Narxlar ro‘yxati', 'Qurilmalar ro‘yxati'] }, 0),
  q(89, 'cabinet', 'screenshots/dashboard.png',
    { q: 'Что делает кнопка «Выход» в разделе Кабинет?', opts: ['Полный выход с аккаунта', 'Закрывает кассу', 'Отправляет SMS', 'Печатает чек'] },
    { q: 'Kabinetdagi «Выход» tugmasi nima qiladi?', opts: ['Akkauntdan to‘liq chiqish', 'Kassani yopadi', 'SMS yuboradi', 'Chek chop etadi'] }, 0),
  q(90, 'cabinet', 'screenshots/dashboard.png',
    { q: 'Какого цвета карточка «Выход» в Кабинете?', opts: ['Синяя', 'Зелёная', 'Красная', 'Серая'] },
    { q: 'Kabinetdagi «Выход» kartochkasining rangi qanday?', opts: ['Ko‘k', 'Yashil', 'Qizil', 'Kulrang'] }, 2),

  // ─────────  Подгруппы / детали (детальные знание UI и фактов)  ─────────
  q(91, 'general', 'screenshots/dashboard.png',
    { q: 'Где находится плюс-кнопка для добавления (быстрого создания) рядом с балансом?', opts: ['Слева вверху', 'Справа от зелёной кнопки баланса', 'В шапке справа', 'В правом нижнем углу страницы'] },
    { q: 'Balans yonidagi «+» tugmasi qayerda joylashgan?', opts: ['Yuqori chap', 'Yashil balans tugmasidan o‘ngda', 'Yuqori panel o‘ngda', 'Sahifa pastki o‘ng burchagida'] }, 1),
  q(92, 'general', 'screenshots/dashboard.png',
    { q: 'Какая иконка у раздела «Складские операции» в боковом меню?', opts: ['Корзина', 'Папка', 'Книга/коробка', 'Стрелка'] },
    { q: 'Yon menyudagi «Складские операции» ning belgisi qanday?', opts: ['Savat', 'Papka', 'Kitob/quti', 'Strelka'] }, 2),
  q(93, 'general', 'screenshots/dashboard.png',
    { q: 'У какого раздела бокового меню иконка с диаграммой?', opts: ['Главная', 'Отчеты', 'Кабинет', 'Справочник'] },
    { q: 'Yon menyuda diagramma belgisi qaysi bo‘limda?', opts: ['Главная', 'Hisobotlar', 'Kabinet', 'Spravochnik'] }, 1),
  q(94, 'general', 'screenshots/dashboard.png',
    { q: 'У какого раздела бокового меню иконка шестерёнки?', opts: ['Настройки', 'Кабинет', 'Главная', 'Отчеты'] },
    { q: 'Yon menyuda shesternya belgisi qaysi bo‘limda?', opts: ['Sozlamalar', 'Kabinet', 'Bosh sahifa', 'Hisobotlar'] }, 0),
  q(95, 'general', 'screenshots/dashboard.png',
    { q: 'Раздел «Кабинет» отмечен иконкой…', opts: ['Шестерёнки', 'Бейджа/удостоверения', 'Графика', 'Папки'] },
    { q: '«Кабинет» qanday belgi bilan ko‘rsatilgan?', opts: ['Shesternya', 'Badj/guvohnoma', 'Grafik', 'Papka'] }, 1),
  q(96, 'general', 'screenshots/dashboard.png',
    { q: 'Какой цвет фона у активного пункта меню «Главная»?', opts: ['Тёмно-синий', 'Зелёный', 'Красный', 'Оранжевый'] },
    { q: 'Faol «Главная» menyu bandining fon rangi qanday?', opts: ['To‘q ko‘k', 'Yashil', 'Qizil', 'Apelsin'] }, 0),
  q(97, 'general', 'screenshots/dashboard.png',
    { q: 'Какой раздел стоит между «Финансовые операции» и «Настройки» в боковом меню?', opts: ['Кабинет', 'Отчеты', 'Справочник', 'Главная'] },
    { q: 'Yon menyuda «Финансовые операции» va «Настройки» orasida qaysi bo‘lim?', opts: ['Kabinet', 'Hisobotlar', 'Spravochnik', 'Bosh sahifa'] }, 1),
  q(98, 'general', 'screenshots/dashboard.png',
    { q: 'Какой раздел в самом низу бокового меню?', opts: ['Кабинет', 'Настройки', 'Главная', 'Отчеты'] },
    { q: 'Yon menyuning eng pastida qaysi bo‘lim?', opts: ['Kabinet', 'Sozlamalar', 'Bosh sahifa', 'Hisobotlar'] }, 0),
  q(99, 'general', 'screenshots/dashboard.png',
    { q: 'Сколько групп карточек в категории «Настройки» (внутри карточек дашборда)?', opts: ['7', '9', '12', '5'] },
    { q: 'Bosh sahifadagi «Настройки» kategoriyasida nechta kartochka?', opts: ['7', '9', '12', '5'] }, 1),
  q(100, 'general', 'screenshots/dashboard.png',
    { q: 'Какая фраза стоит над разделами «Тарифы / Подписки / Кассы / Данные / Выход»?', opts: ['Кабинет', 'Настройки', 'Финансовые операции', 'Справочник'] },
    { q: '«Тарифы / Подписки / Кассы / Данные / Выход» bo‘limlari ustida qanday ibora bor?', opts: ['Kabinet', 'Sozlamalar', 'Moliyaviy amallar', 'Spravochnik'] }, 0),

  // ────────────  Глубокие/тонкие вопросы (101-200)  ────────────
  q(101, 'reference', 'screenshots/clients.png',
    { q: 'Сколько сегодняшних клиентов с ненулевой суммой долга на скриншоте?', opts: ['0', '1', '2 и более', 'Нельзя определить'] },
    { q: 'Skrinshotdagi qarz summasi nolga teng bo‘lmagan mijozlar soni?', opts: ['0', '1', '2 va undan ko‘p', 'Aniqlash mumkin emas'] }, 0),
  q(102, 'reference', 'screenshots/clients.png',
    { q: 'У клиента «Mirali» сумма покупок составляет…', opts: ['28 350 UZS', '4 867 000 UZS', '501 000 UZS', '1 716 000 UZS'] },
    { q: '«Mirali» mijozining xaridlar summasi qancha?', opts: ['28 350 UZS', '4 867 000 UZS', '501 000 UZS', '1 716 000 UZS'] }, 1),
  q(103, 'reference', 'screenshots/clients.png',
    { q: 'Какая дата регистрации у клиента «Aslan»?', opts: ['09.04.2026', '03.03.2026', '20.01.2026', '12.01.2026'] },
    { q: '«Aslan» mijozining ro‘yxatdan o‘tgan sanasi qaysi?', opts: ['09.04.2026', '03.03.2026', '20.01.2026', '12.01.2026'] }, 0),
  q(104, 'reference', 'screenshots/clients.png',
    { q: 'Сколько раз клиент Shaxzod совершил покупки?', opts: ['1', '3', '5', '7'] },
    { q: 'Mijoz Shaxzod necha marta xarid qilgan?', opts: ['1', '3', '5', '7'] }, 2),
  q(105, 'reference', 'screenshots/clients.png',
    { q: 'У клиента «Mobile2» какой телефон?', opts: ['+998 909118811', '+998 901247931', '+998 944182882', '+998 971301600'] },
    { q: '«Mobile2» mijozining telefoni qanday?', opts: ['+998 909118811', '+998 901247931', '+998 944182882', '+998 971301600'] }, 1),
  q(106, 'warehouse', 'screenshots/products.png',
    { q: 'Какой остаток товара «QAZI SHERIN VAKUM KG»?', opts: ['0', '5', '110', '-110'] },
    { q: '«QAZI SHERIN VAKUM KG» mahsulotining qoldig‘i qancha?', opts: ['0', '5', '110', '-110'] }, 0),
  q(107, 'warehouse', 'screenshots/products.png',
    { q: 'Какая средняя наценка на странице «Товары» в KPI?', opts: ['0.0000 %', '10 %', '25 %', '100 %'] },
    { q: '«Tovarlar» KPI dagi o‘rtacha foyda foizi qancha?', opts: ['0.0000 %', '10 %', '25 %', '100 %'] }, 0),
  q(108, 'warehouse', 'screenshots/products.png',
    { q: 'Какая себестоимость указана на скриншоте «Товары» в KPI-блоке?', opts: ['-187 000.00 UZS', '0 UZS', '500 000 UZS', '-2 297 000 UZS'] },
    { q: '«Tovarlar» KPI blokidagi tannarx qancha?', opts: ['-187 000.00 UZS', '0 UZS', '500 000 UZS', '-2 297 000 UZS'] }, 0),
  q(109, 'warehouse', 'screenshots/products.png',
    { q: 'Какое количество товаров (шт.) указано в KPI на странице «Товары»?', opts: ['0', '-110.00 ед', '500', '110 ед'] },
    { q: '«Tovarlar» KPI dagi miqdor qancha?', opts: ['0', '-110.00 ед', '500', '110 ед'] }, 1),
  q(110, 'warehouse', 'screenshots/products.png',
    { q: 'Какая колонка отсутствует в таблице «Товары»?', opts: ['Себестоимость', 'Цена продажи', 'Остаток', 'Налог'] },
    { q: '«Tovarlar» jadvalida qaysi ustun yo‘q?', opts: ['Tannarx', 'Sotuv narxi', 'Qoldiq', 'Soliq'] }, 3),
  q(111, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой URL у страницы «Отчёт о продаже» в LUME (фрагмент)?', opts: ['/dashboard', '/salepoint/sale-report', '/salepoint/orders', '/salepoint/products'] },
    { q: 'LUME’dagi «Отчёт о продаже» sahifasining URL qismi qanday?', opts: ['/dashboard', '/salepoint/sale-report', '/salepoint/orders', '/salepoint/products'] }, 1),
  q(112, 'reports', 'screenshots/sales_report.png',
    { q: 'У возвратов в KPI отчёта используется…', opts: ['Зелёная стрелка', 'Красная/розовая стрелка', 'Синяя стрелка', 'Серая стрелка'] },
    { q: 'Hisobotdagi «Возвраты» KPI bloki uchun … ishlatilgan', opts: ['Yashil strelka', 'Qizil/pushti strelka', 'Ko‘k strelka', 'Kulrang strelka'] }, 1),
  q(113, 'reports', 'screenshots/sales_report.png',
    { q: 'У продажи в KPI отчёта используется…', opts: ['Зелёная стрелка вверх', 'Красная стрелка', 'Синяя стрелка', 'Серая стрелка'] },
    { q: 'Hisobotdagi «Продажи» KPI bloki uchun … ishlatilgan', opts: ['Yashil yuqoriga strelka', 'Qizil strelka', 'Ko‘k strelka', 'Kulrang strelka'] }, 0),
  q(114, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой цвет графика у KPI «Скидка»?', opts: ['Фиолетовый/пурпурный', 'Жёлтый', 'Зелёный', 'Серый'] },
    { q: '«Скидка» KPI grafigining rangi qanday?', opts: ['Binafsha/purple', 'Sariq', 'Yashil', 'Kulrang'] }, 0),
  q(115, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой цвет графика у KPI «Конечный итог»?', opts: ['Синий', 'Жёлтый', 'Зелёный', 'Серый'] },
    { q: '«Конечный итог» KPI grafigi qaysi rangda?', opts: ['Ko‘k', 'Sariq', 'Yashil', 'Kulrang'] }, 0),
  q(116, 'finance', 'screenshots/sold_checks.png',
    { q: 'Какой URL у «Проданные чеки» (фрагмент)?', opts: ['/dashboard', '/salepoint/orders', '/salepoint/sold-checks', '/sold-checks'] },
    { q: '«Проданные чеки» URL qismi qanday?', opts: ['/dashboard', '/salepoint/orders', '/salepoint/sold-checks', '/sold-checks'] }, 1),
  q(117, 'general', undefined,
    { q: 'На какой домен указывает основной URL системы?', opts: ['admin.lume.uz', 'cabinet.lume.uz', 'lume.uz/admin', 'pos.lume.uz'] },
    { q: 'Tizimning asosiy URL qaysi domenga ishora qiladi?', opts: ['admin.lume.uz', 'cabinet.lume.uz', 'lume.uz/admin', 'pos.lume.uz'] }, 0),
  q(118, 'general', undefined,
    { q: 'Какой телефон поддержки указан на странице входа?', opts: ['+998 (77) 489-89-91', '+998 (90) 123-45-67', '+998 (33) 000-00-00', '+998 (71) 200-00-00'] },
    { q: 'Kirish sahifasida ko‘rsatilgan qo‘llab-quvvatlash telefoni qanday?', opts: ['+998 (77) 489-89-91', '+998 (90) 123-45-67', '+998 (33) 000-00-00', '+998 (71) 200-00-00'] }, 0),
  q(119, 'general', undefined,
    { q: 'Слоган admin.lume.uz на странице входа звучит как…', opts: ['Административная система вашего бизнеса', 'Современная касса', 'Лучшая POS-система', 'Контроль продаж'] },
    { q: 'admin.lume.uz kirish sahifasining shiori qanday?', opts: ['Sizning biznesingizning ma’muriy tizimi (Административная система вашего бизнеса)', 'Zamonaviy kassa', 'Eng yaxshi POS-tizim', 'Sotuv nazorati'] }, 0),
  q(120, 'general', 'screenshots/dashboard.png',
    { q: 'Сколько кнопок-разделов отображается в самом боковом меню (без доп. контента)?', opts: ['5', '6', '7', '8'] },
    { q: 'Yon menyu o‘zida (qo‘shimcha kontentsiz) nechta tugma bor?', opts: ['5', '6', '7', '8'] }, 2),

  // 121-140 — детальные роли разделов и URL-фрагменты
  q(121, 'reports', 'screenshots/top_sales.png',
    { q: 'Какой URL у раздела «Топ продаж»?', opts: ['/salepoint/topsale', '/salepoint/orders', '/topsale', '/dashboard/top'] },
    { q: '«Топ продаж» URL qismi qanday?', opts: ['/salepoint/topsale', '/salepoint/orders', '/topsale', '/dashboard/top'] }, 0),
  q(122, 'reports', 'screenshots/pl_report.png',
    { q: 'URL раздела «P&L отчёт»?', opts: ['/salepoint/pl', '/salepoint/profitloss', '/salepoint/pl-report', '/pl'] },
    { q: '«P&L отчёт» URL qismi qanday?', opts: ['/salepoint/pl', '/salepoint/profitloss', '/salepoint/pl-report', '/pl'] }, 1),
  q(123, 'reports', 'screenshots/balance.png',
    { q: 'URL раздела «Салдо»?', opts: ['/salepoint/saldo', '/saldo', '/balance', '/finance/balance'] },
    { q: '«Салдо» URL qismi qanday?', opts: ['/salepoint/saldo', '/saldo', '/balance', '/finance/balance'] }, 0),
  q(124, 'reports', 'screenshots/abc_report.png',
    { q: 'URL раздела «Отчёт ABC»?', opts: ['/salepoint/abc', '/abc-report', '/salepoint/abcreport', '/reports/abc'] },
    { q: '«Отчёт ABC» URL qismi qanday?', opts: ['/salepoint/abc', '/abc-report', '/salepoint/abcreport', '/reports/abc'] }, 0),
  q(125, 'reports', 'screenshots/xyz_report.png',
    { q: 'URL раздела «Отчёт XYZ»?', opts: ['/salepoint/xyz', '/xyz-report', '/salepoint/xyzreport', '/reports/xyz'] },
    { q: '«Отчёт XYZ» URL qismi qanday?', opts: ['/salepoint/xyz', '/xyz-report', '/salepoint/xyzreport', '/reports/xyz'] }, 0),
  q(126, 'reports', 'screenshots/abc_xyz_report.png',
    { q: 'URL раздела «Отчёт ABC/XYZ»?', opts: ['/salepoint/abcxyz', '/salepoint/abc-xyz', '/abc-xyz', '/reports/abcxyz'] },
    { q: '«Отчёт ABC/XYZ» URL qismi qanday?', opts: ['/salepoint/abcxyz', '/salepoint/abc-xyz', '/abc-xyz', '/reports/abcxyz'] }, 0),
  q(127, 'reports', 'screenshots/params_report.png',
    { q: 'URL раздела «Отчёт по параметрам»?', opts: ['/salepoint/paramsreport', '/salepoint/params', '/reports/params', '/paramsreport'] },
    { q: '«Отчёт по параметрам» URL qismi qanday?', opts: ['/salepoint/paramsreport', '/salepoint/params', '/reports/params', '/paramsreport'] }, 0),
  q(128, 'reports', 'screenshots/product_report.png',
    { q: 'URL раздела «Товарный отчёт»?', opts: ['/salepoint/productreport', '/salepoint/products', '/reports/products', '/productreport'] },
    { q: '«Товарный отчёт» URL qismi qanday?', opts: ['/salepoint/productreport', '/salepoint/products', '/reports/products', '/productreport'] }, 0),
  q(129, 'reports', 'screenshots/no_movement.png',
    { q: 'URL раздела «Товары без движения»?', opts: ['/salepoint/without-movement', '/salepoint/no-movement', '/without-movement', '/reports/idle'] },
    { q: '«Товары без движения» URL qismi qanday?', opts: ['/salepoint/without-movement', '/salepoint/no-movement', '/without-movement', '/reports/idle'] }, 0),
  q(130, 'reports', 'screenshots/material_report.png',
    { q: 'URL раздела «Материальный отчёт» (часть пути)?', opts: ['/material', '/reports/material', '/salepoint/material', '/material-report'] },
    { q: '«Материальный отчёт» URL qismi qanday?', opts: ['/material', '/reports/material', '/salepoint/material', '/material-report'] }, 2),
  q(131, 'settings', 'screenshots/checks_settings.png',
    { q: 'URL «Чеки» в Настройках?', opts: ['/salepoint/settings/checks', '/settings/checks', '/checks', '/salepoint/checks'] },
    { q: 'Sozlamalardagi «Чеки» URL?', opts: ['/salepoint/settings/checks', '/settings/checks', '/checks', '/salepoint/checks'] }, 0),
  q(132, 'settings', 'screenshots/devices.png',
    { q: 'URL раздела «Устройства»?', opts: ['/salepoint/devices', '/devices', '/settings/devices', '/equipment'] },
    { q: '«Устройства» URL qismi qanday?', opts: ['/salepoint/devices', '/devices', '/settings/devices', '/equipment'] }, 0),
  q(133, 'settings', 'screenshots/parameters.png',
    { q: 'URL раздела «Параметры»?', opts: ['/salepoint/parameters', '/parameters', '/settings/parameters', '/params'] },
    { q: '«Параметры» URL qismi qanday?', opts: ['/salepoint/parameters', '/parameters', '/settings/parameters', '/params'] }, 0),
  q(134, 'settings', 'screenshots/tags.png',
    { q: 'URL раздела «Теги»?', opts: ['/salepoint/tags', '/tags', '/settings/tags', '/labels'] },
    { q: '«Теги» URL qismi qanday?', opts: ['/salepoint/tags', '/tags', '/settings/tags', '/labels'] }, 0),
  q(135, 'settings', 'screenshots/interface.png',
    { q: 'URL раздела «Интерфейс»?', opts: ['/salepoint/interface', '/interface', '/settings/interface', '/ui'] },
    { q: '«Интерфейс» URL qismi qanday?', opts: ['/salepoint/interface', '/interface', '/settings/interface', '/ui'] }, 0),
  q(136, 'settings', 'screenshots/telegram_bot.png',
    { q: 'URL раздела «Телеграм бот»?', opts: ['/salepoint/tgbot', '/tgbot', '/telegram', '/bot'] },
    { q: '«Телеграм бот» URL qismi qanday?', opts: ['/salepoint/tgbot', '/tgbot', '/telegram', '/bot'] }, 0),
  q(137, 'settings', 'screenshots/pricing.png',
    { q: 'URL раздела «Ценообразование»?', opts: ['/vendor/prices', '/pricing', '/salepoint/pricing', '/prices'] },
    { q: '«Ценообразование» URL qismi qanday?', opts: ['/vendor/prices', '/pricing', '/salepoint/pricing', '/prices'] }, 0),
  q(138, 'settings', 'screenshots/pricetags.png',
    { q: 'URL раздела «Ценники» (Настройки)?', opts: ['/salepoint/pricing', '/salepoint/pricetags', '/pricetags', '/labels'] },
    { q: 'Sozlamalardagi «Ценники» URL?', opts: ['/salepoint/pricing', '/salepoint/pricetags', '/pricetags', '/labels'] }, 0),
  q(139, 'cabinet', 'screenshots/subscriptions.png',
    { q: 'URL раздела «Подписки» в Кабинете?', opts: ['/salepoint/cabinet/subscriptions', '/subscriptions', '/cabinet/subs', '/cabinet/subscription'] },
    { q: 'Kabinetdagi «Подписки» URL?', opts: ['/salepoint/cabinet/subscriptions', '/subscriptions', '/cabinet/subs', '/cabinet/subscription'] }, 0),
  q(140, 'general', undefined,
    { q: 'Какой URL у дашборда после входа?', opts: ['/home', '/dashboard', '/main', '/cabinet'] },
    { q: 'Kirishdan keyingi dashboard URL?', opts: ['/home', '/dashboard', '/main', '/cabinet'] }, 1),

  // 141-170 — функции и взаимосвязи
  q(141, 'finance', 'screenshots/check_returns.png',
    { q: 'Что является первичной операцией для «Возвраты чеков»?', opts: ['Покупка / продажа товара', 'Списание', 'Импорт', 'Z-отчёт'] },
    { q: '«Возвраты чеков» uchun boshlang‘ich amal nima?', opts: ['Tovar sotib olish/sotish', 'Hisobdan chiqarish', 'Import', 'Z-hisobot'] }, 0),
  q(142, 'finance', 'screenshots/mutual_settlements.png',
    { q: '«Взаиморасчёт» в первую очередь нужен для…', opts: ['Учёта взаимных задолженностей с контрагентами', 'Учёта зарплат сотрудников', 'Учёта остатков', 'Учёта смен'] },
    { q: '«Взаиморасчёт» asosan kim bilan bo‘ladigan hisob-kitobni boshqaradi?', opts: ['Kontragentlar bilan o‘zaro qarzlar', 'Xodimlar maoshi', 'Qoldiqlar', 'Smenalar'] }, 0),
  q(143, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой раздел кабинета даёт визуальные графики дневных продаж?', opts: ['Отчёт о продаже', 'Печать ценников', 'Подписки', 'Контрагенты'] },
    { q: 'Kunlik sotuvlarni grafik ko‘rsatuvchi bo‘lim?', opts: ['Sotuv hisoboti', 'Narx yorliqlarini chop etish', 'Obunalar', 'Kontragentlar'] }, 0),
  q(144, 'warehouse', 'screenshots/products.png',
    { q: 'Какой действие происходит при клике «+ Добавить товар»?', opts: ['Открывается форма создания товара', 'Печатается чек', 'Формируется отчёт', 'Удаляется товар'] },
    { q: '«+ Добавить товар» bosilganda nima sodir bo‘ladi?', opts: ['Tovar yaratish formasi ochiladi', 'Chek chop etiladi', 'Hisobot tuziladi', 'Tovar o‘chiriladi'] }, 0),
  q(145, 'warehouse', 'screenshots/products.png',
    { q: 'На странице «Товары» сортировка работает по…', opts: ['Алфавиту', 'Колонкам с иконкой стрелок (Остаток, Себестоимость, Цена продажи)', 'Только по Дате', 'Не работает'] },
    { q: '«Товары» da saralash qaysi ustunlar bo‘yicha?', opts: ['Alifbo', 'Strelkali ustunlar (Qoldiq, Tannarx, Sotuv narxi)', 'Faqat sana', 'Ishlamaydi'] }, 1),
  q(146, 'warehouse', 'screenshots/inventory.png',
    { q: 'Что станет результатом инвентаризации с расхождением?', opts: ['Создание акта расхождения', 'Печать чека продажи', 'Создание зарплаты', 'СМС клиенту'] },
    { q: 'Farqli inventarizatsiya natijasi nima bo‘ladi?', opts: ['Farqlar akti tuziladi', 'Sotuv cheki chop etiladi', 'Maosh yaratiladi', 'Mijozga SMS'] }, 0),
  q(147, 'warehouse', 'screenshots/transfer.png',
    { q: 'Трансфер обычно требует наличия минимум…', opts: ['1 склада', '2 точек/складов', '3 кассиров', '0 пользователей'] },
    { q: 'Trans­fer odatda kamida nechtani talab qiladi?', opts: ['1 ombor', '2 ta nuqta/ombor', '3 kassir', '0 foydalanuvchi'] }, 1),
  q(148, 'reference', 'screenshots/loyalty.png',
    { q: 'Какие формы лояльности обычно поддерживает LUME?', opts: ['Бонусы и скидки для постоянных клиентов', 'Прокат техники', 'Продажу криптовалют', 'Рекламу в Google'] },
    { q: 'LUME odatda qanday lo‘yallik shakllarini qo‘llaydi?', opts: ['Doimiy mijozlar uchun bonus va chegirmalar', 'Texnika ijarasi', 'Kripto sotish', 'Google reklamasi'] }, 0),
  q(149, 'reference', 'screenshots/sms_blast.png',
    { q: 'Раздел «Шаблоны СМС» полезен для…', opts: ['Быстрого формирования рассылок', 'Печати чеков', 'Учёта зарплат', 'Контроля смен'] },
    { q: '«Шаблоны СМС» nima uchun foydali?', opts: ['SMS rassilkalarini tezda shakllantirish', 'Cheklar chop etish', 'Maosh hisobi', 'Smenalar nazorati'] }, 0),
  q(150, 'cabinet', 'screenshots/subscriptions.png',
    { q: 'Что обычно отображается в «Подписках»?', opts: ['Активные тарифные подписки и их статус', 'Список товаров', 'Зарплата', 'Чеки'] },
    { q: '«Подписки» da odatda nima ko‘rsatiladi?', opts: ['Faol tarif obunalari va ularning holati', 'Tovarlar ro‘yxati', 'Maosh', 'Cheklar'] }, 0),
  q(151, 'cabinet', 'screenshots/cash_registers.png',
    { q: 'В «Кассах» можно увидеть…', opts: ['Список кассовых аппаратов точки', 'Список клиентов', 'Импорт товаров', 'Налоги'] },
    { q: '«Кассы» da nima ko‘rinadi?', opts: ['Nuqtaning kassa apparatlari ro‘yxati', 'Mijozlar ro‘yxati', 'Tovar import', 'Soliqlar'] }, 0),
  q(152, 'cabinet', 'screenshots/company_data.png',
    { q: 'Что нельзя изменить в «Данные»?', opts: ['Реквизиты', 'Название компании', 'Логин учётной записи администратора', 'Адрес'] },
    { q: '«Данные» da nimani o‘zgartirib bo‘lmaydi?', opts: ['Rekvizitlar', 'Kompaniya nomi', 'Administrator login', 'Manzil'] }, 2),
  q(153, 'reference', 'screenshots/contractors.png',
    { q: 'Кого учитывает раздел «Контрагенты»?', opts: ['Поставщиков и партнёров', 'Сотрудников', 'Кассиров', 'Покупателей-физлиц'] },
    { q: '«Контрагенты» kimlarni hisobga oladi?', opts: ['Yetkazib beruvchilar va hamkorlar', 'Xodimlar', 'Kassirlar', 'Jismoniy shaxs xaridorlari'] }, 0),
  q(154, 'reference', 'screenshots/personnel.png',
    { q: 'Карточка «Персонал» относится к группе…', opts: ['Справочник', 'Складские операции', 'Финансовые операции', 'Настройки'] },
    { q: '«Персонал» kartochkasi qaysi guruhga tegishli?', opts: ['Spravochnik', 'Ombor amallari', 'Moliyaviy amallar', 'Sozlamalar'] }, 0),
  q(155, 'reference', 'screenshots/drivers.png',
    { q: '«Водители» относятся к группе…', opts: ['Справочник', 'Складские операции', 'Финансовые операции', 'Кабинет'] },
    { q: '«Водители» qaysi guruhga tegishli?', opts: ['Spravochnik', 'Ombor amallari', 'Moliyaviy amallar', 'Kabinet'] }, 0),
  q(156, 'warehouse', 'screenshots/manufacturing_act.png',
    { q: '«Акт изготовления» обычно следует за…', opts: ['Техкартой и приходом сырья', 'Импортом клиентов', 'Возвратом', 'Печатью ценников'] },
    { q: '«Акт изготовления» odatda … dan keyin amalga oshiriladi', opts: ['Texkarta va xomashyo kirimi', 'Mijozlar import', 'Qaytarish', 'Narx yorliqlarini chop etish'] }, 0),
  q(157, 'warehouse', 'screenshots/tech_cards.png',
    { q: 'Что является входом в техкарту?', opts: ['Состав ингредиентов и нормы', 'Список клиентов', 'Список зарплат', 'Список смен'] },
    { q: 'Texkartaga nima kiritiladi?', opts: ['Ingredientlar tarkibi va meyorlar', 'Mijozlar ro‘yxati', 'Maosh ro‘yxati', 'Smena ro‘yxati'] }, 0),
  q(158, 'finance', 'screenshots/salary.png',
    { q: 'Зарплату в системе обычно выплачивают на основе…', opts: ['Ставки и/или % от продаж', 'Кассового остатка', 'Цены продажи', 'Импорта товаров'] },
    { q: 'Tizimda maosh odatda nima asosida to‘lanadi?', opts: ['Stavka va/yoki sotuvdan %', 'Kassa qoldig‘i', 'Sotuv narxi', 'Tovar import'] }, 0),
  q(159, 'finance', 'screenshots/accounts.png',
    { q: 'Раздел «Счета» относится к…', opts: ['Финансовым операциям', 'Складским операциям', 'Отчётам', 'Настройкам'] },
    { q: '«Счета» bo‘limi qayerga tegishli?', opts: ['Moliyaviy amallar', 'Ombor amallari', 'Hisobotlar', 'Sozlamalar'] }, 0),
  q(160, 'finance', 'screenshots/sold_checks.png',
    { q: 'Проданные чеки также есть на дашборде в группе…', opts: ['Начало работы', 'Складские операции', 'Финансовые операции', 'И в первом, и в третьем'] },
    { q: '«Проданные чеки» bosh sahifada qaysi guruhda?', opts: ['Начало работы', 'Ombor amallari', 'Moliyaviy amallar', 'Birinchi va uchinchida ham'] }, 3),
  q(161, 'general', 'screenshots/dashboard.png',
    { q: 'В каком углу страницы кнопка «свернуть/развернуть» сайдбар?', opts: ['Левый верхний', 'Левый нижний', 'Между сайдбаром и контентом (язычок)', 'Правый верхний'] },
    { q: 'Sayd-barni yig‘ish/yoyish tugmasi qaysi joyda?', opts: ['Yuqori chap', 'Pastki chap', 'Sayd-bar va kontent orasida (tilcha)', 'Yuqori o‘ng'] }, 2),
  q(162, 'reports', 'screenshots/sales_report.png',
    { q: 'Где в отчёте о продаже выбирается период?', opts: ['В правом верхнем углу — селектор «дата - дата»', 'Внизу страницы', 'В левом меню', 'Нельзя выбирать'] },
    { q: 'Sotuv hisobotida davr qayerda tanlanadi?', opts: ['Yuqori o‘ngda — «sana - sana» selektor', 'Pastda', 'Chap menyuda', 'Tanlab bo‘lmaydi'] }, 0),
  q(163, 'reports', 'screenshots/sales_report.png',
    { q: 'Какой статистический блок есть ниже KPI в отчёте о продаже?', opts: ['Структура платежей', 'Топ кассиров', 'Активные пользователи', 'СМС'] },
    { q: 'Sotuv hisobotida KPI dan keyin qaysi blok bor?', opts: ['To‘lov tuzilishi', 'Top kassirlar', 'Faol foydalanuvchilar', 'SMS'] }, 0),
  q(164, 'reports', 'screenshots/sales_report.png',
    { q: 'В легенде структуры платежей обычно отображаются…', opts: ['Наличные и Карта (с процентами)', 'Только Карта', 'Только Наличные', 'Только Терминал'] },
    { q: 'To‘lovlar tuzilishi legendasida odatda nima?', opts: ['Naqd va Karta (foiz bilan)', 'Faqat Karta', 'Faqat Naqd', 'Faqat Terminal'] }, 0),
  q(165, 'general', 'screenshots/dashboard.png',
    { q: 'Какой формат имеет URL входа в систему?', opts: ['admin.lume.uz/', 'admin.lume.uz/login', 'admin.lume.uz/auth', 'admin.lume.uz/signin'] },
    { q: 'Tizimga kirish URL formati?', opts: ['admin.lume.uz/', 'admin.lume.uz/login', 'admin.lume.uz/auth', 'admin.lume.uz/signin'] }, 0),
  q(166, 'general', undefined,
    { q: 'Какой текст основной CTA-кнопки на странице входа в LUME?', opts: ['Регистрация', 'Войти', 'Логин', 'Продолжить'] },
    { q: 'LUME kirish sahifasidagi asosiy CTA tugma matni?', opts: ['Ro‘yxatdan o‘tish', 'Kirish', 'Login', 'Davom etish'] }, 0),
  q(167, 'general', undefined,
    { q: 'На странице входа admin.lume.uz используется поле…', opts: ['Только e-mail', 'E-mail и пароль', 'Только телефон', 'Логин и СМС'] },
    { q: 'admin.lume.uz kirish sahifasida qaysi maydonlar?', opts: ['Faqat e-mail', 'E-mail va parol', 'Faqat telefon', 'Login va SMS'] }, 1),
  q(168, 'general', 'screenshots/dashboard.png',
    { q: 'Что отображается на странице сразу после входа?', opts: ['Дашборд с карточками всех модулей', 'Только список товаров', 'Только список клиентов', 'Только профиль'] },
    { q: 'Kirishdan keyin sahifada nima ko‘rinadi?', opts: ['Barcha modullar kartalari bilan dashboard', 'Faqat tovarlar ro‘yxati', 'Faqat mijozlar ro‘yxati', 'Faqat profil'] }, 0),
  q(169, 'general', 'screenshots/dashboard.png',
    { q: 'У большинства карточек дашборда…', opts: ['Есть цветная иконка слева вверху и описание под названием', 'Только текст без иконок', 'Только большие фото', 'Видео'] },
    { q: 'Bosh sahifa kartalarida odatda…', opts: ['Yuqori chapda rangli belgi va nomi tagida tavsifi bor', 'Faqat matn', 'Faqat katta foto', 'Video'] }, 0),
  q(170, 'general', 'screenshots/dashboard.png',
    { q: 'В каком месте сайдбара отображается баланс «749 700 UZS»?', opts: ['Сверху над логотипом', 'В нижней части сайдбара', 'В правом нижнем углу', 'В шапке справа'] },
    { q: '«749 700 UZS» balans qayerda?', opts: ['Logotip ustida', 'Sayd-bar pastida', 'Pastki o‘ngda', 'Yuqori panel o‘ngda'] }, 1),

  // 171-200 — продвинутые/деталь­ные
  q(171, 'reference', 'screenshots/clients.png',
    { q: 'Какой телефон у клиента «Suxrob»?', opts: ['+998 909118811', '+998 777771668', '+998 901247931', '+998 944182882'] },
    { q: '«Suxrob» mijozining telefoni qanday?', opts: ['+998 909118811', '+998 777771668', '+998 901247931', '+998 944182882'] }, 1),
  q(172, 'reference', 'screenshots/clients.png',
    { q: 'Сколько раз совершил покупку «Abc client»?', opts: ['0', '1', '3', '5'] },
    { q: '«Abc client» necha marta xarid qilgan?', opts: ['0', '1', '3', '5'] }, 0),
  q(173, 'reference', 'screenshots/clients.png',
    { q: 'Какая дата регистрации у «Mirali»?', opts: ['09.04.2026', '12.01.2026', '03.03.2026', '06.01.2026'] },
    { q: '«Mirali» mijozining ro‘yxatdan o‘tgan sanasi?', opts: ['09.04.2026', '12.01.2026', '03.03.2026', '06.01.2026'] }, 1),
  q(174, 'reference', 'screenshots/clients.png',
    { q: 'У какого клиента сумма покупок 1 716 000 UZS?', opts: ['Aslan', 'Shaxzod', 'Mirali', 'Mobile2'] },
    { q: '1 716 000 UZS xaridi qaysi mijozda?', opts: ['Aslan', 'Shaxzod', 'Mirali', 'Mobile2'] }, 1),
  q(175, 'reference', 'screenshots/clients.png',
    { q: 'Сколько колонок в таблице «Клиенты» (включая №)?', opts: ['4', '5', '6', '7'] },
    { q: '«Клиенты» jadvalida (№ bilan) nechta ustun?', opts: ['4', '5', '6', '7'] }, 3),
  q(176, 'warehouse', 'screenshots/products.png',
    { q: 'Сколько строк товаров видно на скриншоте «Товары» (примерно)?', opts: ['1-2', '3-4', '6-7', 'Больше 20'] },
    { q: '«Tovarlar» skrinshotida taxminan nechta qator ko‘rinadi?', opts: ['1-2', '3-4', '6-7', '20 dan ko‘p'] }, 2),
  q(177, 'warehouse', 'screenshots/products.png',
    { q: 'Какая цена продажи у «DRIFT PULUTLI MOSHI…»?', opts: ['9 000 UZS', '250 000 UZS', '330 000 UZS', '500 000 UZS'] },
    { q: '«DRIFT PULUTLI MOSHI…» sotuv narxi?', opts: ['9 000 UZS', '250 000 UZS', '330 000 UZS', '500 000 UZS'] }, 1),
  q(178, 'warehouse', 'screenshots/products.png',
    { q: 'Какая цена продажи у «TRELLER»?', opts: ['250 000 UZS', '330 000 UZS', '500 000 UZS', '225 000 UZS'] },
    { q: '«TRELLER» sotuv narxi?', opts: ['250 000 UZS', '330 000 UZS', '500 000 UZS', '225 000 UZS'] }, 0),
  q(179, 'warehouse', 'screenshots/products.png',
    { q: 'Какая цена продажи у «QAZI TAM TAM VAKUM»?', opts: ['225 000 UZS', '250 000 UZS', '330 000 UZS', '500 000 UZS'] },
    { q: '«QAZI TAM TAM VAKUM» sotuv narxi?', opts: ['225 000 UZS', '250 000 UZS', '330 000 UZS', '500 000 UZS'] }, 0),
  q(180, 'warehouse', 'screenshots/products.png',
    { q: 'Какая себестоимость у «Printer» в первой строке?', opts: ['9 000 UZS', '0 UZS', '500 000 UZS', '187 000 UZS'] },
    { q: 'Birinchi qatordagi «Printer» tannarxi qancha?', opts: ['9 000 UZS', '0 UZS', '500 000 UZS', '187 000 UZS'] }, 0),
  q(181, 'reports', 'screenshots/sales_report.png',
    { q: 'У какого KPI значение в UZS не подписано?', opts: ['Все 4 KPI имеют подпись «UZS»', 'Скидка', 'Возвраты', 'Конечный итог'] },
    { q: 'Qaysi KPI da «UZS» yozuvi yo‘q?', opts: ['Hammasida UZS bor', 'Скидка', 'Возвраты', 'Конечный итог'] }, 0),
  q(182, 'reports', 'screenshots/sales_report.png',
    { q: 'Какое значение Продажи на скриншоте?', opts: ['0.00 UZS', '500 000 UZS', '102 000 UZS', '1 000 UZS'] },
    { q: 'Skrinshotda «Продажи» qiymati qancha?', opts: ['0.00 UZS', '500 000 UZS', '102 000 UZS', '1 000 UZS'] }, 0),
  q(183, 'reports', 'screenshots/sales_report.png',
    { q: 'Какое количество чеков на дату в KPI «Продажи» на скрине?', opts: ['0', '5', '15', '50'] },
    { q: 'Skrinshotda «Продажи» KPI dagi cheklar soni qancha?', opts: ['0', '5', '15', '50'] }, 0),
  q(184, 'reports', 'screenshots/sales_report.png',
    { q: 'Какое значение «Конечный итог» на скрине?', opts: ['0.00 UZS', '500 000 UZS', '102 000 UZS', '749 700 UZS'] },
    { q: 'Skrinshotda «Конечный итог» qancha?', opts: ['0.00 UZS', '500 000 UZS', '102 000 UZS', '749 700 UZS'] }, 0),
  q(185, 'reports', 'screenshots/sales_report.png',
    { q: 'Какие есть оси у блока «Структура платежей»?', opts: ['Только X (категории)', 'Числовая (Y) и категории (X)', 'Только Y', 'Без осей'] },
    { q: '«Структура платежей» blokida qanday o‘qlar bor?', opts: ['Faqat X', 'Y va X', 'Faqat Y', 'O‘qlarsiz'] }, 1),
  q(186, 'reports', 'screenshots/sales_report.png',
    { q: 'Какие проценты подписаны рядом с «Наличные» и «Карта» на скрине?', opts: ['0.00% обоим', '50% / 50%', '100% / 0%', '25% / 75%'] },
    { q: 'Skrinshotda «Наличные» va «Карта» yonida qaysi foizlar?', opts: ['Ikkalasi ham 0.00%', '50% / 50%', '100% / 0%', '25% / 75%'] }, 0),
  q(187, 'general', 'screenshots/dashboard.png',
    { q: 'Какой текст в логотипе под «LUME» в шапке?', opts: ['ADMIN SYSTEM', 'POS', 'OFFICE', 'PORTAL'] },
    { q: 'Yuqori paneldagi «LUME» ostida qanday matn?', opts: ['ADMIN SYSTEM', 'POS', 'OFFICE', 'PORTAL'] }, 0),
  q(188, 'general', 'screenshots/dashboard.png',
    { q: 'Какой иконкой обозначен раздел «Главная»?', opts: ['Дом', 'Шестерёнка', 'График', 'Корзина'] },
    { q: '«Главная» qanday belgi bilan?', opts: ['Uy', 'Shesternya', 'Grafik', 'Savat'] }, 0),
  q(189, 'general', 'screenshots/dashboard.png',
    { q: 'Какой иконкой обозначены «Финансовые операции»?', opts: ['Здание/банк', 'Дом', 'Шестерёнка', 'Конверт'] },
    { q: '«Финансовые операции» qanday belgi bilan?', opts: ['Bino/bank', 'Uy', 'Shesternya', 'Konvert'] }, 0),
  q(190, 'general', 'screenshots/dashboard.png',
    { q: 'Какой иконкой обозначен «Справочник»?', opts: ['Книга', 'Шестерёнка', 'График', 'Чек'] },
    { q: '«Справочник» qanday belgi bilan?', opts: ['Kitob', 'Shesternya', 'Grafik', 'Chek'] }, 0),
  q(191, 'general', 'screenshots/dashboard.png',
    { q: 'Раздел «Складские операции» в категориях карточек дашборда содержит сколько подразделов (примерно)?', opts: ['~5', '~13', '~30', '~50'] },
    { q: 'Bosh sahifa kartalaridagi «Складские операции» da taxminan nechta bo‘lim bor?', opts: ['~5', '~13', '~30', '~50'] }, 1),
  q(192, 'general', 'screenshots/dashboard.png',
    { q: 'Сколько разделов в категории «Кабинет» (карточки)?', opts: ['3', '4', '5', '7'] },
    { q: '«Кабинет» kategoriyasida nechta kartochka?', opts: ['3', '4', '5', '7'] }, 2),
  q(193, 'general', 'screenshots/dashboard.png',
    { q: 'В категории «Финансовые операции» какие разделы?', opts: ['Проданные чеки, Возвраты чеков, Удалённые чеки, Отложенные чеки, Взаиморасчёт, Счета, Зарплата', 'Только чеки и зарплата', 'Только зарплата и счёт', 'Только клиенты и зарплата'] },
    { q: '«Финансовые операции» da qaysi bo‘limlar?', opts: ['Проданные чеки, Возвраты чеков, Удалённые чеки, Отложенные чеки, Взаиморасчёт, Счета, Зарплата', 'Faqat cheklar va maosh', 'Faqat maosh va hisob', 'Faqat mijozlar va maosh'] }, 0),
  q(194, 'general', 'screenshots/dashboard.png',
    { q: 'В категории «Отчёты» какой отчёт начинается на букву «P»?', opts: ['P&L отчёт', 'Print', 'Power', 'Pay'] },
    { q: '«Отчёты» kategoriyasida «P» harfi bilan boshlanadigan hisobot?', opts: ['P&L отчёт', 'Print', 'Power', 'Pay'] }, 0),
  q(195, 'general', 'screenshots/dashboard.png',
    { q: 'Какой раздел в категории «Кабинет» имеет красный цвет иконки?', opts: ['Тарифы', 'Подписки', 'Кассы', 'Выход'] },
    { q: '«Кабинет» da qaysi bo‘limning ikonasi qizil?', opts: ['Тарифы', 'Подписки', 'Кассы', 'Выход'] }, 3),
  q(196, 'general', 'screenshots/dashboard.png',
    { q: 'Подзаголовок карточки «Тарифы» содержит:', opts: ['Текущий тариф и условиям', 'Список товаров', 'Зарплата сотрудников', 'Список устройств'] },
    { q: '«Тарифы» kartochkasi quyi sarlavhasida qanday yozuv?', opts: ['Текущий тариф и условиям (Joriy tarif va shartlar)', 'Tovarlar ro‘yxati', 'Xodimlar maoshi', 'Qurilmalar ro‘yxati'] }, 0),
  q(197, 'general', 'screenshots/dashboard.png',
    { q: 'Каким цветом подсвечен активный пункт «Главная»?', opts: ['Серый', 'Тёмно-синий', 'Зелёный', 'Розовый'] },
    { q: 'Faol «Главная» qaysi rangda?', opts: ['Kulrang', 'To‘q ko‘k', 'Yashil', 'Pushti'] }, 1),
  q(198, 'general', 'screenshots/dashboard.png',
    { q: 'У карточки «Отчёт о продаже» иконка какого цвета?', opts: ['Жёлтая/оранжевая', 'Синяя', 'Зелёная', 'Серая'] },
    { q: '«Отчёт о продаже» kartochkasi belgisi qaysi rangda?', opts: ['Sariq/apelsin', 'Ko‘k', 'Yashil', 'Kulrang'] }, 0),
  q(199, 'general', 'screenshots/dashboard.png',
    { q: 'У карточки «Товары» иконка какого цвета?', opts: ['Зелёная', 'Синяя', 'Жёлтая', 'Красная'] },
    { q: '«Товары» kartochkasi belgisi qaysi rangda?', opts: ['Yashil', 'Ko‘k', 'Sariq', 'Qizil'] }, 0),
  q(200, 'general', 'screenshots/dashboard.png',
    { q: 'У карточки «Счета» иконка какого цвета?', opts: ['Оранжевая/коричневая', 'Зелёная', 'Синяя', 'Серая'] },
    { q: '«Счета» kartochkasi belgisi qaysi rangda?', opts: ['Apelsin/jigarrang', 'Yashil', 'Ko‘k', 'Kulrang'] }, 0),
];

// Sanity check at boot
if (QUESTIONS.length !== 200) {
  // We do NOT throw at runtime in production — surfaced only in dev.
  if (process.env.NODE_ENV !== 'production') {
    console.warn('[questions] expected 200 questions, got', QUESTIONS.length);
  }
}

export function getQuestionById(id: number): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}

// Returns a public-facing version of the question without the correct index.
export function publicQuestion(qq: Question) {
  return {
    id: qq.id,
    cat: qq.cat,
    shot: qq.shot,
    ru: qq.ru,
    uz: qq.uz,
  };
}
