#!/bin/bash
# Rename Cyrillic screenshot filenames to ASCII slugs for safe URL serving.
set -e
cd "$(dirname "$0")/../public/screenshots"

declare -A MAP=(
  ["sec_P_L_отчет.png"]="pl_report.png"
  ["sec_Z_отчеты.png"]="z_reports.png"
  ["sec_Акт_изготовления.png"]="manufacturing_act.png"
  ["sec_Акции.png"]="promotions.png"
  ["sec_Аудит_маркировок.png"]="marking_audit.png"
  ["sec_Весовые_товары.png"]="weighted_products.png"
  ["sec_Взаиморасч_т.png"]="mutual_settlements.png"
  ["sec_Водители.png"]="drivers.png"
  ["sec_Возврат_прихода.png"]="receipt_return.png"
  ["sec_Возвраты_чеков.png"]="check_returns.png"
  ["sec_Группировка.png"]="grouping.png"
  ["sec_Данные.png"]="company_data.png"
  ["sec_Документы.png"]="documents.png"
  ["sec_Зарплата.png"]="salary.png"
  ["sec_Избранные_товары.png"]="favorite_products.png"
  ["sec_Импорт_товаров.png"]="import_products.png"
  ["sec_Инвентаризация.png"]="inventory.png"
  ["sec_Интерфейс.png"]="interface.png"
  ["sec_Кассы.png"]="cash_registers.png"
  ["sec_Клиенты.png"]="clients.png"
  ["sec_Контрагенты.png"]="contractors.png"
  ["sec_Лояльность.png"]="loyalty.png"
  ["sec_Материальный_отчет.png"]="material_report.png"
  ["sec_Методы_оплаты.png"]="payment_methods.png"
  ["sec_Отложенные_чеки.png"]="pending_checks.png"
  ["sec_Отчет_ABC.png"]="abc_report.png"
  ["sec_Отчет_ABC_XYZ.png"]="abc_xyz_report.png"
  ["sec_Отчет_XYZ.png"]="xyz_report.png"
  ["sec_Отчет_о_продаже.png"]="sales_report.png"
  ["sec_Отчет_по_параметрам.png"]="params_report.png"
  ["sec_Параметры.png"]="parameters.png"
  ["sec_Переоценка.png"]="reprice.png"
  ["sec_Персонал.png"]="personnel.png"
  ["sec_Печать_ценников.png"]="print_pricetags.png"
  ["sec_Подписки.png"]="subscriptions.png"
  ["sec_Приход.png"]="receipt.png"
  ["sec_Проданные_чеки.png"]="sold_checks.png"
  ["sec_Реализация.png"]="realization.png"
  ["sec_СМС_рассылка.png"]="sms_blast.png"
  ["sec_Салдо.png"]="balance.png"
  ["sec_Смены.png"]="shifts.png"
  ["sec_Списание.png"]="writeoff.png"
  ["sec_Счета.png"]="accounts.png"
  ["sec_Тарифы.png"]="tariffs.png"
  ["sec_Теги.png"]="tags.png"
  ["sec_Телеграм_бот.png"]="telegram_bot.png"
  ["sec_Техкарты.png"]="tech_cards.png"
  ["sec_Товарный_отчет.png"]="product_report.png"
  ["sec_Товары.png"]="products.png"
  ["sec_Товары_без_движения.png"]="no_movement.png"
  ["sec_Топ_продаж.png"]="top_sales.png"
  ["sec_Трансфер.png"]="transfer.png"
  ["sec_Удал_нные_чеки.png"]="deleted_checks.png"
  ["sec_Устройства.png"]="devices.png"
  ["sec_Ценники.png"]="pricetags.png"
  ["sec_Ценообразование.png"]="pricing.png"
  ["sec_Чеки.png"]="checks_settings.png"
  ["sec_Шаблоны_СМС.png"]="sms_templates.png"
  ["sec_ЭДО.png"]="edo.png"
)

for old in "${!MAP[@]}"; do
  if [ -f "$old" ]; then
    mv -f "$old" "${MAP[$old]}"
    echo "renamed: $old -> ${MAP[$old]}"
  fi
done

echo "done"
ls
