// Script to seed lessons from screenshots
// Run with: npx ts-node scripts/seed-lessons.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const lessons = [
  // Складские операции (Warehouse)
  { category: 'warehouse', screenshot: 'screenshots/products.png', ruName: 'Товары', uzName: 'Tovarlar', ruDescription: 'Раздел для управления товарами: добавление, редактирование, поиск и просмотр информации о товарах', uzDescription: 'Tovarlarni boshqarish bo\'limi: qo\'shish, tahrirlash, qidirish va tovarlar haqida ma\'lumotlarni ko\'rish', ruFunctionality: 'Добавление новых товаров, редактирование существующих, просмотр остатков, себестоимости и цен продажи, поиск по названию или артикулу', uzFunctionality: 'Yangi tovarlar qo\'shish, mavjudlarni tahrirlash, qoldiqlarni, tannarx va sotuv narxlarini ko\'rish, nom yoki artikul bo\'yicha qidirish', uiLocation: 'Главное меню → Склад → Товары', order: 1 },
  { category: 'warehouse', screenshot: 'screenshots/receipt.png', ruName: 'Приход', uzName: 'Kirim', ruDescription: 'Оформление поступления товаров от поставщиков', uzDescription: 'Yetkazib beruvchilardan tovar qabul qilishni rasmiylashtirish', ruFunctionality: 'Создание документов прихода, выбор поставщика, добавление товаров, указание цен и количества, отслеживание статусов: Черновик, Оформлен', uzFunctionality: 'Kirim hujjatlarini yaratish, yetkazib beruvchini tanlash, tovarlarni qo\'shish, narx va miqdorni ko\'rsatish, holatlarni kuzatish: Qoralama, Rasmiylashtirilgan', uiLocation: 'Главное меню → Склад → Приход', order: 2 },
  { category: 'warehouse', screenshot: 'screenshots/receipt_return.png', ruName: 'Возврат прихода', uzName: 'Kirimni qaytarish', ruDescription: 'Возврат товаров поставщикам', uzDescription: 'Tovarlarni yetkazib beruvchilarga qaytarish', ruFunctionality: 'Оформление возврата товаров поставщику, выбор прихода для возврата, указание причины и количества возвращаемых товаров', uzFunctionality: 'Yetkazib beruvchiga tovarlarni qaytarishni rasmiylashtirish, qaytarish uchun kirimni tanlash, sabab va qaytariladigan tovarlar miqdorini ko\'rsatish', uiLocation: 'Главное меню → Склад → Возврат прихода', order: 3 },
  { category: 'warehouse', screenshot: 'screenshots/transfer.png', ruName: 'Трансфер', uzName: 'Transfer', ruDescription: 'Перемещение товаров между складами и торговыми точками', uzDescription: 'Tovarlarni omborlar va savdo nuqtalari orasida ko\'chirish', ruFunctionality: 'Создание документа трансфера, выбор склада-отправителя и склада-получателя, добавление товаров, отслеживание статусов: Отправлен, Получен', uzFunctionality: 'Transfer hujjatini yaratish, yuboruvchi ombor va qabul qiluvchi omborni tanlash, tovarlarni qo\'shish, holatlarni kuzatish: Yuborilgan, Qabul qilingan', uiLocation: 'Главное меню → Склад → Трансфер', order: 4 },
  { category: 'warehouse', screenshot: 'screenshots/realization.png', ruName: 'Реализация', uzName: 'Realizatsiya', ruDescription: 'Отгрузка и продажа товаров контрагентам', uzDescription: 'Tovarlarni kontragentlarga jo\'natish va sotish', ruFunctionality: 'Создание документа реализации, выбор контрагента, добавление товаров, отслеживание статусов: Черновик, Оформлен, Отправлен', uzFunctionality: 'Realizatsiya hujjatini yaratish, kontragentni tanlash, tovarlarni qo\'shish, holatlarni kuzatish: Qoralama, Rasmiylashtirilgan, Yuborilgan', uiLocation: 'Главное меню → Склад → Реализация', order: 5 },
  { category: 'warehouse', screenshot: 'screenshots/reprice.png', ruName: 'Переоценка', uzName: 'Qayta baholash', ruDescription: 'Массовое изменение цен на товары', uzDescription: 'Tovarlar narxlarini ommaviy o\'zgartirish', ruFunctionality: 'Создание документа переоценки, выбор товаров, установка новых цен, применение изменений', uzFunctionality: 'Qayta baholash hujjatini yaratish, tovarlarni tanlash, yangi narxlarni o\'rnatish, o\'zgarishlarni qo\'llash', uiLocation: 'Главное меню → Склад → Переоценка', order: 6 },
  { category: 'warehouse', screenshot: 'screenshots/inventory.png', ruName: 'Инвентаризация', uzName: 'Inventarizatsiya', ruDescription: 'Сверка фактического наличия товаров с учётными данными', uzDescription: 'Tovarlarning haqiqiy mavjudligini hisob ma\'lumotlari bilan solishtirish', ruFunctionality: 'Создание инвентаризации, выбор типа (полная/частичная), подсчёт фактических остатков, выявление расхождений, принятие результатов', uzFunctionality: 'Inventarizatsiya yaratish, turini tanlash (to\'liq/qisman), haqiqiy qoldiqlarni hisoblash, farqlarni aniqlash, natijalarni qabul qilish', uiLocation: 'Главное меню → Склад → Инвентаризация', order: 7 },
  { category: 'warehouse', screenshot: 'screenshots/writeoff.png', ruName: 'Списание', uzName: 'Yozib chiqarish', ruDescription: 'Удаление испорченных или списанных товаров', uzDescription: 'Buzilgan yoki yozib chiqarilgan tovarlarni o\'chirish', ruFunctionality: 'Создание документа списания, выбор товаров, указание причины списания и ответственного лица', uzFunctionality: 'Yozib chiqarish hujjatini yaratish, tovarlarni tanlash, yozib chiqarish sababi va mas\'ul shaxsni ko\'rsatish', uiLocation: 'Главное меню → Склад → Списание', order: 8 },
  { category: 'warehouse', screenshot: 'screenshots/grouping.png', ruName: 'Группировка', uzName: 'Guruhlash', ruDescription: 'Объединение товарных позиций для упрощения анализа', uzDescription: 'Tahlilni soddalashtirish uchun tovar pozitsiyalarini birlashtirish', ruFunctionality: 'Создание групп товаров, объединение позиций по категориям, анализ сгруппированных данных', uzFunctionality: 'Tovar guruhlarini yaratish, pozitsiyalarni kategoriyalar bo\'yicha birlashtirish, guruhlangan ma\'lumotlarni tahlil qilish', uiLocation: 'Главное меню → Склад → Группировка', order: 9 },
  { category: 'warehouse', screenshot: 'screenshots/weighted_products.png', ruName: 'Весовые товары', uzName: 'Og\'irlikli tovarlar', ruDescription: 'Учёт и продажа товаров по весу', uzDescription: 'Tovarlarni og\'irlik bo\'yicha hisobga olish va sotish', ruFunctionality: 'Настройка весовых товаров, указание единиц измерения, работа с весами при продаже', uzFunctionality: 'Og\'irlikli tovarlarni sozlash, o\'lchov birliklarini ko\'rsatish, sotishda tarozilar bilan ishlash', uiLocation: 'Главное меню → Склад → Весовые товары', order: 10 },
  { category: 'warehouse', screenshot: 'screenshots/import_products.png', ruName: 'Импорт товаров', uzName: 'Tovarlarni import qilish', ruDescription: 'Массовый импорт товаров из файлов', uzDescription: 'Tovarlarni fayllardan ommaviy import qilish', ruFunctionality: 'Загрузка файлов Excel, CSV, сопоставление полей, проверка данных, массовое добавление товаров', uzFunctionality: 'Excel, CSV fayllarini yuklash, maydonlarni moslashtirish, ma\'lumotlarni tekshirish, tovarlarni ommaviy qo\'shish', uiLocation: 'Главное меню → Склад → Импорт товаров', order: 11 },
  { category: 'warehouse', screenshot: 'screenshots/tech_cards.png', ruName: 'Техкарты', uzName: 'Tex-kartalar', ruDescription: 'Состав рецептур и калькуляция себестоимости', uzDescription: 'Retsepturalar tarkibi va tannarx kalkulyatsiyasi', ruFunctionality: 'Создание техкарт, указание состава и пропорций, автоматический расчёт себестоимости готовой продукции', uzFunctionality: 'Tex-kartalarni yaratish, tarkib va nisbatlarni ko\'rsatish, tayyor mahsulot tannarxini avtomatik hisoblash', uiLocation: 'Главное меню → Склад → Техкарты', order: 12 },
  { category: 'warehouse', screenshot: 'screenshots/manufacturing_act.png', ruName: 'Акт изготовления', uzName: 'Ishlab chiqarish akri', ruDescription: 'Фиксация выпуска готовой продукции', uzDescription: 'Tayyor mahsulot ishlab chiqarilishini qayd etish', ruFunctionality: 'Создание акта изготовления, выбор техкарты, указание количества, автоматическое списание материалов', uzFunctionality: 'Ishlab chiqarish akri yaratish, tex-kartani tanlash, miqdorni ko\'rsatish, materiallarni avtomatik yozib chiqarish', uiLocation: 'Главное меню → Склад → Акт изготовления', order: 13 },
  { category: 'warehouse', screenshot: 'screenshots/favorite_products.png', ruName: 'Избранные товары', uzName: 'Sevimli tovarlar', ruDescription: 'Быстрый доступ к часто используемым товарам', uzDescription: 'Tez-tez ishlatiladigan tovarlarga tez kirish', ruFunctionality: 'Добавление товаров в избранное, быстрый поиск и доступ к избранным товарам', uzFunctionality: 'Tovarlarni sevimlilarga qo\'shish, sevimli tovarlarni tez qidirish va ularga kirish', uiLocation: 'Главное меню → Склад → Избранные товары', order: 14 },
  { category: 'warehouse', screenshot: 'screenshots/pricetags.png', ruName: 'Ценники', uzName: 'Narx yorliqlari', ruDescription: 'Просмотр и управление ценниками товаров', uzDescription: 'Tovarlar narx yorliqlarini ko\'rish va boshqarish', ruFunctionality: 'Просмотр ценников, массовое редактирование, экспорт данных', uzFunctionality: 'Narx yorliqlarini ko\'rish, ommaviy tahrirlash, ma\'lumotlarni eksport qilish', uiLocation: 'Главное меню → Склад → Ценники', order: 15 },

  // Справочник (Reference)
  { category: 'reference', screenshot: 'screenshots/personnel.png', ruName: 'Персонал', uzName: 'Personal', ruDescription: 'Управление сотрудниками и их данными', uzDescription: 'Xodimlar va ularning ma\'lumotlarini boshqarish', ruFunctionality: 'Добавление сотрудников, указание должности и прав доступа, просмотр списка сотрудников, редактирование данных', uzFunctionality: 'Xodimlarni qo\'shish, lavozim va kirish huquqlarini ko\'rsatish, xodimlar ro\'yxatini ko\'rish, ma\'lumotlarni tahrirlash', uiLocation: 'Главное меню → Справочник → Персонал', order: 16 },
  { category: 'reference', screenshot: 'screenshots/drivers.png', ruName: 'Водители', uzName: 'Haydovchilar', ruDescription: 'Учёт водителей и их данных', uzDescription: 'Haydovchilar va ularning ma\'lumotlarini hisobga olish', ruFunctionality: 'Добавление водителей, указание контактных данных и логинов, привязка к транспортным средствам', uzFunctionality: 'Haydovchilarni qo\'shish, kontakt ma\'lumotlari va loginlarni ko\'rsatish, transport vositalariga biriktirish', uiLocation: 'Главное меню → Справочник → Водители', order: 17 },
  { category: 'reference', screenshot: 'screenshots/shifts.png', ruName: 'Смены', uzName: 'Smenalar', ruDescription: 'Контроль и ведение рабочих смен', uzDescription: 'Ish smenalarini nazorat qilish va yuritish', ruFunctionality: 'Просмотр смен по кассам и датам, открытие и закрытие смен, просмотр выручки за смену', uzFunctionality: 'Smenalarni kassa va sana bo\'yicha ko\'rish, smenalarni ochish va yopish, smena davomidagi tushumni ko\'rish', uiLocation: 'Главное меню → Справочник → Смены', order: 18 },
  { category: 'reference', screenshot: 'screenshots/z_reports.png', ruName: 'Z-отчёты', uzName: 'Z-hisobotlar', ruDescription: 'Информация об отчётах, отправленных в ОФД', uzDescription: 'OFD ga yuborilgan hisobotlar haqida ma\'lumot', ruFunctionality: 'Просмотр Z-отчётов, фильтрация по дате и кассе, экспорт данных', uzFunctionality: 'Z-hisobotlarni ko\'rish, sana va kassa bo\'yicha filtrlash, ma\'lumotlarni eksport qilish', uiLocation: 'Главное меню → Справочник → Z-отчёты', order: 19 },
  { category: 'reference', screenshot: 'screenshots/print_pricetags.png', ruName: 'Печать ценников', uzName: 'Narx yorliqlarini chop etish', ruDescription: 'Быстрая генерация и печать ценников', uzDescription: 'Narx yorliqlarini tezkor yaratish va chop etish', ruFunctionality: 'Выбор товаров для печати, настройка шаблона ценника, массовая печать', uzFunctionality: 'Chop etish uchun tovarlarni tanlash, narx yorlig\'i shablonini sozlash, ommaviy chop etish', uiLocation: 'Главное меню → Справочник → Печать ценников', order: 20 },
  { category: 'reference', screenshot: 'screenshots/clients.png', ruName: 'Клиенты', uzName: 'Mijozlar', ruDescription: 'Управление клиентской базой и данными', uzDescription: 'Mijozlar bazasini va ma\'lumotlarni boshqarish', ruFunctionality: 'Добавление клиентов, просмотр истории покупок, управление долгами и скидками, поиск по имени или телефону', uzFunctionality: 'Mijozlarni qo\'shish, xarid tarixini ko\'rish, qarz va chegirmalarni boshqarish, ism yoki telefon bo\'yicha qidirish', uiLocation: 'Главное меню → Справочник → Клиенты', order: 21 },
  { category: 'reference', screenshot: 'screenshots/loyalty.png', ruName: 'Лояльность', uzName: 'Sodiqlik', ruDescription: 'Настройка программ поощрения постоянных клиентов', uzDescription: 'Doimiy mijozlarni rag\'batlantirish dasturlarini sozlash', ruFunctionality: 'Настройка программ лояльности, начисление баллов, настройка уровней скидок, просмотр статистики участников', uzFunctionality: 'Sodiqlik dasturlarini sozlash, ballar yig\'ish, chegirma darajalarini sozlash, ishtirokchilar statistikasini ko\'rish', uiLocation: 'Главное меню → Справочник → Лояльность', order: 22 },
  { category: 'reference', screenshot: 'screenshots/contractors.png', ruName: 'Контрагенты', uzName: 'Kontragentlar', ruDescription: 'Управление поставщиками, партнёрами и организациями', uzDescription: 'Yetkazib beruvchilar, hamkorlar va tashkilotlarni boshqarish', ruFunctionality: 'Добавление контрагентов, указание контактных данных, просмотр истории взаиморасчётов, группировка по типам', uzFunctionality: 'Kontragentlarni qo\'shish, kontakt ma\'lumotlarini ko\'rsatish, o\'zaro hisob-kitob tarixini ko\'rish, turlar bo\'yicha guruhlash', uiLocation: 'Главное меню → Справочник → Контрагенты', order: 23 },
  { category: 'reference', screenshot: 'screenshots/sms_blast.png', ruName: 'СМС рассылка', uzName: 'SMS tarqatish', ruDescription: 'Массовая отправка SMS-сообщений клиентам', uzDescription: 'Mijozlarga ommaviy SMS xabarlar yuborish', ruFunctionality: 'Выбор получателей, составление сообщения, отправка SMS, просмотр статистики доставки', uzFunctionality: 'Qabul qiluvchilarni tanlash, xabar tuzish, SMS yuborish, yetkazib berish statistikasini ko\'rish', uiLocation: 'Главное меню → Справочник → СМС рассылка', order: 24 },
  { category: 'reference', screenshot: 'screenshots/sms_templates.png', ruName: 'Шаблоны СМС', uzName: 'SMS shablonlari', ruDescription: 'Создание и хранение шаблонов SMS-сообщений', uzDescription: 'SMS xabarlari shablonlarini yaratish va saqlash', ruFunctionality: 'Создание шаблонов сообщений, использование переменных, быстрый выбор при отправке', uzFunctionality: 'Xabar shablonlarini yaratish, o\'zgaruvchilardan foydalanish, yuborishda tez tanlash', uiLocation: 'Главное меню → Справочник → Шаблоны СМС', order: 25 },
  { category: 'reference', screenshot: 'screenshots/marking_audit.png', ruName: 'Аудит маркировок', uzName: 'Markirovka auditi', ruDescription: 'Проверка точности и корректности маркировок', uzDescription: 'Markirovkalarning aniqligi va to\'g\'riligini tekshirish', ruFunctionality: 'Проверка кодов маркировки, сравнение с базой, выявление ошибок, формирование отчётов', uzFunctionality: 'Markirovka kodlarini tekshirish, baza bilan solishtirish, xatolarni aniqlash, hisobotlar shakllantirish', uiLocation: 'Главное меню → Справочник → Аудит маркировок', order: 26 },
  { category: 'reference', screenshot: 'screenshots/edo.png', ruName: 'ЭДО', uzName: 'ЭДО', ruDescription: 'Электронный документооборот', uzDescription: 'Elektron hujjat aylanmasi', ruFunctionality: 'Обмен документами в электронном виде, подписание ЭЦП, отправка и получение документов', uzFunctionality: 'Hujjatlarni elektron ko\'rinishda almashinish, ESQ bilan imzolash, hujjatlarni yuborish va qabul qilish', uiLocation: 'Главное меню → Справочник → ЭДО', order: 27 },
  { category: 'reference', screenshot: 'screenshots/promotions.png', ruName: 'Акции', uzName: 'Aksiyalar', ruDescription: 'Создание скидочных кампаний и акций', uzDescription: 'Chegirma kampaniyalari va aksiyalar yaratish', ruFunctionality: 'Создание акций, настройка условий и скидок, выбор товаров-участников, отслеживание статусов', uzFunctionality: 'Aksiyalarni yaratish, shartlar va chegirmalarni sozlash, ishtirok etuvchi tovarlarni tanlash, holatlarni kuzatish', uiLocation: 'Главное меню → Справочник → Акции', order: 28 },
  { category: 'reference', screenshot: 'screenshots/documents.png', ruName: 'Документы', uzName: 'Hujjatlar', ruDescription: 'Хранение и работа с документами', uzDescription: 'Hujjatlarni saqlash va ular bilan ishlash', ruFunctionality: 'Загрузка документов, категоризация, поиск, просмотр и скачивание', uzFunctionality: 'Hujjatlarni yuklash, kategoriyalash, qidirish, ko\'rish va yuklab olish', uiLocation: 'Главное меню → Справочник → Документы', order: 29 },
  { category: 'reference', screenshot: 'screenshots/tags.png', ruName: 'Теги', uzName: 'Teglar', ruDescription: 'Управление тегами для категоризации', uzDescription: 'Kategoriyalash uchun teglarni boshqarish', ruFunctionality: 'Создание и редактирование тегов, присвоение тегов товарам и клиентам, фильтрация по тегам', uzFunctionality: 'Teglarni yaratish va tahrirlash, tovarlar va mijozlarga teglar berish, teglar bo\'yicha filtrlash', uiLocation: 'Главное меню → Справочник → Теги', order: 30 },

  // Финансовые операции (Finance)
  { category: 'finance', screenshot: 'screenshots/sold_checks.png', ruName: 'Проданные чеки', uzName: 'Sotilgan cheklar', ruDescription: 'Список всех завершённых продаж', uzDescription: 'Barcha tugallangan sotuvlar ro\'yxati', ruFunctionality: 'Просмотр проданных чеков, фильтрация по дате и сотруднику, просмотр деталей чека, печать копии', uzFunctionality: 'Sotilgan cheklarni ko\'rish, sana va xodim bo\'yicha filtrlash, chek tafsilotlarini ko\'rish, nusxasini chop etish', uiLocation: 'Главное меню → Финансы → Проданные чеки', order: 31 },
  { category: 'finance', screenshot: 'screenshots/check_returns.png', ruName: 'Возвраты чеков', uzName: 'Chek qaytarish', ruDescription: 'Учёт и обработка возвратных чеков', uzDescription: 'Qaytarilgan cheklarni hisobga olish va qayta ishlash', ruFunctionality: 'Оформление возврата чека, указание причины, возврат средств, печать чека возврата', uzFunctionality: 'Chekni qaytarishni rasmiylashtirish, sababni ko\'rsatish, mablag\'larni qaytarish, qaytarish chekini chop etish', uiLocation: 'Главное меню → Финансы → Возвраты чеков', order: 32 },
  { category: 'finance', screenshot: 'screenshots/deleted_checks.png', ruName: 'Удалённые чеки', uzName: 'O\'chirilgan cheklar', ruDescription: 'Чеки с удалёнными товарами', uzDescription: 'O\'chirilgan tovarlar bo\'lgan cheklar', ruFunctionality: 'Просмотр чеков с удалёнными позициями, восстановление товаров, история изменений', uzFunctionality: 'O\'chirilgan pozitsiyali cheklarni ko\'rish, tovarlarni qayta tiklash, o\'zgarishlar tarixi', uiLocation: 'Главное меню → Финансы → Удалённые чеки', order: 33 },
  { category: 'finance', screenshot: 'screenshots/pending_checks.png', ruName: 'Отложенные чеки', uzName: 'Kechiktirilgan cheklar', ruDescription: 'Сохранённые чеки, ожидающие оплаты', uzDescription: 'To\'lovni kutayotgan saqlangan cheklar', ruFunctionality: 'Просмотр отложенных чеков, продолжение оформления, удаление отложенных чеков', uzFunctionality: 'Kechiktirilgan cheklarni ko\'rish, rasmiylashtirishni davom ettirish, kechiktirilgan cheklarni o\'chirish', uiLocation: 'Главное меню → Финансы → Отложенные чеки', order: 34 },
  { category: 'finance', screenshot: 'screenshots/mutual_settlements.png', ruName: 'Взаиморасчёт', uzName: 'O\'zaro hisob-kitob', ruDescription: 'Контроль взаимных задолженностей и платежей', uzDescription: 'O\'zaro qarzlar va to\'lovlarni nazorat qilish', ruFunctionality: 'Просмотр начального остатка, кредита, дебета, конечного итога по контрагентам', uzFunctionality: 'Boshlang\'ich qoldiq, kredit, debit, kontragentlar bo\'yicha yakuniy natijani ko\'rish', uiLocation: 'Главное меню → Финансы → Взаиморасчёт', order: 35 },
  { category: 'finance', screenshot: 'screenshots/accounts.png', ruName: 'Счета', uzName: 'Hisoblar', ruDescription: 'Создание, ведение и оплата счетов', uzDescription: 'Hisoblarni yaratish, yuritish va to\'lash', ruFunctionality: 'Создание счетов, отправка клиентам, отслеживание оплаты, печать счетов', uzFunctionality: 'Hisoblarni yaratish, mijozlarga yuborish, to\'lovni kuzatish, hisoblarni chop etish', uiLocation: 'Главное меню → Финансы → Счета', order: 36 },
  { category: 'finance', screenshot: 'screenshots/salary.png', ruName: 'Зарплата', uzName: 'Ish haqi', ruDescription: 'Расчёт и выплата заработной платы', uzDescription: 'Ish haqini hisoblash va to\'lash', ruFunctionality: 'Настройка окладов и премий, расчёт зарплаты, учёт выплат, формирование ведомостей', uzFunctionality: 'Oylik va mukofotlarni sozlash, ish haqini hisoblash, to\'lovlarni hisobga olish, hisobotlar tuzish', uiLocation: 'Главное меню → Финансы → Зарплата', order: 37 },
  { category: 'finance', screenshot: 'screenshots/cash_registers.png', ruName: 'Кассы', uzName: 'Kassalar', ruDescription: 'Управление кассами и денежными средствами', uzDescription: 'Kassalar va pul mablag\'larini boshqarish', ruFunctionality: 'Создание касс, просмотр остатков, перемещение средств между кассами', uzFunctionality: 'Kassalarni yaratish, qoldiqlarni ko\'rish, kassalar orasida mablag\'larni ko\'chirish', uiLocation: 'Главное меню → Финансы → Кассы', order: 38 },
  { category: 'finance', screenshot: 'screenshots/payment_methods.png', ruName: 'Способы оплаты', uzName: 'To\'lov usullari', ruDescription: 'Настройка способов приёма платежей', uzDescription: 'To\'lovlarni qabul qilish usullarini sozlash', ruFunctionality: 'Добавление способов оплаты (наличные, карта, терминал и др.), настройка комиссий', uzFunctionality: 'To\'lov usullarini qo\'shish (naqd pul, karta, terminal va boshqalar), komissiyalarni sozlash', uiLocation: 'Главное меню → Финансы → Способы оплаты', order: 39 },
  { category: 'finance', screenshot: 'screenshots/balance.png', ruName: 'Баланс', uzName: 'Balans', ruDescription: 'Обзор финансового состояния', uzDescription: 'Moliyaviy holatni ko\'rish', ruFunctionality: 'Просмотр общего баланса, движение средств, остатки по счетам и кассам', uzFunctionality: 'Umumiy balansni ko\'rish, mablag\'lar harakati, hisoblar va kassalar bo\'yicha qoldiqlar', uiLocation: 'Главное меню → Финансы → Баланс', order: 40 },

  // Отчёты (Reports)
  { category: 'reports', screenshot: 'screenshots/dashboard.png', ruName: 'Панель управления', uzName: 'Boshqaruv paneli', ruDescription: 'Обзор ключевых показателей бизнеса', uzDescription: 'Biznesning asosiy ko\'rsatkichlarini ko\'rish', ruFunctionality: 'Просмотр выручки, продаж, остатков, графиков и диаграмм в режиме реального времени', uzFunctionality: 'Tushum, sotuvlar, qoldiqlar, grafiklar va diagrammalarni real vaqtda ko\'rish', uiLocation: 'Главное меню → Отчёты → Панель управления', order: 41 },
  { category: 'reports', screenshot: 'screenshots/abc_report.png', ruName: 'ABC отчёт', uzName: 'ABC hisobot', ruDescription: 'Анализ товаров по категориям важности', uzDescription: 'Tovarlarni ahamiyat kategoriyalari bo\'yicha tahlil qilish', ruFunctionality: 'Классификация товаров по категориям A, B, C на основе вклада в выручку', uzFunctionality: 'Tovarlarni tushumga qo\'shgan hissasi asosida A, B, C kategoriyalariga ajratish', uiLocation: 'Главное меню → Отчёты → ABC отчёт', order: 42 },
  { category: 'reports', screenshot: 'screenshots/xyz_report.png', ruName: 'XYZ отчёт', uzName: 'XYZ hisobot', ruDescription: 'Анализ стабильности спроса', uzDescription: 'Talab barqarorligini tahlil qilish', ruFunctionality: 'Классификация товаров по стабильности спроса: X (стабильный), Y (сезонный), Z (нерегулярный)', uzFunctionality: 'Tovarlarni talab barqarorligi bo\'yicha tasniflash: X (barqaror), Y (mavsumiy), Z (noqonuniy)', uiLocation: 'Главное меню → Отчёты → XYZ отчёт', order: 43 },
  { category: 'reports', screenshot: 'screenshots/abc_xyz_report.png', ruName: 'ABC-XYZ отчёт', uzName: 'ABC-XYZ hisobot', ruDescription: 'Комплексный анализ товаров', uzDescription: 'Tovarlarni kompleks tahlil qilish', ruFunctionality: 'Сочетание ABC и XYZ анализа для оптимизации управления запасами', uzFunctionality: 'Zaxiralarni boshqarishni optimallashtirish uchun ABC va XYZ tahlilini birlashtirish', uiLocation: 'Главное меню → Отчёты → ABC-XYZ отчёт', order: 44 },
  { category: 'reports', screenshot: 'screenshots/sales_report.png', ruName: 'Отчёт по продажам', uzName: 'Sotuvlar hisoboti', ruDescription: 'Детальная статистика продаж', uzDescription: 'Sotuvlarning batafsil statistikasi', ruFunctionality: 'Просмотр продаж по периодам, товарам, категориям, сотрудникам, экспорт данных', uzFunctionality: 'Sotuvlarni davrlar, tovarlar, kategoriyalar, xodimlar bo\'yicha ko\'rish, ma\'lumotlarni eksport qilish', uiLocation: 'Главное меню → Отчёты → Отчёт по продажам', order: 45 },
  { category: 'reports', screenshot: 'screenshots/top_sales.png', ruName: 'Топ продаж', uzName: 'Sotuvlar reytingi', ruDescription: 'Рейтинг лучших продаж', uzDescription: 'Eng yaxshi sotuvlar reytingi', ruFunctionality: 'Просмотр топ продаваемых товаров, сотрудников, категорий за период', uzFunctionality: 'Davr davomida eng ko\'p sotilgan tovarlar, xodimlar, kategoriyalarni ko\'rish', uiLocation: 'Главное меню → Отчёты → Топ продаж', order: 46 },
  { category: 'reports', screenshot: 'screenshots/product_report.png', ruName: 'Отчёт по товарам', uzName: 'Tovarlar hisoboti', ruDescription: 'Статистика по товарам', uzDescription: 'Tovarlar bo\'yicha statistika', ruFunctionality: 'Просмотр движения товаров, остатков, оборачиваемости, прибыльности', uzFunctionality: 'Tovarlar harakati, qoldiqlar, aylanma, daromadlilikni ko\'rish', uiLocation: 'Главное меню → Отчёты → Отчёт по товарам', order: 47 },
  { category: 'reports', screenshot: 'screenshots/params_report.png', ruName: 'Отчёт по параметрам', uzName: 'Parametrlar hisoboti', ruDescription: 'Анализ по дополнительным параметрам товаров', uzDescription: 'Tovarlarning qo\'shimcha parametrlari bo\'yicha tahlil', ruFunctionality: 'Анализ продаж и остатков по цвету, размеру, бренду и другим параметрам', uzFunctionality: 'Sotuvlar va qoldiqlarni rang, o\'lcham, brend va boshqa parametrlar bo\'yicha tahlil qilish', uiLocation: 'Главное меню → Отчёты → Отчёт по параметрам', order: 48 },
  { category: 'reports', screenshot: 'screenshots/material_report.png', ruName: 'Материальный отчёт', uzName: 'Material hisobot', ruDescription: 'Отчёт по материалам и сырью', uzDescription: 'Materiallar va xom ashyo bo\'yicha hisobot', ruFunctionality: 'Просмотр движения материалов, остатков, списания на производство', uzFunctionality: 'Materiallar harakati, qoldiqlar, ishlab chiqarishga yozib chiqarishni ko\'rish', uiLocation: 'Главное меню → Отчёты → Материальный отчёт', order: 49 },
  { category: 'reports', screenshot: 'screenshots/pl_report.png', ruName: 'P&L отчёт', uzName: 'P&L hisobot', ruDescription: 'Отчёт о прибылях и убытках', uzDescription: 'Foyda va zarar hisoboti', ruFunctionality: 'Просмотр доходов, расходов, валовой и чистой прибыли', uzFunctionality: 'Daromadlar, xarajatlar, yalpi va sof foydani ko\'rish', uiLocation: 'Главное меню → Отчёты → P&L отчёт', order: 50 },
  { category: 'reports', screenshot: 'screenshots/no_movement.png', ruName: 'Нет движения', uzName: 'Harakatsiz', ruDescription: 'Товары без движения за период', uzDescription: 'Davr davomida harakatsiz tovarlar', ruFunctionality: 'Выявление товаров без продаж и закупок за указанный период', uzFunctionality: 'Ko\'rsatilgan davr davomida sotuv va xarid bo\'lmagan tovarlarni aniqlash', uiLocation: 'Главное меню → Отчёты → Нет движения', order: 51 },

  // Настройки (Settings)
  { category: 'settings', screenshot: 'screenshots/company_data.png', ruName: 'Данные компании', uzName: 'Kompaniya ma\'lumotlari', ruDescription: 'Настройка информации о компании', uzDescription: 'Kompaniya haqida ma\'lumotlarni sozlash', ruFunctionality: 'Ввод названия, адреса, контактов, реквизитов компании, загрузка логотипа', uzFunctionality: 'Kompaniya nomi, manzili, kontaktlari, rekvizitlarini kiritish, logotipni yuklash', uiLocation: 'Главное меню → Настройки → Данные компании', order: 52 },
  { category: 'settings', screenshot: 'screenshots/tariffs.png', ruName: 'Тарифы', uzName: 'Tariflar', ruDescription: 'Управление тарифными планами', uzDescription: 'Tarif rejalarini boshqarish', ruFunctionality: 'Просмотр текущего тарифа, смена тарифа, просмотр истории платежей', uzFunctionality: 'Joriy tarifni ko\'rish, tarifni o\'zgartirish, to\'lovlar tarixini ko\'rish', uiLocation: 'Главное меню → Настройки → Тарифы', order: 53 },
  { category: 'settings', screenshot: 'screenshots/subscriptions.png', ruName: 'Подписки', uzName: 'Obunalar', ruDescription: 'Управление подписками на услуги', uzDescription: 'Xizmatlarga obunalarni boshqarish', ruFunctionality: 'Просмотр активных подписок, подключение и отключение дополнительных услуг', uzFunctionality: 'Faol obunalarni ko\'rish, qo\'shimcha xizmatlarni ulash va uzish', uiLocation: 'Главное меню → Настройки → Подписки', order: 54 },
  { category: 'settings', screenshot: 'screenshots/devices.png', ruName: 'Устройства', uzName: 'Qurilmalar', ruDescription: 'Управление подключёнными устройствами', uzDescription: 'Ulangan qurilmalarni boshqarish', ruFunctionality: 'Просмотр списка устройств, привязка новых устройств, отвязка устройств', uzFunctionality: 'Qurilmalar ro\'yxatini ko\'rish, yangi qurilmalarni ulash, qurilmalarni uzish', uiLocation: 'Главное меню → Настройки → Устройства', order: 55 },
  { category: 'settings', screenshot: 'screenshots/pricing.png', ruName: 'Цены', uzName: 'Narxlar', ruDescription: 'Настройка типов цен', uzDescription: 'Narx turlarini sozlash', ruFunctionality: 'Создание типов цен (розничная, оптовая и др.), настройка наценок и скидок', uzFunctionality: 'Narx turlarini yaratish (chakana, ulgurji va boshqalar), qo\'shimcha narxlar va chegirmalarni sozlash', uiLocation: 'Главное меню → Настройки → Цены', order: 56 },
  { category: 'settings', screenshot: 'screenshots/parameters.png', ruName: 'Параметры', uzName: 'Parametrlar', ruDescription: 'Настройка дополнительных параметров товаров', uzDescription: 'Tovarlarning qo\'shimcha parametrlarini sozlash', ruFunctionality: 'Создание параметров (цвет, размер, бренд и др.), настройка значений', uzFunctionality: 'Parametrlarni yaratish (rang, o\'lcham, brend va boshqalar), qiymatlarni sozlash', uiLocation: 'Главное меню → Настройки → Параметры', order: 57 },
  { category: 'settings', screenshot: 'screenshots/checks_settings.png', ruName: 'Настройки чеков', uzName: 'Chek sozlamalari', ruDescription: 'Настройка параметров печати чеков', uzDescription: 'Chek chop etish parametrlarini sozlash', ruFunctionality: 'Настройка заголовка и подвала чека, логотипа, реквизитов, формата', uzFunctionality: 'Chek sarlavhasi va tag qismini, logotip, rekvizitlar, formatni sozlash', uiLocation: 'Главное меню → Настройки → Настройки чеков', order: 58 },
  { category: 'settings', screenshot: 'screenshots/interface.png', ruName: 'Интерфейс', uzName: 'Interfeys', ruDescription: 'Настройка внешнего вида системы', uzDescription: 'Tizimning tashqi ko\'rinishini sozlash', ruFunctionality: 'Выбор языка, настройка темы, цветовой схемы', uzFunctionality: 'Tilni tanlash, mavzuni sozlash, rang sxemasini sozlash', uiLocation: 'Главное меню → Настройки → Интерфейс', order: 59 },
  { category: 'settings', screenshot: 'screenshots/telegram_bot.png', ruName: 'Telegram бот', uzName: 'Telegram bot', ruDescription: 'Настройка интеграции с Telegram', uzDescription: 'Telegram bilan integratsiyani sozlash', ruFunctionality: 'Подключение Telegram бота, настройка уведомлений, команды бота', uzFunctionality: 'Telegram botini ulash, bildirishnomalarni sozlash, bot buyruqlari', uiLocation: 'Главное меню → Настройки → Telegram бот', order: 60 },
];

async function main() {
  console.log('Starting seed...');

  // Clear existing lessons
  await prisma.lesson.deleteMany({});
  console.log('Cleared existing lessons');

  // Insert new lessons
  for (const lesson of lessons) {
    await prisma.lesson.create({
      data: lesson,
    });
  }

  console.log(`Inserted ${lessons.length} lessons`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
