// 200 lessons about Lume Admin buttons and features
// Run: npx ts-node scripts/seed-lessons.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const lessons = [
  // === ГЛАВНАЯ (1-5) ===
  { category: 'cabinet', ruName: 'Главная', uzName: 'Bosh sahifa', ruDescription: 'Главная страница с обзором всех функций', uzDescription: 'Barcha funksiyalar sharhi bilan bosh sahifa', ruFunctionality: 'Открывает дашборд с быстрым доступом к основным разделам', uzFunctionality: 'Asosiy bo\'limlarga tez kirish bilan dashbordni ochadi', uiLocation: 'Боковое меню → Главная', order: 1 },
  { category: 'cabinet', ruName: 'Баланс', uzName: 'Balans', ruDescription: 'Отображение текущего баланса счёта', uzDescription: 'Hisobning joriy balansini ko\'rsatish', ruFunctionality: 'Показывает баланс в верхней части меню, при клике открывает детали', uzFunctionality: 'Menyu yuqori qismida balansni ko\'rsatadi, bosilganda tafsilotlarni ochadi', uiLocation: 'Верхняя панель → Баланс', order: 2 },
  { category: 'cabinet', ruName: 'Пополнение', uzName: 'To\'ldirish', ruDescription: 'Кнопка пополнения баланса', uzDescription: 'Balansni to\'ldirish tugmasi', ruFunctionality: 'Открывает форму пополнения баланса через платёжные системы', uzFunctionality: 'To\'lov tizimlari orqali balansni to\'ldirish formasini ochadi', uiLocation: 'Верхняя панель → Пополнение', order: 3 },
  { category: 'cabinet', ruName: 'Профиль пользователя', uzName: 'Foydalanuvchi profili', ruDescription: 'Открытие профиля текущего пользователя', uzDescription: 'Joriy foydalanuvchi profilini ochish', ruFunctionality: 'При клике на имя пользователя открывается меню с настройками профиля', uzFunctionality: 'Foydalanuvchi ismi bosilganda profil sozlamalari bilan menyu ochiladi', uiLocation: 'Верхняя панель → Имя пользователя', order: 4 },
  { category: 'cabinet', ruName: 'Выход', uzName: 'Chiqish', ruDescription: 'Кнопка выхода из системы', uzDescription: 'Tizimdan chiqish tugmasi', ruFunctionality: 'Завершает сессию и перенаправляет на страницу входа', uzFunctionality: 'Sessiyani tugatib, kirish sahifasiga yo\'naltiradi', uiLocation: 'Боковое меню → Кабинет → Выход', order: 5 },

  // === СКЛАД: ТОВАРЫ (6-20) ===
  { category: 'warehouse', ruName: 'Товары', uzName: 'Tovarlar', ruDescription: 'Раздел управления товарами', uzDescription: 'Tovarlarni boshqarish bo\'limi', ruFunctionality: 'Открывает список всех товаров с поиском и фильтрами', uzFunctionality: 'Qidiruv va filtrlar bilan barcha tovarlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Товары', order: 6 },
  { category: 'warehouse', ruName: 'Добавить товар', uzName: 'Tovar qo\'shish', ruDescription: 'Кнопка создания нового товара', uzDescription: 'Yangi tovar yaratish tugmasi', ruFunctionality: 'Открывает форму для добавления нового товара в базу', uzFunctionality: 'Bazaga yangi tovar qo\'shish uchun formani ochadi', uiLocation: 'Товары → Кнопка "Добавить"', order: 7 },
  { category: 'warehouse', ruName: 'Поиск товаров', uzName: 'Tovarlarni qidirish', ruDescription: 'Поле поиска по товарам', uzDescription: 'Tovarlar bo\'yicha qidiruv maydoni', ruFunctionality: 'Позволяет искать товары по названию, артикулу или штрих-коду', uzFunctionality: 'Tovarlarni nom, artikul yoki shtrix-kod bo\'yicha qidirishga imkon beradi', uiLocation: 'Товары → Поле поиска', order: 8 },
  { category: 'warehouse', ruName: 'Фильтр по категории', uzName: 'Kategoriya bo\'yicha filtr', ruDescription: 'Фильтрация товаров по категориям', uzDescription: 'Tovarlarni kategoriyalar bo\'yicha filtrlash', ruFunctionality: 'Позволяет отфильтровать список товаров по выбранной категории', uzFunctionality: 'Tanlangan kategoriya bo\'yicha tovarlar ro\'yxatini filtrlashga imkon beradi', uiLocation: 'Товары → Фильтры → Категория', order: 9 },
  { category: 'warehouse', ruName: 'Фильтр по складу', uzName: 'Ombor bo\'yicha filtr', ruDescription: 'Фильтрация товаров по складам', uzDescription: 'Tovarlarni omborlar bo\'yicha filtrlash', ruFunctionality: 'Показывает товары конкретного склада или торговой точки', uzFunctionality: 'Ma\'lum ombor yoki savdo nuqtasining tovarlarini ko\'rsatadi', uiLocation: 'Товары → Фильтры → Склад', order: 10 },
  { category: 'warehouse', ruName: 'Редактировать товар', uzName: 'Tovarni tahrirlash', ruDescription: 'Кнопка редактирования товара', uzDescription: 'Tovarni tahrirlash tugmasi', ruFunctionality: 'Открывает форму редактирования выбранного товара', uzFunctionality: 'Tanlangan tovarni tahrirlash formasini ochadi', uiLocation: 'Товары → Иконка карандаша', order: 11 },
  { category: 'warehouse', ruName: 'Удалить товар', uzName: 'Tovarni o\'chirish', ruDescription: 'Кнопка удаления товара', uzDescription: 'Tovarni o\'chirish tugmasi', ruFunctionality: 'Удаляет выбранный товар из базы после подтверждения', uzFunctionality: 'Tasdiqlangandan so\'ng tanlangan tovarni bazadan o\'chiradi', uiLocation: 'Товары → Иконка корзины', order: 12 },
  { category: 'warehouse', ruName: 'Экспорт товаров', uzName: 'Tovarlarni eksport', ruDescription: 'Экспорт списка товаров в файл', uzDescription: 'Tovarlar ro\'yxatini faylga eksport qilish', ruFunctionality: 'Позволяет выгрузить список товаров в Excel или CSV', uzFunctionality: 'Tovarlar ro\'yxatini Excel yoki CSV ga yuklab olish imkonini beradi', uiLocation: 'Товары → Кнопка "Экспорт"', order: 13 },
  { category: 'warehouse', ruName: 'Карточка товара', uzName: 'Tovar kartochkasi', ruDescription: 'Открытие детальной карточки товара', uzDescription: 'Tovarning batafsil kartochkasini ochish', ruFunctionality: 'Показывает полную информацию о товаре: остатки, цены, движение', uzFunctionality: 'Tovar haqida to\'liq ma\'lumotni ko\'rsatadi: qoldiqlar, narxlar, harakat', uiLocation: 'Товары → Клик на название товара', order: 14 },
  { category: 'warehouse', ruName: 'Добавить в избранное', uzName: 'Sevimlilarga qo\'shish', ruDescription: 'Добавление товара в избранное', uzDescription: 'Tovarni sevimlilarga qo\'shish', ruFunctionality: 'Сохраняет товар в списке избранных для быстрого доступа', uzFunctionality: 'Tovarni tez kirish uchun sevimlilar ro\'yxatida saqlaydi', uiLocation: 'Товары → Иконка звезды', order: 15 },
  { category: 'warehouse', ruName: 'Массовое редактирование', uzName: 'Ommaviy tahrirlash', ruDescription: 'Редактирование нескольких товаров', uzDescription: 'Bir nechta tovarlarni tahrirlash', ruFunctionality: 'Позволяет изменить цену или категорию для выбранных товаров', uzFunctionality: 'Tanlangan tovarlar uchun narx yoki kategoriyani o\'zgartirishga imkon beradi', uiLocation: 'Товары → Чекбоксы → Массовые действия', order: 16 },
  { category: 'warehouse', ruName: 'Печать ценника', uzName: 'Narx yorlig\'ini chop etish', ruDescription: 'Печать ценника для товара', uzDescription: 'Tovar uchun narx yorlig\'ini chop etish', ruFunctionality: 'Формирует и печатает ценник для выбранного товара', uzFunctionality: 'Tanlangan tovar uchun narx yorlig\'ini shakllantirib chop etadi', uiLocation: 'Товары → Кнопка "Печать ценника"', order: 17 },
  { category: 'warehouse', ruName: 'Копировать товар', uzName: 'Tovarni nusxalash', ruDescription: 'Создание копии товара', uzDescription: 'Tovar nusxasini yaratish', ruFunctionality: 'Создаёт дубликат товара с теми же характеристиками', uzFunctionality: 'Xuddi shu xususiyatlarga ega tovar dublikatini yaratadi', uiLocation: 'Товары → Кнопка "Копировать"', order: 18 },
  { category: 'warehouse', ruName: 'История изменений', uzName: 'O\'zgarishlar tarixi', ruDescription: 'Просмотр истории изменений товара', uzDescription: 'Tovar o\'zgarishlari tarixini ko\'rish', ruFunctionality: 'Показывает все изменения цены, остатков и других данных товара', uzFunctionality: 'Narx, qoldiqlar va boshqa tovar ma\'lumotlarining barcha o\'zgarishlarini ko\'rsatadi', uiLocation: 'Товары → Карточка товара → История', order: 19 },
  { category: 'warehouse', ruName: 'Штрих-код товара', uzName: 'Tovar shtrix-kodi', ruDescription: 'Просмотр и печать штрих-кода', uzDescription: 'Shtrix-kodni ko\'rish va chop etish', ruFunctionality: 'Показывает штрих-код товара с возможностью печати', uzFunctionality: 'Chop etish imkoniyati bilan tovar shtrix-kodini ko\'rsatadi', uiLocation: 'Товары → Карточка товара → Штрих-код', order: 20 },

  // === СКЛАД: ПРИХОД (21-35) ===
  { category: 'warehouse', ruName: 'Приход', uzName: 'Kirim', ruDescription: 'Раздел оформления поступлений товаров', uzDescription: 'Tovarlar kelib tushishini rasmiylashtirish bo\'limi', ruFunctionality: 'Открывает список документов поступления товаров от поставщиков', uzFunctionality: 'Yetkazib beruvchilardan tovarlar kelib tushishi hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Приход', order: 21 },
  { category: 'warehouse', ruName: 'Создать приход', uzName: 'Kirim yaratish', ruDescription: 'Кнопка создания документа прихода', uzDescription: 'Kirim hujjatini yaratish tugmasi', ruFunctionality: 'Открывает форму для создания нового документа поступления', uzFunctionality: 'Yangi kelib tushish hujjatini yaratish uchun formani ochadi', uiLocation: 'Приход → Кнопка "Создать"', order: 22 },
  { category: 'warehouse', ruName: 'Выбор поставщика', uzName: 'Yetkazib beruvchini tanlash', ruDescription: 'Выбор контрагента-поставщика', uzDescription: 'Yetkazib beruvchi kontragentni tanlash', ruFunctionality: 'Позволяет выбрать поставщика из списка контрагентов', uzFunctionality: 'Kontragentlar ro\'yxatidan yetkazib beruvchini tanlash imkonini beradi', uiLocation: 'Приход → Форма → Поле "Поставщик"', order: 23 },
  { category: 'warehouse', ruName: 'Добавить товары в приход', uzName: 'Kirimga tovar qo\'shish', ruDescription: 'Добавление товаров в документ прихода', uzDescription: 'Kirim hujjatiga tovar qo\'shish', ruFunctionality: 'Открывает форму выбора товаров для добавления в документ', uzFunctionality: 'Hujjatga qo\'shish uchun tovarlarni tanlash formasini ochadi', uiLocation: 'Приход → Форма → Кнопка "Добавить товар"', order: 24 },
  { category: 'warehouse', ruName: 'Статус "Черновик"', uzName: '"Qoralama" holati', ruDescription: 'Статус черновика документа', uzDescription: 'Hujjat qoralama holati', ruFunctionality: 'Документ сохраняется как черновик, можно редактировать', uzFunctionality: 'Hujjat qoralama sifatida saqlanadi, tahrirlash mumkin', uiLocation: 'Приход → Статусы → Черновик', order: 25 },
  { category: 'warehouse', ruName: 'Статус "Оформлен"', uzName: '"Rasmiylashtirilgan" holati', ruDescription: 'Проведение документа прихода', uzDescription: 'Kirim hujjatini o\'tkazish', ruFunctionality: 'Документ проводится, товары зачисляются на склад', uzFunctionality: 'Hujjat o\'tkaziladi, tovarlar omborga qabul qilinadi', uiLocation: 'Приход → Статусы → Оформлен', order: 26 },
  { category: 'warehouse', ruName: 'Печать прихода', uzName: 'Kirimni chop etish', ruDescription: 'Печать документа прихода', uzDescription: 'Kirim hujjatini chop etish', ruFunctionality: 'Формирует печатную форму документа для печати', uzFunctionality: 'Chop etish uchun hujjatning bosma shaklini yaratadi', uiLocation: 'Приход → Кнопка "Печать"', order: 27 },
  { category: 'warehouse', ruName: 'Удалить приход', uzName: 'Kirimni o\'chirish', ruDescription: 'Удаление документа прихода', uzDescription: 'Kirim hujjatini o\'chirish', ruFunctionality: 'Удаляет документ прихода (только в статусе черновика)', uzFunctionality: 'Kirim hujjatini o\'chiradi (faqat qoralama holatida)', uiLocation: 'Приход → Кнопка "Удалить"', order: 28 },
  { category: 'warehouse', ruName: 'Фильтр приходов по дате', uzName: 'Kirimlarni sana bo\'yicha filtrlash', ruDescription: 'Фильтрация документов по периоду', uzDescription: 'Hujjatlarni davr bo\'yicha filtrlash', ruFunctionality: 'Позволяет отфильтровать документы за выбранный период', uzFunctionality: 'Tanlangan davr uchun hujjatlarni filtrlashga imkon beradi', uiLocation: 'Приход → Фильтры → Дата', order: 29 },
  { category: 'warehouse', ruName: 'Фильтр приходов по поставщику', uzName: 'Kirimlarni yetkazib beruvchi bo\'yicha filtrlash', ruDescription: 'Фильтрация по контрагенту', uzDescription: 'Kontragent bo\'yicha filtrlash', ruFunctionality: 'Показывает документы выбранного поставщика', uzFunctionality: 'Tanlangan yetkazib beruvchining hujjatlarini ko\'rsatadi', uiLocation: 'Приход → Фильтры → Поставщик', order: 30 },
  { category: 'warehouse', ruName: 'Копировать приход', uzName: 'Kirimni nusxalash', ruDescription: 'Создание копии документа', uzDescription: 'Hujjat nusxasini yaratish', ruFunctionality: 'Создаёт новый документ на основе существующего', uzFunctionality: 'Mavjud asosda yangi hujjat yaratadi', uiLocation: 'Приход → Кнопка "Копировать"', order: 31 },
  { category: 'warehouse', ruName: 'Провести приход', uzName: 'Kirimni o\'tkazish', ruDescription: 'Кнопка проведения документа', uzDescription: 'Hujjatni o\'tkazish tugmasi', ruFunctionality: 'Проводит документ и зачисляет товары на склад', uzFunctionality: 'Hujjatni o\'tkazadi va tovarlarni omborga qabul qiladi', uiLocation: 'Приход → Кнопка "Провести"', order: 32 },
  { category: 'warehouse', ruName: 'Отменить проведение', uzName: 'O\'tkazishni bekor qilish', ruDescription: 'Отмена проведённого документа', uzDescription: 'O\'tkazilgan hujjatni bekor qilish', ruFunctionality: 'Отменяет проведение и возвращает товары поставщику', uzFunctionality: 'O\'tkazishni bekor qiladi va tovarlarni yetkazib beruvchiga qaytaradi', uiLocation: 'Приход → Кнопка "Отменить"', order: 33 },
  { category: 'warehouse', ruName: 'Расширения прихода', uzName: 'Kirim kengaytmalari', ruDescription: 'Дополнительные поля документа', uzDescription: 'Hujjatning qo\'shimcha maydonlari', ruFunctionality: 'Позволяет добавить комментарий, номер накладной и другие данные', uzFunctionality: 'Izoh, nakladnaya raqami va boshqa ma\'lumotlarni qo\'shishga imkon beradi', uiLocation: 'Приход → Форма → Расширения', order: 34 },
  { category: 'warehouse', ruName: 'Сканер штрих-кода', uzName: 'Shtrix-kod skaneri', ruDescription: 'Сканирование товаров при приходе', uzDescription: 'Kirimda tovarlarni skanerlash', ruFunctionality: 'Позволяет добавлять товары сканированием штрих-кода', uzFunctionality: 'Shtrix-kodni skanerlab tovar qo\'shishga imkon beradi', uiLocation: 'Приход → Иконка сканера', order: 35 },

  // === СКЛАД: ВОЗВРАТ ПРИХОДА (36-40) ===
  { category: 'warehouse', ruName: 'Возврат прихода', uzName: 'Kirimni qaytarish', ruDescription: 'Раздел возвратов товаров поставщикам', uzDescription: 'Yetkazib beruvchilarga tovarlarni qaytarish bo\'limi', ruFunctionality: 'Открывает список документов возврата товаров поставщикам', uzFunctionality: 'Yetkazib beruvchilarga tovar qaytarish hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Возврат прихода', order: 36 },
  { category: 'warehouse', ruName: 'Создать возврат прихода', uzName: 'Kirim qaytarish yaratish', ruDescription: 'Создание документа возврата', uzDescription: 'Qaytarish hujjatini yaratish', ruFunctionality: 'Открывает форму для создания возврата поставщику', uzFunctionality: 'Yetkazib beruvchiga qaytarish yaratish uchun formani ochadi', uiLocation: 'Возврат прихода → Кнопка "Создать"', order: 37 },
  { category: 'warehouse', ruName: 'Выбор прихода для возврата', uzName: 'Qaytarish uchun kirimni tanlash', ruDescription: 'Выбор документа для возврата', uzDescription: 'Qaytarish uchun hujjatni tanlash', ruFunctionality: 'Позволяет выбрать приход, из которого возвращаются товары', uzFunctionality: 'Tovarlar qaytarilayotgan kirimni tanlash imkonini beradi', uiLocation: 'Возврат прихода → Выбор документа', order: 38 },
  { category: 'warehouse', ruName: 'Причина возврата', uzName: 'Qaytarish sababi', ruDescription: 'Указание причины возврата', uzDescription: 'Qaytarish sababini ko\'rsatish', ruFunctionality: 'Позволяет указать причину возврата товара', uzFunctionality: 'Tovarni qaytarish sababini ko\'rsatish imkonini beradi', uiLocation: 'Возврат прихода → Поле "Причина"', order: 39 },
  { category: 'warehouse', ruName: 'Печать возврата', uzName: 'Qaytarishni chop etish', ruDescription: 'Печать документа возврата', uzDescription: 'Qaytarish hujjatini chop etish', ruFunctionality: 'Формирует печатную форму документа возврата', uzFunctionality: 'Qaytarish hujjatining bosma shaklini yaratadi', uiLocation: 'Возврат прихода → Кнопка "Печать"', order: 40 },

  // === СКЛАД: ТРАНСФЕР (41-50) ===
  { category: 'warehouse', ruName: 'Трансфер', uzName: 'Transfer', ruDescription: 'Раздел перемещения товаров', uzDescription: 'Tovarlarni ko\'chirish bo\'limi', ruFunctionality: 'Открывает список документов перемещения товаров между складами', uzFunctionality: 'Omborlar orasida tovar ko\'chirish hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Трансфер', order: 41 },
  { category: 'warehouse', ruName: 'Создать трансфер', uzName: 'Transfer yaratish', ruDescription: 'Создание документа перемещения', uzDescription: 'Ko\'chirish hujjatini yaratish', ruFunctionality: 'Открывает форму для создания документа перемещения', uzFunctionality: 'Ko\'chirish hujjatini yaratish uchun formani ochadi', uiLocation: 'Трансфер → Кнопка "Создать"', order: 42 },
  { category: 'warehouse', ruName: 'Склад-отправитель', uzName: 'Yuboruvchi ombor', ruDescription: 'Выбор склада отправления', uzDescription: 'Yuborish omborini tanlash', ruFunctionality: 'Позволяет выбрать склад, с которого отправляются товары', uzFunctionality: 'Tovarlar yuborilayotgan omborni tanlash imkonini beradi', uiLocation: 'Трансфер → Форма → Поле "Отправитель"', order: 43 },
  { category: 'warehouse', ruName: 'Склад-получатель', uzName: 'Qabul qiluvchi ombor', ruDescription: 'Выбор склада получения', uzDescription: 'Qabul qilish omborini tanlash', ruFunctionality: 'Позволяет выбрать склад, на который поступят товары', uzFunctionality: 'Tovarlar keladigan omborni tanlash imkonini beradi', uiLocation: 'Трансфер → Форма → Поле "Получатель"', order: 44 },
  { category: 'warehouse', ruName: 'Статус "Отправлен"', uzName: '"Yuborilgan" holati', ruDescription: 'Статус отправленного трансфера', uzDescription: 'Yuborilgan transfer holati', ruFunctionality: 'Товары списаны со склада-отправителя', uzFunctionality: 'Tovarlar yuboruvchi ombordan yozib chiqarildi', uiLocation: 'Трансфер → Статусы → Отправлен', order: 45 },
  { category: 'warehouse', ruName: 'Статус "Получен"', uzName: '"Qabul qilingan" holati', ruDescription: 'Статус полученного трансфера', uzDescription: 'Qabul qilingan transfer holati', ruFunctionality: 'Товары зачислены на склад-получатель', uzFunctionality: 'Tovarlar qabul qiluvchi omborga qabul qilindi', uiLocation: 'Трансфер → Статусы → Получен', order: 46 },
  { category: 'warehouse', ruName: 'Принять трансфер', uzName: 'Transferni qabul qilish', ruDescription: 'Кнопка принятия товаров', uzDescription: 'Tovarlarni qabul qilish tugmasi', ruFunctionality: 'Подтверждает получение товаров на склад-получатель', uzFunctionality: 'Tovarlarning qabul qiluvchi omborga kelishini tasdiqlaydi', uiLocation: 'Трансфер → Кнопка "Принять"', order: 47 },
  { category: 'warehouse', ruName: 'Фильтр трансферов по статусу', uzName: 'Transferlarni holat bo\'yicha filtrlash', ruDescription: 'Фильтрация по статусу документа', uzDescription: 'Hujjat holati bo\'yicha filtrlash', ruFunctionality: 'Позволяет фильтровать документы по статусу', uzFunctionality: 'Hujjatlarni holat bo\'yicha filtrlash imkonini beradi', uiLocation: 'Трансфер → Фильтры → Статус', order: 48 },
  { category: 'warehouse', ruName: 'Отправить трансфер', uzName: 'Transferni yuborish', ruDescription: 'Кнопка отправки товаров', uzDescription: 'Tovarlarni yuborish tugmasi', ruFunctionality: 'Отправляет товары со склада-отправителя', uzFunctionality: 'Tovarlarni yuboruvchi ombordan yuboradi', uiLocation: 'Трансфер → Кнопка "Отправить"', order: 49 },
  { category: 'warehouse', ruName: 'Отменить трансфер', uzName: 'Transferni bekor qilish', ruDescription: 'Отмена документа трансфера', uzDescription: 'Transfer hujjatini bekor qilish', ruFunctionality: 'Отменяет перемещение и возвращает товары', uzFunctionality: 'Ko\'chirishni bekor qiladi va tovarlarni qaytaradi', uiLocation: 'Трансфер → Кнопка "Отменить"', order: 50 },

  // === СКЛАД: РЕАЛИЗАЦИЯ (51-55) ===
  { category: 'warehouse', ruName: 'Реализация', uzName: 'Realizatsiya', ruDescription: 'Раздел отгрузки товаров', uzDescription: 'Tovarlarni jo\'natish bo\'limi', ruFunctionality: 'Открывает список документов отгрузки товаров контрагентам', uzFunctionality: 'Kontragentlarga tovar jo\'natish hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Реализация', order: 51 },
  { category: 'warehouse', ruName: 'Создать реализацию', uzName: 'Realizatsiya yaratish', ruDescription: 'Создание документа реализации', uzDescription: 'Realizatsiya hujjatini yaratish', ruFunctionality: 'Открывает форму для создания документа отгрузки', uzFunctionality: 'Jo\'natish hujjatini yaratish uchun formani ochadi', uiLocation: 'Реализация → Кнопка "Создать"', order: 52 },
  { category: 'warehouse', ruName: 'Выбор покупателя', uzName: 'Xaridorni tanlash', ruDescription: 'Выбор контрагента-покупателя', uzDescription: 'Xaridor kontragentni tanlash', ruFunctionality: 'Позволяет выбрать покупателя из списка контрагентов', uzFunctionality: 'Kontragentlar ro\'yxatidan xaridorni tanlash imkonini beradi', uiLocation: 'Реализация → Форма → Поле "Покупатель"', order: 53 },
  { category: 'warehouse', ruName: 'Печать реализации', uzName: 'Realizatsiyani chop etish', ruDescription: 'Печать документа реализации', uzDescription: 'Realizatsiya hujjatini chop etish', ruFunctionality: 'Формирует печатную форму накладной', uzFunctionality: 'Nakladnaya bosma shaklini yaratadi', uiLocation: 'Реализация → Кнопка "Печать"', order: 54 },
  { category: 'warehouse', ruName: 'Статусы реализации', uzName: 'Realizatsiya holatlari', ruDescription: 'Управление статусами документа', uzDescription: 'Hujjat holatlarini boshqarish', ruFunctionality: 'Позволяет менять статус: Черновик, Оформлен, Отправлен', uzFunctionality: 'Holatni o\'zgartirish imkonini beradi: Qoralama, Rasmiylashtirilgan, Yuborilgan', uiLocation: 'Реализация → Статусы', order: 55 },

  // === СКЛАД: ПЕРЕОЦЕНКА (56-60) ===
  { category: 'warehouse', ruName: 'Переоценка', uzName: 'Qayta baholash', ruDescription: 'Раздел массового изменения цен', uzDescription: 'Narlarni ommaviy o\'zgartirish bo\'limi', ruFunctionality: 'Открывает список документов переоценки товаров', uzFunctionality: 'Tovarlarni qayta baholash hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Переоценка', order: 56 },
  { category: 'warehouse', ruName: 'Создать переоценку', uzName: 'Qayta baholash yaratish', ruDescription: 'Создание документа переоценки', uzDescription: 'Qayta baholash hujjatini yaratish', ruFunctionality: 'Открывает форму для массового изменения цен', uzFunctionality: 'Narlarni ommaviy o\'zgartirish uchun formani ochadi', uiLocation: 'Переоценка → Кнопка "Создать"', order: 57 },
  { category: 'warehouse', ruName: 'Выбор товаров для переоценки', uzName: 'Qayta baholash uchun tovarlarni tanlash', ruDescription: 'Добавление товаров в документ', uzDescription: 'Hujjatga tovar qo\'shish', ruFunctionality: 'Позволяет выбрать товары для изменения цен', uzFunctionality: 'Narlarni o\'zgartirish uchun tovarlarni tanlash imkonini beradi', uiLocation: 'Переоценка → Кнопка "Добавить товары"', order: 58 },
  { category: 'warehouse', ruName: 'Новая цена товара', uzName: 'Tovarning yangi narxi', ruDescription: 'Установка новой цены', uzDescription: 'Yangi narxni o\'rnatish', ruFunctionality: 'Позволяет указать новую цену для каждого товара', uzFunctionality: 'Har bir tovar uchun yangi narxni ko\'rsatish imkonini beradi', uiLocation: 'Переоценка → Таблица → Поле "Новая цена"', order: 59 },
  { category: 'warehouse', ruName: 'Провести переоценку', uzName: 'Qayta baholashni o\'tkazish', ruDescription: 'Применение новых цен', uzDescription: 'Yangi narxlarni qo\'llash', ruFunctionality: 'Применяет новые цены к выбранным товарам', uzFunctionality: 'Tanlangan tovarlarga yangi narxlarni qo\'llaydi', uiLocation: 'Переоценка → Кнопка "Провести"', order: 60 },

  // === СКЛАД: ИНВЕНТАРИЗАЦИЯ (61-65) ===
  { category: 'warehouse', ruName: 'Инвентаризация', uzName: 'Inventarizatsiya', ruDescription: 'Раздел сверки остатков', uzDescription: 'Qoldiqlarni solishtirish bo\'limi', ruFunctionality: 'Открывает список документов инвентаризации', uzFunctionality: 'Inventarizatsiya hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Инвентаризация', order: 61 },
  { category: 'warehouse', ruName: 'Создать инвентаризацию', uzName: 'Inventarizatsiya yaratish', ruDescription: 'Создание документа инвентаризации', uzDescription: 'Inventarizatsiya hujjatini yaratish', ruFunctionality: 'Открывает форму для проведения сверки остатков', uzFunctionality: 'Qoldiqlarni solishtirish uchun formani ochadi', uiLocation: 'Инвентаризация → Кнопка "Создать"', order: 62 },
  { category: 'warehouse', ruName: 'Фактический остаток', uzName: 'Haqiqiy qoldiq', ruDescription: 'Ввод фактического количества', uzDescription: 'Haqiqiy miqdorni kiritish', ruFunctionality: 'Позволяет ввести фактическое количество товаров', uzFunctionality: 'Tovarlarning haqiqiy miqdorini kiritish imkonini beradi', uiLocation: 'Инвентаризация → Таблица → Поле "Факт"', order: 63 },
  { category: 'warehouse', ruName: 'Расхождения инвентаризации', uzName: 'Inventarizatsiya farqlari', ruDescription: 'Просмотр расхождений', uzDescription: 'Farqlarni ko\'rish', ruFunctionality: 'Показывает разницу между учётными и фактическими остатками', uzFunctionality: 'Hisob va haqiqiy qoldiqlar o\'rtasidagi farqni ko\'rsatadi', uiLocation: 'Инвентаризация → Вкладка "Расхождения"', order: 64 },
  { category: 'warehouse', ruName: 'Принять инвентаризацию', uzName: 'Inventarizatsiyani qabul qilish', ruDescription: 'Подтверждение результатов', uzDescription: 'Natijalarni tasdiqlash', ruFunctionality: 'Корректирует остатки согласно фактическим данным', uzFunctionality: 'Qoldiqlarni haqiqiy ma\'lumotlarga ko\'ra tuzatadi', uiLocation: 'Инвентаризация → Кнопка "Принять"', order: 65 },

  // === СКЛАД: СПИСАНИЕ (66-70) ===
  { category: 'warehouse', ruName: 'Списание', uzName: 'Yozib chiqarish', ruDescription: 'Раздел списания товаров', uzDescription: 'Tovarlarni yozib chiqarish bo\'limi', ruFunctionality: 'Открывает список документов списания', uzFunctionality: 'Yozib chiqarish hujjatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Списание', order: 66 },
  { category: 'warehouse', ruName: 'Создать списание', uzName: 'Yozib chiqarish yaratish', ruDescription: 'Создание документа списания', uzDescription: 'Yozib chiqarish hujjatini yaratish', ruFunctionality: 'Открывает форму для оформления списания', uzFunctionality: 'Yozib chiqarishni rasmiylashtirish uchun formani ochadi', uiLocation: 'Списание → Кнопка "Создать"', order: 67 },
  { category: 'warehouse', ruName: 'Причина списания', uzName: 'Yozib chiqarish sababi', ruDescription: 'Указание причины списания', uzDescription: 'Yozib chiqarish sababini ko\'rsatish', ruFunctionality: 'Позволяет указать причину: порча, истечение срока, хищение', uzFunctionality: 'Sababni ko\'rsatish imkonini beradi: buzilish, muddati tugash, o\'g\'irlik', uiLocation: 'Списание → Поле "Причина"', order: 68 },
  { category: 'warehouse', ruName: 'Ответственный за списание', uzName: 'Yozib chiqarish bo\'yicha mas\'ul', ruDescription: 'Выбор ответственного лица', uzDescription: 'Mas\'ul shaxsni tanlash', ruFunctionality: 'Позволяет указать сотрудника, ответственного за списание', uzFunctionality: 'Yozib chiqarish uchun mas\'ul xodimni ko\'rsatish imkonini beradi', uiLocation: 'Списание → Поле "Ответственный"', order: 69 },
  { category: 'warehouse', ruName: 'Провести списание', uzName: 'Yozib chiqarishni o\'tkazish', ruDescription: 'Подтверждение списания', uzDescription: 'Yozib chiqarishni tasdiqlash', ruFunctionality: 'Списывает товары со склада', uzFunctionality: 'Tovarlarni ombordan yozib chiqaradi', uiLocation: 'Списание → Кнопка "Провести"', order: 70 },

  // === СКЛАД: ГРУППИРОВКА (71-73) ===
  { category: 'warehouse', ruName: 'Группировка', uzName: 'Guruhlash', ruDescription: 'Раздел объединения товаров', uzDescription: 'Tovarlarni birlashtirish bo\'limi', ruFunctionality: 'Открывает раздел для создания групп товаров', uzFunctionality: 'Tovar guruhlarini yaratish bo\'limini ochadi', uiLocation: 'Боковое меню → Складские операции → Группировка', order: 71 },
  { category: 'warehouse', ruName: 'Создать группу', uzName: 'Guruh yaratish', ruDescription: 'Создание группы товаров', uzDescription: 'Tovar guruhi yaratish', ruFunctionality: 'Позволяет создать новую группу для объединения товаров', uzFunctionality: 'Tovarlarni birlashtirish uchun yangi guruh yaratish imkonini beradi', uiLocation: 'Группировка → Кнопка "Создать"', order: 72 },
  { category: 'warehouse', ruName: 'Добавить товары в группу', uzName: 'Guruhga tovar qo\'shish', ruDescription: 'Добавление товаров в группу', uzDescription: 'Guruhga tovarlar qo\'shish', ruFunctionality: 'Позволяет добавить товары в существующую группу', uzFunctionality: 'Mavjud guruhga tovarlar qo\'shish imkonini beradi', uiLocation: 'Группировка → Кнопка "Добавить"', order: 73 },

  // === СКЛАД: ВЕСОВЫЕ ТОВАРЫ (74-76) ===
  { category: 'warehouse', ruName: 'Весовые товары', uzName: 'Og\'irlikli tovarlar', ruDescription: 'Раздел товаров на вес', uzDescription: 'Og\'irlik bo\'yicha tovarlar bo\'limi', ruFunctionality: 'Открывает список товаров, продаваемых на вес', uzFunctionality: 'Og\'irlik bo\'yicha sotiladigan tovarlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Весовые товары', order: 74 },
  { category: 'warehouse', ruName: 'Настройка весового товара', uzName: 'Og\'irlikli tovarni sozlash', ruDescription: 'Параметры весового товара', uzDescription: 'Og\'irlikli tovar parametrlari', ruFunctionality: 'Позволяет настроить единицы измерения и точность', uzFunctionality: 'O\'lchov birliklari va aniqlikni sozlash imkonini beradi', uiLocation: 'Весовые товары → Настройки', order: 75 },
  { category: 'warehouse', ruName: 'Тара весового товара', uzName: 'Og\'irlikli tovar tarasi', ruDescription: 'Учёт веса тары', uzDescription: 'Tara og\'irligini hisobga olish', ruFunctionality: 'Позволяет указать вес тары для вычета', uzFunctionality: 'Ayirish uchun tara og\'irligini ko\'rsatish imkonini beradi', uiLocation: 'Весовые товары → Поле "Тара"', order: 76 },

  // === СКЛАД: ИМПОРТ (77-80) ===
  { category: 'warehouse', ruName: 'Импорт товаров', uzName: 'Tovarlarni import qilish', ruDescription: 'Раздел массового импорта', uzDescription: 'Ommaviy import bo\'limi', ruFunctionality: 'Открывает форму для загрузки товаров из файла', uzFunctionality: 'Fayldan tovarlarni yuklash formasini ochadi', uiLocation: 'Боковое меню → Складские операции → Импорт товаров', order: 77 },
  { category: 'warehouse', ruName: 'Загрузить файл импорта', uzName: 'Import faylini yuklash', ruDescription: 'Загрузка файла для импорта', uzDescription: 'Import uchun fayl yuklash', ruFunctionality: 'Позволяет загрузить Excel или CSV файл с товарами', uzFunctionality: 'Tovarli Excel yoki CSV faylni yuklash imkonini beradi', uiLocation: 'Импорт → Кнопка "Загрузить"', order: 78 },
  { category: 'warehouse', ruName: 'Сопоставление полей', uzName: 'Maydonlarni moslashtirish', ruDescription: 'Настройка соответствия полей', uzDescription: 'Maydonlar mosligini sozlash', ruFunctionality: 'Позволяет сопоставить поля файла с полями системы', uzFunctionality: 'Fayl maydonlarini tizim maydonlari bilan moslashtirish imkonini beradi', uiLocation: 'Импорт → Шаг "Сопоставление"', order: 79 },
  { category: 'warehouse', ruName: 'Запустить импорт', uzName: 'Importni boshlash', ruDescription: 'Запуск процесса импорта', uzDescription: 'Import jarayonini boshlash', ruFunctionality: 'Начинает загрузку товаров в базу', uzFunctionality: 'Tovarlarni bazaga yuklashni boshlaydi', uiLocation: 'Импорт → Кнопка "Импортировать"', order: 80 },

  // === СКЛАД: ТЕХКАРТЫ (81-85) ===
  { category: 'warehouse', ruName: 'Техкарты', uzName: 'Tex-kartalar', ruDescription: 'Раздел рецептур и калькуляции', uzDescription: 'Retseptura va kalkulyatsiya bo\'limi', ruFunctionality: 'Открывает список техкарт для производства', uzFunctionality: 'Ishlab chiqarish uchun tex-kartalar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Техкарты', order: 81 },
  { category: 'warehouse', ruName: 'Создать техкарту', uzName: 'Tex-karta yaratish', ruDescription: 'Создание рецептуры', uzDescription: 'Retseptura yaratish', ruFunctionality: 'Открывает форму для создания техкарты', uzFunctionality: 'Tex-karta yaratish uchun formani ochadi', uiLocation: 'Техкарты → Кнопка "Создать"', order: 82 },
  { category: 'warehouse', ruName: 'Ингредиенты техкарты', uzName: 'Tex-karta ingredientlari', ruDescription: 'Добавление ингредиентов', uzDescription: 'Ingredientlar qo\'shish', ruFunctionality: 'Позволяет добавить материалы и их количество', uzFunctionality: 'Materiallar va ularning miqdorini qo\'shish imkonini beradi', uiLocation: 'Техкарты → Таблица ингредиентов', order: 83 },
  { category: 'warehouse', ruName: 'Себестоимость техкарты', uzName: 'Tex-karta tannarxi', ruDescription: 'Расчёт себестоимости', uzDescription: 'Tannarxni hisoblash', ruFunctionality: 'Автоматически рассчитывает себестоимость продукта', uzFunctionality: 'Mahsulot tannarxini avtomatik hisoblaydi', uiLocation: 'Техкарты → Поле "Себестоимость"', order: 84 },
  { category: 'warehouse', ruName: 'Готовая продукция техкарты', uzName: 'Tex-karta tayyor mahsuloti', ruDescription: 'Указание готового продукта', uzDescription: 'Tayyor mahsulotni ko\'rsatish', ruFunctionality: 'Позволяет указать, какой продукт получается', uzFunctionality: 'Qanday mahsulot olinishini ko\'rsatish imkonini beradi', uiLocation: 'Техкарты → Поле "Продукт"', order: 85 },

  // === СКЛАД: АКТ ИЗГОТОВЛЕНИЯ (86-90) ===
  { category: 'warehouse', ruName: 'Акт изготовления', uzName: 'Ishlab chiqarish akri', ruDescription: 'Раздел выпуска продукции', uzDescription: 'Mahsulot chiqarish bo\'limi', ruFunctionality: 'Открывает список актов изготовления', uzFunctionality: 'Ishlab chiqarish aktlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Акт изготовления', order: 86 },
  { category: 'warehouse', ruName: 'Создать акт изготовления', uzName: 'Ishlab chiqarish akri yaratish', ruDescription: 'Создание акта производства', uzDescription: 'Ishlab chiqarish aktini yaratish', ruFunctionality: 'Открывает форму для оформления выпуска', uzFunctionality: 'Chiqarishni rasmiylashtirish uchun formani ochadi', uiLocation: 'Акт изготовления → Кнопка "Создать"', order: 87 },
  { category: 'warehouse', ruName: 'Выбор техкарты', uzName: 'Tex-kartani tanlash', ruDescription: 'Выбор рецептуры для производства', uzDescription: 'Ishlab chiqarish uchun retsepturani tanlash', ruFunctionality: 'Позволяет выбрать техкарту для изготовления', uzFunctionality: 'Ishlab chiqarish uchun tex-kartani tanlash imkonini beradi', uiLocation: 'Акт изготовления → Поле "Техкарта"', order: 88 },
  { category: 'warehouse', ruName: 'Количество продукции', uzName: 'Mahsulot miqdori', ruDescription: 'Указание количества', uzDescription: 'Miqdorni ko\'rsatish', ruFunctionality: 'Позволяет указать, сколько единиц производится', uzFunctionality: 'Necha birlik ishlab chiqarilishini ko\'rsatish imkonini beradi', uiLocation: 'Акт изготовления → Поле "Количество"', order: 89 },
  { category: 'warehouse', ruName: 'Провести акт изготовления', uzName: 'Ishlab chiqarish akriini o\'tkazish', ruDescription: 'Подтверждение производства', uzDescription: 'Ishlab chiqarishni tasdiqlash', ruFunctionality: 'Списывает материалы и приходует готовую продукцию', uzFunctionality: 'Materiallarni yozib chiqarib, tayyor mahsulotni qabul qiladi', uiLocation: 'Акт изготовления → Кнопка "Провести"', order: 90 },

  // === СКЛАД: ИЗБРАННЫЕ (91-93) ===
  { category: 'warehouse', ruName: 'Избранные товары', uzName: 'Sevimli tovarlar', ruDescription: 'Раздел избранных товаров', uzDescription: 'Sevimli tovarlar bo\'limi', ruFunctionality: 'Открывает список избранных товаров для быстрого доступа', uzFunctionality: 'Tez kirish uchun sevimli tovarlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Складские операции → Избранные товары', order: 91 },
  { category: 'warehouse', ruName: 'Удалить из избранного', uzName: 'Sevimlilardan o\'chirish', ruDescription: 'Удаление из избранного', uzDescription: 'Sevimlilardan o\'chirish', ruFunctionality: 'Удаляет товар из списка избранных', uzFunctionality: 'Tovarni sevimlilar ro\'yxatidan o\'chiradi', uiLocation: 'Избранные → Иконка звезды', order: 92 },
  { category: 'warehouse', ruName: 'Добавить все в чек', uzName: 'Hammasini chekka qo\'shish', ruDescription: 'Массовое добавление в чек', uzDescription: 'Chekka ommaviy qo\'shish', ruFunctionality: 'Позволяет добавить все избранные товары в чек', uzFunctionality: 'Barcha sevimli tovarlarni chekka qo\'shish imkonini beradi', uiLocation: 'Избранные → Кнопка "Добавить все"', order: 93 },

  // === СПРАВОЧНИК: ПЕРСОНАЛ (94-100) ===
  { category: 'reference', ruName: 'Персонал', uzName: 'Personal', ruDescription: 'Раздел управления сотрудниками', uzDescription: 'Xodimlarni boshqarish bo\'limi', ruFunctionality: 'Открывает список всех сотрудников', uzFunctionality: 'Barcha xodimlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Персонал', order: 94 },
  { category: 'reference', ruName: 'Добавить сотрудника', uzName: 'Xodim qo\'shish', ruDescription: 'Создание карточки сотрудника', uzDescription: 'Xodim kartochkasini yaratish', ruFunctionality: 'Открывает форму для добавления нового сотрудника', uzFunctionality: 'Yangi xodim qo\'shish uchun formani ochadi', uiLocation: 'Персонал → Кнопка "Добавить"', order: 95 },
  { category: 'reference', ruName: 'Должность сотрудника', uzName: 'Xodim lavozimi', ruDescription: 'Назначение должности', uzDescription: 'Lavozimni tayinlash', ruFunctionality: 'Позволяет указать должность и права доступа', uzFunctionality: 'Lavozim va kirish huquqlarini ko\'rsatish imkonini beradi', uiLocation: 'Персонал → Поле "Должность"', order: 96 },
  { category: 'reference', ruName: 'Права доступа', uzName: 'Kirish huquqlari', ruDescription: 'Настройка прав сотрудника', uzDescription: 'Xodim huquqlarini sozlash', ruFunctionality: 'Позволяет ограничить доступ к разделам', uzFunctionality: 'Bo\'limlarga kirishni cheklash imkonini beradi', uiLocation: 'Персонал → Вкладка "Права"', order: 97 },
  { category: 'reference', ruName: 'PIN-код сотрудника', uzName: 'Xodim PIN-kodi', ruDescription: 'Установка PIN-кода', uzDescription: 'PIN-kodni o\'rnatish', ruFunctionality: 'Позволяет задать PIN для входа в кассу', uzFunctionality: 'Kassaga kirish uchun PIN belgilash imkonini beradi', uiLocation: 'Персонал → Поле "PIN"', order: 98 },
  { category: 'reference', ruName: 'Уволить сотрудника', uzName: 'Xodimni ishdan bo\'shatish', ruDescription: 'Увольнение сотрудника', uzDescription: 'Xodimni ishdan bo\'shatish', ruFunctionality: 'Деактивирует учётную запись сотрудника', uzFunctionality: 'Xodim akkauntini o\'chiradi', uiLocation: 'Персонал → Кнопка "Уволить"', order: 99 },
  { category: 'reference', ruName: 'История работы', uzName: 'Ish tarixi', ruDescription: 'История сотрудника', uzDescription: 'Xodim tarixi', ruFunctionality: 'Показывает историю смен и продаж сотрудника', uzFunctionality: 'Xodimning smenalar va sotuvlar tarixini ko\'rsatadi', uiLocation: 'Персонал → Вкладка "История"', order: 100 },

  // === СПРАВОЧНИК: ВОДИТЕЛИ (101-103) ===
  { category: 'reference', ruName: 'Водители', uzName: 'Haydovchilar', ruDescription: 'Раздел управления водителями', uzDescription: 'Haydovchilarni boshqarish bo\'limi', ruFunctionality: 'Открывает список водителей для доставки', uzFunctionality: 'Yetkazib berish uchun haydovchilar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Водители', order: 101 },
  { category: 'reference', ruName: 'Добавить водителя', uzName: 'Haydovchi qo\'shish', ruDescription: 'Создание карточки водителя', uzDescription: 'Haydovchi kartochkasini yaratish', ruFunctionality: 'Открывает форму для добавления водителя', uzFunctionality: 'Haydovchi qo\'shish uchun formani ochadi', uiLocation: 'Водители → Кнопка "Добавить"', order: 102 },
  { category: 'reference', ruName: 'Привязка к машине', uzName: 'Avtomobilga biriktirish', ruDescription: 'Привязка водителя к ТС', uzDescription: 'Haydovchini transport vositasiga biriktirish', ruFunctionality: 'Позволяет связать водителя с автомобилем', uzFunctionality: 'Haydovchini avtomobil bilan bog\'lash imkonini beradi', uiLocation: 'Водители → Поле "Автомобиль"', order: 103 },

  // === СПРАВОЧНИК: СМЕНЫ (104-108) ===
  { category: 'reference', ruName: 'Смены', uzName: 'Smenalar', ruDescription: 'Раздел управления сменами', uzDescription: 'Smenalarni boshqarish bo\'limi', ruFunctionality: 'Открывает список рабочих смен', uzFunctionality: 'Ish smenalari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Смены', order: 104 },
  { category: 'reference', ruName: 'Открыть смену', uzName: 'Smenani ochish', ruDescription: 'Открытие новой смены', uzDescription: 'Yangi smena ochish', ruFunctionality: 'Открывает смену на кассе', uzFunctionality: 'Kassada smena ochadi', uiLocation: 'Смены → Кнопка "Открыть"', order: 105 },
  { category: 'reference', ruName: 'Закрыть смену', uzName: 'Smenani yopish', ruDescription: 'Закрытие смены', uzDescription: 'Smenani yopish', ruFunctionality: 'Закрывает смену и формирует Z-отчёт', uzFunctionality: 'Smenani yopib, Z-hisobot shakllantiradi', uiLocation: 'Смены → Кнопка "Закрыть"', order: 106 },
  { category: 'reference', ruName: 'Выручка за смену', uzName: 'Smena tushumi', ruDescription: 'Просмотр выручки', uzDescription: 'Tushumni ko\'rish', ruFunctionality: 'Показывает сумму продаж за смену', uzFunctionality: 'Smena davomidagi sotuv summasini ko\'rsatadi', uiLocation: 'Смены → Колонка "Выручка"', order: 107 },
  { category: 'reference', ruName: 'Фильтр смен по кассе', uzName: 'Smenalarni kassa bo\'yicha filtrlash', ruDescription: 'Фильтрация по кассе', uzDescription: 'Kassa bo\'yicha filtrlash', ruFunctionality: 'Позволяет фильтровать смены по кассам', uzFunctionality: 'Smenalarni kassalar bo\'yicha filtrlash imkonini beradi', uiLocation: 'Смены → Фильтр "Касса"', order: 108 },

  // === СПРАВОЧНИК: Z-ОТЧЁТЫ (109-111) ===
  { category: 'reference', ruName: 'Z-отчёты', uzName: 'Z-hisobotlar', ruDescription: 'Раздел фискальных отчётов', uzDescription: 'Fiskal hisobotlar bo\'limi', ruFunctionality: 'Открывает список Z-отчётов, отправленных в ОФД', uzFunctionality: 'OFD ga yuborilgan Z-hisobotlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Z-отчёты', order: 109 },
  { category: 'reference', ruName: 'Печать Z-отчёта', uzName: 'Z-hisobotni chop etish', ruDescription: 'Печать фискального отчёта', uzDescription: 'Fiskal hisobotni chop etish', ruFunctionality: 'Позволяет распечатать копию Z-отчёта', uzFunctionality: 'Z-hisobot nusxasini chop etish imkonini beradi', uiLocation: 'Z-отчёты → Кнопка "Печать"', order: 110 },
  { category: 'reference', ruName: 'Отправить в ОФД', uzName: 'OFD ga yuborish', ruDescription: 'Отправка отчёта в ОФД', uzDescription: 'Hisobotni OFD ga yuborish', ruFunctionality: 'Отправляет фискальные данные в налоговую', uzFunctionality: 'Fiskal ma\'lumotlarni soliq organlariga yuboradi', uiLocation: 'Z-отчёты → Кнопка "Отправить"', order: 111 },

  // === СПРАВОЧНИК: ПЕЧАТЬ ЦЕННИКОВ (112-114) ===
  { category: 'reference', ruName: 'Печать ценников', uzName: 'Narx yorliqlarini chop etish', ruDescription: 'Раздел генерации ценников', uzDescription: 'Narx yorliqlarini yaratish bo\'limi', ruFunctionality: 'Открывает форму для массовой печати ценников', uzFunctionality: 'Narx yorliqlarini ommaviy chop etish formasini ochadi', uiLocation: 'Боковое меню → Справочник → Печать ценников', order: 112 },
  { category: 'reference', ruName: 'Шаблон ценника', uzName: 'Narx yorlig\'i shabloni', ruDescription: 'Выбор шаблона ценника', uzDescription: 'Narx yorlig\'i shablonini tanlash', ruFunctionality: 'Позволяет выбрать формат ценника', uzFunctionality: 'Narx yorlig\'i formatini tanlash imkonini beradi', uiLocation: 'Печать ценников → Выбор шаблона', order: 113 },
  { category: 'reference', ruName: 'Печать выбранных', uzName: 'Tanlanganlarni chop etish', ruDescription: 'Печать выбранных ценников', uzDescription: 'Tanlangan yorliqlarni chop etish', ruFunctionality: 'Отправляет на печать выбранные ценники', uzFunctionality: 'Tanlangan narx yorliqlarini chop etishga yuboradi', uiLocation: 'Печать ценников → Кнопка "Печать"', order: 114 },

  // === СПРАВОЧНИК: КЛИЕНТЫ (115-122) ===
  { category: 'reference', ruName: 'Клиенты', uzName: 'Mijozlar', ruDescription: 'Раздел управления клиентами', uzDescription: 'Mijozlarni boshqarish bo\'limi', ruFunctionality: 'Открывает базу клиентов', uzFunctionality: 'Mijozlar bazasini ochadi', uiLocation: 'Боковое меню → Справочник → Клиенты', order: 115 },
  { category: 'reference', ruName: 'Добавить клиента', uzName: 'Mijoz qo\'shish', ruDescription: 'Создание карточки клиента', uzDescription: 'Mijoz kartochkasini yaratish', ruFunctionality: 'Открывает форму для добавления нового клиента', uzFunctionality: 'Yangi mijoz qo\'shish uchun formani ochadi', uiLocation: 'Клиенты → Кнопка "Добавить"', order: 116 },
  { category: 'reference', ruName: 'Поиск клиента', uzName: 'Mijozni qidirish', ruDescription: 'Поиск по клиентам', uzDescription: 'Mijozlar bo\'yicha qidiruv', ruFunctionality: 'Позволяет найти клиента по имени или телефону', uzFunctionality: 'Mijozni ism yoki telefon bo\'yicha topish imkonini beradi', uiLocation: 'Клиенты → Поле поиска', order: 117 },
  { category: 'reference', ruName: 'История покупок клиента', uzName: 'Mijoz xaridlari tarixi', ruDescription: 'История покупок', uzDescription: 'Xaridlar tarixi', ruFunctionality: 'Показывает все покупки выбранного клиента', uzFunctionality: 'Tanlangan mijozning barcha xaridlarini ko\'rsatadi', uiLocation: 'Клиенты → Карточка → История', order: 118 },
  { category: 'reference', ruName: 'Долг клиента', uzName: 'Mijoz qarzi', ruDescription: 'Просмотр задолженности', uzDescription: 'Qarzni ko\'rish', ruFunctionality: 'Показывает сумму долга клиента', uzFunctionality: 'Mijoz qarz summasini ko\'rsatadi', uiLocation: 'Клиенты → Колонка "Долг"', order: 119 },
  { category: 'reference', ruName: 'Скидка клиента', uzName: 'Mijoz chegirmasi', ruDescription: 'Настройка скидки', uzDescription: 'Chegirmni sozlash', ruFunctionality: 'Позволяет задать индивидуальную скидку', uzFunctionality: 'Individual chegirma belgilash imkonini beradi', uiLocation: 'Клиенты → Поле "Скидка"', order: 120 },
  { category: 'reference', ruName: 'Баллы лояльности', uzName: 'Sodiqlik ballari', ruDescription: 'Просмотр баллов', uzDescription: 'Ballarni ko\'rish', ruFunctionality: 'Показывает накопленные баллы клиента', uzFunctionality: 'Mijozning yig\'gan ballarini ko\'rsatadi', uiLocation: 'Клиенты → Поле "Баллы"', order: 121 },
  { category: 'reference', ruName: 'Блокировка клиента', uzName: 'Mijozni bloklash', ruDescription: 'Блокировка клиента', uzDescription: 'Mijozni bloklash', ruFunctionality: 'Блокирует возможность покупок в долг', uzFunctionality: 'Qarzga xarid qilish imkoniyatini bloklaydi', uiLocation: 'Клиенты → Кнопка "Блокировать"', order: 122 },

  // === СПРАВОЧНИК: ЛОЯЛЬНОСТЬ (123-126) ===
  { category: 'reference', ruName: 'Лояльность', uzName: 'Sodiqlik', ruDescription: 'Раздел программ лояльности', uzDescription: 'Sodiqlik dasturlari bo\'limi', ruFunctionality: 'Открывает настройки программ поощрения', uzFunctionality: 'Rag\'batlantirish dasturlari sozlamalarini ochadi', uiLocation: 'Боковое меню → Справочник → Лояльность', order: 123 },
  { category: 'reference', ruName: 'Создать программу', uzName: 'Dastur yaratish', ruDescription: 'Создание программы лояльности', uzDescription: 'Sodiqlik dasturi yaratish', ruFunctionality: 'Открывает форму для создания программы', uzFunctionality: 'Dastur yaratish uchun formani ochadi', uiLocation: 'Лояльность → Кнопка "Создать"', order: 124 },
  { category: 'reference', ruName: 'Начисление баллов', uzName: 'Ballar yig\'ish', ruDescription: 'Настройка начисления баллов', uzDescription: 'Ballar yig\'ishni sozlash', ruFunctionality: 'Позволяет настроить правила начисления', uzFunctionality: 'Yig\'ish qoidalarini sozlash imkonini beradi', uiLocation: 'Лояльность → Настройки "Баллы"', order: 125 },
  { category: 'reference', ruName: 'Уровни лояльности', uzName: 'Sodiqlik darajalari', ruDescription: 'Настройка уровней', uzDescription: 'Darajalarni sozlash', ruFunctionality: 'Позволяет создать уровни с разными бонусами', uzFunctionality: 'Turli bonusli darajalar yaratish imkonini beradi', uiLocation: 'Лояльность → Вкладка "Уровни"', order: 126 },

  // === СПРАВОЧНИК: КОНТРАГЕНТЫ (127-132) ===
  { category: 'reference', ruName: 'Контрагенты', uzName: 'Kontragentlar', ruDescription: 'Раздел управления контрагентами', uzDescription: 'Kontragentlarni boshqarish bo\'limi', ruFunctionality: 'Открывает список поставщиков и партнёров', uzFunctionality: 'Yetkazib beruvchilar va hamkorlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Контрагенты', order: 127 },
  { category: 'reference', ruName: 'Добавить контрагента', uzName: 'Kontragent qo\'shish', ruDescription: 'Создание карточки контрагента', uzDescription: 'Kontragent kartochkasini yaratish', ruFunctionality: 'Открывает форму для добавления контрагента', uzFunctionality: 'Kontragent qo\'shish uchun formani ochadi', uiLocation: 'Контрагенты → Кнопка "Добавить"', order: 128 },
  { category: 'reference', ruName: 'Тип контрагента', uzName: 'Kontragent turi', ruDescription: 'Выбор типа контрагента', uzDescription: 'Kontragent turini tanlash', ruFunctionality: 'Позволяет указать тип: поставщик, покупатель, партнёр', uzFunctionality: 'Turni ko\'rsatish imkonini beradi: yetkazib beruvchi, xaridor, hamkor', uiLocation: 'Контрагенты → Поле "Тип"', order: 129 },
  { category: 'reference', ruName: 'Взаиморасчёты с контрагентом', uzName: 'Kontragent bilan o\'zaro hisob-kitob', ruDescription: 'Просмотр расчётов', uzDescription: 'Hisob-kitoblarni ko\'rish', ruFunctionality: 'Показывает историю взаиморасчётов', uzFunctionality: 'O\'zaro hisob-kitob tarixini ko\'rsatadi', uiLocation: 'Контрагенты → Карточка → Расчёты', order: 130 },
  { category: 'reference', ruName: 'Договор контрагента', uzName: 'Kontragent shartnomasi', ruDescription: 'Привязка договора', uzDescription: 'Shartnomani biriktirish', ruFunctionality: 'Позволяет указать номер и дату договора', uzFunctionality: 'Shartnoma raqami va sanasini ko\'rsatish imkonini beradi', uiLocation: 'Контрагенты → Поле "Договор"', order: 131 },
  { category: 'reference', ruName: 'Удалить контрагента', uzName: 'Kontragentni o\'chirish', ruDescription: 'Удаление контрагента', uzDescription: 'Kontragentni o\'chirish', ruFunctionality: 'Удаляет контрагента из базы', uzFunctionality: 'Kontragentni bazadan o\'chiradi', uiLocation: 'Контрагенты → Кнопка "Удалить"', order: 132 },

  // === СПРАВОЧНИК: СМС (133-138) ===
  { category: 'reference', ruName: 'СМС рассылка', uzName: 'SMS tarqatish', ruDescription: 'Раздел массовых рассылок', uzDescription: 'Ommaviy tarqatish bo\'limi', ruFunctionality: 'Открывает форму для отправки SMS клиентам', uzFunctionality: 'Mijozlarga SMS yuborish formasini ochadi', uiLocation: 'Боковое меню → Справочник → СМС рассылка', order: 133 },
  { category: 'reference', ruName: 'Выбор получателей', uzName: 'Qabul qiluvchilarni tanlash', ruDescription: 'Выбор клиентов для рассылки', uzDescription: 'Tarqatish uchun mijozlarni tanlash', ruFunctionality: 'Позволяет выбрать группу клиентов', uzFunctionality: 'Mijozlar guruhini tanlash imkonini beradi', uiLocation: 'СМС рассылка → Выбор клиентов', order: 134 },
  { category: 'reference', ruName: 'Текст сообщения', uzName: 'Xabar matni', ruDescription: 'Ввод текста SMS', uzDescription: 'SMS matnini kiritish', ruFunctionality: 'Позволяет написать текст сообщения', uzFunctionality: 'Xabar matnini yozish imkonini beradi', uiLocation: 'СМС рассылка → Поле "Текст"', order: 135 },
  { category: 'reference', ruName: 'Отправить рассылку', uzName: 'Tarqatishni yuborish', ruDescription: 'Запуск рассылки', uzDescription: 'Tarqatishni boshlash', ruFunctionality: 'Отправляет SMS выбранным клиентам', uzFunctionality: 'Tanlangan mijozlarga SMS yuboradi', uiLocation: 'СМС рассылка → Кнопка "Отправить"', order: 136 },
  { category: 'reference', ruName: 'Шаблоны СМС', uzName: 'SMS shablonlari', ruDescription: 'Раздел шаблонов сообщений', uzDescription: 'Xabar shablonlari bo\'limi', ruFunctionality: 'Открывает список сохранённых шаблонов', uzFunctionality: 'Saqlangan shablonlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Шаблоны СМС', order: 137 },
  { category: 'reference', ruName: 'Создать шаблон', uzName: 'Shablon yaratish', ruDescription: 'Создание шаблона СМС', uzDescription: 'SMS shablonini yaratish', ruFunctionality: 'Позволяет создать шаблон для повторного использования', uzFunctionality: 'Qayta foydalanish uchun shablon yaratish imkonini beradi', uiLocation: 'Шаблоны СМС → Кнопка "Создать"', order: 138 },

  // === СПРАВОЧНИК: ДОКУМЕНТЫ (139-141) ===
  { category: 'reference', ruName: 'Документы', uzName: 'Hujjatlar', ruDescription: 'Раздел хранения документов', uzDescription: 'Hujjatlarni saqlash bo\'limi', ruFunctionality: 'Открывает список загруженных документов', uzFunctionality: 'Yuklangan hujjatlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Документы', order: 139 },
  { category: 'reference', ruName: 'Загрузить документ', uzName: 'Hujjat yuklash', ruDescription: 'Загрузка нового документа', uzDescription: 'Yangi hujjat yuklash', ruFunctionality: 'Позволяет загрузить файл в систему', uzFunctionality: 'Tizimga fayl yuklash imkonini beradi', uiLocation: 'Документы → Кнопка "Загрузить"', order: 140 },
  { category: 'reference', ruName: 'Скачать документ', uzName: 'Hujjatni yuklab olish', ruDescription: 'Скачивание документа', uzDescription: 'Hujjatni yuklab olish', ruFunctionality: 'Позволяет скачать документ на устройство', uzFunctionality: 'Hujjatni qurilmaga yuklab olish imkonini beradi', uiLocation: 'Документы → Кнопка "Скачать"', order: 141 },

  // === СПРАВОЧНИК: АУДИТ (142-143) ===
  { category: 'reference', ruName: 'Аудит маркировок', uzName: 'Markirovka auditi', ruDescription: 'Раздел проверки маркировок', uzDescription: 'Markirovkalarni tekshirish bo\'limi', ruFunctionality: 'Открывает форму для проверки кодов маркировки', uzFunctionality: 'Markirovka kodlarini tekshirish formasini ochadi', uiLocation: 'Боковое меню → Справочник → Аудит маркировок', order: 142 },
  { category: 'reference', ruName: 'Сканировать маркировку', uzName: 'Markirovkani skanerlash', ruDescription: 'Сканирование кода', uzDescription: 'Kodni skanerlash', ruFunctionality: 'Позволяет проверить код маркировки', uzFunctionality: 'Markirovka kodini tekshirish imkonini beradi', uiLocation: 'Аудит маркировок → Поле сканирования', order: 143 },

  // === СПРАВОЧНИК: ЭДО (144-145) ===
  { category: 'reference', ruName: 'ЭДО', uzName: 'ЭДО', ruDescription: 'Раздел электронного документооборота', uzDescription: 'Elektron hujjat aylanmasi bo\'limi', ruFunctionality: 'Открывает список электронных документов', uzFunctionality: 'Elektron hujjatlar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → ЭДО', order: 144 },
  { category: 'reference', ruName: 'Подписать документ', uzName: 'Hujjatni imzolash', ruDescription: 'Подписание ЭЦП', uzDescription: 'ESQ bilan imzolash', ruFunctionality: 'Позволяет подписать документ электронной подписью', uzFunctionality: 'Hujjatni elektron imzo bilan imzolash imkonini beradi', uiLocation: 'ЭДО → Кнопка "Подписать"', order: 145 },

  // === СПРАВОЧНИК: АКЦИИ (146-148) ===
  { category: 'reference', ruName: 'Акции', uzName: 'Aksiyalar', ruDescription: 'Раздел управления акциями', uzDescription: 'Aksiyalarni boshqarish bo\'limi', ruFunctionality: 'Открывает список акций и скидок', uzFunctionality: 'Aksiyalar va chegirmalar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Справочник → Акции', order: 146 },
  { category: 'reference', ruName: 'Создать акцию', uzName: 'Aksiya yaratish', ruDescription: 'Создание новой акции', uzDescription: 'Yangi aksiya yaratish', ruFunctionality: 'Открывает форму для создания акции', uzFunctionality: 'Aksiya yaratish uchun formani ochadi', uiLocation: 'Акции → Кнопка "Создать"', order: 147 },
  { category: 'reference', ruName: 'Активировать акцию', uzName: 'Aksiyani faollashtirish', ruDescription: 'Запуск акции', uzDescription: 'Aksiyani ishga tushirish', ruFunctionality: 'Делает акцию активной для покупателей', uzFunctionality: 'Aksiyani xaridorlar uchun faol qiladi', uiLocation: 'Акции → Переключатель "Активна"', order: 148 },

  // === ФИНАНСЫ: ЧЕКИ (149-160) ===
  { category: 'finance', ruName: 'Проданные чеки', uzName: 'Sotilgan cheklar', ruDescription: 'Размотр проданных чеков', uzDescription: 'Sotilgan cheklar bo\'limi', ruFunctionality: 'Открывает список всех проданных чеков', uzFunctionality: 'Barcha sotilgan cheklar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Проданные чеки', order: 149 },
  { category: 'finance', ruName: 'Просмотр чека', uzName: 'Chekni ko\'rish', ruDescription: 'Детали чека', uzDescription: 'Chek tafsilotlari', ruFunctionality: 'Показывает полную информацию о чеке', uzFunctionality: 'Chek haqida to\'liq ma\'lumotni ko\'rsatadi', uiLocation: 'Проданные чеки → Клик на чек', order: 150 },
  { category: 'finance', ruName: 'Печать копии чека', uzName: 'Chek nusxasini chop etish', ruDescription: 'Печать дубликата', uzDescription: 'Dublikatni chop etish', ruFunctionality: 'Позволяет распечатать копию чека', uzFunctionality: 'Chek nusxasini chop etish imkonini beradi', uiLocation: 'Проданные чеки → Кнопка "Печать"', order: 151 },
  { category: 'finance', ruName: 'Возвраты чеков', uzName: 'Chek qaytarish', ruDescription: 'Раздел возвратов', uzDescription: 'Qaytarish bo\'limi', ruFunctionality: 'Открывает список возвращённых чеков', uzFunctionality: 'Qaytarilgan cheklar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Возвраты чеков', order: 152 },
  { category: 'finance', ruName: 'Оформить возврат', uzName: 'Qaytarishni rasmiylashtirish', ruDescription: 'Создание возврата', uzDescription: 'Qaytarish yaratish', ruFunctionality: 'Открывает форму для оформления возврата', uzFunctionality: 'Qaytarishni rasmiylashtirish uchun formani ochadi', uiLocation: 'Возвраты чеков → Кнопка "Возврат"', order: 153 },
  { category: 'finance', ruName: 'Удалённые чеки', uzName: 'O\'chirilgan cheklar', ruDescription: 'Чеки с удалёнными товарами', uzDescription: 'O\'chirilgan tovarli cheklar', ruFunctionality: 'Открывает чеки с удалёнными позициями', uzFunctionality: 'O\'chirilgan pozitsiyali cheklarni ochadi', uiLocation: 'Боковое меню → Финансовые операции → Удалённые чеки', order: 154 },
  { category: 'finance', ruName: 'Отложенные чеки', uzName: 'Kechiktirilgan cheklar', ruDescription: 'Сохранённые чеки', uzDescription: 'Saqlangan cheklar', ruFunctionality: 'Открывает список отложенных чеков', uzFunctionality: 'Kechiktirilgan cheklar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Отложенные чеки', order: 155 },
  { category: 'finance', ruName: 'Продолжить чек', uzName: 'Chekni davom ettirish', ruDescription: 'Возобновление чека', uzDescription: 'Chekni davom ettirish', ruFunctionality: 'Позволяет продолжить оформление отложенного чека', uzFunctionality: 'Kechiktirilgan chekni rasmiylashtirishni davom ettirish imkonini beradi', uiLocation: 'Отложенные чеки → Кнопка "Продолжить"', order: 156 },
  { category: 'finance', ruName: 'Взаиморасчёт', uzName: 'O\'zaro hisob-kitob', ruDescription: 'Раздел расчётов с контрагентами', uzDescription: 'Kontragentlar bilan hisob-kitob bo\'limi', ruFunctionality: 'Открывает ведомость взаиморасчётов', uzFunctionality: 'O\'zaro hisob-kitob varaqasini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Взаиморасчёт', order: 157 },
  { category: 'finance', ruName: 'Счета', uzName: 'Hisoblar', ruDescription: 'Раздел счетов', uzDescription: 'Hisoblar bo\'limi', ruFunctionality: 'Открывает список счетов на оплату', uzFunctionality: 'To\'lov hisoblari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Счета', order: 158 },
  { category: 'finance', ruName: 'Создать счёт', uzName: 'Hisob yaratish', ruDescription: 'Создание счёта', uzDescription: 'Hisob yaratish', ruFunctionality: 'Открывает форму для создания счёта', uzFunctionality: 'Hisob yaratish uchun formani ochadi', uiLocation: 'Счета → Кнопка "Создать"', order: 159 },
  { category: 'finance', ruName: 'Оплатить счёт', uzName: 'Hisobni to\'lash', ruDescription: 'Оплата счёта', uzDescription: 'Hisobni to\'lash', ruFunctionality: 'Фиксирует оплату счёта', uzFunctionality: 'Hisob to\'lovini qayd etadi', uiLocation: 'Счета → Кнопка "Оплатить"', order: 160 },

  // === ФИНАНСЫ: ЗАРПЛАТА (161-163) ===
  { category: 'finance', ruName: 'Зарплата', uzName: 'Ish haqi', ruDescription: 'Раздел расчёта зарплат', uzDescription: 'Ish haqini hisoblash bo\'limi', ruFunctionality: 'Открывает модуль расчёта зарплат', uzFunctionality: 'Ish haqini hisoblash modulini ochadi', uiLocation: 'Боковое меню → Финансовые операции → Зарплата', order: 161 },
  { category: 'finance', ruName: 'Начислить зарплату', uzName: 'Ish haqini hisoblash', ruDescription: 'Начисление зарплаты', uzDescription: 'Ish haqini hisoblash', ruFunctionality: 'Позволяет начислить зарплату сотрудникам', uzFunctionality: 'Xodimlarga ish haqini hisoblash imkonini beradi', uiLocation: 'Зарплата → Кнопка "Начислить"', order: 162 },
  { category: 'finance', ruName: 'Выплатить зарплату', uzName: 'Ish haqini to\'lash', ruDescription: 'Выплата зарплаты', uzDescription: 'Ish haqini to\'lash', ruFunctionality: 'Фиксирует выплату зарплаты', uzFunctionality: 'Ish haqi to\'lovini qayd etadi', uiLocation: 'Зарплата → Кнопка "Выплатить"', order: 163 },

  // === ОТЧЁТЫ (164-175) ===
  { category: 'reports', ruName: 'Отчёт о продаже', uzName: 'Sotuv hisoboti', ruDescription: 'Отчёт по продажам', uzDescription: 'Sotuvlar bo\'yicha hisobot', ruFunctionality: 'Открывает детальный отчёт по продажам', uzFunctionality: 'Sotuvlar bo\'yicha batafsil hisobotni ochadi', uiLocation: 'Боковое меню → Отчёты → Отчёт о продаже', order: 164 },
  { category: 'reports', ruName: 'Фильтр отчёта по дате', uzName: 'Hisobotni sana bo\'yicha filtrlash', ruDescription: 'Выбор периода отчёта', uzDescription: 'Hisobot davrini tanlash', ruFunctionality: 'Позволяет выбрать период для отчёта', uzFunctionality: 'Hisobot uchun davrni tanlash imkonini beradi', uiLocation: 'Отчёты → Фильтр "Период"', order: 165 },
  { category: 'reports', ruName: 'Экспорт отчёта', uzName: 'Hisobotni eksport qilish', ruDescription: 'Выгрузка отчёта', uzDescription: 'Hisobotni yuklab olish', ruFunctionality: 'Позволяет выгрузить отчёт в Excel', uzFunctionality: 'Hisobotni Excelga yuklab olish imkonini beradi', uiLocation: 'Отчёты → Кнопка "Экспорт"', order: 166 },
  { category: 'reports', ruName: 'Топ продаж', uzName: 'Sotuvlar reytingi', ruDescription: 'Рейтинг продаж', uzDescription: 'Sotuvlar reytingi', ruFunctionality: 'Показывает самые продаваемые товары', uzFunctionality: 'Eng ko\'p sotilgan tovarlarni ko\'rsatadi', uiLocation: 'Боковое меню → Отчёты → Топ продаж', order: 167 },
  { category: 'reports', ruName: 'P&L отчёт', uzName: 'P&L hisobot', ruDescription: 'Отчёт о прибылях и убытках', uzDescription: 'Foyda va zarar hisoboti', ruFunctionality: 'Показывает доходы, расходы и прибыль', uzFunctionality: 'Daromad, xarajat va foydani ko\'rsatadi', uiLocation: 'Боковое меню → Отчёты → P&L отчёт', order: 168 },
  { category: 'reports', ruName: 'Салдо', uzName: 'Saldo', ruDescription: 'Балансовый отчёт', uzDescription: 'Balans hisoboti', ruFunctionality: 'Показывает остатки и балансы', uzFunctionality: 'Qoldiqlar va balanslarni ko\'rsatadi', uiLocation: 'Боковое меню → Отчёты → Салдо', order: 169 },
  { category: 'reports', ruName: 'Материальный отчёт', uzName: 'Material hisobot', ruDescription: 'Отчёт по материалам', uzDescription: 'Materiallar bo\'yicha hisobot', ruFunctionality: 'Показывает движение материалов', uzFunctionality: 'Materiallar harakatini ko\'rsatadi', uiLocation: 'Боковое меню → Отчёты → Материальный отчёт', order: 170 },
  { category: 'reports', ruName: 'Отчёт ABC', uzName: 'ABC hisobot', ruDescription: 'ABC-анализ товаров', uzDescription: 'Tovarlarning ABC-tahlili', ruFunctionality: 'Классифицирует товары по важности', uzFunctionality: 'Tovarlarni ahamiyat bo\'yicha tasniflaydi', uiLocation: 'Боковое меню → Отчёты → Отчёт ABC', order: 171 },
  { category: 'reports', ruName: 'Отчёт XYZ', uzName: 'XYZ hisobot', ruDescription: 'XYZ-анализ спроса', uzDescription: 'Talabning XYZ-tahlili', ruFunctionality: 'Анализирует стабильность спроса', uzFunctionality: 'Talab barqarorligini tahlil qiladi', uiLocation: 'Боковое меню → Отчёты → Отчёт XYZ', order: 172 },
  { category: 'reports', ruName: 'Отчёт ABC/XYZ', uzName: 'ABC/XYZ hisobot', ruDescription: 'Комплексный анализ', uzDescription: 'Kompleks tahlil', ruFunctionality: 'Сочетает ABC и XYZ анализ', uzFunctionality: 'ABC va XYZ tahlilini birlashtiradi', uiLocation: 'Боковое меню → Отчёты → Отчёт ABC/XYZ', order: 173 },
  { category: 'reports', ruName: 'Отчёт по параметрам', uzName: 'Parametrlar hisoboti', ruDescription: 'Отчёт по атрибутам товаров', uzDescription: 'Tovar atributlari bo\'yicha hisobot', ruFunctionality: 'Анализ по цвету, размеру и другим параметрам', uzFunctionality: 'Rang, o\'lcham va boshqa parametrlar bo\'yicha tahlil', uiLocation: 'Боковое меню → Отчёты → Отчёт по параметрам', order: 174 },
  { category: 'reports', ruName: 'Товары без движения', uzName: 'Harakatsiz tovarlar', ruDescription: 'Товары без движения', uzDescription: 'Harakatsiz tovarlar', ruFunctionality: 'Показывает товары без продаж', uzFunctionality: 'Sotuv bo\'lmagan tovarlarni ko\'rsatadi', uiLocation: 'Боковое меню → Отчёты → Товары без движения', order: 175 },

  // === НАСТРОЙКИ (176-195) ===
  { category: 'settings', ruName: 'Методы оплаты', uzName: 'To\'lov usullari', ruDescription: 'Настройка способов оплаты', uzDescription: 'To\'lov usullarini sozlash', ruFunctionality: 'Открывает список способов приёма платежей', uzFunctionality: 'To\'lov qabul qilish usullari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Настройки → Методы оплаты', order: 176 },
  { category: 'settings', ruName: 'Добавить метод оплаты', uzName: 'To\'lov usulini qo\'shish', ruDescription: 'Создание метода оплаты', uzDescription: 'To\'lov usulini yaratish', ruFunctionality: 'Позволяет добавить новый способ оплаты', uzFunctionality: 'Yangi to\'lov usulini qo\'shish imkonini beradi', uiLocation: 'Методы оплаты → Кнопка "Добавить"', order: 177 },
  { category: 'settings', ruName: 'Ценники', uzName: 'Narx yorliqlari', ruDescription: 'Настройка ценников', uzDescription: 'Narx yorliqlarini sozlash', ruFunctionality: 'Открывает настройки печати ценников', uzFunctionality: 'Narx yorliqlarini chop etish sozlamalarini ochadi', uiLocation: 'Боковое меню → Настройки → Ценники', order: 178 },
  { category: 'settings', ruName: 'Чеки', uzName: 'Cheklar', ruDescription: 'Настройка печати чеков', uzDescription: 'Cheklarni chop etishni sozlash', ruFunctionality: 'Открывает параметры кассовых чеков', uzFunctionality: 'Kassa cheklari parametrlarini ochadi', uiLocation: 'Боковое меню → Настройки → Чеки', order: 179 },
  { category: 'settings', ruName: 'Логотип на чеке', uzName: 'Chekdagi logotip', ruDescription: 'Загрузка логотипа', uzDescription: 'Logotipni yuklash', ruFunctionality: 'Позволяет добавить логотип на чек', uzFunctionality: 'Chekka logotip qo\'shish imkonini beradi', uiLocation: 'Чеки → Поле "Логотип"', order: 180 },
  { category: 'settings', ruName: 'Устройства', uzName: 'Qurilmalar', ruDescription: 'Подключение оборудования', uzDescription: 'Uskunani ulash', ruFunctionality: 'Открывает список подключённых устройств', uzFunctionality: 'Ulangan qurilmalar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Настройки → Устройства', order: 181 },
  { category: 'settings', ruName: 'Добавить устройство', uzName: 'Qurilma qo\'shish', ruDescription: 'Подключение нового устройства', uzDescription: 'Yangi qurilma ulash', ruFunctionality: 'Позволяет добавить кассу, принтер или сканер', uzFunctionality: 'Kassa, printer yoki skaner qo\'shish imkonini beradi', uiLocation: 'Устройства → Кнопка "Добавить"', order: 182 },
  { category: 'settings', ruName: 'Ценообразование', uzName: 'Narx belgilash', ruDescription: 'Настройка правил цен', uzDescription: 'Narx qoidalarini sozlash', ruFunctionality: 'Открывает правила формирования цен', uzFunctionality: 'Narx shakllantirish qoidalarini ochadi', uiLocation: 'Боковое меню → Настройки → Ценообразование', order: 183 },
  { category: 'settings', ruName: 'Параметры', uzName: 'Parametrlar', ruDescription: 'Дополнительные параметры товаров', uzDescription: 'Tovarlarning qo\'shimcha parametrlari', ruFunctionality: 'Открывает настройку атрибутов товаров', uzFunctionality: 'Tovar atributlarini sozlashni ochadi', uiLocation: 'Боковое меню → Настройки → Параметры', order: 184 },
  { category: 'settings', ruName: 'Теги', uzName: 'Teglar', ruDescription: 'Управление тегами', uzDescription: 'Teglarni boshqarish', ruFunctionality: 'Открывает список тегов для категоризации', uzFunctionality: 'Kategoriyalash uchun teglar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Настройки → Теги', order: 185 },
  { category: 'settings', ruName: 'Интерфейс', uzName: 'Interfeys', ruDescription: 'Настройка внешнего вида', uzDescription: 'Tashqi ko\'rinishni sozlash', ruFunctionality: 'Открывает настройки темы и языка', uzFunctionality: 'Mavzu va til sozlamalarini ochadi', uiLocation: 'Боковое меню → Настройки → Интерфейс', order: 186 },
  { category: 'settings', ruName: 'Смена языка', uzName: 'Tilni o\'zgartirish', ruDescription: 'Выбор языка интерфейса', uzDescription: 'Interfeys tilini tanlash', ruFunctionality: 'Позволяет выбрать русский или узбекский', uzFunctionality: 'Rus yoki o\'zbek tilini tanlash imkonini beradi', uiLocation: 'Интерфейс → Поле "Язык"', order: 187 },
  { category: 'settings', ruName: 'Телеграм бот', uzName: 'Telegram bot', ruDescription: 'Настройка уведомлений', uzDescription: 'Bildirishnomalarni sozlash', ruFunctionality: 'Открывает настройки Telegram бота', uzFunctionality: 'Telegram bot sozlamalarini ochadi', uiLocation: 'Боковое меню → Настройки → Телеграм бот', order: 188 },
  { category: 'settings', ruName: 'Подключить бота', uzName: 'Botni ulash', ruDescription: 'Подключение Telegram бота', uzDescription: 'Telegram botni ulash', ruFunctionality: 'Позволяет подключить бота для уведомлений', uzFunctionality: 'Bildirishnomalar uchun botni ulash imkonini beradi', uiLocation: 'Телеграм бот → Кнопка "Подключить"', order: 189 },
  { category: 'settings', ruName: 'Тарифы', uzName: 'Tariflar', ruDescription: 'Управление тарифом', uzDescription: 'Tarifni boshqarish', ruFunctionality: 'Открывает информацию о текущем тарифе', uzFunctionality: 'Joriy tarif haqida ma\'lumotni ochadi', uiLocation: 'Боковое меню → Настройки → Тарифы', order: 190 },
  { category: 'settings', ruName: 'Сменить тариф', uzName: 'Tarifni o\'zgartirish', ruDescription: 'Смена тарифного плана', uzDescription: 'Tarif rejasini o\'zgartirish', ruFunctionality: 'Позволяет перейти на другой тариф', uzFunctionality: 'Boshqa tarifga o\'tish imkonini beradi', uiLocation: 'Тарифы → Кнопка "Сменить"', order: 191 },
  { category: 'settings', ruName: 'Подписки', uzName: 'Obunalar', ruDescription: 'Управление подписками', uzDescription: 'Obunalarni boshqarish', ruFunctionality: 'Открывает список активных подписок', uzFunctionality: 'Faol obunalar ro\'yxatini ochadi', uiLocation: 'Боковое меню → Настройки → Подписки', order: 192 },
  { category: 'settings', ruName: 'Кассы', uzName: 'Kassalar', ruDescription: 'Управление кассами', uzDescription: 'Kassalarni boshqarish', ruFunctionality: 'Открывает список кассовых аппаратов', uzFunctionality: 'Kassa apparatlari ro\'yxatini ochadi', uiLocation: 'Боковое меню → Настройки → Кассы', order: 193 },
  { category: 'settings', ruName: 'Данные компании', uzName: 'Kompaniya ma\'lumotlari', ruDescription: 'Реквизиты компании', uzDescription: 'Kompaniya rekvizitlari', ruFunctionality: 'Открывает форму с реквизитами', uzFunctionality: 'Rekvizitli formani ochadi', uiLocation: 'Боковое меню → Настройки → Данные', order: 194 },
  { category: 'settings', ruName: 'Сохранить данные', uzName: 'Ma\'lumotlarni saqlash', ruDescription: 'Сохранение реквизитов', uzDescription: 'Rekvizitlarni saqlash', ruFunctionality: 'Сохраняет данные компании', uzFunctionality: 'Kompaniya ma\'lumotlarini saqlaydi', uiLocation: 'Данные → Кнопка "Сохранить"', order: 195 },

  // === КАБИНЕТ (196-200) ===
  { category: 'cabinet', ruName: 'Кабинет', uzName: 'Kabinet', ruDescription: 'Личный кабинет', uzDescription: 'Shaxsiy kabinet', ruFunctionality: 'Открывает личный кабинет пользователя', uzFunctionality: 'Foydalanuvchining shaxsiy kabinetini ochadi', uiLocation: 'Боковое меню → Кабинет', order: 196 },
  { category: 'cabinet', ruName: 'Изменить пароль', uzName: 'Parolni o\'zgartirish', ruDescription: 'Смена пароля', uzDescription: 'Parolni o\'zgartirish', ruFunctionality: 'Позволяет изменить пароль аккаунта', uzFunctionality: 'Akkaunt parolini o\'zgartirish imkonini beradi', uiLocation: 'Кабинет → Смена пароля', order: 197 },
  { category: 'cabinet', ruName: 'Уведомления', uzName: 'Bildirishnomalar', ruDescription: 'Настройка уведомлений', uzDescription: 'Bildirishnomalarni sozlash', ruFunctionality: 'Позволяет настроить уведомления', uzFunctionality: 'Bildirishnomalarni sozlash imkonini beradi', uiLocation: 'Кабинет → Уведомления', order: 198 },
  { category: 'cabinet', ruName: 'История входов', uzName: 'Kirishlar tarixi', ruDescription: 'История авторизаций', uzDescription: 'Avtorizatsiya tarixi', ruFunctionality: 'Показывает историю входов в систему', uzFunctionality: 'Tizimga kirish tarixini ko\'rsatadi', uiLocation: 'Кабинет → История входов', order: 199 },
  { category: 'cabinet', ruName: 'Удалить аккаунт', uzName: 'Akkauntni o\'chirish', ruDescription: 'Удаление аккаунта', uzDescription: 'Akkauntni o\'chirish', ruFunctionality: 'Позволяет удалить аккаунт', uzFunctionality: 'Akkauntni o\'chirish imkonini beradi', uiLocation: 'Кабинет → Удалить аккаунт', order: 200 },
];

async function main() {
  console.log('Starting seed...');

  try {
    // Check if lessons already exist
    const existingCount = await prisma.lesson.count();
    
    if (existingCount > 0) {
      console.log(`Lessons already exist (${existingCount} records). Skipping seed.`);
      console.log('Set FORCE_SEED=1 to force re-seed.');
      
      if (process.env.FORCE_SEED !== '1') {
        return;
      }
      
      console.log('FORCE_SEED=1, re-seeding...');
      await prisma.lesson.deleteMany({});
      console.log('Cleared existing lessons');
    }

    // Insert new lessons
    for (const lesson of lessons) {
      await prisma.lesson.create({ data: lesson });
    }

    console.log(`Inserted ${lessons.length} lessons`);
  } catch (error) {
    console.error('Seed error:', error);
    // Don't fail the build if seed fails
    console.log('Continuing without seed...');
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
