// Update lessons 121-160 with detailed descriptions (3+ paragraphs)
// Run: node --import tsx scripts/update-lessons-121-160.ts

import dotenv from 'dotenv';
dotenv.config();

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const detailedLessons: {
  order: number;
  ruDescription: string;
  uzDescription: string;
  ruFunctionality: string;
  uzFunctionality: string;
}[] = [
  // === СПРАВОЧНИК: КЛИЕНТЫ (продолжение) ===
  {
    order: 121,
    ruDescription: 'Баллы лояльности отображают накопленные бонусы клиента в программе поощрения. Это важный показатель активности и вовлечённости покупателя в систему лояльности организации.\n\nКаждая покупка приносит клиенту определённое количество баллов в зависимости от правил программы. Баллы можно использовать для оплаты части стоимости товаров или получать специальные скидки и привилегии.\n\nИстория начисления и списания баллов сохраняется в системе, что позволяет анализировать поведение клиента и предлагать персонализированные условия. Админы могут вручную корректировать баланс баллов при необходимости.',
    uzDescription: 'Sodiqlik ballari mijozning rag\'batlantirish dasturida to\'plagan bonuslarini ko\'rsatadi. Bu xaridorning sodiqlik tizimiga faolligi va jalbiy darajasining muhim ko\'rsatkichidir.\n\nHar bir xarid mijozga dastur qoidalariga ko\'ra ma\'lum miqdorda ball olib keladi. Ballarni tovarlar narxining bir qismini to\'lash uchun ishlatish yoki maxsus chegirmalar va imtiyozlarga ega bo\'lish mumkin.\n\nBallarning yig\'ilishi va sarflash tarixi tizimda saqlanadi, bu mijoz xulqini tahlil qilish va shaxsiylashtirilgan shartlarni taklif qilish imkonini beradi. Adminlar zarurat bo\'lganda qo\'lda ball balansini tuzatishi mumkin.',
    ruFunctionality: 'Отображает текущий баланс баллов лояльности клиента с возможностью просмотра истории операций. При клике на поле открывается детальная информация о всех начислениях и списаниях.\n\nСистема автоматически рассчитывает доступные баллы для использования при оформлении чека. Админы могут вручную добавлять или списывать баллы через форму редактирования клиента.\n\nБаллы имеют срок действия, который отображается рядом с балансом. Это помогает клиентам планировать использование накопленных бонусов.',
    uzFunctionality: 'Mijozning sodiqlik ballari joriy balansini operatsiyalar tarixini ko\'rish imkoniyati bilan ko\'rsatadi. Maydon bosilganda barcha yig\'ish va sarflash haqida batafsil ma\'lumot ochiladi.\n\nTizim chekni rasmiylashtirishda foydalanish uchun mavjud ballarni avtomatik hisoblaydi. Adminlar mijozni tahrirlash formasi orqali qo\'lda ball qo\'shish yoki yozib chiqarishi mumkin.\n\nBallarning amal qilish muddati bor, u balans yonida ko\'rsatiladi. Bu mijozlarga to\'plangan bonuslardan foydalanishni rejalashtirishga yordam beradi.'
  },

  {
    order: 122,
    ruDescription: 'Блокировка клиента позволяет ограничить возможность покупок в долг для ненадёжных клиентов. Это инструмент управления кредитными рисками и дебиторской задолженностью.\n\nПри блокировке клиент не может совершать покупки с отсрочкой платежа, но может продолжать покупать за наличный расчёт. Это помогает контролировать рост просроченной задолженности.\n\nСистема уведомляет клиента о блокировке при попытке оформить покупку в долг. Админы могут снять блокировку после погашения задолженности или по решению руководства.',
    uzDescription: 'Mijozni bloklash ishonchsiz mijozlarga qarzga xarid qilish imkoniyatini cheklash imkonini beradi. Bu kredit xavflari va debitorlik qarzini boshqarish vositasidir.\n\nBloklashda mijoz to\'lovni kechiktirib xarid qilishi mumkin emas, lekin naqd pulga xarid qilishni davom ettirishi mumkin. Bu kechiktirilgan qarzning o\'sishini nazorat qilishga yordam beradi.\n\nTizim mijozga qarzga xarid qilishga urinishda bloklash haqida xabar beradi. Adminlar qarz to\'langandan so\'ng yoki rahbariyat qaroriga binoan blokni olib tashlashi mumkin.',
    ruFunctionality: 'Устанавливает статус блокировки для клиента, что предотвращает оформление покупок в долг. При активации блокировки система требует указания причины и опционально даты автоматической разблокировки.\n\nЗаблокированные клиенты помечаются специальным значком в списке для быстрой идентификации. При попытке создать документ реализации в долг система показывает предупреждение о блокировке.\n\nИстория блокировок сохраняется с указанием даты, причины и администратора, установившего блок. Это помогает анализировать платежную дисциплину клиентов.',
    uzFunctionality: 'Mijoz uchun bloklash holatini o\'rnatadi, bu qarzga xarid qilishni rasmiylashtirishni oldini oladi. Bloklash faollashtirilganda tizim sababni ko\'rsatishni va ixtiyoriy ravishda avtomatik blokdan chiqarish sanasini talab qiladi.\n\nBloklangan mijozlar ro\'yxatda tez identifikatsiya qilish uchun maxsus belgi bilan belgilanadi. Qarzga realizatsiya hujjatini yaratishga urinishda tizim bloklash haqida ogohlantirish ko\'rsatadi.\n\nBloklash tarixi sana, sabab va blokni o\'rnatgan administrator ko\'rsatilgan holda saqlanadi. Bu mijozlarning to\'lov intizomini tahlil qilishga yordam beradi.'
  },

  // === СПРАВОЧНИК: ЛОЯЛЬНОСТЬ ===
  {
    order: 123,
    ruDescription: 'Раздел "Лояльность" предназначен для создания и управления программами поощрения постоянных клиентов. Это мощный инструмент повышения удержания покупателей и увеличения среднего чека.\n\nВ разделе можно настроить различные механики вознаграждения: начисление баллов за покупки, уровни привилегий, персональные скидки и специальные предложения. Каждая программа может иметь свои правила и условия.\n\nСистема поддерживает интеграцию с пластиковыми картами лояльности и мобильными приложениями. Это позволяет клиентам накапливать и тратить бонусы удобным способом.',
    uzDescription: '"Sodiqlik" bo\'limi doimiy mijozlarni rag\'batlantirish dasturlarini yaratish va boshqarish uchun mo\'ljallangan. Bu xaridorlarni ushlab qolish va o\'rtacha chekni oshirishning kuchli vositasidir.\n\nBo\'limda turli mukofotlash mexanizmlarini sozlash mumkin: xaridlar uchun ball yig\'ish, imtiyoz darajalari, shaxsiy chegirmalar va maxsus takliflar. Har bir dastur o\'z qoidalari va shartlariga ega bo\'lishi mumkin.\n\nTizim sodiqlik plastik kartalari va mobil ilovalar bilan integratsiyani qo\'llab-quvvatlaydi. Bu mijozlarga qulay usulda bonus yig\'ish va sarflash imkonini beradi.',
    ruFunctionality: 'Открывает центр управления программами лояльности с возможностью создания, редактирования и анализа эффективности. Интерфейс включает обзор ключевых показателей: количество участников, начисленные баллы, уровень вовлечённости.\n\nКаждая программа имеет гибкие настройки: правила начисления баллов, пороги перехода между уровнями, сроки действия бонусов. Можно создавать сложные комбинированные механики поощрения.\n\nСистема автоматически обрабатывает транзакции лояльности при продажах и предоставляет отчёты для анализа эффективности программ.',
    uzFunctionality: 'Sodiqlik dasturlarini yaratish, tahrirlash va samaradorlikni tahlil qilish imkoniyati bilan boshqaruv markazini ochadi. Interfeys asosiy ko\'rsatkichlarning ko\'rinishini o\'z ichiga oladi: ishtirokchilar soni, yig\'ilgan ballar, jalb qilish darajasi.\n\nHar bir dastur moslashuvchan sozlamalarga ega: ball yig\'ish qoidalari, darajalar o\'rtasida o\'tish chegaralari, bonuslarning amal qilish muddati. Murakkab birikma rag\'batlantirish mexanizmlarini yaratish mumkin.\n\nTizim sotuvlarda sodiqlik operatsiyalarini avtomatik qayta ishlaydi va dasturlar samaradorligini tahlil qilish uchun hisobotlarni taqdim etadi.'
  },

  {
    order: 124,
    ruDescription: 'Кнопка создания программы открывает форму для настройки новой программы лояльности. Это первый шаг к построению долгосрочных отношений с клиентами.\n\nВ форме указывается название программы, описание, правила начисления и использования баллов. Можно настроить несколько уровней участия с различными привилегиями.\n\nПосле создания программа становится доступной для подключения клиентов через номер телефона, карту или QR-код. Система автоматически отслеживает участие и начисляет вознаграждения.',
    uzDescription: 'Dastur yaratish tugmasi yangi sodiqlik dasturini sozlash uchuna formani ochadi. Bu mijozlar bilan uzoq muddatli munosabatlarni qurishga birinchi qadam.\n\nFormada dastur nomi, tavsifi, ballarni yig\'ish va foydalanish qoidalari ko\'rsatiladi. Turli imtiyozlar bilan bir nechta ishtirok darajalarini sozlash mumkin.\n\nYaratilgandan so\'ng dastur mijozlar uchun telefon raqami, karta yoki QR-kod orqali ulanish uchun mavjud bo\'ladi. Tizim ishtirokni avtomatik kuzatadi va mukofotlarni yig\'ib beradi.',
    ruFunctionality: 'Открывает многошаговую форму создания программы лояльности с пошаговой настройкой параметров. Первый шаг — ввод базовой информации: название, описание, период действия.\n\nВторой шаг — настройка правил начисления баллов: процент от суммы покупки, множители для определённых категорий товаров, бонусы за первую покупку. Можно настроить дни с ускоренным начислением.\n\nТретий шаг — создание уровней лояльности с порогами перехода и индивидуальными привилегиями. После сохранения программа готова к использованию.',
    uzFunctionality: 'Parametrlarni bosqichma-bosqich sozlash bilan sodiqlik dasturini yaratishning ko\'p bosqichli formasini ochadi. Birinchi qadam — asosiy ma\'lumotlarni kiritish: nom, tavsif, amal qilish davri.\n\nIkkinchi qadam — ball yig\'ish qoidalarini sozlash: xarid summasidan foiz, ma\'lum tovar kategoriyalari uchun ko\'paytiruvchilar, birinchi xarid uchun bonuslar. Tezlashtirilgan yig\'ish kunlarini sozlash mumkin.\n\nUchinchi qadam — o\'tish chegaralari va shaxsiy imtiyozlar bilan sodiqlik darajalarini yaratish. Saqlangandan so\'ng dastur foydalanishga tayyor.'
  },

  {
    order: 125,
    ruDescription: 'Настройка начисления баллов определяет правила, по которым клиенты получают бонусы за свои покупки. Это ключевой элемент программы лояльности, влияющий на мотивацию клиентов.\n\nМожно настроить фиксированный процент от суммы покупки или дифференцированные ставки для разных категорий товаров. Дополнительно доступны бонусы за определённые действия: регистрацию, день рождения, рефералов.\n\nСистема поддерживает временные акции с ускоренным начислением в определённые дни или периоды. Это позволяет стимулировать продажи в низкие сезоны.',
    uzDescription: 'Ball yig\'ish sozlamalari mijozlar o\'z xaridlari uchun bonuslarni qanday qoidalar bo\'yicha olishini belgilaydi. Bu mijozlarning motivatsiyasiga ta\'sir qiluvchi sodiqlik dasturining muhim elementi.\n\nXarid summasidan belgilangan foizni yoki turli tovar kategoriyalari uchun differentsial stavkalarni sozlash mumkin. Qo\'shimcha ravishda ma\'lum harakatlar uchun bonuslar mavjud: ro\'yxatdan o\'tish, tug\'ilgan kun, referral.\n\nTizim ma\'lum kunlar yoki davrlarda tezlashtirilgan yig\'ish bilan vaqtinchalik aksiyalarni qo\'llab-quvvatlaydi. Bu past mavsumlarda sotuvlarni rag\'batlantirish imkonini beradi.',
    ruFunctionality: 'Открывает панель настройки правил начисления баллов с гибкими параметрами. Основная формула — процент от суммы чека, который можно дифференцировать по категориям, времени или сумме покупки.\n\nДополнительные механики включают: приветственные баллы при регистрации, бонусы в день рождения, награды за приглашение друзей. Можно настроить округление суммы баллов и минимальный порог начисления.\n\nСистема валидирует настройки и показывает примеры расчёта баллов для типичных покупок. Это помогает избежать ошибок при конфигурации программы.',
    uzFunctionality: 'Moslashuvchan parametrlar bilan ball yig\'ish qoidalarini sozlash panelini ochadi. Asosiy formula — chek summasidan foiz, uni kategoriyalar, vaqt yoki xarid summasi bo\'yicha differentsiallashtirish mumkin.\n\nQo\'shimcha mexanizmlar quyidagilarni o\'z ichiga oladi: ro\'yxatdan o\'tganda salomlash ballari, tug\'ilgan kunda bonuslar, do\'stlarni taklif qilish uchun mukofotlar. Ballar summasini yaxlitlash va yig\'ishning minimal chegarasini sozlash mumkin.\n\nTizim sozlamalarni tasdiqlaydi va tipik xaridlar uchun ball hisoblash namunalarini ko\'rsatadi. Bu konfiguratsiyada xatolardan qochishga yordam beradi.'
  },

  {
    order: 126,
    ruDescription: 'Уровни лояльности создают иерархическую систему привилегий для клиентов в зависимости от их активности. Это мотивирует покупателей увеличивать обороты для достижения новых статусов.\n\nКаждый уровень имеет свои пороги перехода и набор привилегий: процент кэшбэка, персональная скидка, приоритетное обслуживание, эксклюзивные акции. Клиенты видят свой прогресс до следующего уровня.\n\nСистема автоматически пересчитывает уровень клиента на основе его покупок за определённый период. Можно настроить понижение уровня при снижении активности.',
    uzDescription: 'Sodiqlik darajalari mijozlarning faolligiga qarab ular uchun imtiyozlarning ierarxik tizimini yaratadi. Bu xaridorlarni yangi maqomlarga erishish uchun aylanmalarni oshirishga undaydi.\n\nHar bir darajaning o\'z o\'tish chegaralari va imtiyozlar to\'plami bor: keşback foizi, shaxsiy chegirma, ustuvor xizmat ko\'rsatish, eksklyuziv aksiyalar. Mijozlar keyingi darajagacha bo\'lgan o\'z taraqqiyotini ko\'rishadi.\n\nTizim ma\'lum davr mobaynidagi xaridlar asosida mijoz darajasini avtomatik qayta hisoblaydi. Faollik pasayganda darajani tushirishni sozlash mumkin.',
    ruFunctionality: 'Открывает интерфейс управления уровнями лояльности с визуальным представлением иерархии. Можно создать до 10 уровней с индивидуальными названиями, иконками и цветовыми обозначениями.\n\nДля каждого уровня настраиваются: порог перехода в баллах или сумме покупок, процент бонуса, размер скидки, специальные условия. Система показывает распределение клиентов по уровням.\n\nКлиенты видят свой текущий уровень и прогресс до следующего в личном кабинете или при оформлении чека. Это создаёт игровой элемент и мотивацию к развитию.',
    uzFunctionality: 'Ierarxiyaning vizual tasviri bilan sodiqlik darajalarini boshqarish interfeysini ochadi. 10 tagacha darajani shaxsiy nomlar, ikonkalar va rangli belgilar bilan yaratish mumkin.\n\nHar bir daraja uchun sozlanadi: ballarda yoki xarid summasida o\'tish chegarasi, bonus foizi, chegirma hajmi, maxsus shartlar. Tizim mijozlarning darajalar bo\'yicha taqsimlanishini ko\'rsatadi.\n\nMijozlar o\'zlarining joriy darajasini va keyingisigacha bo\'lgan taraqqiyotini shaxsiy kabinetda yoki chekni rasmiylashtirishda ko\'rishadi. Bu o\'yin elementini va rivojlanishga motivatsiyani yaratadi.'
  },

  // === СПРАВОЧНИК: КОНТРАГЕНТЫ ===
  {
    order: 127,
    ruDescription: 'Раздел "Контрагенты" содержит базу данных всех организаций и физических лиц, с которыми компания ведёт бизнес. Это центральный справочник для работы с поставщиками, покупателями и партнёрами.\n\nВ разделе хранится полная информация о контрагентах: реквизиты, контакты, история взаимоотношений, документы. Система поддерживает поиск и фильтрацию по различным критериям.\n\nНа основе данных контрагентов формируются документы поставки, реализации, счета и взаиморасчёты. Корректное ведение справочника обеспечивает точность учёта.',
    uzDescription: '"Kontragentlar" bo\'limi kompaniya biznes yurayotgan barcha tashkilotlar va jismoniy shaxslarning ma\'lumotlar bazasini o\'z ichiga oladi. Bu yetkazib beruvchilar, xaridorlar va hamkorlar bilan ishlash uchun markaziy ma\'lumotnomadir.\n\nBo\'limda kontragentlar haqida to\'liq ma\'lumotlar saqlanadi: rekvizitlar, kontaktlar, o\'zaro munosabatlar tarixi, hujjatlar. Tizim turli mezonlar bo\'yicha qidiruv va filtrlashni qo\'llab-quvvatlaydi.\n\nKontragentlar ma\'lumotlari asosida yetkazib berish, realizatsiya, hisoblar va o\'zaro hisob-kitob hujjatlari shakllantiriladi. Ma\'lumotnomani to\'g\'ri yuritish hisobning aniqligini ta\'minlaydi.',
    ruFunctionality: 'Открывает реестр контрагентов с возможностью просмотра, поиска и управления записями. Интерфейс включает таблицу с основными данными: наименование, тип, ИНН, телефон, текущий баланс взаиморасчётов.\n\nПоиск работает по наименованию, ИНН, номеру телефона и другим идентификаторам. Фильтрация позволяет отобрать контрагентов по типу, группе, статусу или другим параметрам.\n\nИз карточки контрагента доступна вся история взаимодействий: документы, платежи, контакты. Это обеспечивает комплексный взгляд на отношения с партнёром.',
    uzFunctionality: 'Yozuvlarni ko\'rish, qidirish va boshqarish imkoniyati bilan kontragentlar reestrini ochadi. Interfeys asosiy ma\'lumotlar bilan jadvalni o\'z ichiga oladi: nom, tur, INN, telefon, o\'zaro hisob-kitoblarning joriy balansi.\n\nQidiruv nom, INN, telefon raqami va boshqa identifikatorlar bo\'yicha ishlaydi. Filtrlash kontragentlarni tur, guruh, holat yoki boshqa parametrlar bo\'yicha tanlash imkonini beradi.\n\nKontragent kartochkasidan o\'zaro munosabatlarning butun tarixi mavjud: hujjatlar, to\'lovlar, kontaktlar. Bu hamkor bilan munosabatlarga kompleks qarashni ta\'minlaydi.'
  },

  {
    order: 128,
    ruDescription: 'Кнопка добавления контрагента открывает форму для создания новой записи в справочнике контрагентов. Это первый шаг при появлении нового партнёра или клиента.\n\nФорма содержит все необходимые поля: наименование, тип контрагента, юридические реквизиты, контактные данные. Система поддерживает автозаполнение данных по ИНН для юридических лиц.\n\nПосле сохранения контрагент становится доступен для выбора в документах. Можно привязать несколько контактных лиц и адресов к одной организации.',
    uzDescription: 'Kontragent qo\'shish tugmasi kontragentlar ma\'lumotnomasida yangi yozuv yaratish uchuna formani ochadi. Bu yangi hamkor yoki mijoz paydo bo\'lganda birinchi qadam.\n\nForma barcha kerakli maydonlarni o\'z ichiga oladi: nom, kontragent turi, yuridik rekvizitlar, kontakt ma\'lumotlari. Tizim yuridik shaxslar uchun INN bo\'yicha ma\'lumotlarni avtomatik to\'ldirishni qo\'llab-quvvatlaydi.\n\nSaqlangandan so\'ng kontragent hujjatlarda tanlash uchun mavjud bo\'ladi. Bir tashkilotga bir nechta kontakt shaxslar va manzillarni biriktirish mumkin.',
    ruFunctionality: 'Открывает комплексную форму создания контрагента с группировкой полей по разделам. Основные данные: наименование, тип, группа. Юридические данные: ИНН, КПП, ОГРН, адрес.\n\nКонтактная информация включает телефон, email, сайт, физический адрес. Для каждого контакта можно добавить примечания и несколько контактных лиц.\n\nСистема проверяет уникальность ИНН и корректность введённых данных. После сохранения карточка доступна для редактирования и использования в документах.',
    uzFunctionality: 'Maydonlarni bo\'limlar bo\'yicha guruhlash bilan kontragent yaratishning kompleks formasini ochadi. Asosiy ma\'lumotlar: nom, tur, guruh. Yuridik ma\'lumotlar: INN, KPP, OGRN, manzil.\n\nKontakt ma\'lumotlari telefon, email, sayt, jismoniy manzilni o\'z ichiga oladi. Har bir kontakt uchun izohlar va bir nechta kontakt shaxslarni qo\'shish mumkin.\n\nTizim INNning noyobligini va kiritilgan ma\'lumotlarning to\'g\'riligini tekshiradi. Saqlangandan so\'ng kartochka tahrirlash va hujjatlarda foydalanish uchun mavjud.'
  },

  {
    order: 129,
    ruDescription: 'Поле типа контрагента позволяет классифицировать организацию или физическое лицо по роли в бизнес-процессах. Это важный параметр для правильного учёта и отчётности.\n\nДоступные типы: поставщик, покупатель, партнёр, конкурент. Один контрагент может иметь несколько типов одновременно, например, быть и поставщиком, и покупателем.\n\nТип влияет на доступные операции: поставщики — для документов поступления, покупатели — для реализации. Система автоматически формирует отчёты по каждому типу контрагентов.',
    uzDescription: 'Kontragent turi maydoni tashkilot yoki jismoniy shaxsni biznes jarayonlaridagi roliga ko\'ra tasniflash imkonini beradi. Bu to\'g\'ri hisob va hisobot uchun muhim parametr.\n\nMavjud turlar: yetkazib beruvchi, xaridor, hamkor, raqobatchi. Bir kontragent bir vaqtning o\'zida bir nechta turga ega bo\'lishi mumkin, masalan, ham yetkazib beruvchi, ham xaridor bo\'lish.\n\nTur mavjud operatsiyalarga ta\'sir qiladi: yetkazib beruvchilar — kelib tushish hujjatlari uchun, xaridorlar — realizatsiya uchun. Tizim har bir kontragent turi bo\'yicha avtomatik hisobotlarni shakllantiradi.',
    ruFunctionality: 'Позволяет выбрать один или несколько типов для классификации контрагента. Выбор типа влияет на отображение контрагента в соответствующих разделах и отчётах.\n\nПри выборе типа "Поставщик" контрагент появляется в формах выбора для документов прихода и возврата. Тип "Покупатель" делает его доступным для реализаций и взаиморасчётов.\n\nСистема поддерживает составные типы: контрагент может быть одновременно поставщиком и покупателем. В этом случае он доступен во всех соответствующих документах.',
    uzFunctionality: 'Kontragentni tasniflash uchun bir yoki bir nechta turni tanlash imkonini beradi. Tur tanlash kontragentning tegishli bo\'limlar va hisobotlarda ko\'rsatilishiga ta\'sir qiladi.\n\n"Yetkazib beruvchi" turi tanlanganda kontragent kirim va qaytarish hujjatlari tanlash formasida paydo bo\'ladi. "Xaridor" turi uni realizatsiyalar va o\'zaro hisob-kitoblar uchun mavjud qiladi.\n\nTizim murakkab turlarni qo\'llab-quvvatlaydi: kontragent bir vaqtning o\'zida yetkazib beruvchi va xaridor bo\'lishi mumkin. Bu holda u barcha tegishli hujjatlarda mavjud.'
  },

  {
    order: 130,
    ruDescription: 'Взаиморасчёты с контрагентом показывают историю всех финансовых операций между организацией и партнёром. Это ключевой инструмент контроля дебиторской и кредиторской задолженности.\n\nВкладка взаиморасчётов отображает начальный остаток, все приходные и расходные операции, и конечное сальдо. Каждая операция привязана к документу с возможностью перехода.\n\nМожно сформировать акт сверки взаиморасчётов за любой период. Это необходимо для подтверждения задолженности перед составлением отчётности или при спорных ситуациях.',
    uzDescription: 'Kontragent bilan o\'zaro hisob-kitoblar tashkilot va hamkor o\'rtasidagi barcha moliyaviy operatsiyalar tarixini ko\'rsatadi. Bu debitorlik va kreditorlik qarzini nazorat qilishning muhim vositasidir.\n\nO\'zaro hisob-kitoblar yorlig\'i boshlang\'ich qoldiqni, barcha kiruvchi va chiquvchi operatsiyalarni va yakuniy saldoni ko\'rsatadi. Har bir operatsiya o\'tish imkoniyati bilan hujjatga bog\'langan.\n\nHar qanday davr uchun o\'zaro hisob-kitoblar dalolatnomasini shakllantirish mumkin. Bu hisobot tuzishdan oldin yoki bahsli holatlarda qarzni tasdiqlash uchun zarur.',
    ruFunctionality: 'Открывает ведомость взаиморасчётов с детализацией по документам и датам. Показывает начальное сальдо, обороты за период и конечное сальдо с разбивкой по типам операций.\n\nКаждая строка соответствует документу: поступление, реализация, платёж, корректировка. При клике на строку открывается исходный документ для просмотра деталей.\n\nДоступны фильтры по периоду, типу операции и статусу документа. Можно распечатать акт сверки или экспортировать данные в Excel для анализа.',
    uzFunctionality: 'Hujjatlar va sanalar bo\'yicha batafsil ma\'lumot bilan o\'zaro hisob-kitob varaqasini ochadi. Dastlabki saldo, davrdagi aylanmalar va yakuniy saldoni operatsiya turlari bo\'yicha taqsimlash bilan ko\'rsatadi.\n\nHar bir qator hujjatga mos keladi: kelib tushish, realizatsiya, to\'lov, tuzatish. Qator bosilganda tafsilotlarni ko\'rish uchun asl hujjat ochiladi.\n\nDavr, operatsiya turi va hujjat holati bo\'yicha filtrlar mavjud. Dalolatnomani chop etish yoki tahlil uchun ma\'lumotlarni Excelga eksport qilish mumkin.'
  },

  {
    order: 131,
    ruDescription: 'Поле договора позволяет привязать к контрагенту договор, регулирующий условия сотрудничества. Это важно для юридического оформления отношений и контроля сроков.\n\nВ поле указывается номер и дата договора. Система поддерживает хранение сканированной копии договора в разделе документов для быстрого доступа.\n\nНа основе данных договора система может напоминать о приближении срока действия или автоматически применять условия договора в документах.',
    uzDescription: 'Shartnoma maydoni kontragentga hamkorlik shartlarini tartibga soluvchi shartnomani biriktirish imkonini beradi. Bu munosabatlarning huquqiy rasmiylashtirilishi va muddatlarni nazorat qilish uchun muhim.\n\nMaydonda shartnoma raqami va sanasi ko\'rsatiladi. Tizim tez kirish uchun hujjatlar bo\'limida shartnomaning skanerlangan nusxasini saqlashni qo\'llab-quvvatlaydi.\n\nShartnoma ma\'lumotlari asosida tizim amal qilish muddati yaqinlashishi haqida eslatishi yoki hujjatlarda shartnoma shartlarini avtomatik qo\'llashi mumkin.',
    ruFunctionality: 'Позволяет указать номер, дату и срок действия договора с контрагентом. Данные договора используются при формировании документов и контроле условий сотрудничества.\n\nПри заполнении поля открывается форма с расширенными параметрами: тип договора, срок действия, условия оплаты, ответственность сторон. Можно привязать скан-копию.\n\nСистема автоматически проверяет срок действия договора и предупреждает о необходимости продления. Условия договора подставляются в документы по умолчанию.',
    uzFunctionality: 'Kontragent bilan shartnoma raqami, sanasi va amal qilish muddatini ko\'rsatish imkonini beradi. Shartnoma ma\'lumotlari hujjatlarni shakllantirishda va hamkorlik shartlarini nazorat qilishda ishlatiladi.\n\nMaydon to\'ldirilganda kengaytirilgan parametrlar bilan forma ochiladi: shartnoma turi, amal qilish muddati, to\'lov shartlari, tomonlarning mas\'uliyati. Skan nusxani biriktirish mumkin.\n\nTizim shartnomaning amal qilish muddatini avtomatik tekshiradi va uzaytirish zarurligi haqida ogohlantiradi. Shartnoma shartlari hujjatlarga standart bo\'yicha qo\'yiladi.'
  },

  {
    order: 132,
    ruDescription: 'Кнопка удаления контрагента позволяет удалить запись из справочника. Эта операция требует подтверждения и имеет ограничения для защиты целостности данных.\n\nУдалить можно только контрагента, по которому нет движений в учёте. Если есть документы или платежи, система предложит пометить контрагента как неактивного вместо удаления.\n\nПри удалении система проверяет связи с другими объектами и показывает предупреждение о невозможности восстановления данных.',
    uzDescription: 'Kontragentni o\'chirish tugmasi ma\'lumotnomadan yozuvni o\'chirish imkonini beradi. Bu operatsiya tasdiqlashni talab qiladi va ma\'lumotlar yaxlitligini himoya qilish uchun cheklovlarga ega.\n\nFaqat hisobda harakati bo\'lmagan kontragentni o\'chirish mumkin. Agar hujjatlar yoki to\'lovlar bo\'lsa, tizim o\'chirish o\'rniga kontragentni nofaol deb belgilashni taklif qiladi.\n\nO\'chirishda tizim boshqa ob\'ektlar bilan bog\'lanishlarni tekshiradi va ma\'lumotlarni qayta tiklab bo\'lmasligi haqida ogohlantirish ko\'rsatadi.',
    ruFunctionality: 'Инициирует процедуру удаления контрагента с проверкой связанных объектов. Сначала система анализирует наличие документов, платежей и других связей с данным контрагентом.\n\nЕсли связи обнаружены, предлагается перевести контрагента в статус "Неактивен" вместо удаления. Это сохраняет историю операций и целостность данных.\n\nПри подтверждении удаления все данные контрагента безвозвратно удаляются из системы. Рекомендуется использовать архивацию для сохранения истории.',
    uzFunctionality: 'Bog\'langan ob\'ektlarni tekshirish bilan kontragentni o\'chirish jarayonini boshlaydi. Avval tizim hujjatlar, to\'lovlar va ushbu kontragent bilan boshqa bog\'lanishlarning mavjudligini tahlil qiladi.\n\nAgar bog\'lanishlar aniqlansa, o\'chirish o\'rniga kontragentni "Nofaol" holatiga o\'tkazish taklif etiladi. Bu operatsiyalar tarixini va ma\'lumotlar yaxlitligini saqlaydi.\n\nO\'chirish tasdiqlanganda kontragentning barcha ma\'lumotlari tizimdan qaytarib olinmaydi o\'chiriladi. Tarixni saqlash uchun arxivlashdan foydalanish tavsiya etiladi.'
  },

  // === СПРАВОЧНИК: СМС РАССЫЛКА ===
  {
    order: 133,
    ruDescription: 'Раздел "СМС рассылка" предназначен для организации массовых информационных и маркетинговых кампаний через SMS-сообщения. Это эффективный канал коммуникации с клиентами.\n\nВ разделе можно создавать и отправлять сообщения как отдельным клиентам, так и группам по различным критериям. Система поддерживает персонализацию сообщений с подстановкой имени и других данных.\n\nСтатистика рассылок позволяет оценить эффективность: количество доставленных сообщений, открытия, переходы по ссылкам. Это помогает оптимизировать контент и время отправки.',
    uzDescription: '"SMS tarqatish" bo\'limi SMS-xabarlar orqali ommaviy axborot va marketing kampaniyalarini tashkil qilish uchun mo\'ljallangan. Bu mijozlar bilan samarali aloqa kanalidir.\n\nBo\'limda xabarlarni ham alohida mijozlarga, ham turli mezonlar bo\'yicha guruhlarga yuborish va yaratish mumkin. Tizim xabarlarni nom va boshqa ma\'lumotlarni qo\'yish bilan shaxsiylashtirishni qo\'llab-quvvatlaydi.\n\nTarqatish statistikasi samaradorlikni baholash imkonini beradi: yetkazilgan xabarlar soni, ochish, havolalarga o\'tish. Bu kontent va yuborish vaqtini optimallashtirishga yordam beradi.',
    ruFunctionality: 'Открывает центр управления СМС-рассылками с историей кампаний и статистикой. Интерфейс включает конструктор сообщений, выбор аудитории и планирование отправки.\n\nДля создания рассылки нужно выбрать получателей из базы клиентов, написать текст сообщения и указать время отправки. Можно использовать шаблоны для типовых сообщений.\n\nСистема отслеживает статус каждого сообщения: отправлено, доставлено, прочитано. Отчёты доступны в реальном времени и могут быть выгружены для анализа.',
    uzFunctionality: 'Kampaniyalar tarixi va statistika bilan SMS-tarqatishlarni boshqarish markazini ochadi. Interfeys xabar konstruktori, auditoriyani tanlash va yuborishni rejalashtirishni o\'z ichiga oladi.\n\nTarqatish yaratish uchun mijozlar bazasidan qabul qiluvchilarni tanlash, xabar matnini yozish va yuborish vaqtini ko\'rsatish kerak. Tipik xabarlar uchun shablonlardan foydalanish mumkin.\n\nTizim har bir xabarning holatini kuzatadi: yuborilgan, yetkazilgan, o\'qilgan. Hisobotlar real vaqtda mavjud va tahlil uchun yuklab olinishi mumkin.'
  },

  {
    order: 134,
    ruDescription: 'Выбор получателей рассылки определяет аудиторию, которая получит СМС-сообщения. Правильный таргетинг повышает эффективность кампании и снижает затраты.\n\nМожно выбрать получателей вручную из списка клиентов или использовать фильтры для автоматического отбора. Доступны критерии: дата последней покупки, сумма покупок, категория товаров, день рождения.\n\nСистема показывает предварительную оценку размера аудитории и стоимости рассылки перед запуском. Это помогает планировать бюджет маркетинговых активностей.',
    uzDescription: 'Tarqatish qabul qiluvchilarini tanlash SMS-xabarlarni oladigan auditoriyani belgilaydi. To\'g\'ri targetlash kampaniya samaradorligini oshiradi va xarajatlarni kamaytiradi.\n\nQabul qiluvchilarni mijozlar ro\'yxatidan qo\'lda tanlash yoki avtomatik tanlash uchun filtrlardan foydalanish mumkin. Mavjud mezonlar: oxirgi xarid sanasi, xaridlar summasi, tovarlar kategoriyasi, tug\'ilgan kun.\n\nTizim ishga tushirishdan oldin auditoriya hajmi va tarqatish narxining oldindan bahosini ko\'rsatadi. Bu marketing faoliyati byudjetini rejalashtirishga yordam beradi.',
    ruFunctionality: 'Открывает форму выбора аудитории с ручным и автоматическим отбором. Ручной режим позволяет отметить конкретных клиентов из списка с поиском и фильтрацией.\n\nАвтоматический отбор использует сегментацию: клиенты, не совершавшие покупки более N дней, активные покупатели, клиенты с определённой суммой покупок. Можно комбинировать условия.\n\nПредварительный просмотр показывает количество выбранных получателей и расчётную стоимость рассылки. Можно исключить отдельных клиентов из выборки.',
    uzFunctionality: 'Qo\'lda va avtomatik tanlash bilan auditoriyani tanlash formasini ochadi. Qo\'lla rejim qidiruv va filtrlash bilan ro\'yxatdan aniq mijozlarni belgilash imkonini beradi.\n\nAvtomatik tanlash segmentatsiyadan foydalanadi: N kundan ko\'p xarid qilmagan mijozlar, faol xaridorlar, ma\'lum xarid summasi bilan mijozlar. Shartlarni biriktirish mumkin.\n\nOldindan ko\'rish tanlangan qabul qiluvchilar sonini va taxminiy tarqatish narxini ko\'rsatadi. Tanlovdan alohida mijozlarni chiqarib tashlash mumkin.'
  },

  {
    order: 135,
    ruDescription: 'Поле текста сообщения предназначено для ввода содержания СМС, которое получат клиенты. Качество текста напрямую влияет на эффективность рассылки.\n\nСистема поддерживает персонализацию с помощью переменных: имя клиента, название организации, сумма бонусов. Это делает сообщение более релевантным и повышает конверсию.\n\nОграничение длины СМС — 70 символов для кириллицы и 160 для латиницы. Система показывает счётчик символов и предупреждает о превышении лимита, что может увеличить стоимость.',
    uzDescription: 'Xabar matni maydoni mijozlar oladigan SMS tarkibini kiritish uchun mo\'ljallangan. Matn sifati to\'g\'ridan-to\'g\'ri tarqatish samaradorligiga ta\'sir qiladi.\n\nTizim o\'zgaruvchilar yordamida shaxsiylashtirishni qo\'llab-quvvatlaydi: mijoz ismi, tashkilot nomi, bonus summasi. Bu xabarni yanada dolzarb qiladi va konversiyani oshiradi.\n\nSMS uzunligi cheklovi — kirill uchun 70 ta belgi va lotin uchun 160 ta. Tizim belgilar hisoblagichini ko\'rsatadi va chegirmani oshib ketishi haqida ogohlantiradi, bu narxni oshirishi mumkin.',
    ruFunctionality: 'Открывает текстовый редактор для составления сообщения с проверкой орфографии и подсчётом символов. Можно использовать готовые шаблоны или написать текст с нуля.\n\nПерсонализация достигается вставкой переменных в фигурных скобках: {name} — имя клиента, {bonus} — баланс бонусов. При отправке переменные заменяются на актуальные данные.\n\nСистема предупреждает о потенциальных проблемах: использование слов-спам-триггеров, слишком длинный текст. Это помогает избежать блокировки сообщений операторами.',
    uzFunctionality: 'Imlo tekshirish va belgilarni hisoblash bilan xabar tuzish uchun matn muharririni ochadi. Tayyor shablonlardan foydalanish yoki matnni noldan yozish mumkin.\n\nShaxsiylashtirish figurali qavslarda o\'zgaruvchilarni kiritish orqali erishiladi: {name} — mijoz ismi, {bonus} — bonus balansi. Yuborishda o\'zgaruvchilar dolzarb ma\'lumotlarga almashtiriladi.\n\nTizim potentsial muammolar haqida ogohlantiradi: spam-trigger so\'zlardan foydalanish, juda uzun matn. Bu operatorlar tomonidan xabarlarni bloklashdan qochishga yordam beradi.'
  },

  {
    order: 136,
    ruDescription: 'Кнопка отправки рассылки запускает процесс доставки СМС-сообщений выбранной аудитории. Это финальный шаг создания кампании.\n\nПеред отправкой система показывает итоговую информацию: количество получателей, текст сообщения, расчётную стоимость. Требуется подтверждение для списания средств со баланса.\n\nРассылку можно запланировать на определённое время или отправить немедленно. Отложенные рассылки отображаются в календаре маркетинговых активностей.',
    uzDescription: 'Tarqatishni yuborish tugmasi tanlangan auditoriyaga SMS-xabarlar yetkazib berish jarayonini boshlaydi. Bu kampaniya yaratishning yakuniy qadami.\n\nYuborishdan oldin tizim yakuniy ma\'lumotlarni ko\'rsatadi: qabul qiluvchilar soni, xabar matni, taxminiy narx. Mablag\'larni balansdan yozib qo\'yish uchun tasdiqlash talab qilinadi.\n\nTarqatishni aniq vaqtga rejalashtirish yoki darhol yuborish mumkin. Kechiktirilgan tarqatishlar marketing faoliyati taqvimida ko\'rsatiladi.',
    ruFunctionality: 'Инициирует отправку СМС-рассылки через интегрированный SMS-шлюз. Сначала проверяется достаточность баланса для покрытия стоимости рассылки.\n\nПри нехватке средств предлагается пополнить баланс или уменьшить аудиторию. При достаточном балансе запускается процесс отправки с отслеживанием статуса каждого сообщения.\n\nПосле завершения рассылки доступна детальная статистика: доставлено, не доставлено, ошибки. Данные сохраняются для анализа эффективности кампании.',
    uzFunctionality: 'Integratsiyalashgan SMS-shlyuz orqali SMS-tarqatishni yuborishni boshlaydi. Avval tarqatish narxini qoplash uchun balans yetarliligi tekshiriladi.\n\nMablag\'lar yetishmaganda balansni to\'ldirish yoki auditoriyani kamaytirish taklif etiladi. Balans yetarli bo\'lganda har bir xabar holatini kuzatish bilan yuborish jarayoni boshlanadi.\n\nTarqatish tugagandan so\'ng batafsil statistika mavjud: yetkazildi, yetkazilmadi, xatolar. Ma\'lumotlar kampaniya samaradorligini tahlil qilish uchun saqlanadi.'
  },

  {
    order: 137,
    ruDescription: 'Раздел "Шаблоны СМС" содержит сохранённые тексты сообщений для повторного использования. Это ускоряет создание рассылок и обеспечивает единообразие коммуникации.\n\nШаблоны группируются по категориям: поздравления с днём рождения, напоминания о забытой корзине, информация об акциях, сервисные уведомления. Каждый шаблон можно отредактировать.\n\nИспользование шаблонов экономит время при регулярных рассылках и снижает вероятность ошибок в тексте. Переменные персонализации автоматически подставляют данные клиента.',
    uzDescription: '"SMS shablonlari" bo\'limida qayta foydalanish uchun saqlangan xabar matnlari mavjud. Bu tarqatishlarni yaratishni tezlashtiradi va aloqada bir xillikni ta\'minlaydi.\n\nShablonlar kategoriyalar bo\'yicha guruhlanadi: tug\'ilgan kun bilan tabrik, unutilgan savat haqida eslatma, aksiyalar haqida ma\'lumot, xizmat xabarlari. Har bir shablonni tahrirlash mumkin.\n\nShablonlardan foydalanish muntazam tarqatishlarda vaqtni tejaydi va matndagi xatolik ehtimolini kamaytiradi. Shaxsiylashtirish o\'zgaruvchilari avtomatik mijoz ma\'lumotlarini qo\'yadi.',
    ruFunctionality: 'Открывает библиотеку шаблонов СМС-сообщений с поиском и фильтрацией по категориям. Каждый шаблон содержит название, категорию, текст и переменные персонализации.\n\nПри выборе шаблона открывается предпросмотр с примером подставленных данных. Можно использовать шаблон как есть или модифицировать перед отправкой.\n\nАдминистраторы могут создавать и редактировать шаблоны, настраивать категории. Система хранит историю изменений шаблонов для контроля.',
    uzFunctionality: 'Kategoriyalar bo\'yicha qidiruv va filtrlash bilan SMS-xabarlar shablonlari kutubxonasini ochadi. Har bir shablon nom, kategoriya, matn va shaxsiylashtirish o\'zgaruvchilarini o\'z ichiga oladi.\n\nShablon tanlanganda qo\'yilgan ma\'lumotlar namunasi bilan oldindan ko\'rish ochiladi. Shablonni shu kabi ishlatish yoki yuborishdan oldin o\'zgartirish mumkin.\n\nAdministratorlar shablonlarni yaratishi va tahrirlashi, kategoriyalarni sozlashi mumkin. Tizim nazorat uchun shablonlar o\'zgarishlar tarixini saqlaydi.'
  },

  {
    order: 138,
    ruDescription: 'Кнопка создания шаблона открывает форму для сохранения нового текста сообщения в библиотеку шаблонов. Это полезно для часто используемых типов рассылок.\n\nВ форме указывается название шаблона для быстрого поиска, категория для группировки и сам текст сообщения. Текст может содержать переменные для персонализации.\n\nПосле сохранения шаблон становится доступен всем пользователям с правами работы с рассылками. Можно настроить права на редактирование шаблонов.',
    uzDescription: 'Shablon yaratish tugmasi yangi xabar matnini shablonlar kutubxonasiga saqlash uchuna formani ochadi. Bu tez-tez ishlatiladigan tarqatish turlari uchun foydalidir.\n\nFormada tez qidirish uchun shablon nomi, guruhlash uchun kategoriya va xabar matnining o\'zi ko\'rsatiladi. Matn shaxsiylashtirish uchun o\'zgaruvchilarni o\'z ichiga olishi mumkin.\n\nSaqlangandan so\'ng shablon tarqatishlar bilan ishlash huquqi bor barcha foydalanuvchilar uchun mavjud bo\'ladi. Shablonlarni tahrirlash huquqlarini sozlash mumkin.',
    ruFunctionality: 'Открывает форму создания шаблона с полями: название, категория, текст сообщения. Редактор текста поддерживает вставку переменных персонализации из списка.\n\nДоступные переменные: имя клиента, название организации, баланс бонусов, дата последней покупки. При наведении на переменную показывается описание и пример значения.\n\nСистема проверяет корректность синтаксиса переменных и предупреждает о возможных ошибках. После сохранения шаблон появляется в библиотеке и готов к использованию.',
    uzFunctionality: 'Maydonlar bilan shablon yaratish formasini ochadi: nom, kategoriya, xabar matni. Matn muharriri ro\'yxatdan shaxsiylashtirish o\'zgaruvchilarini kiritishni qo\'llab-quvvatlaydi.\n\nMavjud o\'zgaruvchilar: mijoz ismi, tashkilot nomi, bonus balansi, oxirgi xarid sanasi. O\'zgaruvchi ustiga kursiv olib borilganda tavsif va qiymat namunasi ko\'rsatiladi.\n\nTizim o\'zgaruvchilar sintaksisining to\'g\'riligini tekshiradi va mumkin bo\'lgan xatolar haqida ogohlantiradi. Saqlangandan so\'ng shablon kutubxonada paydo bo\'ladi va foydalanishga tayyor.'
  },

  // === СПРАВОЧНИК: ДОКУМЕНТЫ ===
  {
    order: 139,
    ruDescription: 'Раздел "Документы" предназначен для хранения и управления файлами в системе. Это централизованный архив для договоров, сертификатов, сканов и других документов.\n\nВ разделе отображается список загруженных файлов с информацией о названии, типе, размере, дате загрузки и авторе. Документы можно группировать по папкам и категориям.\n\nСистема поддерживает версионность документов: при загрузке новой версии сохраняется история предыдущих версий. Это обеспечивает контроль изменений и возможность отката.',
    uzDescription: '"Hujjatlar" bo\'limi tizimda fayllarni saqlash va boshqarish uchun mo\'ljallangan. Bu shartnomalar, sertifikatlar, skanlar va boshqa hujjatlar uchun markazlashtirilgan arxiv.\n\nBo\'limda nom, tur, hajm, yuklash sanasi va muallif haqida ma\'lumot bilan yuklangan fayllar ro\'yxati ko\'rsatiladi. Hujjatlarni papkalar va kategoriyalar bo\'yicha guruhlash mumkin.\n\nTizim hujjatlarning versiyaliligini qo\'llab-quvvatlaydi: yangi versiya yuklanganda oldingi versiyalar tarixi saqlanadi. Bu o\'zgarishlarni nazorat qilishni va qaytish imkoniyatini ta\'minlaydi.',
    ruFunctionality: 'Открывает файловый менеджер с деревом папок и списком документов. Интерфейс поддерживает загрузку файлов drag-and-drop, предпросмотр и скачивание.\n\nДокументы можно связывать с объектами системы: контрагентами, товарами, сотрудниками. Это обеспечивает быстрый доступ к документации из карточек соответствующих объектов.\n\nПоиск работает по названию, описанию и содержимому документа (для текстовых форматов). Фильтрация доступна по типу файла, дате загрузки, автору.',
    uzFunctionality: 'Papklar daraxti va hujjatlar ro\'yxati bilan fayl menejerini ochadi. Interfeys drag-and-drop bilan fayl yuklash, oldindan ko\'rish va yuklab olishni qo\'llab-quvvatlaydi.\n\nHujjatlarni tizim ob\'ektlari bilan bog\'lash mumkin: kontragentlar, tovarlar, xodimlar. Bu tegishli ob\'ektlar kartochkalaridan hujjatlarga tez kirishni ta\'minlaydi.\n\nQidiruv nom, tavsif va hujjat tarkibi bo\'yicha ishlaydi (matn formatlari uchun). Filtrlash fayl turi, yuklash sanasi, muallif bo\'yicha mavjud.'
  },

  {
    order: 140,
    ruDescription: 'Кнопка загрузки документа позволяет добавить новый файл в систему. Это универсальный инструмент для хранения любой документации.\n\nЗагрузка поддерживает различные форматы файлов: PDF, DOC, XLS, изображения, архивы. Система автоматически определяет тип файла и создаёт превью для изображений.\n\nПри загрузке можно указать название, описание, категорию и связать документ с объектами системы. Это упрощает последующий поиск и навигацию.',
    uzDescription: 'Hujjat yuklash tugmasi tizimga yangi fayl qo\'shish imkonini beradi. Bu har qanday hujjatlarni saqlash uchun universal vosita.\n\nYuklash turli fayl formatlarini qo\'llab-quvvatlaydi: PDF, DOC, XLS, rasmlar, arxivlar. Tizim fayl turini avtomatik aniqlaydi va rasmlar uchun oldindan ko\'rish yaratadi.\n\nYuklashda nom, tavsif, kategoriya ko\'rsatish va hujjatni tizim ob\'ektlari bilan bog\'lash mumkin. Bu keyingi qidiruv va navigatsiyani soddalashtiradi.',
    ruFunctionality: 'Открывает диалог загрузки файла с поддержкой drag-and-drop и выбора через проводник. Можно загрузить один или несколько файлов одновременно.\n\nПосле выбора файлов открывается форма редактирования метаданных: название, описание, категория, теги. Можно сразу привязать документ к контрагенту или другому объекту.\n\nСистема проверяет файл на вирусы, генерирует превью для поддерживаемых форматов и сохраняет в облачном хранилище. Прогресс загрузки отображается в реальном времени.',
    uzFunctionality: 'Drag-and-drop va provodnik orqali tanlash bilan fayl yuklash dialogini ochadi. Bir vaqtning o\'zida bir yoki bir nechta fayl yuklash mumkin.\n\nFayllar tanlangandan so\'ng metama\'lumotlarni tahrirlash formasi ochiladi: nom, tavsif, kategoriya, teglar. Hujjatni darhol kontragent yoki boshqa ob\'ektga biriktirish mumkin.\n\nTizim faylni viruslarga tekshiradi, qo\'llab-quvvatlanadigan formatlar uchun oldindan ko\'rish generatsiya qiladi va bulutli saqlashda saqlaydi. Yuklash jarayoni real vaqtda ko\'rsatiladi.'
  },

  {
    order: 141,
    ruDescription: 'Функция скачивания документа позволяет сохранить файл из системы на локальное устройство. Это необходимо для работы с документами во внешних программах.\n\nПри скачивании система передаёт оригинальный файл с сохранением имени и формата. Для документов с несколькими версиями можно выбрать конкретную версию для скачивания.\n\nВсе операции скачивания логируются для контроля доступа к конфиденциальной информации. Админы могут ограничить скачивание определённых типов документов.',
    uzDescription: 'Hujjatni yuklab olish funksiyasi faylni tizimdan mahalliy qurilmaga saqlash imkonini beradi. Bu hujjatlar bilan tashqi dasturlarda ishlash uchun zarur.\n\nYuklab olishda tizim nom va formatni saqlab original faylni uzatadi. Bir nechta versiyali hujjatlar uchun yuklab olish uchun aniq versiyani tanlash mumkin.\n\nBarcha yuklab olish operatsiyalari maxfiy ma\'lumotlarga kirishni nazorat qilish uchun log qilinadi. Adminlar ma\'lum turdagi hujjatlarni yuklab olishni cheklashi mumkin.',
    ruFunctionality: 'Инициирует загрузку выбранного документа на устройство пользователя. Файл передаётся через защищённое соединение с сохранением оригинального имени.\n\nДля документов с несколькими версиями доступен выбор конкретной версии из выпадающего меню. По умолчанию скачивается последняя актуальная версия.\n\nЕсли документ защищён паролем или имеет ограничения доступа, система запросит подтверждение прав перед скачиванием. История скачиваний сохраняется в журнале.',
    uzFunctionality: 'Tanlangan hujjatni foydalanuvchi qurilmasiga yuklashni boshlaydi. Fayl original nom saqlangan holda himoyalangan ulanish orqali uzatiladi.\n\nBir nechta versiyali hujjatlar uchun ochiladigan menudan aniq versiyani tanlash mavjud. Standart bo\'yicha oxirgi dolzarb versiya yuklab olinadi.\n\nAgar hujjat parol bilan himoyalangan bo\'lsa yoki kirish cheklovlari bo\'lsa, tizim yuklab olishdan oldin huquqlarni tasdiqlashni so\'raydi. Yuklab olishlar tarixi jurnalda saqlanadi.'
  },

  // === СПРАВОЧНИК: АУДИТ МАРКИРОВОК ===
  {
    order: 142,
    ruDescription: 'Раздел "Аудит маркировок" предназначен для проверки кодов маркировки товаров, подлежащих обязательной маркировке. Это необходимо для соответствия требованиям законодательства.\n\nВ разделе можно проверить код Data Matrix или QR-код на принадлежность к реестру маркированных товаров. Система показывает информацию о товаре, производителе и статусе кода.\n\nПроверка маркировки помогает избежать оборота контрафактной продукции и защищает бизнес от штрафов. Результаты проверок сохраняются для подтверждения добросовестности.',
    uzDescription: '"Markirovka auditi" bo\'limi majburiy markirovkaga tortiladigan tovarlar markirovka kodlarini tekshirish uchun mo\'ljallangan. Bu qonunchilik talablariga moslik uchun zarur.\n\nBo\'limda Data Matrix yoki QR-kodni markirovka qilingan tovarlar reestriga tegishliligini tekshirish mumkin. Tizim tovar, ishlab chiqaruvchi va kod holati haqida ma\'lumot ko\'rsatadi.\n\nMarkirovkani tekshirish qalbaki mahsulotlar aylanmasidan qochishga va biznesni jarimalardan himoya qilishga yordam beradi. Tekshirish natijalari xolislikni tasdiqlash uchun saqlanadi.',
    ruFunctionality: 'Открывает инструмент проверки кодов маркировки с подключением к государственной системе. Интерфейс включает поле для ввода кода вручную или сканирования.\n\nПосле ввода кода система отправляет запрос в реестр и показывает результат: валидный код, дату выпуска, производителя, текущий статус в обороте. Для невалидных кодов показывается причина.\n\nИстория проверок сохраняется с указанием даты, времени, кода и результата. Можно сформировать отчёт о проведённых проверках для контролирующих органов.',
    uzFunctionality: 'Davlat tizimiga ulanish bilan markirovka kodlarini tekshirish vositasini ochadi. Interfeys qo\'lda kiritish yoki skanerlash uchun maydonni o\'z ichiga oladi.\n\nKod kiritilgandan so\'ng tizim reestrga so\'rov yuboradi va natijani ko\'rsatadi: haqiqiy kod, chiqarilgan sanasi, ishlab chiqaruvchi, aylanmadagi joriy holati. Noto\'g\'ri kodlar uchun sabab ko\'rsatiladi.\n\nTekshirishlar tarixi sana, vaqt, kod va natija ko\'rsatilgan holda saqlanadi. Nazorat qiluvchi organlar uchun o\'tkazilgan tekshirishlar hisobotini shakllantirish mumkin.'
  },

  {
    order: 143,
    ruDescription: 'Функция сканирования маркировки позволяет быстро проверить код с упаковки товара. Это ускоряет процесс приёмки и инвентаризации маркированных товаров.\n\nДля сканирования используется камера мобильного устройства или подключённый сканер штрих-кодов. Система автоматически распознаёт Data Matrix коды и направляет на проверку.\n\nРезультат сканирования отображается мгновенно с визуальной индикацией: зелёный для валидных кодов, красный для проблемных. Можно настроить звуковые оповещения.',
    uzDescription: 'Markirovkani skanerlash funksiyasi tovar qadoqidagi kodni tez tekshirish imkonini beradi. Bu markirovka qilingan tovarlarni qabul qilish va inventarizatsiyani tezlashtiradi.\n\nSkanerlash uchun mobil qurilma kamerasi yoki ulangan shtrix-kod skaneri ishlatiladi. Tizim Data Matrix kodlarni avtomatik taniydi va tekshirishga yo\'naltiradi.\n\nSkanerlash natijasi vizual indikatsiya bilan bir zumda ko\'rsatiladi: haqiqiy kodlar uchun yashil, muammoli uchun qizil. Ovozli ogohlantirishlarni sozlash mumkin.',
    ruFunctionality: 'Активирует режим сканирования с использованием камеры устройства или внешнего сканера. Камера автоматически фокусируется на коде и распознаёт Data Matrix.\n\nПосле успешного распознавания код автоматически отправляется на проверку в систему маркировки. Результат отображается на экране с возможностью перехода к деталям.\n\nПри обнаружении невалидного или проблемного кода система показывает предупреждение с рекомендациями по действиям. Можно добавить комментарий к результату сканирования.',
    uzFunctionality: 'Qurilma kamerasi yoki tashqi skanerdan foydalanib skanerlash rejimini faollashtiradi. Kamera avtomatik kodga fokuslanadi va Data Matrix ni taniydi.\n\nMuvaffaqiyatli tan olingandan so\'ng kod avtomatik markirovka tizimiga tekshirish uchun yuboriladi. Natija ekranda tafsilotlarga o\'tish imkoniyati bilan ko\'rsatiladi.\n\nNoto\'g\'ri yoki muammoli kod aniqlanganda tizim harakatlar bo\'yicha tavsiyalar bilan ogohlantirish ko\'rsatadi. Skanerlash natijasiga izoh qo\'shish mumkin.'
  },

  // === СПРАВОЧНИК: ЭДО ===
  {
    order: 144,
    ruDescription: 'Раздел "ЭДО" предназначен для работы с электронным документооборотом между контрагентами. Это современный способ обмена юридически значимыми документами.\n\nВ разделе отображаются входящие и исходящие документы, требующие подписания или обработки. Система поддерживает основные типы документов: накладные, акты, счета-фактуры.\n\nИспользование ЭДО ускоряет документооборот, снижает затраты на бумагу и хранение, исключает потерю документов. Все документы имеют юридическую силу благодаря электронной подписи.',
    uzDescription: '"EDO" bo\'limi kontragentlar o\'rtasida elektron hujjat aylanmasi bilan ishlash uchun mo\'ljallangan. Bu huquqiy ahamiyatga ega hujjatlarni almashinuvning zamonaviy usuli.\n\nBo\'limda imzolash yoki qayta ishlash talab qilinadigan kiruvchi va chiquvchi hujjatlar ko\'rsatiladi. Tizim asosiy hujjat turlarini qo\'llab-quvvatlaydi: nakladnoylar, aktlar, hisob-fakturalar.\n\nEDO dan foydalanish hujjat aylanmasini tezlashtiradi, qog\'oz va saqlash xarajatlarini kamaytiradi, hujjatlarni yo\'qotishni istisno qiladi. Barcha hujjatlar elektron imzo tufayli huquqiy kuchga ega.',
    ruFunctionality: 'Открывает рабочий стол электронного документооборота с папками: входящие, исходящие, черновики, архив. Каждая папка показывает количество документов с разбивкой по статусам.\n\nДокументы в списке содержат наименование, контрагента, сумму, дату и статус подписания. Фильтрация доступна по периоду, контрагенту, типу документа.\n\nИз карточки документа можно просмотреть содержимое, подписать, отправить или отклонить. Система хранит историю всех действий с документом.',
    uzFunctionality: 'Kiruvchi, chiquvchi, qoralama, arxiv papkalari bilan elektron hujjat aylanmasi ish stolini ochadi. Har bir papka hujjatlar sonini holatlar bo\'yicha taqsimlash bilan ko\'rsatadi.\n\nRo\'yxatdagi hujjatlar nom, kontragent, summa, sana va imzolash holatini o\'z ichiga oladi. Davr, kontragent, hujjat turi bo\'yicha filtrlash mavjud.\n\nHujjat kartochkasidan tarkibni ko\'rish, imzolash, yuborish yoki rad etish mumkin. Tizim hujjat bilan barcha harakatlar tarixini saqlaydi.'
  },

  {
    order: 145,
    ruDescription: 'Функция подписания документа позволяет заверить электронный документ электронной цифровой подписью. Это придаёт документу юридическую силу.\n\nДля подписания используется ЭЦП, зарегистрированная в системе. Можно использовать как локальный сертификат, так и облачную подпись через авторизованный сервис.\n\nПосле подписания документ становится неизменяемым и может быть отправлен контрагенту. Система фиксирует дату и время подписания, а также сертификат, использованный для подписи.',
    uzDescription: 'Hujjatni imzolash funksiyasi elektron hujjatni elektron raqamli imzo bilan tasdiqlash imkonini beradi. Bu hujjatga huquqiy kuch beradi.\n\nImzolash uchun tizimda ro\'yxatdan o\'tgan ERQ ishlatiladi. Mahalliy sertifikat ham, avtorizatsiyalangan xizmat orqali bulutli imzo ham ishlatish mumkin.\n\nImzolangandan so\'ng hujjat o\'zgartirib bo\'lmaydigan bo\'ladi va kontragentga yuborilishi mumkin. Tizim imzolash sanasi va vaqtini, shuningdek imzo uchun ishlatilgan sertifikatni qayd etadi.',
    ruFunctionality: 'Открывает диалог подписания документа с выбором сертификата ЭЦП. Система показывает информацию о документе для проверки перед подписанием.\n\nПри выборе локального сертификата система запрашивает PIN-код токена. Для облачной подписи открывается окно авторизации в сервисе провайдера.\n\nПосле успешного подписания документ помечается статусом "Подписан" и становится доступен для отправки. Визуальная метка подписи добавляется в документ.',
    uzFunctionality: 'ERQ sertifikatini tanlash bilan hujjatni imzolash dialogini ochadi. Tizim imzolashdan oldin tekshirish uchun hujjat haqida ma\'lumot ko\'rsatadi.\n\nMahalliy sertifikat tanlanganda tizim token PIN-kodini so\'raydi. Bulutli imzo uchun provayder xizmatida avtorizatsiya oynasi ochiladi.\n\nMuvaffaqiyatli imzolangandan so\'ng hujjat "Imzolangan" holati bilan belgilanadi va yuborish uchun mavjud bo\'ladi. Imzoning vizual belgisi hujjatga qo\'shiladi.'
  },

  // === СПРАВОЧНИК: АКЦИИ ===
  {
    order: 146,
    ruDescription: 'Раздел "Акции" предназначен для создания и управления маркетинговыми акциями и специальными предложениями. Это инструмент для привлечения и удержания клиентов.\n\nВ разделе отображается список акций с информацией о названии, периоде действия, типе скидки и статусе. Акции можно фильтровать по статусу: активные, запланированные, завершённые.\n\nСистема поддерживает различные типы акций: скидка на товар, подарок при покупке, комплект со скидкой, накопительная акция. Каждая акция имеет гибкие настройки условий.',
    uzDescription: '"Aksiyalar" bo\'limi marketing aksiyalari va maxsus takliflarni yaratish va boshqarish uchun mo\'ljallangan. Bu mijozlarni jalb qilish va ushlab qolish vositasidir.\n\nBo\'limda nom, amal qilish davri, chegirma turi va holat haqida ma\'lumot bilan aksiyalar ro\'yxati ko\'rsatiladi. Aksiyalarni holat bo\'yicha filtrlash mumkin: faol, rejalashtirilgan, tugallangan.\n\nTizim turli aksiya turlarini qo\'llab-quvvatlaydi: tovarga chegirma, xarid bilan sovg\'a, chegirmali komplekt, to\'plash aksiyasi. Har bir aksiya shartlarning moslashuvchan sozlamalariga ega.',
    ruFunctionality: 'Открывает центр управления акциями с обзором ключевых показателей: активные акции, охват товаров, эффективность. Интерфейс включает календарь акций для планирования.\n\nКаждая акция содержит условия применения: период действия, список товаров, размер скидки, ограничения по сумме или количеству. Можно настроить расписание по дням недели и времени.\n\nСистема автоматически применяет акции при продаже符合条件的 товаров. Отчёты показывают влияние акций на продажи и прибыль.',
    uzFunctionality: 'Asosiy ko\'rsatkichlar ko\'rinishi bilan aksiyalarni boshqarish markazini ochadi: faol aksiyalar, tovarlar qamrovi, samaradorlik. Interfeys rejalashtirish uchun aksiyalar taqvimini o\'z ichiga oladi.\n\nHar bir aksiya qo\'llash shartlarini o\'z ichiga oladi: amal qilish davri, tovarlar ro\'yxati, chegirma hajmi, summa yoki miqdor bo\'yicha cheklovlar. Hafta kunlari va vaqt bo\'yicha jadvalni sozlash mumkin.\n\nTizim mos keluvchi tovarlar sotilganda aksiyalarni avtomatik qo\'llaydi. Hisobotlar aksiyalarning sotuvlar va foydaga ta\'sirini ko\'rsatadi.'
  },

  {
    order: 147,
    ruDescription: 'Кнопка создания акции открывает форму для настройки нового специального предложения. Это первый шаг к запуску маркетинговой кампании.\n\nВ форме указывается название и описание акции, период действия, тип скидки или бонуса. Затем добавляются товары, участвующие в акции, и настраиваются условия.\n\nМожно создать сложные комбинированные акции: "купи N товаров и получи скидку X%" или "при покупке категории A — подарок из категории B". Система проверяет корректность настроек.',
    uzDescription: 'Aksiya yaratish tugmasi yangi maxsus taklifni sozlash uchun formani ochadi. Bu marketing kampaniyasini ishga tushirishga birinchi qadam.\n\nFormada aksiya nomi va tavsifi, amal qilish davri, chegirma yoki bonus turi ko\'rsatiladi. Keyin aksiyada ishtirok etuvchi tovarlar qo\'shiladi va shartlar sozlanadi.\n\nMurakkab birikma aksiyalarni yaratish mumkin: "N ta tovar sotib oling va X% chegirma oling" yoki "A kategoriyasini sotib oling — B kategoriyasidan sovg\'a". Tizim sozlamalarning to\'g\'riligini tekshiradi.',
    ruFunctionality: 'Открывает многошаговый мастер создания акции с пошаговой настройкой. Первый шаг — базовая информация: название, описание, период действия.\n\nВторой шаг — выбор типа акции и настройка механики: процент скидки, фиксированная сумма, подарок. Можно настроить пороги срабатывания по сумме или количеству.\n\nТретий шаг — выбор товаров и настройка ограничений. Предпросмотр показывает, как акция будет выглядеть для покупателя. После сохранения акция готова к активации.',
    uzFunctionality: 'Bosqichma-bosqich sozlash bilan aksiya yaratishning ko\'p bosqichli ustasini ochadi. Birinchi qadam — asosiy ma\'lumotlar: nom, tavsif, amal qilish davri.\n\nIkkinchi qadam — aksiya turini tanlash va mexanikani sozlash: chegirma foizi, belgilangan summa, sovg\'a. Summa yoki miqdor bo\'yicha ishga tushirish chegaralarini sozlash mumkin.\n\nUchinchi qadam — tovarlarni tanlash va cheklovlarni sozlash. Oldindan ko\'rish aksiyaning xaridor uchun qanday ko\'rinishini ko\'rsatadi. Saqlangandan so\'ng aksiya faollashtirishga tayyor.'
  },

  {
    order: 148,
    ruDescription: 'Переключатель активации акции включает или отключает действие специального предложения. Только активные акции применяются при продаже товаров.\n\nПри активации система проверяет корректность настроек акции и наличие необходимых данных. Если есть ошибки, выводится предупреждение с описанием проблемы.\n\nАкцию можно временно деактивировать без удаления. Это удобно для сезонных предложений или при необходимости приостановить акцию. Все настройки сохраняются для повторной активации.',
    uzDescription: 'Aksiya faollashtirish kaliti maxsus taklifning amal qilishini yoqadi yoki o\'chiradi. Faqat faol aksiyalar tovarlar sotilganda qo\'llaniladi.\n\nFaollashtirilganda tizim aksiya sozlamalarining to\'g\'riligini va kerakli ma\'lumotlarning mavjudligini tekshiradi. Xatolar bo\'lsa, muammo tavsifi bilan ogohlantirish chiqariladi.\n\nAksiyani o\'chirmasdan vaqtincha faolsizlantirish mumkin. Bu mavsumiy takliflar yoki aksiyani vaqtincha to\'xtatish zarurati uchun qulay. Barcha sozlamalar qayta faollashtirish uchun saqlanadi.',
    ruFunctionality: 'Переключает статус акции между "Активна" и "Неактивна". При активации система выполняет валидацию настроек и показывает результат.\n\nЕсли акция активна, она автоматически применяется при оформлении чека с подходящими товарами. Система показывает информацию о применённой акции в чеке.\n\nДеактивация приостанавливает действие акции, но сохраняет все настройки. Можно указать причину деактивации для внутреннего учёта. История изменений статуса сохраняется.',
    uzFunctionality: 'Aksiya holatini "Faol" va "Nofaol" o\'rtasida almashtiradi. Faollashtirilganda tizim sozlamalarni tasdiqlaydi va natijani ko\'rsatadi.\n\nAgar aksiya faol bo\'lsa, u mos keluvchi tovarlar bilan chekni rasmiylashtirishda avtomatik qo\'llaniladi. Tizim chekda qo\'llangan aksiya haqida ma\'lumotni ko\'rsatadi.\n\nFaolsizlantirish aksiyaning amal qilishini to\'xtatadi, lekin barcha sozlamalarni saqlaydi. Ichki hisob uchun faolsizlantirish sababini ko\'rsatish mumkin. Holat o\'zgarishlar tarixi saqlanadi.'
  },

  // === ФИНАНСЫ: ЧЕКИ ===
  {
    order: 149,
    ruDescription: 'Раздел "Проданные чеки" содержит историю всех завершённых продаж за наличный и безналичный расчёт. Это основной источник данных о выручке организации.\n\nВ разделе отображается список чеков с информацией о дате, времени, сумме, способе оплаты и кассире. Чеки можно фильтровать по периоду, точке продаж, кассиру.\n\nКаждый чек содержит детализацию: список товаров, количество, цены, применённые скидки и бонусы. Эта информация используется для анализа продаж и работы с возвратами.',
    uzDescription: '"Sotilgan cheklar" bo\'limi naqd va naqdsiz hisob-kitob bo\'yicha barcha tugallangan sotuvlar tarixini o\'z ichiga oladi. Bu tashkilot tushumining asosiy manbai.\n\nBo\'limda sana, vaqt, summa, to\'lov usuli va kassir haqida ma\'lumot bilan cheklar ro\'yxati ko\'rsatiladi. Cheklarni davr, savdo nuqtasi, kassir bo\'yicha filtrlash mumkin.\n\nHar bir chek batafsil ma\'lumotni o\'z ichiga oladi: tovarlar ro\'yxati, miqdor, narxlar, qo\'llangan chegirmalar va bonuslar. Bu ma\'lumotlar sotuvlarni tahlil qilish va qaytarishlar bilan ishlash uchun ishlatiladi.',
    ruFunctionality: 'Открывает реестр проданных чеков с возможностью просмотра, поиска и фильтрации. Интерфейс включает сводную информацию: количество чеков, сумма выручки, средний чек за период.\n\nПоиск работает по номеру чека, наименованию товара и другим параметрам. Фильтрация позволяет отобрать чеки по различным критериям для анализа.\n\nИз списка можно открыть карточку чека для просмотра деталей, распечатать копию или оформить возврат. Массовые действия позволяют выгрузить данные в Excel.',
    uzFunctionality: 'Ko\'rish, qidirish va filtrlash imkoniyati bilan sotilgan cheklar reestrini ochadi. Interfeys umumiy ma\'lumotni o\'z ichiga oladi: cheklar soni, tushum summasi, davr uchun o\'rtacha chek.\n\nQidiruv chek raqami, tovar nomi va boshqa parametrlar bo\'yicha ishlaydi. Filtrlash tahlil uchun turli mezonlar bo\'yicha cheklarni tanlash imkonini beradi.\n\nRo\'yxatdan chek kartochkasini tafsilotlarni ko\'rish uchun ochish, nusxasini chop etish yoki qaytarishni rasmiylashtirish mumkin. Ommaviy harakatlar ma\'lumotlarni Excelga yuklash imkonini beradi.'
  },

  {
    order: 150,
    ruDescription: 'Просмотр чека открывает детальную информацию о конкретной транзакции продажи. Это необходимо для работы с клиентами, анализа и разрешения спорных ситуаций.\n\nВ карточке чека отображаются: номер и дата, список товаров с ценами и количеством, применённые скидки и бонусы, итоговая сумма и способ оплаты.\n\nТакже доступна информация о кассире, точке продаж и кассе, на которой был пробит чек. История изменений чека сохраняется для контроля.',
    uzDescription: 'Chekni ko\'rish aniq sotuv transaksiyasi haqida batafsil ma\'lumotni ochadi. Bu mijozlar bilan ishlash, tahlil va bahsli holatlarni hal qilish uchun zarur.\n\nChek kartochkasida ko\'rsatiladi: raqam va sana, narx va miqdor bilan tovarlar ro\'yxati, qo\'llangan chegirmalar va bonuslar, yakuniy summa va to\'lov usuli.\n\nShuningdek kassir, savdo nuqtasi va chek urilgan kassa haqida ma\'lumot mavjud. Chek o\'zgarishlar tarixi nazorat uchun saqlanadi.',
    ruFunctionality: 'Открывает карточку чека с полной информацией о транзакции. Основная секция содержит список товаров, цены, количество и итоги по каждой позиции.\n\nДополнительные вкладки показывают: применённые скидки и акции, использованные бонусы, информацию о клиенте и его программе лояльности, историю оплат.\n\nИз карточки доступны действия: печать копии чека, отправка на email клиента, оформление возврата, создание расходной накладной. Все действия логируются.',
    uzFunctionality: 'Transaksiya haqida to\'liq ma\'lumot bilan chek kartochkasini ochadi. Asosiy bo\'lim tovarlar ro\'yxati, narxlar, miqdor va har bir pozitsiya bo\'yicha yakuniylarni o\'z ichiga oladi.\n\nQo\'shimcha yorliqlar quyidagilarni ko\'rsatadi: qo\'llangan chegirmalar va aksiyalar, ishlatilgan bonuslar, mijoz va uning sodiqlik dasturi haqida ma\'lumot, to\'lovlar tarixi.\n\nKartochkadan harakatlar mavjud: chek nusxasini chop etish, mijoz emailiga yuborish, qaytarishni rasmiylashtirish, chiqim nakladnoysi yaratish. Barcha harakatlar log qilinadi.'
  },

  {
    order: 151,
    ruDescription: 'Функция печати копии чека позволяет распечатать дубликат фискального документа. Это необходимо при утере оригинала или по запросу клиента.\n\nКопия чека содержит все данные оригинала: список товаров, суммы, фискальные признаки. Отличие только в пометке "Копия" или "Дубликат".\n\nПечать доступна для любой организации-продавца и любой кассы, где есть подключённый принтер. Можно отправить копию чека на email клиента.',
    uzDescription: 'Chek nusxasini chop etish funksiyasi fiskal hujjat dublikatini chop etish imkonini beradi. Bu original yo\'qolganda yoki mijoz so\'raganda zarur.\n\nChek nusxasi originalning barcha ma\'lumotlarini o\'z ichiga oladi: tovarlar ro\'yxati, summalar, fiskal belgilari. Farqi faqat "Nusxa" yoki "Dublikat" yozuvida.\n\nChop etish har qanday sotuvchi tashkilot va ulangan printerli har qanday kassa uchun mavjud. Chek nusxasini mijoz emailiga yuborish mumkin.',
    ruFunctionality: 'Инициирует печать дубликата чека на подключённом фискальном принтере. Система формирует документ с полной информацией оригинальной продажи.\n\nПри печати копии система помечает её специальным признаком, чтобы отличить от оригинала. Фискальные данные сохраняются для соответствия требованиям законодательства.\n\nДополнительно можно отправить электронную копию чека на email или в SMS. Это удобно для клиентов, которые хотят сохранить историю покупок.',
    uzFunctionality: 'Ulangan fiskal printerda chek dublikatini chop etishni boshlaydi. Tizim original sotuvning to\'liq ma\'lumoti bilan hujjatni shakllantiradi.\n\nNusxa chop etilganda tizim uni originaldan farqlash uchun maxsus belgi bilan belgilaydi. Fiskal ma\'lumotlar qonunchilik talablariga moslik uchun saqlanadi.\n\nQo\'shimcha ravishda elektron chek nusxasini email yoki SMS ga yuborish mumkin. Bu xaridlar tarixini saqlamoqchi bo\'lgan mijozlar uchun qulay.'
  },

  {
    order: 152,
    ruDescription: 'Раздел "Возвраты чеков" содержит историю всех операций возврата товаров покупателями. Это важный инструмент анализа качества и сервиса.\n\nВ разделе отображается список возвратов с информацией об оригинальном чеке, возвращённых товарах, сумме возврата и причине. Возвраты можно фильтровать по периоду и причине.\n\nАнализ возвратов помогает выявлять проблемные товары, недостатки в работе персонала и улучшать качество обслуживания. Система формирует отчёты по возвратам.',
    uzDescription: '"Cheklar qaytarish" bo\'limi xaridorlar tomonidan tovarlarni qaytarishning barcha operatsiyalari tarixini o\'z ichiga oladi. Bu sifat va xizmat ko\'rsatishni tahlil qilishning muhim vositasidir.\n\nBo\'limda original chek, qaytarilgan tovarlar, qaytarish summasi va sabab haqida ma\'lumot bilan qaytarishlar ro\'yxati ko\'rsatiladi. Qaytarishlarni davr va sabab bo\'yicha filtrlash mumkin.\n\nQaytarishlarni tahlil qilish muammoli tovarlarni, xodimlar ishidagi kamchiliklarni aniqlash va xizmat ko\'rsatish sifatini yaxshilashga yordam beradi. Tizim qaytarishlar bo\'yicha hisobotlarni shakllantiradi.',
    ruFunctionality: 'Открывает реестр документов возврата с возможностью просмотра деталей каждого возврата. Интерфейс включает статистику: сумма возвратов, процент от продаж, основные причины.\n\nКаждый документ возврата связан с оригинальным чеком продажи. При клике доступен переход к исходному чеку для анализа.\n\nИз раздела можно создать новый документ возврата, найти конкретный возврат по номеру или товарам. Данные доступны для экспорта в Excel для анализа.',
    uzFunctionality: 'Har bir qaytarish tafsilotlarini ko\'rish imkoniyati bilan qaytarish hujjatlari reestrini ochadi. Interfeys statistikani o\'z ichiga oladi: qaytarishlar summasi, sotuvlardan foizi, asosiy sabablar.\n\nHar bir qaytarish hujjati original sotuv cheki bilan bog\'langan. Bosilganda tahlil uchun asl chekka o\'tish mavjud.\n\nBo\'limdan yangi qaytarish hujjatini yaratish, aniq qaytarishni raqam yoki tovarlar bo\'yicha topish mumkin. Ma\'lumotlar tahlil uchun Excelga eksport qilish uchun mavjud.'
  },

  {
    order: 153,
    ruDescription: 'Функция оформления возврата создаёт документ на возврат товаров покупателю. Это юридически значимая операция, требующая соблюдения правил.\n\nДля оформления возврата нужно найти оригинальный чек, выбрать возвращаемые товары и указать причину возврата. Система проверяет возможность возврата по срокам и состоянию.\n\nПосле оформления возврата формируется кассовый чек возврата и возвращаются деньги покупателю. Товары возвращаются на склад и становятся доступны для продажи.',
    uzDescription: 'Qaytarishni rasmiylashtirish funksiyasi mijozga tovarlarni qaytarish bo\'yicha hujjat yaratadi. Bu qoidalarga rioya qilishni talab qiluvchi huquqiy ahamiyatga ega operatsiya.\n\nQaytarishni rasmiylashtirish uchun original chekni topish, qaytariladigan tovarlarni tanlash va qaytarish sababini ko\'rsatish kerak. Tizim muddatlar va holat bo\'yicha qaytarish imkoniyatini tekshiradi.\n\nQaytarish rasmiylashtirilgandan so\'ng kassa qaytarish cheki shakllantiriladi va mijozga pul qaytariladi. Tovarlar omborga qaytariladi va sotish uchun mavjud bo\'ladi.',
    ruFunctionality: 'Открывает форму оформления возврата с поиском оригинального чека. Поиск работает по номеру чека, дате, телефону клиента или наименованию товара.\n\nПосле нахождения чека система показывает список товаров, доступных для возврата. Нужно отметить возвращаемые позиции и указать причину из справочника причин.\n\nПри подтверждении система формирует чек возврата, возвращает деньги выбранным способом и оприходует товары на склад. Все данные сохраняются для отчётности.',
    uzFunctionality: 'Original chekni qidirish bilan qaytarishni rasmiylashtirish formasini ochadi. Qidiruv chek raqami, sana, mijoz telefoni yoki tovar nomi bo\'yicha ishlaydi.\n\nChek topilgandan so\'ng tizim qaytarish uchun mavjud tovarlar ro\'yxatini ko\'rsatadi. Qaytariladigan pozitsiyalarni belgilash va sabablar ma\'lumotnomasidan sababni ko\'rsatish kerak.\n\nTasdiqlanganda tizim qaytarish chekini shakllantiradi, tanlangan usul bilan pulni qaytaradi va tovarlarni omborga qabul qiladi. Barcha ma\'lumotlar hisobot uchun saqlanadi.'
  },

  {
    order: 154,
    ruDescription: 'Раздел "Удалённые чеки" показывает чеки, из которых были удалены позиции до финального оформления. Это инструмент контроля работы персонала.\n\nВ разделе отображается информация о том, какие товары были удалены из чека, кем и по какой причине. Это помогает выявлять ошибки и злоупотребления персонала.\n\nАнализ удалённых позиций может показать проблемы в работе кассиров: частые удаления, удаление дорогих товаров, неоправданные удаления. Система формирует отчёты для контроля.',
    uzDescription: '"O\'chirilgan cheklar" bo\'limi yakuniy rasmiylashtirishdan oldin pozitsiyalari o\'chirilgan cheklarni ko\'rsatadi. Bu xodimlar ishini nazorat qilish vositasidir.\n\nBo\'limda chekdan qanday tovarlar o\'chirilganligi, kim tomonidan va qanday sababga ko\'ra haqida ma\'lumot ko\'rsatiladi. Bu xatoliklar va xodimlarning suiiste\'mollarini aniqlashga yordam beradi.\n\nO\'chirilgan pozitsiyalarni tahlil qilish kassirlar ishidagi muammolarni ko\'rsatishi mumkin: tez-tez o\'chirish, qimmat tovarlarni o\'chirish, asossiz o\'chirish. Tizim nazorat uchun hisobotlarni shakllantiradi.',
    ruFunctionality: 'Открывает журнал удалённых позиций с детализацией по каждому случаю. Каждая запись содержит информацию о чеке, удалённом товаре, кассире и причине.\n\nПри удалении товара из чека система требует указания причины: отказ клиента, ошибка кассира, нет в наличии. Это обеспечивает прозрачность и контроль.\n\nОтчёты показывают статистику удалений по кассирам, товарам, причинам. Можно настроить уведомления о превышении порога удалений для оперативного реагирования.',
    uzFunctionality: 'Har bir holat bo\'yicha batafsil ma\'lumot bilan o\'chirilgan pozitsiyalar jurnalini ochadi. Har bir yozuv chek, o\'chirilgan tovar, kassir va sabab haqida ma\'lumotni o\'z ichiga oladi.\n\nChekdan tovar o\'chirilganda tizim sababni ko\'rsatishni talab qiladi: mijoz rad etdi, kassir xatosi, mavjud emas. Bu shaffoflik va nazoratni ta\'minlaydi.\n\nHisobotlar kassirlar, tovarlar, sabablar bo\'yicha o\'chirish statistikasini ko\'rsatadi. Tezkor javob berish uchun o\'chirish chegarasi oshganda bildirishnomalarni sozlash mumkin.'
  },

  {
    order: 155,
    ruDescription: 'Раздел "Отложенные чеки" содержит чеки, которые были сохранены для продолжения оформления позже. Это удобно при обслуживании нескольких клиентов одновременно.\n\nОтложенный чек сохраняет список выбранных товаров и позволяет вернуться к нему в любое время. Система хранит отложенные чеки до 24 часов или дольше по настройкам.\n\nЭта функция особенно полезна в пиковые часы, когда клиент забыл карту или нужно уточнить информацию. Кассир может обслужить других клиентов и вернуться к отложенному чеку.',
    uzDescription: '"Kechiktirilgan cheklar" bo\'limi keyinroq davom ettirish uchun saqlangan cheklarni o\'z ichiga oladi. Bu bir vaqtning o\'zida bir nechta mijozlarga xizmat ko\'rsatishda qulay.\n\nKechiktirilgan chek tanlangan tovarlar ro\'yxatini saqlaydi va istalgan vaqtda unga qaytish imkonini beradi. Tizim kechiktirilgan cheklarni 24 soatgacha yoki sozlamalarga ko\'ra uzoqroq saqlaydi.\n\nBu funksiya ayniqsa cho\'qqi soatlarida, mijoz kartani unutganda yoki ma\'lumotni aniqlashtirish kerak bo\'lganda foydalidir. Kassir boshqa mijozlarga xizmat ko\'rsatib, kechiktirilgan chekka qaytishi mumkin.',
    ruFunctionality: 'Открывает список отложенных чеков с информацией о времени создания, сумме и кассире. Каждый чек показывает, сколько времени прошло с момента отложения.\n\nИз списка можно продолжить оформление чека, удалить его или передать другому кассиру. При продолжении открывается чек с сохранёнными товарами.\n\nСистема автоматически уведомляет о приближении истечения срока хранения отложенного чека. Можно настроить автоматическое удаление по истечении срока.',
    uzFunctionality: 'Yaratilgan vaqti, summasi va kassir haqida ma\'lumot bilan kechiktirilgan cheklar ro\'yxatini ochadi. Har bir chek kechiktirilgan vaqtdan qancha vaqt o\'tganini ko\'rsatadi.\n\nRo\'yxatdan chekni davom ettirish, uni o\'chirish yoki boshqa kassirga uzatish mumkin. Davom ettirilganda saqlangan tovarlar bilan chek ochiladi.\n\nTizim kechiktirilgan chek saqlash muddati tugashiga yaqinlashganda avtomatik ogohlantiradi. Muddati tugaganda avtomatik o\'chirishni sozlash mumkin.'
  },

  {
    order: 156,
    ruDescription: 'Функция продолжения чека открывает отложенный чек для завершения оформления. Это позволяет вернуться к обслуживанию клиента после перерыва.\n\nПри продолжении чека все ранее добавленные товары сохраняются в списке. Кассир может добавить новые позиции, удалить или изменить количество.\n\nПосле завершения оформления чек пробивается и становится проданным. Отложенный чек удаляется из списка отложенных и появляется в истории продаж.',
    uzDescription: 'Chekni davom ettirish funksiyasi rasmiylashtirishni tugatish uchun kechiktirilgan chekni ochadi. Bu tanaffusdan keyin mijozga xizmat ko\'rsatishga qaytish imkonini beradi.\n\nChek davom ettirilganda avval qo\'shilgan barcha tovarlar ro\'yxatda saqlanadi. Kassir yangi pozitsiyalar qo\'shishi, o\'chirishi yoki miqdorni o\'zgartirishi mumkin.\n\nRasmiylashtirish tugagandan so\'ng chek uriladi va sotilgan bo\'ladi. Kechiktirilgan chek kechiktirilganlar ro\'yxatidan o\'chirilib, sotuvlar tarixida paydo bo\'ladi.',
    ruFunctionality: 'Загружает отложенный чек в интерфейс кассира со всеми сохранёнными товарами. Кассир видит список товаров, итоговую сумму и может продолжить оформление.\n\nДоступны все стандартные операции: добавление товаров, применение скидок, выбор способа оплаты. Изменения автоматически сохраняются.\n\nПосле успешной оплаты отложенный чек преобразуется в проданный и удаляется из списка отложенных. История показывает, что чек был отложен и продолжен позже.',
    uzFunctionality: 'Barcha saqlangan tovarlar bilan kechiktirilgan chekni kassir interfeysiga yuklaydi. Kassir tovarlar ro\'yxatini, yakuniy summani ko\'radi va rasmiylashtirishni davom ettirishi mumkin.\n\nBarcha standart operatsiyalar mavjud: tovarlar qo\'shish, chegirmalarni qo\'llash, to\'lov usulini tanlash. O\'zgarishlar avtomatik saqlanadi.\n\nMuvaffaqiyatli to\'lovdan so\'ng kechiktirilgan chek sotilganga aylanadi va kechiktirilganlar ro\'yxatidan o\'chiriladi. Tarix chek kechiktirilgan va keyinroq davom ettirilganligini ko\'rsatadi.'
  },

  {
    order: 157,
    ruDescription: 'Раздел "Взаиморасчёт" предназначен для контроля финансовых отношений с контрагентами. Это инструмент управления дебиторской и кредиторской задолженностью.\n\nВ разделе отображается сводная информация о долгах: кому должна организация и кто должен организации. Данные группируются по контрагентам с развёрткой по документам.\n\nНа основе данных можно планировать платежи, выявлять просроченную задолженность и принимать меры по её взысканию. Система формирует акты сверки.',
    uzDescription: '"O\'zaro hisob-kitob" bo\'limi kontragentlar bilan moliyaviy munosabatlarni nazorat qilish uchun mo\'ljallangan. Bu debitorlik va kreditorlik qarzini boshqarish vositasidir.\n\nBo\'limda qarzlar haqida umumiy ma\'lumot ko\'rsatiladi: kimga tashkilot qarz va kim tashkilotga qarz. Ma\'lumotlar hujjatlar bo\'yicha ochilish bilan kontragentlar bo\'yicha guruhlanadi.\n\nMa\'lumotlar asosida to\'lovlarni rejalashtirish, kechiktirilgan qarzni aniqlash va undirish choralarini ko\'rish mumkin. Tizim dalolatnomalarni shakllantiradi.',
    ruFunctionality: 'Открывает ведомость взаиморасчётов с контрагентами. Интерфейс показывает начальное сальдо, обороты за период и конечное сальдо по каждому контрагенту.\n\nДетализация показывает все документы, сформировавшие задолженность: накладные, акты, платёжные поручения. При клике открывается исходный документ.\n\nДоступны фильтры по периоду, контрагенту, типу задолженности. Можно сформировать акт сверки, отправить уведомление о долге или создать документ корректировки.',
    uzFunctionality: 'Kontragentlar bilan o\'zaro hisob-kitob varaqasini ochadi. Interfeys har bir kontragent bo\'yicha boshlang\'ich saldo, davrdagi aylanmalar va yakuniy saldoni ko\'rsatadi.\n\nBatafsil ma\'lumot qarzni hosil qilgan barcha hujjatlarni ko\'rsatadi: nakladnoylar, aktlar, to\'lov topshiriqlari. Bosilganda asl hujjat ochiladi.\n\nDavr, kontragent, qarz turi bo\'yicha filtrlar mavjud. Dalolatnomani shakllantirish, qarz haqida bildirishnoma yuborish yoki tuzatish hujjatini yaratish mumkin.'
  },

  {
    order: 158,
    ruDescription: 'Раздел "Счета" содержит список счетов на оплату, выставленных контрагентам. Это инструмент для работы с предоплатой и расчётами.\n\nВ разделе отображаются счета с информацией о контрагенте, сумме, статусе оплаты и сроке действия. Счета можно фильтровать по статусу: неоплаченные, частично оплаченные, оплаченные.\n\nНа основании счёта контрагент может произвести оплату. Система отслеживает статус оплаты и связывает платежи с соответствующими счетами.',
    uzDescription: '"Hisoblar" bo\'limi kontragentlarga berilgan to\'lov hisoblari ro\'yxatini o\'z ichiga oladi. Bu oldindan to\'lov va hisob-kitoblar bilan ishlash vositasidir.\n\nBo\'limda kontragent, summa, to\'lov holati va amal qilish muddati haqida ma\'lumot bilan hisoblar ko\'rsatiladi. Hisoblarni holat bo\'yicha filtrlash mumkin: to\'lanmagan, qisman to\'langan, to\'langan.\n\nHisob asosida kontragent to\'lovni amalga oshirishi mumkin. Tizim to\'lov holatini kuzatadi va to\'lovlarni tegishli hisoblar bilan bog\'laydi.',
    ruFunctionality: 'Открывает реестр счетов на оплату с возможностью создания, редактирования и отслеживания. Интерфейс показывает ключевые данные: номер, дата, контрагент, сумма, статус.\n\nКаждый счёт связан с документом-основанием: договором, заказом, реализацией. При оплате система автоматически закрывает счёт и связывает платёж.\n\nИз карточки счёта можно распечатать форму счёта для контрагента, отправить по email или сформировать ссылку для онлайн-оплаты. История изменений статуса сохраняется.',
    uzFunctionality: 'Yaratish, tahrirlash va kuzatish imkoniyati bilan to\'lov hisoblari reestrini ochadi. Interfeys asosiy ma\'lumotlarni ko\'rsatadi: raqam, sana, kontragent, summa, holat.\n\nHar bir hisob asos hujjat bilan bog\'langan: shartnoma, buyurtma, realizatsiya. To\'lovda tizim avtomatik hisobni yopadi va to\'lovni bog\'laydi.\n\nHisob kartochkasidan kontragent uchun hisob formasini chop etish, email orqali yuborish yoki onlayn to\'lov uchun havolani shakllantirish mumkin. Holat o\'zgarishlar tarixi saqlanadi.'
  },

  {
    order: 159,
    ruDescription: 'Кнопка создания счёта открывает форму для выставления нового счёта на оплату контрагенту. Это первый шаг при работе с предоплатой.\n\nВ форме нужно указать контрагента, список товаров или услуг, цены и условия оплаты. Система автоматически рассчитывает сумму счёта и НДС.\n\nПосле сохранения счёт получает уникальный номер и становится доступен для печати и отправки контрагенту. Статус счёта — "Не оплачен" до поступления платежа.',
    uzDescription: 'Hisob yaratish tugmasi kontragentga yangi to\'lov hisobini berish uchun formani ochadi. Bu oldindan to\'lov bilan ishlashda birinchi qadam.\n\nFormada kontragentni, tovarlar yoki xizmatlar ro\'yxatini, narxlarni va to\'lov shartlarini ko\'rsatish kerak. Tizim avtomatik hisob summasini va QQSni hisoblaydi.\n\nSaqlangandan so\'ng hisob noyob raqam oladi va chop etish va kontragentga yuborish uchun mavjud bo\'ladi. Hisob holati — to\'lov kelguncha "To\'lanmagan".',
    ruFunctionality: 'Открывает форму создания счёта с выбором контрагента и добавлением позиций. Товары можно выбрать из справочника или указать услугу вручную.\n\nФорма включает реквизиты плательщика, расчётный счёт для оплаты, срок действия счёта. Можно указать условия частичной оплаты или авансового платежа.\n\nПосле сохранения счёт можно распечатать в стандартной форме, отправить по email с вложением или сгенерировать QR-код для быстрой оплаты. Счёт появляется в реестре для отслеживания.',
    uzFunctionality: 'Kontragentni tanlash va pozitsiyalarni qo\'shish bilan hisob yaratish formasini ochadi. Tovarlarni ma\'lumotnomadan tanlash yoki xizmatni qo\'lda ko\'rsatish mumkin.\n\nForma to\'lovchi rekvizitlari, to\'lash uchun hisob-raqam, hisob amal qilish muddatini o\'z ichiga oladi. Qisman to\'lov yoki avans to\'lovi shartlarini ko\'rsatish mumkin.\n\nSaqlangandan so\'ng hisobni standart shaklda chop etish, ilova bilan email orqali yuborish yoki tez to\'lash uchun QR-kod generatsiya qilish mumkin. Hisob kuzatish uchun reestrda paydo bo\'ladi.'
  },

  {
    order: 160,
    ruDescription: 'Функция оплаты счёта фиксирует поступление платежа по выставленному счёту. Это завершает цикл работы со счётом и формирует финансовую операцию.\n\nПри оплате нужно указать сумму, дату и способ поступления средств: банковский перевод, наличные, электронный платёж. Можно указать номер платёжного документа.\n\nПосле оплаты счёт переходит в статус "Оплачен" и связывается с финансовой операцией. Если оплата частичная, счёт остаётся в статусе "Частично оплачен" с указанием остатка.',
    uzDescription: 'Hisobni to\'lash funksiyasi berilgan hisob bo\'yicha to\'lov kelishini qayd etadi. Bu hisob bilan ishlash siklini tugatadi va moliyaviy operatsiyani shakllantiradi.\n\nTo\'lovda summani, sanani va mablag\'lar kelish usulini ko\'rsatish kerak: bank o\'tkazmasi, naqd pul, elektron to\'lov. To\'lov hujjati raqamini ko\'rsatish mumkin.\n\nTo\'langandan so\'ng hisob "To\'langan" holatiga o\'tadi va moliyaviy operatsiya bilan bog\'lanadi. Agar to\'lov qisman bo\'lsa, hisob qoldiq ko\'rsatilgan holda "Qisman to\'langan" holatida qoladi.',
    ruFunctionality: 'Открывает форму регистрации платежа по счёту с указанием параметров оплаты. Система показывает сумму к оплате и предлагает зачесть аванс или предоплату.\n\nПри полном погашении счёт закрывается и появляется в разделе "Оплаченные". При частичной оплате система пересчитывает остаток долга.\n\nПлатёж автоматически создаёт финансовую операцию в разделе взаиморасчётов. Можно распечатать подтверждение оплаты для архива. История платежей по счёту сохраняется.',
    uzFunctionality: 'To\'lov parametrlarini ko\'rsatish bilan hisob bo\'yicha to\'lovni ro\'yxatdan o\'tkazish formasini ochadi. Tizim to\'lanadigan summani ko\'rsatadi va avans yoki oldindan to\'lovni hisobga olishni taklif qiladi.\n\nTo\'liq to\'langanda hisob yopiladi va "To\'langan" bo\'limida paydo bo\'ladi. Qisman to\'lovda tizim qarz qoldig\'ini qayta hisoblaydi.\n\nTo\'lov avtomatik o\'zaro hisob-kitoblar bo\'limida moliyaviy operatsiya yaratadi. Arxiv uchun to\'lov tasdiqlamasini chop etish mumkin. Hisob bo\'yicha to\'lovlar tarixi saqlanadi.'
  }
];

async function main() {
  console.log('Updating lessons 121-160 with detailed descriptions...');

  for (const lesson of detailedLessons) {
    const result = await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
        ruFunctionality: lesson.ruFunctionality,
        uzFunctionality: lesson.uzFunctionality,
      },
    });
    console.log(`Updated lesson ${lesson.order}: ${result.count} records`);
  }

  console.log('Done! Updated 40 lessons (121-160).');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
