// Update all 200 lessons with detailed descriptions (3+ paragraphs)
// Run: npx ts-node scripts/update-lessons-full.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const detailedLessons: { order: number; ruDescription: string; uzDescription: string; ruFunctionality?: string; uzFunctionality?: string }[] = [
  // === ГЛАВНАЯ (1-5) ===
  { order: 1, ruDescription: 'Главная страница системы Lume Admin является центральной точкой доступа ко всем функциям и возможностям программы. Здесь пользователь видит актуальную информацию о состоянии бизнеса, включая статистику продаж, остатки на складах и важные уведомления. Интерфейс главной страницы интуитивно понятен и позволяет быстро ориентироваться в системе.\n\nДашборд главной страницы содержит виджеты с ключевыми показателями эффективности: выручка за день, количество продаж, средний чек и другие метрики. Эти данные обновляются в реальном времени, что позволяет оперативно реагировать на изменения в работе.\n\nС главной страницы также доступен быстрый переход к часто используемым функциям: создание чека, добавление товара, просмотр отчётов. Это значительно ускоряет работу и повышает эффективность сотрудников.', uzDescription: 'Lume Admin tizimining bosh sahifasi dasturning barcha funksiyalari va imkoniyatlariga markaziy kirish nuqtasidir. Bu yerda foydalanuvchi biznes holati haqida dolzarb ma\'lumotlarni ko\'radi, shu jumladan sotuv statistikasi, omborlardagi qoldiqlar va muhim bildirishnomalar. Bosh sahifa interfeysi intuitiv tushunarli bo\'lib, tizimda tez yo\'nalinga imkon beradi.\n\nBosh sahifa dashbordi samaradorlikning asosiy ko\'rsatkichlari bilan vidjetlarni o\'z ichiga oladi: kunlik tushum, sotuvlar soni, o\'rtacha chek va boshqa ko\'rsatkichlar. Bu ma\'lumotlar real vaqtda yangilanib, ish jarayonidagi o\'zgarishlarga o\'z vaqtida munosabat bildirishga imkon beradi.\n\nBosh sahifadan shuningdek tez-tez ishlatiladigan funksiyalarga tez o\'tish mumkin: chek yaratish, tovar qo\'shish, hisobotlarni ko\'rish. Bu ishni sezilarli darajada tezlashtiradi va xodimlarning samaradorligini oshiradi.' },

  { order: 2, ruDescription: 'Баланс счёта отображается в верхней части интерфейса и показывает текущее состояние расчётного счёта организации. Это ключевой показатель, который позволяет оперативно контролировать финансовое состояние компании и планировать расходы.\n\nПри клике на баланс открывается детальная информация о движении средств: входящие и исходящие платежи, даты операций и контрагенты. Это позволяет быстро найти нужную операцию и проверить её корректность.\n\nБаланс обновляется автоматически при проведении финансовых операций: оплата от покупателя увеличивает баланс, а оплата поставщику — уменьшает. Система также учитывает курсовые разницы при работе с валютными счетами.', uzDescription: 'Hisob balansi interfeysning yuqori qismida ko\'rsatiladi va tashkilotning hisob-raqamining joriy holatini aks ettiradi. Bu kompaniyaning moliyaviy holatini operativ nazorat qilish va xarajatlarni rejalashtirishga imkon beruvchi asosiy ko\'rsatkichdir.\n\nBalans bosilganda mablag\'lar harakati haqida batafsil ma\'lumot ochiladi: kiruvchi va chiquvchi to\'lovlar, operatsiyalar sanalari va kontragentlar. Bu kerakli operatsiyani tez topish va uning to\'g\'riligini tekshirish imkonini beradi.\n\nBalans moliyaviy operatsiyalar o\'tkazilganda avtomatik yangilanadi: xaridordan to\'lov balansni oshiradi, yetkazib beruvchiga to\'lov esa kamaytiradi. Tizim shuningdek valyutaviy hisoblar bilan ishlashda valyuta farqlarini hisobga oladi.' },

  { order: 3, ruDescription: 'Кнопка пополнения баланса находится в верхней панели и предоставляет быстрый доступ к функционалу пополнения расчётного счёта. Это важная функция для поддержания достаточного уровня средств на счету для бесперебойной работы бизнеса.\n\nПри нажатии открывается форма выбора способа пополнения: банковский перевод, платёжная карта или электронный кошелёк. Система поддерживает интеграцию с большинством популярных платёжных систем и банков.\n\nПосле выбора способа система формирует платёжное поручение или переводит на страницу платёжного шлюза. Все операции пополнения сохраняются в истории с указанием даты, времени и способа оплаты.', uzDescription: 'Balansni to\'ldirish tugmasi yuqori panelda joylashgan bo\'lib, hisob-raqamni to\'ldirish funktsiyasiga tez kirishni ta\'minlaydi. Bu biznesning uzluksiz ishlashi uchun hisobda yetarli mablag\' darajasini saqlab qolish uchun muhim funksiya.\n\nBosilganda to\'ldirish usulini tanlash formasi ochiladi: bank o\'tkazmasi, to\'lov kartasi yoki elektron hamyon. Tizim ko\'pchilik mashhur to\'lov tizimlari va banklar bilan integratsiyani qo\'llab-quvvatlaydi.\n\nUsul tanlangandan so\'ng tizim to\'lov topshiriqlarini shakllantiradi yoki to\'lov shlyuzi sahifasiga o\'tkazadi. Barcha to\'ldirish operatsiyalari sana, vaqt va to\'lov usuli ko\'rsatilgan holda tarixda saqlanadi.' },

  { order: 4, ruDescription: 'Профиль пользователя содержит персональные данные сотрудника и настройки его работы в системе. Это центральное место для управления личной информацией, паролем и предпочтениями интерфейса.\n\nВ профиле можно изменить пароль, настроить уведомления, выбрать язык интерфейса и тему оформления. Каждый пользователь может адаптировать систему под свои потребности и привычный стиль работы.\n\nДля администраторов профиль также показывает информацию о правах доступа и роли пользователя. Это помогает контролировать безопасность системы и при необходимости корректировать уровень доступа сотрудника.', uzDescription: 'Foydalanuvchi profili xodimning shaxsiy ma\'lumotlarini va tizimdagi ish sozlamalarini o\'z ichiga oladi. Bu shaxsiy ma\'lumotlar, parol va interfeys afzalliklarini boshqarish uchun markaziy joy hisoblanadi.\n\nProfil ichida parolni o\'zgartirish, bildirishnomalarni sozlash, interfeys tilini va mavzuni tanlash mumkin. Har bir foydalanuvchi tizimni o\'z ehtiyojlariga va o\'rganish uslubiga moslashtirishi mumkin.\n\nAdministratorlar uchun profil shuningdek foydalanuvchi huquqlari va roli haqida ma\'lumotni ko\'rsatadi. Bu tizim xavfsizligini nazorat qilishga va zarurat bo\'lganda xodimning kirish darajasini tuzatishga yordam beradi.' },

  { order: 5, ruDescription: 'Кнопка выхода из системы обеспечивает безопасное завершение работы с программой. Это важный элемент безопасности, который предотвращает несанкционированный доступ к системе в отсутствие пользователя.\n\nПри нажатии на кнопку система запрашивает подтверждение выхода, чтобы исключить случайное действие. После подтверждения сессия завершается, и все несохранённые данные могут быть потеряны.\n\nРекомендуется всегда использовать кнопку выхода при завершении работы, особенно на общих или публичных компьютерах. Это гарантирует сохранность коммерческой информации и персональных данных.', uzDescription: 'Tizimdan chiqish tugmasi dastur bilan ishlashni xavfsiz tugatishni ta\'minlaydi. Bu foydalanuvchi yo\'qligida tizimga ruxsatsiz kirishning oldini oluvchi muhim xavfsizlik elementidir.\n\nTugma bosilganda tizim chiqishni tasdiqlashni so\'raydi, bu tasodifiy harakatni istisno qiladi. Tasdiqlangandan so\'ng sessiya tugatiladi va barcha saqlanmagan ma\'lumotlar yo\'qolishi mumkin.\n\nIsh tugatilganda, ayniqsa umumiy yoki ommaviy kompyuterlarda chiqish tugmasidan foydalanish tavsiya etiladi. Bu tijorat ma\'lumotlari va shaxsiy ma\'lumotlarning xavfsizligini kafolatlaydi.' },

  // === СКЛАД: ТОВАРЫ (6-20) ===
  { order: 6, ruDescription: 'Раздел "Товары" является основой складского учёта и содержит полный список всех товаров организации. Здесь хранится информация о наименованиях, ценах, остатках, единицах измерения и других характеристиках продукции.\n\nИнтерфейс раздела включает таблицу с возможностью сортировки и фильтрации по различным параметрам: категория, бренд, склад, наличие. Поиск работает по названию, артикулу и штрих-коду, что позволяет мгновенно находить нужную позицию.\n\nВ этом разделе можно выполнять все основные операции с товарами: добавление новых позиций, редактирование существующих, удаление неактуальных товаров. Также доступны функции массового редактирования и экспорта данных в различные форматы.', uzDescription: '"Tovarlar" bo\'limi ombor hisobining asosi hisoblanadi va tashkilotning barcha tovarlari ro\'yxatini o\'z ichiga oladi. Bu yerda nomlar, narxlar, qoldiqlar, o\'lchov birliklari va mahsulotning boshqa xususiyatlari haqida ma\'lumotlar saqlanadi.\n\nBo\'lim interfeysi turli parametrlar bo\'yicha saralash va filtrlash imkoniyati bilan jadvalni o\'z ichiga oladi: kategoriya, brend, ombor, mavjudlik. Qidiruv nom, artikul va shtrix-kod bo\'yicha ishlaydi, bu kerakli pozitsiyani bir zumda topishga imkon beradi.\n\nBu bo\'limda tovarlar bilan barcha asosiy operatsiyalarni bajarish mumkin: yangi pozitsiyalar qo\'shish, mavjudlarni tahrirlash, dolzarb bo\'lmagan tovarlarni o\'chirish. Shuningdek ommaviy tahrirlash va ma\'lumotlarni turli formatlarda eksport qilish funksiyalari mavjud.' },

  { order: 7, ruDescription: 'Кнопка добавления товара открывает форму создания новой позиции в справочнике товаров. Это первый шаг при появлении нового товара в ассортименте организации.\n\nФорма содержит все необходимые поля: наименование на разных языках, артикул, штрих-код, категорию, единицу измерения, цены закупки и продажи. Обязательные поля отмечены специальным образом, и система не позволит сохранить товар без их заполнения.\n\nПосле заполнения формы и сохранения товар появляется в общем списке и становится доступен для всех складских операций: прихода, реализации, инвентаризации. Можно также загрузить изображение товара для удобства идентификации.', uzDescription: 'Tovar qo\'shish tugmasi tovarlar ma\'lumotnomasida yangi pozitsiya yaratish formasini ochadi. Bu tashkilot assortimentida yangi tovar paydo bo\'lganda birinchi qadam hisoblanadi.\n\nForma barcha kerakli maydonlarni o\'z ichiga oladi: turli tillarda nom, artikul, shtrix-kod, kategoriya, o\'lchov birligi, xarid va sotuv narxlari. Majburiy maydonlar maxsus belgi bilan belgilanadi va tizim ularsiz tovarni saqlashga yo\'l qo\'ymaydi.\n\nForma to\'ldirilib saqlangandan so\'ng, tovar umumiy ro\'yxatda paydo bo\'ladi va barcha ombor operatsiyalari uchun mavjud bo\'ladi: kirim, realizatsiya, inventarizatsiya. Tovarni identifikatsiya qilish qulayligi uchun uning tasvirini yuklash ham mumkin.' },

  { order: 8, ruDescription: 'Поле поиска товаров позволяет быстро найти нужную позицию в базе данных без необходимости пролистывать весь список. Это значительно ускоряет работу, особенно при большом ассортименте.\n\nПоиск работает в реальном времени: результаты появляются уже при вводе первых символов. Система ищет по названию товара, артикулу, штрих-коду и другим идентификаторам. Результаты сортируются по релевантности.\n\nДля более точного поиска можно использовать специальные операторы: кавычки для точного совпадения фразы, минус для исключения слов. Это помогает найти товар даже при неполном знании его названия.', uzDescription: 'Tovarlarni qidirish maydoni butun ro\'yxatni aylantirish zaruriyatisiz bazadan kerakli pozitsiyani tez topish imkonini beradi. Bu ishni sezilarli darajada tezlashtiradi, ayniqsa katta assortimentda.\n\nQidiruv real vaqtda ishlaydi: natijalar birinchi belgilarni kiritishda paydo bo\'ladi. Tizim tovar nomi, artikul, shtrix-kod va boshqa identifikatorlar bo\'yicha qidiradi. Natijalar dolzarblik bo\'yicha saralanadi.\n\nAniqroq qidirish uchun maxsus operatorlardan foydalanish mumkin: iboraning to\'liq mos kelishi uchun tirnoqlar, so\'zlarni istisno qilish uchun minus. Bu tovar nomini to\'liq bilmasa ham topishga yordam beradi.' },

  { order: 9, ruDescription: 'Фильтр по категории позволяет ограничить список товаров определённой группой, что упрощает работу с ассортиментом. Категории образуют иерархическую структуру, отражающую логику организации товаров.\n\nПри выборе категории система показывает только товары, относящиеся к ней и её подкатегориям. Это особенно полезно при работе с большими справочниками, когда нужно сосредоточиться на конкретной группе продукции.\n\nФильтр можно комбинировать с другими фильтрами и поиском для максимально точного отбора товаров. Также доступен множественный выбор категорий для одновременного просмотра нескольких групп.', uzDescription: 'Kategoriya bo\'yicha filtr tovarlar ro\'yxatini ma\'lum guruh bilan cheklash imkonini beradi, bu assortiment bilan ishlashni soddalashtiradi. Kategoriyalar tovarlarning mantiqiy tuzilishini aks ettiruvchi ierarxik tuzilmani hosil qiladi.\n\nKategoriya tanlanganda tizim faqat unga va uning ost-kategoriyalariga tegishli tovarlarni ko\'rsatadi. Bu katta ma\'lumotnomalar bilan ishlashda, aniq mahsulot guruhi ustida ishlash kerak bo\'lganda ayniqsa foydali.\n\nFiltrni boshqa filtrlar va qidiruv bilan birlashtirish mumkin, tovarlarni maksimal aniq tanlash uchun. Shuningdek bir vaqtning o\'zida bir nechta kategoriyani ko\'rish uchun ko\'p tanlov ham mavjud.' },

  { order: 10, ruDescription: 'Фильтр по складу показывает остатки товаров на конкретном складе или торговой точке. Это необходимо при работе в многозвенной сети для контроля запасов по местоположению.\n\nПри выборе склада система отображает только те товары, которые есть в наличии на этом объекте. Также показывается актуальное количество и статус наличия. Это помогает избежать ситуаций, когда товар заказывается с отсутствующего склада.\n\nФильтр особенно полезен для менеджеров складов, которые контролируют только свой объект. Можно настроить фильтр по умолчанию, чтобы при входе в раздел сразу видеть товары своего склада.', uzDescription: 'Ombor bo\'yicha filtr aniq ombor yoki savdo nuqtasidagi tovar qoldiqlarini ko\'rsatadi. Bu ko\'p bo\'g\'inli tarmoqda joylashuv bo\'yicha zaxiralarni nazorat qilish uchun zarur.\n\nOmbor tanlanganda tizim faqat ushbu ob\'ektda mavjud bo\'lgan tovarlarni ko\'rsatadi. Shuningdek dolzarb miqdor va mavjudlik holati ko\'rsatiladi. Bu tovar mavjud bo\'lmagan ombordan buyurtma qilinish holatlarining oldini oladi.\n\nFiltr ayniqsa faqat o\'z ob\'ektini nazorat qiluvchi ombor menejerlari uchun foydali. Kirish vaqtida o\'z omborining tovarlarini darhol ko\'rish uchun filtrni standart qilib sozlash mumkin.' },

  { order: 11, ruDescription: 'Кнопка редактирования товара открывает форму изменения параметров существующей позиции. Это позволяет актуализировать информацию о товаре при изменении условий работы.\n\nВ форме редактирования доступны все те же поля, что и при создании товара. Можно изменить наименование, цены, категорию, описание и другие характеристики. История изменений сохраняется, что позволяет отследить, кто и когда вносил корректировки.\n\nПри редактировании цен система может предложить обновить цены в связанных документах или пересчитать себестоимость. Это помогает поддерживать актуальность учётных данных.', uzDescription: 'Tovarni tahrirlash tugmasi mavjud pozitsiya parametrlarini o\'zgartirish formasini ochadi. Bu ish sharoitlari o\'zgarganda tovar haqidagi ma\'lumotlarni dolzarblashtirish imkonini beradi.\n\nTahrirlash formasida tovar yaratishdagidek barcha maydonlar mavjud. Nom, narxlar, kategoriya, tavsif va boshqa xususiyatlarni o\'zgartirish mumkin. O\'zgarishlar tarixi saqlanib qoladi, bu kim va qachon tuzatishlar kiritganini kuzatish imkonini beradi.\n\nNarlarni tahrirlashda tizim bog\'liq hujjatlarda narxlarni yangilashni yoki tannarxni qayta hisoblashni taklif qilishi mumkin. Bu hisob ma\'lumotlarining dolzarbligini saqlashga yordam beradi.' },

  { order: 12, ruDescription: 'Кнопка удаления товара удаляет позицию из справочника товаров. Это действие требует подтверждения и имеет ограничения для защиты целостности данных.\n\nУдалить можно только тот товар, по которому нет движений в учёте. Если товар участвовал в приходах, реализациях или других операциях, система предложит пометить его как неактивный вместо удаления. Это позволяет сохранить историю операций.\n\nПеред удалением система показывает предупреждение о невозможности восстановления данных. Рекомендуется использовать эту функцию только для позиций, созданных по ошибке.', uzDescription: 'Tovarni o\'chirish tugmasi pozitsiyani tovarlar ma\'lumotnomasidan o\'chiradi. Bu harakat tasdiqlashni talab qiladi va ma\'lumotlar yaxlitligini himoya qilish uchun cheklovlarga ega.\n\nFaqat hisobda harakati bo\'lmagan tovarni o\'chirish mumkin. Agar tovar kirim, realizatsiya yoki boshqa operatsiyalarda qatnashgan bo\'lsa, tizim o\'chirish o\'rniga uni nofaol deb belgilashni taklif qiladi. Bu operatsiyalar tarixini saqlab qolish imkonini beradi.\n\nO\'chirishdan oldin tizim ma\'lumotlarni qayta tiklab bo\'lmasligi haqida ogohlantirish ko\'rsatadi. Bu funksiyadan faqat xato yaratilgan pozitsiyalar uchun foydalanish tavsiya etiladi.' },

  { order: 13, ruDescription: 'Функция экспорта товаров позволяет выгрузить список товаров в файл для работы во внешних программах или передачи контрагентам. Это востребованная функция для прайс-листов и инвентаризации.\n\nЭкспорт доступен в форматах Excel и CSV. При выгрузке можно выбрать конкретные колонки для экспорта, чтобы получить только нужную информацию. Также можно применить фильтры перед экспортом и выгрузить только отобранные товары.\n\nПолученный файл можно использовать для печати прайс-листа, загрузки на маркетплейсы или анализа в Excel. Это удобный способ обмена данными с внешними системами.', uzDescription: 'Tovarlarni eksport funksiyasi tovarlar ro\'yxatini tashqi dasturlarda ishlash yoki kontragentlarga uzatish uchun faylga yuklash imkonini beradi. Bu narx-listlar va inventarizatsiya uchun talab qilinadigan funksiya.\n\nEksport Excel va CSV formatlarida mavjud. Yuklashda faqat kerakli ma\'lumotni olish uchun eksport qilinadigan aniq ustunlarni tanlash mumkin. Shuningdek eksport oldidan filtrlarni qo\'llash va faqat tanlangan tovarlarni yuklash mumkin.\n\nOlingan faylni narx-listni chop etish, marketpleyslarga yuklash yoki Excel da tahlil qilish uchun ishlatish mumkin. Bu tashqi tizimlar bilan ma\'lumotlar almashinuvining qulay usuli.' },

  { order: 14, ruDescription: 'Карточка товара содержит полную информацию о конкретной позиции: описание, характеристики, цены, остатки по складам и историю движения. Это детальное представление товара в системе.\n\nВ карточке товара можно увидеть текущие остатки на каждом складе, историю изменения цен, последние операции поступления и реализации. Эта информация помогает принимать решения о закупках и ценообразовании.\n\nИз карточки товара также доступны быстрые действия: создать приход, реализацию, напечатать ценник или штрих-код. Это ускоряет работу операторов складского учёта.', uzDescription: 'Tovar kartochkasi aniq pozitsiya haqida to\'liq ma\'lumotni o\'z ichiga oladi: tavsif, xususiyatlar, narxlar, omborlar bo\'yicha qoldiqlar va harakat tarixi. Bu tizimdagi tovarning batafsil ko\'rinishi.\n\nTovar kartochkasida har bir ombordagi joriy qoldiqlarni, narx o\'zgarishlari tarixini, oxirgi kirim va realizatsiya operatsiyalarini ko\'rish mumkin. Bu ma\'lumotlar xaridlar va narx belgilash bo\'yicha qarorlar qabul qilishga yordam beradi.\n\nTovar kartochkasidan shuningdek tezkor harakatlar mavjud: kirim, realizatsiya yaratish, narx yorlig\'i yoki shtrix-kod chop etish. Bu ombor hisobi operatorlarining ishini tezlashtiradi.' },

  { order: 15, ruDescription: 'Функция добавления в избранное позволяет сохранить товар в персональном списке для быстрого доступа. Это удобно для товаров, которые часто используются в работе.\n\nИзбранные товары отображаются в отдельном разделе и на видном месте интерфейса. При создании чека или документа можно быстро добавить товар из избранного, не прибегая к поиску.\n\nСписок избранного индивидуален для каждого пользователя, что позволяет каждому сотруднику настроить быстрый доступ под свои потребности. Товар можно добавить или убрать из избранного одним кликом.', uzDescription: 'Sevimlilarga qo\'shish funksiyasi tovarni tez kirish uchun shaxsiy ro\'yxatda saqlash imkonini beradi. Bu ishda tez-tez ishlatiladigan tovarlar uchun qulay.\n\nSevimli tovarlar alohida bo\'limda va interfeysning ko\'zga tashlanadigan joyida ko\'rsatiladi. Chek yoki hujjat yaratishda qidirishga murojaat qilmasdan sevimlilardan tovarni tez qo\'shish mumkin.\n\nSevimlilar ro\'yxati har bir foydalanuvchi uchun individual bo\'lib, har bir xodimga o\'z ehtiyojlariga ko\'ra tez kirishni sozlash imkonini beradi. Tovarni bir marta bosish bilan sevimlilarga qo\'shish yoki olib tashlash mumkin.' },

  { order: 16, ruDescription: 'Массовое редактирование позволяет изменить параметры сразу для нескольких товаров за одну операцию. Это экономит время при необходимости обновить цены, категорию или другие атрибуты для группы товаров.\n\nДля массового редактирования нужно отметить товары с помощью чекбоксов и выбрать действие из меню. Доступные действия: изменение цены, перенос в категорию, изменение единицы измерения, установка статуса.\n\nСистема показывает превью изменений перед применением, чтобы избежать ошибок. После подтверждения все выбранные товары обновляются одновременно, и изменения отражаются в истории.', uzDescription: 'Ommaviy tahrirlash bir operatsiyada bir nechta tovar parametrlarini o\'zgartirish imkonini beradi. Bu tovarlar guruhi uchun narxlarni, kategoriyani yoki boshqa atributlarni yangilash kerak bo\'lganda vaqtni tejaydi.\n\nOmmaviy tahrirlash uchun tovarlarni checkbox lar yordamida belgilash va menyu dan harakatni tanlash kerak. Mavjud harakatlar: narxni o\'zgartirish, kategoriyaga ko\'chirish, o\'lchov birligini o\'zgartirish, holatni o\'rnatish.\n\nTizim xatolardan qochish uchun qo\'llashdan oldin o\'zgarishlarning oldindan ko\'rishini ko\'rsatadi. Tasdiqlangandan so\'ng barcha tanlangan tovarlar bir vaqtning o\'zida yangilanadi va o\'zgarishlar tarixda aks etadi.' },

  { order: 17, ruDescription: 'Функция печати ценника формирует печатную форму ценника для выбранного товара. Это необходимо для оформления торгового зала и соблюдения требований законодательства о защите прав потребителей.\n\nСистема предлагает несколько шаблонов ценников разных размеров и форматов. Можно выбрать шаблон для печати на обычной бумаге или на самоклеящейся этикетке. Доступна настройка шаблона с логотипом организации.\n\nПри печати ценника на него автоматически подставляется актуальная цена товара. Можно также распечатать ценники сразу для нескольких товаров, выбрав их в списке.', uzDescription: 'Narx yorlig\'ini chop etish funksiyasi tanlangan tovar uchun narx yorlig\'ining bosma shaklini yaratadi. Bu savdo zali ni bezash va iste\'molchilar huquqlarini himoya qilish to\'g\'risidagi qonun hujjatlariga rioya qilish uchun zarur.\n\nTizim turli o\'lcham va formatlardagi narx yorliqlarining bir nechta shablonlarini taklif qiladi. Oddiy qog\'ozga yoki o\'z-o\'zidan yopishqoq etiketkaga chop etish uchun shablonni tanlash mumkin. Tashkilot logotipi bilan shablonni sozlash mavjud.\n\nNarx yorlig\'ini chop etishda unga tovarning dolzarb narxi avtomatik qo\'yiladi. Shuningdek ro\'yxatda tanlab bir nechta tovarlar uchun darhol narx yorliqlarini chop etish mumkin.' },

  { order: 18, ruDescription: 'Функция копирования товара создаёт дубликат выбранной позиции со всеми её характеристиками. Это ускоряет добавление похожих товаров, когда новая позиция незначительно отличается от существующей.\n\nПри копировании создаётся новый товар с теми же значениями полей: категория, единица измерения, описание. Нужно только изменить наименование, артикул и скорректировать при необходимости цены.\n\nКопирование особенно полезно при вводе новых модификаций товара: другого цвета, размера или комплектации. Это экономит время на заполнение повторяющихся данных.', uzDescription: 'Tovarni nusxalash funksiyasi tanlangan pozitsiyaning barcha xususiyatlari bilan dublikatini yaratadi. Bu yangi pozitsiya mavjudidan oz farq qilganda o\'xshash tovarlarni qo\'shishni tezlashtiradi.\n\nNusxalashda bir xil maydon qiymatlari bilan yangi tovar yaratiladi: kategoriya, o\'lchov birligi, tavsif. Faqat nomni, artikulni o\'zgartirish va zarurat bo\'lganda narxlarni tuzatish kerak.\n\nNusxalash ayniqsa tovarning yangi modifikatsiyalarini kiritishda foydali: boshqa rang, o\'lcham yoki komplektatsiya. Bu takroriy ma\'lumotlarni to\'ldirish vaqtini tejaydi.' },

  { order: 19, ruDescription: 'История изменений товара показывает все изменения, которые производились с карточкой товара: изменение цен, описания, категории и других параметров. Это важный инструмент контроля и аудита.\n\nВ истории отображается дата и время изменения, пользователь, внёсший изменение, и сами изменённые значения — старое и новое. Это позволяет отследить причины и авторов всех корректировок.\n\nИстория хранится за весь период существования товара и не может быть удалена. Это обеспечивает прозрачность учётных данных и помогает при разборе спорных ситуаций.', uzDescription: 'Tovar o\'zgarishlari tarixi tovar kartochkasi bilan amalga oshirilgan barcha o\'zgarishlarni ko\'rsatadi: narxlar, tavsif, kategoriya va boshqa parametrlarning o\'zgarishi. Bu nazorat va auditoriyaning muhim vositasidir.\n\nTarixda o\'zgarish sanasi va vaqti, o\'zgarish kiritgan foydalanuvchi va o\'zgartirilgan qiymatlar — eski va yangi ko\'rsatiladi. Bu barcha tuzatishlarning sabablari va mualliflarini kuzatish imkonini beradi.\n\nTarix tovar mavjud bo\'lgan butun davrda saqlanadi va o\'chirib bo\'lmaydi. Bu hisob ma\'lumotlarining shaffofligini ta\'minlaydi va bahsli holatlarni hal qilishda yordam beradi.' },

  { order: 20, ruDescription: 'Функция просмотра и печати штрих-кода показывает графическое изображение штрих-кода товара для печати этикеток. Штрих-код используется для идентификации товара при сканировании.\n\nСистема генерирует штрих-код в формате EAN-13 или Code 128 в зависимости от типа кода товара. Изображение можно масштабировать для печати этикеток разного размера.\n\nРаспечатанный штрих-код можно наклеить на товар или упаковку для использования при приёмке, инвентаризации и продаже. Система также поддерживает печать QR-кодов с дополнительной информацией о товаре.', uzDescription: 'Shtrix-kodni ko\'rish va chop etish funksiyasi etiketkalarni chop etish uchun tovar shtrix-kodining grafik tasvirini ko\'rsatadi. Shtrix-kod skanerlashda tovarni identifikatsiya qilish uchun ishlatiladi.\n\nTizim tovar kodi turiga qarab EAN-13 yoki Code 128 formatida shtrix-kod yaratadi. Tasvirni turli o\'lchamdagi etiketkalarni chop etish uchun masshtablashtirish mumkin.\n\nChop etilgan shtrix-kodni qabul qilish, inventarizatsiya va sotishda foydalanish uchun tovar yoki qadoqqa yopishtirish mumkin. Tizim shuningdek tovar haqida qo\'shimcha ma\'lumot bilan QR-kodlarni chop etishni qo\'llab-quvvatlaydi.' },

  // === СКЛАД: ПРИХОД (21-35) ===
  { order: 21, ruDescription: 'Раздел "Приход" предназначен для оформления поступления товаров от поставщиков. Это ключевой раздел складского учёта, где фиксируются все входящие поставки товаров.\n\nВ разделе отображается список документов поступления с информацией о поставщике, дате, сумме и статусе документа. Документы можно фильтровать по периоду, поставщику и статусу проведения.\n\nПравильное оформление прихода обеспечивает корректный учёт товаров и расчёт себестоимости. Все приходы сохраняются в истории и доступны для анализа и аудита.', uzDescription: '"Kirim" bo\'limi yetkazib beruvchilardan tovarlarning kelib tushishini rasmiylashtirish uchun mo\'ljallangan. Bu ombor hisobining asosiy bo\'limi bo\'lib, bu yerda barcha kiruvchi tovar yetkazib berishlar qayd etiladi.\n\nBo\'limda yetkazib beruvchi, sana, summa va hujjat holati haqida ma\'lumot bilan kelib tushish hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni davr, yetkazib beruvchi va o\'tkazish holati bo\'yicha filtrlash mumkin.\n\nKirimga to\'g\'ri rasmiylashtirish tovarlarning to\'g\'ri hisobini va tannarxni hisoblashni ta\'minlaydi. Barcha kirinishlar tarixda saqlanadi va tahlil va auditoriya uchun mavjud.' },

  { order: 22, ruDescription: 'Кнопка создания прихода открывает форму для оформления нового документа поступления товаров. Это первый шаг при приёмке товара от поставщика.\n\nВ форме необходимо указать поставщика, склад получения, дату документа и добавить список товаров с количеством и ценами. Система автоматически рассчитывает сумму документа и НДС.\n\nПосле заполнения документ можно сохранить как черновик или сразу провести, чтобы товары появились на остатках склада. Проведённый документ нельзя редактировать, можно только отменить.', uzDescription: 'Kirim yaratish tugmasi yangi tovar kelib tushish hujjatini rasmiylashtirish uchun formani ochadi. Bu yetkazib beruvchidan tovar qabul qilishdagi birinchi qadam.\n\nFormada yetkazib beruvchi, qabul qiluvchi ombor, hujjat sanasini ko\'rsatish va tovarlar ro\'yxatini miqdor va narxlar bilan qo\'shish kerak. Tizim avtomatik hujjat summasini va QQS ni hisoblaydi.\n\nTo\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki darhol o\'tkazish mumkin, shunda tovarlar ombor qoldiqlarida paydo bo\'ladi. O\'tkazilgan hujjatni tahrirlab bo\'lmaydi, faqat bekor qilish mumkin.' },

  { order: 23, ruDescription: 'Поле выбора поставщика позволяет указать контрагента, от которого поступает товар. Это обязательный реквизит документа прихода, влияющий на расчёты с поставщиками.\n\nПри вводе первых символов названия система предлагает варианты из справочника контрагентов. Можно также создать нового поставщика непосредственно из формы прихода.\n\nВыбранный поставщик автоматически подставляется в расчёты по дебиторской и кредиторской задолженности. История поставок от конкретного поставщика доступна в его карточке.', uzDescription: 'Yetkazib beruvchini tanlash maydoni tovar kelgan kontragentni ko\'rsatish imkonini beradi. Bu kirim hujjatining majburiy rekviziti bo\'lib, yetkazib beruvchilar bilan hisob-kitoblarga ta\'sir qiladi.\n\nNoming birinchi belgilari kiritilganda tizim kontragentlar ma\'lumotnomasidan variantlarni taklif qiladi. Shuningdek kirim formasidan to\'g\'ridan-to\'g\'ri yangi yetkazib beruvchi yaratish mumkin.\n\nTanlangan yetkazib beruvchi avtomatik debitorlik va kreditorlik qarzlari bo\'yicha hisob-kitoblarga qo\'yiladi. Aniq yetkazib beruvchidan yetkazib berishlar tarixi uning kartochkasida mavjud.' },

  { order: 24, ruDescription: 'Кнопка добавления товаров в приход открывает форму выбора позиций для включения в документ. Это основной этап формирования документа поступления.\n\nТовары можно добавлять по одному или выбирать сразу несколько позиций из списка. Для каждого товара указывается количество и цена закупки. Система проверяет корректность введённых данных.\n\nТакже доступно добавление товаров путём сканирования штрих-кода — это значительно ускоряет работу при приёмке больших партий товара.', uzDescription: 'Kirimga tovar qo\'shish tugmasi hujjatga kiritish uchun pozitsiyalarni tanlash formasini ochadi. Bu kelib tushish hujjatini shakllantirishning asosiy bosqichi.\n\nTovarlarni bittadan yoki ro\'yxatdan bir vaqtning o\'zida bir nechta pozitsiyani tanlash mumkin. Har bir tovar uchun miqdor va xarid narxi ko\'rsatiladi. Tizim kiritilgan ma\'lumotlarning to\'g\'riligini tekshiradi.\n\nShuningdek shtrix-kodni skanerlab tovar qo\'shish ham mavjud — bu katta tovar partiyalarini qabul qilishda ishni sezilarli darajada tezlashtiradi.' },

  { order: 25, ruDescription: 'Статус "Черновик" означает, что документ сохранён, но не проведён в учёте. В этом состоянии документ можно редактировать, но товары ещё не отражаются на остатках.\n\nЧерновики используются для предварительной подготовки документов, когда не все данные известны или требуются дополнительные согласования. Документ может находиться в статусе черновика неограниченное время.\n\nКогда все данные проверены и подтверждены, документ можно провести — товары зачислятся на склад, а документ перейдёт в статус "Оформлен".', uzDescription: '"Qoralama" holati hujjat saqlangan, lekin hisobda o\'tkazilmaganligini bildiradi. Bu holatda hujjatni tahrirlash mumkin, ammo tovarlar hali qoldiqlarda aks etmaydi.\n\nQoralamalar barcha ma\'lumotlar ma\'lum bo\'lmaganda yoki qo\'shimcha kelishuvlar talab qilinganda hujjatlarni oldindan tayyorlash uchun ishlatiladi. Hujjat cheksiz vaqt qoralama holatida bo\'lishi mumkin.\n\nBarcha ma\'lumotlar tekshirilib tasdiqlanganda, hujjatni o\'tkazish mumkin — tovarlar omborga qabul qilinadi va hujjat "Rasmiylashtirilgan" holatiga o\'tadi.' },

  { order: 26, ruDescription: 'Статус "Оформлен" означает, что документ проведён в учёте и товары зачислены на склад. Это финальный статус документа прихода, подтверждающий факт поступления.\n\nПроведённый документ влияет на остатки товаров, расчёты с поставщиком и финансовую отчётность. Изменения, внесённые документом, отражаются во всех связанных отчётах и регистрах.\n\nПроведённый документ нельзя редактировать напрямую — для корректировки нужно отменить проведение или создать документ корректировки. Это обеспечивает целостность учётных данных.', uzDescription: '"Rasmiylashtirilgan" holati hujjat hisobda o\'tkazilgan va tovarlar omborga qabul qilinganligini bildiradi. Bu kelib tushishni tasdiqlovchi kirim hujjatining yakuniy holatidir.\n\nO\'tkazilgan hujjat tovar qoldiqlariga, yetkazib beruvchi bilan hisob-kitoblarga va moliyaviy hisobotga ta\'sir qiladi. Hujjat kiritgan o\'zgarishlar barcha bog\'liq hisobotlar va registrlarda aks etadi.\n\nO\'tkazilgan hujjatni to\'g\'ridan-to\'g\'ri tahrirlab bo\'lmaydi — tuzatish uchun o\'tkazishni bekor qilish yoki tuzatish hujjatini yaratish kerak. Bu hisob ma\'lumotlarining yaxlitligini ta\'minlaydi.' },

  { order: 27, ruDescription: 'Функция печати прихода формирует печатную форму документа для архива и подписи. Это необходимо для документооборота с поставщиками и внутреннего контроля.\n\nСистема предлагает несколько шаблонов печатной формы: приходная накладная, приходный ордер, универсальный передаточный документ. Шаблоны соответствуют требованиям бухгалтерского учёта.\n\nРаспечатанный документ можно передать поставщику для подписи или хранить в архиве. Электронная версия документа также доступна для отправки по электронной почте.', uzDescription: 'Kirimni chop etish funksiyasi arxiv va imzo uchun hujjatning bosma shaklini yaratadi. Bu yetkazib beruvchilar bilan hujjat aylanishi va ichki nazorat uchun zarur.\n\nTizim bosma shaklning bir nechta shablonlarini taklif qiladi: kirim nakladnoysi, kirim orderi, universal uzatish hujjati. Shablonlar buxgalteriya hisobi talablariga mos keladi.\n\nChop etilgan hujjatni yetkazib beruvchiga imzolash uchun berish yoki arxivda saqlash mumkin. Hujjatning elektron versiyasi elektron pochta orqali yuborish uchun ham mavjud.' },

  { order: 28, ruDescription: 'Кнопка удаления прихода позволяет удалить документ из системы. Эта функция доступна только для документов в статусе черновика, чтобы защитить целостность учётных данных.\n\nЕсли документ уже проведён, система предложит сначала отменить проведение. После отмены проведения товары будут списаны со склада, и документ вернётся в статус черновика.\n\nУдаление требует подтверждения и логируется в системе. Рекомендуется использовать архивацию вместо удаления для сохранения истории операций.', uzDescription: 'Kirimni o\'chirish tugmasi hujjatni tizimdan o\'chirish imkonini beradi. Bu funksiya faqat qoralama holatidagi hujjatlar uchun mavjud, hisob ma\'lumotlari yaxlitligini himoya qilish uchun.\n\nAgar hujjat allaqachon o\'tkazilgan bo\'lsa, tizim avval o\'tkazishni bekor qilishni taklif qiladi. O\'tkazish bekor qilingandan so\'ng tovarlar ombordan yozib chiqariladi va hujjat qoralama holatiga qaytadi.\n\nO\'chirish tasdiqlashni talab qiladi va tizimda log qilinadi. Operatsiyalar tarixini saqlab qolish uchun o\'chirish o\'rniga arxivlashdan foydalanish tavsiya etiladi.' },

  { order: 29, ruDescription: 'Фильтр приходов по дате позволяет отобрать документы за определённый период. Это необходимо для анализа поставок за неделю, месяц, квартал или произвольный интервал.\n\nМожно выбрать один из предустановленных периодов: сегодня, вчера, текущая неделя, текущий месяц. Также доступен выбор произвольного диапазона дат для точного отбора.\n\nФильтрация по дате помогает найти нужный документ, если известен примерный период его создания. Это ускоряет работу с архивом документов.', uzDescription: 'Kirimlarni sana bo\'yicha filtr ma\'lum bir davr uchun hujjatlarni tanlash imkonini beradi. Bu hafta, oy, chorak yoki ixtiyoriy oraliq uchun yetkazib berishlarni tahlil qilish uchun zarur.\n\nOldindan o\'rnatilgan davrlardan birini tanlash mumkin: bugun, kecha, joriy hafta, joriy oy. Shuningdek aniq tanlash uchun ixtiyoriy sana oralig\'ini tanlash ham mavjud.\n\nSana bo\'yicha filtrlash, agar hujjat yaratilishining taxminiy davri ma\'lum bo\'lsa, kerakli hujjatni topishga yordam beradi. Bu hujjatlar arxivi bilan ishlashni tezlashtiradi.' },

  { order: 30, ruDescription: 'Фильтр приходов по поставщику показывает документы конкретного контрагента. Это удобно для анализа истории отношений с определённым поставщиком.\n\nПри выборе поставщика система отображает все документы поступления от него за выбранный период. Можно увидеть общую сумму поставок, частоту заказов и перечень полученных товаров.\n\nФильтр помогает оценить надёжность поставщика, отследить выполнение обязательств и подготовить данные для переговоров о ценах и условиях сотрудничества.', uzDescription: 'Kirimlarni yetkazib beruvchi bo\'yicha filtr aniq kontragent hujjatlarini ko\'rsatadi. Bu aniq yetkazib beruvchi bilan munosabatlar tarixini tahlil qilish uchun qulay.\n\nYetkazib beruvchi tanlanganda tizim tanlangan davr uchun undan kelgan barcha kelib tushish hujjatlarini ko\'rsatadi. Yetkazib berishlarning umumiy summasi, buyurtmalar chastotasi va olingan tovarlar ro\'yxatini ko\'rish mumkin.\n\nFiltr yetkazib beruvchining ishonchliligini baholash, majburiyatlarning bajarilishini kuzatish va narxlar va hamkorlik shartlari bo\'yicha muzokaralarga ma\'lumotlarni tayyorlashga yordam beradi.' },

  { order: 31, ruDescription: 'Функция копирования прихода создаёт новый документ на основе существующего. Это ускоряет оформление повторяющихся поставок от постоянных поставщиков.\n\nНовый документ наследует все данные исходного: поставщика, список товаров, цены. Нужно только скорректировать количество и дату, что занимает значительно меньше времени, чем создание с нуля.\n\nКопирование особенно полезно при регулярных поставках одинакового ассортимента. Это экономит время оператора и снижает вероятность ошибок при вводе данных.', uzDescription: 'Kirimni nusxalash funksiyasi mavjud asosida yangi hujjat yaratadi. Bu doimiy yetkazib beruvchilardan takroriy yetkazib berishlarni rasmiylashtirishni tezlashtiradi.\n\nYangi hujjat manbadagi barcha ma\'lumotlarni meros qilib oladi: yetkazib beruvchi, tovarlar ro\'yxati, narxlar. Faqat miqdor va sanani tuzatish kerak, bu noldan yaratishdan ancha kam vaqt oladi.\n\nNusxalash ayniqsa bir xil assortimentning muntazam yetkazib berilishida foydali. Bu operator vaqtini tejaydi va ma\'lumotlarni kiritishda xato ehtimolini kamaytiradi.' },

  { order: 32, ruDescription: 'Кнопка проведения прихода завершает оформление документа и зачисляет товары на склад. Это ключевое действие, которое делает документ активным в учёте.\n\nПри проведении система проверяет корректность заполнения всех обязательных полей и рассчитывает финансовые показатели документа. Если есть ошибки, система покажет их список для исправления.\n\nПосле успешного проведения товары появляются на остатках склада, создаётся задолженность перед поставщиком, и документ становится доступен для печати и анализа.', uzDescription: 'Kirimni o\'tkazish tugmasi hujjatni rasmiylashtirishni tugatadi va tovarlarni omborga qabul qiladi. Bu hujjatni hisobda faol qiluvchi asosiy harakat.\n\nO\'tkazishda tizim barcha majburiy maydonlarning to\'g\'ri to\'ldirilishini tekshiradi va hujjatning moliyaviy ko\'rsatkichlarini hisoblaydi. Agar xatolar bo\'lsa, tizim ularning ro\'yxatini tuzatish uchun ko\'rsatadi.\n\nMuvaffaqiyatli o\'tkazilgandan so\'ng tovarlar ombor qoldiqlarida paydo bo\'ladi, yetkazib beruvchi oldidagi qarz yaratiladi va hujjat chop etish va tahlil uchun mavjud bo\'ladi.' },

  { order: 33, ruDescription: 'Кнопка отмены проведения возвращает документ в статус черновика и отменяет все изменения, которые он внёс в учёт. Это используется для корректировки ошибочно проведённых документов.\n\nПри отмене проведения товары списываются со склада, а задолженность перед поставщиком аннулируется. Все связанные документы также должны быть отменены или скорректированы.\n\nОтмена проведения — это ответственное действие, которое должно выполняться только при наличии веских причин. Рекомендуется использовать корректировочные документы вместо отмены для сохранения истории.', uzDescription: 'O\'tkazishni bekor qilish tugmasi hujjatni qoralama holatiga qaytaradi va u hisobga kiritgan barcha o\'zgarishlarni bekor qiladi. Bu noto\'g\'ri o\'tkazilgan hujjatlarni tuzatish uchun ishlatiladi.\n\nO\'tkazish bekor qilinganda tovarlar ombordan yozib chiqariladi va yetkazib beruvchi oldidagi qarz bekor qilinadi. Barcha bog\'liq hujjatlar ham bekor qilinishi yoki tuzatilishi kerak.\n\nO\'tkazishni bekor qilish — bu faqat og\'ir sabablar bo\'lganda bajarilishi kerak bo\'lgan mas\'uliyatli harakat. Tarixni saqlab qolish uchun bekor qilish o\'rniga tuzatish hujjatlaridan foydalanish tavsiya etiladi.' },

  { order: 34, ruDescription: 'Расширения прихода позволяют добавить дополнительную информацию к документу, не предусмотренную стандартными полями. Это настраиваемые поля для специфических потребностей организации.\n\nМожно добавить комментарий с примечаниями к поставке, номер накладной поставщика, номер декларации при импорте и другие данные. Эти поля помогают идентифицировать документ и связать его с внешними системами.\n\nРасширения также могут использоваться для автоматизации: например, номер декларации может автоматически попадать в таможенные документы.', uzDescription: 'Kirim kengaytmalari hujjatga standart maydonlarda nazarda tutilmagan qo\'shimcha ma\'lumotlarni qo\'shish imkonini beradi. Bu tashkilotning o\'ziga xos ehtiyojlari uchun sozlanadigan maydonlardir.\n\nYetkazib berishga oid izohlar, yetkazib beruvchining nakladnaya raqami, importda deklaratsiya raqami va boshqa ma\'lumotlarni qo\'shish mumkin. Bu maydonlar hujjatni identifikatsiya qilishga va uni tashqi tizimlar bilan bog\'lashga yordam beradi.\n\nKengaytmalar avtomatlashtirish uchun ham ishlatilishi mumkin: masalan, deklaratsiya raqami avtomatik bojxona hujjatlariga tushishi mumkin.' },

  { order: 35, ruDescription: 'Иконка сканера штрих-кода активирует режим сканирования для быстрого добавления товаров в приход. Это значительно ускоряет приёмку товаров по сравнению с ручным вводом.\n\nПри сканировании система распознаёт товар по штрих-коду и автоматически добавляет его в документ. Если товара нет в базе, система предложит создать новую карточку товара.\n\nСканер также используется при инвентаризации и продаже товаров. Это универсальный инструмент для работы с товарами, который минимизирует ошибки ввода.', uzDescription: 'Shtrix-kod skaneri ikonkasi kirimga tovarlarni tez qo\'shish uchun skanerlash rejimini faollashtiradi. Bu qo\'lda kiritish bilan solishtirganda tovarlarni qabul qilishni ancha tezlashtiradi.\n\nSkanerlanganda tizim tovarni shtrix-kod bo\'yicha tan oladi va uni avtomatik hujjatga qo\'shadi. Agar tovar bazada bo\'lmasa, tizim yangi tovar kartochkasini yaratishni taklif qiladi.\n\nSkaner shuningdek inventarizatsiya va tovar sotishda ham ishlatiladi. Bu kiritish xatolarini minimallashtiruvchi tovarlar bilan ishlash uchun universal vosita.' },

  // === СКЛАД: ВОЗВРАТ ПРИХОДА (36-40) ===
  { order: 36, ruDescription: 'Раздел "Возврат прихода" предназначен для оформления возвратов товаров поставщикам. Это необходимо при обнаружении брака, пересортице или изменении условий сотрудничества.\n\nВ разделе отображается список документов возврата с указанием исходного прихода, поставщика, причины и суммы возврата. Каждый документ возврата связан с конкретным документом поступления.\n\nПравильное оформление возврата обеспечивает корректный учёт товаров и расчёты с поставщиками. Возвращённые товары списываются со склада, а задолженность перед поставщиком уменьшается.', uzDescription: '"Kirimni qaytarish" bo\'limi yetkazib beruvchilarga tovarlarni qaytarishni rasmiylashtirish uchun mo\'ljallangan. Bu brak topilganda, tartibsizlikda yoki hamkorlik shartlari o\'zgarganda zarur.\n\nBo\'limda asl kirim, yetkazib beruvchi, sabab va qaytarish summasi ko\'rsatilgan qaytarish hujjatlari ro\'yxati ko\'rsatiladi. Har bir qaytarish hujjati aniq kelib tushish hujjati bilan bog\'langan.\n\nQaytarishni to\'g\'ri rasmiylashtirish tovarlarning to\'g\'ri hisobini va yetkazib beruvchilar bilan hisob-kitoblarni ta\'minlaydi. Qaytarilgan tovarlar ombordan yozib chiqariladi va yetkazib beruvchi oldidagi qarz kamayadi.' },

  { order: 37, ruDescription: 'Кнопка создания возврата прихода открывает форму для оформления возврата товаров поставщику. Это первый шаг при необходимости вернуть полученный товар.\n\nВ форме нужно выбрать исходный документ прихода, товары для возврата и указать причину возврата. Система автоматически заполняет данные из выбранного прихода для упрощения оформления.\n\nПосле сохранения и проведения документа товары будут списаны со склада, а сумма возврата отразится в расчётах с поставщиком.', uzDescription: 'Kirim qaytarish yaratish tugmasi yetkazib beruvchiga tovarlarni qaytarishni rasmiylashtirish uchun formani ochadi. Bu olingan tovarni qaytarish zarurati tug\'ilganda birinchi qadam.\n\nFormada asl kirim hujjatini, qaytariladigan tovarlarni tanlash va qaytarish sababini ko\'rsatish kerak. Tizim rasmiylashtirishni soddalashtirish uchun tanlangan kirimdan ma\'lumotlarni avtomatik to\'ldiradi.\n\nHujjat saqlangan va o\'tkazilgandan so\'ng tovarlar ombordan yozib chiqariladi va qaytarish summasi yetkazib beruvchi bilan hisob-kitoblarda aks etadi.' },

  { order: 38, ruDescription: 'Выбор прихода для возврата позволяет указать исходный документ, из которого возвращаются товары. Это связывает возврат с конкретной поставкой для корректного учёта.\n\nПри выборе прихода система показывает список товаров из этого документа с указанием полученного количества. Можно выбрать товары для возврата и указать количество, которое нужно вернуть.\n\nСвязь с исходным приходом обеспечивает прослеживаемость товародвижения и помогает контролировать обоснованность возвратов.', uzDescription: 'Qaytarish uchun kirimni tanlash tovarlar qaytarilayotgan asl hujjatni ko\'rsatish imkonini beradi. Bu qaytarishni aniq yetkazib berish bilan bog\'lab to\'g\'ri hisobni ta\'minlaydi.\n\nKirim tanlanganda tizim ushbu hujjatdan olingan miqdor ko\'rsatilgan tovarlar ro\'yxatini ko\'rsatadi. Qaytarish uchun tovarlarni tanlash va qaytarilishi kerak bo\'lgan miqdorni ko\'rsatish mumkin.\n\nAsl kirim bilan bog\'liqlik tovar harakatini kuzatilishini ta\'minlaydi va qaytarishlarning asosli ekanligini nazorat qilishga yordam beradi.' },

  { order: 39, ruDescription: 'Поле причины возврата позволяет указать основания для возврата товара поставщику. Это важная информация для документооборота и анализа качества поставок.\n\nДоступные причины: брак, несоответствие качества, пересортица, истечение срока годности, нарушение условий договора. Выбор причины влияет на дальнейшие действия по документу.\n\nСтатистика причин возвратов помогает выявлять проблемных поставщиков и принимать решения об изменении условий сотрудничества или поиске альтернативных поставщиков.', uzDescription: 'Qaytarish sababi maydoni yetkazib beruvchiga tovarni qaytarish sabablarini ko\'rsatish imkonini beradi. Bu hujjat aylanishi va yetkazib berish sifatini tahlil qilish uchun muhim ma\'lumot.\n\nMavjud sabablar: brak, sifatga mos kelmaslik, tartibsizlik, yaroqlilik muddati tugash, shartnoma shartlarini buzish. Sabab tanlash hujjat bo\'yicha keyingi harakatlarga ta\'sir qiladi.\n\nQaytarish sabablari statistikasi muammoli yetkazib beruvchilarni aniqlashga va hamkorlik shartlarini o\'zgartirish yoki muqobil yetkazib beruvchilarni qidirish bo\'yicha qarorlar qabul qilishga yordam beradi.' },

  { order: 40, ruDescription: 'Функция печати возврата формирует печатную форму документа для передачи поставщику и хранения в архиве. Это обязательный элемент документооборота при возврате товаров.\n\nПечатная форма содержит информацию о возвращаемых товарах, причине возврата, реквизитах сторон. Документ должен быть подписан обеими сторонами для подтверждения факта возврата.\n\nЭлектронную версию документа можно отправить поставщику по электронной почте для предварительного согласования возврата.', uzDescription: 'Qaytarishni chop etish funksiyasi yetkazib beruvchiga uzatish va arxivda saqlash uchun hujjatning bosma shaklini yaratadi. Bu tovarlarni qaytarishda hujjat aylanishining majburiy elementi.\n\nBosma shakl qaytarilayotgan tovarlar, qaytarish sababi, tomonlarning rekvizitlari haqida ma\'lumotni o\'z ichiga oladi. Hujjat qaytarish faktini tasdiqlash uchun ikkala tomon tomonidan imzolanishi kerak.\n\nHujjatning elektron versiyasini qaytarishni oldindan kelishish uchun yetkazib beruvchiga elektron pochta orqali yuborish mumkin.' },
];

async function main() {
  console.log('Updating lessons with detailed descriptions (1-40)...');

  for (const lesson of detailedLessons) {
    await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
      },
    });
    console.log(`Updated lesson ${lesson.order}`);
  }

  console.log('Done! Run the second script for lessons 41-200.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
