// Update lessons 1-40 with expanded descriptions and functionality (3+ sentences each)
// Run: npx tsx scripts/update-lessons-1-40.ts

import { config } from 'dotenv';
config({ path: '.env' });

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const lessonsData = [
  // === ГЛАВНАЯ (1-5) ===
  { 
    order: 1, 
    ruDescription: 'Главная страница системы Lume Admin является центральной точкой доступа ко всем функциям и возможностям программы. Здесь пользователь видит актуальную информацию о состоянии бизнеса, включая статистику продаж, остатки на складах и важные уведомления. Интерфейс главной страницы интуитивно понятен и позволяет быстро ориентироваться в системе.\n\nДашборд главной страницы содержит виджеты с ключевыми показателями эффективности: выручка за день, количество продаж, средний чек и другие метрики. Эти данные обновляются в реальном времени, что позволяет оперативно реагировать на изменения в работе.\n\nС главной страницы также доступен быстрый переход к часто используемым функциям: создание чека, добавление товара, просмотр отчётов. Это значительно ускоряет работу и повышает эффективность сотрудников.',
    uzDescription: 'Lume Admin tizimining bosh sahifasi dasturning barcha funksiyalari va imkoniyatlariga markaziy kirish nuqtasidir. Bu yerda foydalanuvchi biznes holati haqida dolzarb ma\'lumotlarni ko\'radi, shu jumladan sotuv statistikasi, omborlardagi qoldiqlar va muhim bildirishnomalar. Bosh sahifa interfeysi intuitiv tushunarli bo\'lib, tizimda tez yo\'nalinga imkon beradi.\n\nBosh sahifa dashbordi samaradorlikning asosiy ko\'rsatkichlari bilan vidjetlarni o\'z ichiga oladi: kunlik tushum, sotuvlar soni, o\'rtacha chek va boshqa ko\'rsatkichlar. Bu ma\'lumotlar real vaqtda yangilanib, ish jarayonidagi o\'zgarishlarga o\'z vaqtida munosabat bildirishga imkon beradi.\n\nBosh sahifadan shuningdek tez-tez ishlatiladigan funksiyalarga tez o\'tish mumkin: chek yaratish, tovar qo\'shish, hisobotlarni ko\'rish. Bu ishni sezilarli darajada tezlashtiradi va xodimlarning samaradorligini oshiradi.',
    ruFunctionality: 'Главная страница открывает дашборд с быстрым доступом к основным разделам системы, включая склад, продажи, отчёты и настройки. При клике на виджеты происходит переход к соответствующим разделам с предустановленными фильтрами. Система автоматически обновляет данные каждые несколько минут или при совершении операций другими пользователями.',
    uzFunctionality: 'Bosh sahifa ombor, sotuvlar, hisobotlar va sozlamalar kabi asosiy bo\'limlarga tez kirish bilan dashbordni ochadi. Vidjetlarga bosilganda oldindan o\'rnatilgan filtrlar bilan mos bo\'limlarga o\'tish amalga oshiriladi. Tizim ma\'lumotlarni har bir necha daqiqada avtomatik yangilaydi yoki boshqa foydalanuvchilar operatsiyalar bajarlganda.'
  },

  { 
    order: 2, 
    ruDescription: 'Баланс счёта отображается в верхней части интерфейса и показывает текущее состояние расчётного счёта организации. Это ключевой показатель, который позволяет оперативно контролировать финансовое состояние компании и планировать расходы.\n\nПри клике на баланс открывается детальная информация о движении средств: входящие и исходящие платежи, даты операций и контрагенты. Это позволяет быстро найти нужную операцию и проверить её корректность.\n\nБаланс обновляется автоматически при проведении финансовых операций: оплата от покупателя увеличивает баланс, а оплата поставщику — уменьшает. Система также учитывает курсовые разницы при работе с валютными счетами.',
    uzDescription: 'Hisob balansi interfeysning yuqori qismida ko\'rsatiladi va tashkilotning hisob-raqamining joriy holatini aks ettiradi. Bu kompaniyaning moliyaviy holatini operativ nazorat qilish va xarajatlarni rejalashtirishga imkon beruvchi asosiy ko\'rsatkichdir.\n\nBalans bosilganda mablag\'lar harakati haqida batafsil ma\'lumot ochiladi: kiruvchi va chiquvchi to\'lovlar, operatsiyalar sanalari va kontragentlar. Bu kerakli operatsiyani tez topish va uning to\'g\'riligini tekshirish imkonini beradi.\n\nBalans moliyaviy operatsiyalar o\'tkazilganda avtomatik yangilanadi: xaridordan to\'lov balansni oshiradi, yetkazib beruvchiga to\'lov esa kamaytiradi. Tizim shuningdek valyutaviy hisoblar bilan ishlashda valyuta farqlarini hisobga oladi.',
    ruFunctionality: 'Показывает баланс в верхней части меню в формате числа с разделителями разрядов и символом валюты. При клике на баланс открывается модальное окно с детализацией: последние операции, прогноз поступлений и расходов, а также кнопка быстрого пополнения. Баланс синхронизируется с банковскими выписками при подключенной интеграции.',
    uzFunctionality: 'Balansni menyu yuqori qismida raqamlar ajratuvchilari va valyuta belgisi bilan ko\'rsatadi. Balans bosilganda tafsilotlar bilan modallik oyna ochiladi: oxirgi operatsiyalar, tushumlar va xarajatlar prognozi, shuningdek tez to\'ldirish tugmasi. Balans integratsiya ulanganda bank ko\'chirmalari bilan sinxronlashtiriladi.'
  },

  { 
    order: 3, 
    ruDescription: 'Кнопка пополнения баланса находится в верхней панели и предоставляет быстрый доступ к функционалу пополнения расчётного счёта. Это важная функция для поддержания достаточного уровня средств на счету для бесперебойной работы бизнеса.\n\nПри нажатии открывается форма выбора способа пополнения: банковский перевод, платёжная карта или электронный кошелёк. Система поддерживает интеграцию с большинством популярных платёжных систем и банков.\n\nПосле выбора способа система формирует платёжное поручение или переводит на страницу платёжного шлюза. Все операции пополнения сохраняются в истории с указанием даты, времени и способа оплаты.',
    uzDescription: 'Balansni to\'ldirish tugmasi yuqori panelda joylashgan bo\'lib, hisob-raqamni to\'ldirish funktsiyasiga tez kirishni ta\'minlaydi. Bu biznesning uzluksiz ishlashi uchun hisobda yetarli mablag\' darajasini saqlab qolish uchun muhim funksiya.\n\nBosilganda to\'ldirish usulini tanlash formasi ochiladi: bank o\'tkazmasi, to\'lov kartasi yoki elektron hamyon. Tizim ko\'pchilik mashhur to\'lov tizimlari va banklar bilan integratsiyani qo\'llab-quvvatlaydi.\n\nUsul tanlangandan so\'ng tizim to\'lov topshiriqlarini shakllantiradi yoki to\'lov shlyuzi sahifasiga o\'tkazadi. Barcha to\'ldirish operatsiyalari sana, vaqt va to\'lov usuli ko\'rsatilgan holda tarixda saqlanadi.',
    ruFunctionality: 'Открывает форму пополнения баланса через платёжные системы с выбором способа оплаты: банковская карта, мобильный банкинг или терминал. Система генерирует уникальный код платежа для отслеживания статуса зачисления. После успешной оплаты баланс обновляется автоматически в течение нескольких минут.',
    uzFunctionality: 'To\'lov usulini tanlash bilan to\'lov tizimlari orqali balansni to\'ldirish formasini ochadi: bank kartasi, mobil banking yoki terminal. Tizim to\'lov holatini kuzatish uchun noyob to\'lov kodini yaratadi. Muvaffaqiyatli to\'lovdan so\'ng balans bir necha daqiqa ichida avtomatik yangilanadi.'
  },

  { 
    order: 4, 
    ruDescription: 'Профиль пользователя содержит персональные данные сотрудника и настройки его работы в системе. Это центральное место для управления личной информацией, паролем и предпочтениями интерфейса.\n\nВ профиле можно изменить пароль, настроить уведомления, выбрать язык интерфейса и тему оформления. Каждый пользователь может адаптировать систему под свои потребности и привычный стиль работы.\n\nДля администраторов профиль также показывает информацию о правах доступа и роли пользователя. Это помогает контролировать безопасность системы и при необходимости корректировать уровень доступа сотрудника.',
    uzDescription: 'Foydalanuvchi profili xodimning shaxsiy ma\'lumotlarini va tizimdagi ish sozlamalarini o\'z ichiga oladi. Bu shaxsiy ma\'lumotlar, parol va interfeys afzalliklarini boshqarish uchun markaziy joy hisoblanadi.\n\nProfil ichida parolni o\'zgartirish, bildirishnomalarni sozlash, interfeys tilini va mavzuni tanlash mumkin. Har bir foydalanuvchi tizimni o\'z ehtiyojlariga va o\'rganish uslubiga moslashtirishi mumkin.\n\nAdministratorlar uchun profil shuningdek foydalanuvchi huquqlari va roli haqida ma\'lumotni ko\'rsatadi. Bu tizim xavfsizligini nazorat qilishga va zarurat bo\'lganda xodimning kirish darajasini tuzatishga yordam beradi.',
    ruFunctionality: 'При клике на имя пользователя открывается выпадающее меню с быстрыми действиями: профиль, настройки, выход. В профиле можно редактировать личные данные, сменить пароль, настроить двухфакторную аутентификацию. Администраторы могут просматривать историю входов пользователя и активных сессий.',
    uzFunctionality: 'Foydalanuvchi ismi bosilganda tezkor harakatlar bilan ochiladigan menyu ochiladi: profil, sozlamalar, chiqish. Profilda shaxsiy ma\'lumotlarni tahrirlash, parolni o\'zgartirish, ikki faktorli autentifikatsiyani sozlash mumkin. Administratorlar foydalanuvchi kirish tarixini va faol sessiyalarni ko\'rishlari mumkin.'
  },

  { 
    order: 5, 
    ruDescription: 'Кнопка выхода из системы обеспечивает безопасное завершение работы с программой. Это важный элемент безопасности, который предотвращает несанкционированный доступ к системе в отсутствие пользователя.\n\nПри нажатии на кнопку система запрашивает подтверждение выхода, чтобы исключить случайное действие. После подтверждения сессия завершается, и все несохранённые данные могут быть потеряны.\n\nРекомендуется всегда использовать кнопку выхода при завершении работы, особенно на общих или публичных компьютерах. Это гарантирует сохранность коммерческой информации и персональных данных.',
    uzDescription: 'Tizimdan chiqish tugmasi dastur bilan ishlashni xavfsiz tugatishni ta\'minlaydi. Bu foydalanuvchi yo\'qligida tizimga ruxsatsiz kirishning oldini oluvchi muhim xavfsizlik elementidir.\n\nTugma bosilganda tizim chiqishni tasdiqlashni so\'raydi, bu tasodifiy harakatni istisno qiladi. Tasdiqlangandan so\'ng sessiya tugatiladi va barcha saqlanmagan ma\'lumotlar yo\'qolishi mumkin.\n\nIsh tugatilganda, ayniqsa umumiy yoki ommaviy kompyuterlarda chiqish tugmasidan foydalanish tavsiya etiladi. Bu tijorat ma\'lumotlari va shaxsiy ma\'lumotlarning xavfsizligini kafolatlaydi.',
    ruFunctionality: 'Завершает активную сессию пользователя и очищает все временные данные из памяти браузера. После выхода происходит автоматическое перенаправление на страницу авторизации. Система также деактивирует все токены доступа для предотвращения повторного использования.',
    uzFunctionality: 'Foydalanuvchining faol sessiyasini tugatadi va brauzer xotirasidan barcha vaqtinchalik ma\'lumotlarni tozalaydi. Chiqqandan so\'ng avtomatik ravishda avtorizatsiya sahifasiga qayta yo\'naltiriladi. Tizim shuningdek qayta foydalanishning oldini olish uchun barcha kirish tokenlarini o\'chiradi.'
  },

  // === СКЛАД: ТОВАРЫ (6-20) ===
  { 
    order: 6, 
    ruDescription: 'Раздел "Товары" является основой складского учёта и содержит полный список всех товаров организации. Здесь хранится информация о наименованиях, ценах, остатках, единицах измерения и других характеристиках продукции.\n\nИнтерфейс раздела включает таблицу с возможностью сортировки и фильтрации по различным параметрам: категория, бренд, склад, наличие. Поиск работает по названию, артикулу и штрих-коду, что позволяет мгновенно находить нужную позицию.\n\nВ этом разделе можно выполнять все основные операции с товарами: добавление новых позиций, редактирование существующих, удаление неактуальных товаров. Также доступны функции массового редактирования и экспорта данных.',
    uzDescription: '"Tovarlar" bo\'limi ombor hisobining asosi hisoblanadi va tashkilotning barcha tovarlari ro\'yxatini o\'z ichiga oladi. Bu yerda nomlar, narxlar, qoldiqlar, o\'lchov birliklari va mahsulotning boshqa xususiyatlari haqida ma\'lumotlar saqlanadi.\n\nBo\'lim interfeysi turli parametrlar bo\'yicha saralash va filtrlash imkoniyati bilan jadvalni o\'z ichiga oladi: kategoriya, brend, ombor, mavjudlik. Qidiruv nom, artikul va shtrix-kod bo\'yicha ishlaydi, bu kerakli pozitsiyani bir zumda topishga imkon beradi.\n\nBu bo\'limda tovarlar bilan barcha asosiy operatsiyalarni bajarish mumkin: yangi pozitsiyalar qo\'shish, mavjudlarni tahrirlash, dolzarb bo\'lmagan tovarlarni o\'chirish. Shuningdek ommaviy tahrirlash va ma\'lumotlarni eksport qilish funksiyalari mavjud.',
    ruFunctionality: 'Открывает список всех товаров с поиском и фильтрами по категориям, брендам, складам и наличию. Товары можно сортировать по цене, названию, остаткам или дате создания. Для каждого товара отображается наименование, артикул, штрих-код, цена и текущий остаток на выбранном складе.',
    uzFunctionality: 'Kategoriyalar, brendlar, omborlar va mavjudlik bo\'yicha qidiruv va filtrlar bilan barcha tovarlar ro\'yxatini ochadi. Tovarlarni narx, nom, qoldiq yoki yaratilish sanasi bo\'yicha saralash mumkin. Har bir tovar uchun nom, artikul, shtrix-kod, narx va tanlangan ombordagi joriy qoldiq ko\'rsatiladi.'
  },

  { 
    order: 7, 
    ruDescription: 'Кнопка добавления товара открывает форму создания новой позиции в справочнике товаров. Это первый шаг при появлении нового товара в ассортименте организации.\n\nФорма содержит все необходимые поля: наименование на разных языках, артикул, штрих-код, категорию, единицу измерения, цены закупки и продажи. Обязательные поля отмечены специальным образом, и система не позволит сохранить товар без их заполнения.\n\nПосле заполнения формы и сохранения товар появляется в общем списке и становится доступен для всех складских операций: прихода, реализации, инвентаризации. Можно также загрузить изображение товара для удобства идентификации.',
    uzDescription: 'Tovar qo\'shish tugmasi tovarlar ma\'lumotnomasida yangi pozitsiya yaratish formasini ochadi. Bu tashkilot assortimentida yangi tovar paydo bo\'lganda birinchi qadam hisoblanadi.\n\nForma barcha kerakli maydonlarni o\'z ichiga oladi: turli tillarda nom, artikul, shtrix-kod, kategoriya, o\'lchov birligi, xarid va sotuv narxlari. Majburiy maydonlar maxsus belgi bilan belgilanadi va tizim ularsiz tovarni saqlashga yo\'l qo\'ymaydi.\n\nForma to\'ldirilib saqlangandan so\'ng, tovar umumiy ro\'yxatda paydo bo\'ladi va barcha ombor operatsiyalari uchun mavjud bo\'ladi: kirim, realizatsiya, inventarizatsiya. Tovarni identifikatsiya qilish qulayligi uchun uning tasvirini yuklash ham mumkin.',
    ruFunctionality: 'Открывает форму для добавления нового товара в базу с полями: наименование, артикул, штрих-код, категория, единица измерения, цена закупки и продажи. Система автоматически генерирует артикул и штрих-код если они не указаны вручную. После сохранения товар становится доступен для всех складских операций.',
    uzFunctionality: 'Nom, artikul, shtrix-kod, kategoriya, o\'lchov birligi, xarid va sotuv narxlari maydonlari bilan bazaga yangi tovar qo\'shish uchun formani ochadi. Tizim qo\'lda ko\'rsatilmagan bo\'lsa artikul va shtrix-kodni avtomatik yaratadi. Saqlangandan so\'ng tovar barcha ombor operatsiyalari uchun mavjud bo\'ladi.'
  },

  { 
    order: 8, 
    ruDescription: 'Поле поиска товаров позволяет быстро найти нужную позицию в базе данных без необходимости пролистывать весь список. Это значительно ускоряет работу, особенно при большом ассортименте.\n\nПоиск работает в реальном времени: результаты появляются уже при вводе первых символов. Система ищет по названию товара, артикулу, штрих-коду и другим идентификаторам. Результаты сортируются по релевантности.\n\nДля более точного поиска можно использовать специальные операторы: кавычки для точного совпадения фразы, минус для исключения слов. Это помогает найти товар даже при неполном знании его названия.',
    uzDescription: 'Tovarlarni qidirish maydoni butun ro\'yxatni aylantirish zaruriyatisiz bazadan kerakli pozitsiyani tez topish imkonini beradi. Bu ishni sezilarli darajada tezlashtiradi, ayniqsa katta assortimentda.\n\nQidiruv real vaqtda ishlaydi: natijalar birinchi belgilarni kiritishda paydo bo\'ladi. Tizim tovar nomi, artikul, shtrix-kod va boshqa identifikatorlar bo\'yicha qidiradi. Natijalar dolzarblik bo\'yicha saralanadi.\n\nAniqroq qidirish uchun maxsus operatorlardan foydalanish mumkin: iboraning to\'liq mos kelishi uchun tirnoqlar, so\'zlarni istisno qilish uchun minus. Bu tovar nomini to\'liq bilmasa ham topishga yordam beradi.',
    ruFunctionality: 'Позволяет искать товары по названию, артикулу или штрих-коду с мгновенным отображением результатов. Поиск поддерживает нечёткое совпадение и коррекцию опечаток для более точного нахождения. Результаты обновляются в реальном времени при каждом введённом символе.',
    uzFunctionality: 'Natijalarni bir zumda ko\'rsatish bilan nom, artikul yoki shtrix-kod bo\'yicha tovarlarni qidirish imkonini beradi. Qidiruv aniqroq topish uchun noaniq moslik va xatolarni tuzatishni qo\'llab-quvvatlaydi. Natijalar har bir kiritilgan belgida real vaqtda yangilanadi.'
  },

  { 
    order: 9, 
    ruDescription: 'Фильтр по категории позволяет ограничить список товаров определённой группой, что упрощает работу с ассортиментом. Категории образуют иерархическую структуру, отражающую логику организации товаров.\n\nПри выборе категории система показывает только товары, относящиеся к ней и её подкатегориям. Это особенно полезно при работе с большими справочниками, когда нужно сосредоточиться на конкретной группе продукции.\n\nФильтр можно комбинировать с другими фильтрами и поиском для максимально точного отбора товаров. Также доступен множественный выбор категорий для одновременного просмотра нескольких групп.',
    uzDescription: 'Kategoriya bo\'yicha filtr tovarlar ro\'yxatini ma\'lum guruh bilan cheklash imkonini beradi, bu assortiment bilan ishlashni soddalashtiradi. Kategoriyalar tovarlarning mantiqiy tuzilishini aks ettiruvchi ierarxik tuzilmani hosil qiladi.\n\nKategoriya tanlanganda tizim faqat unga va uning ost-kategoriyalariga tegishli tovarlarni ko\'rsatadi. Bu katta ma\'lumotnomalar bilan ishlashda, aniq mahsulot guruhi ustida ishlash kerak bo\'lganda ayniqsa foydali.\n\nFiltrni boshqa filtrlar va qidiruv bilan birlashtirish mumkin, tovarlarni maksimal aniq tanlash uchun. Shuningdek bir vaqtning o\'zida bir nechta kategoriyani ko\'rish uchun ko\'p tanlov ham mavjud.',
    ruFunctionality: 'Позволяет отфильтровать список товаров по выбранной категории с учётом всех подкатегорий. Фильтр поддерживает множественный выбор категорий для одновременного отображения нескольких групп товаров. Выбранная категория сохраняется в настройках пользователя для следующих сессий.',
    uzFunctionality: 'Barcha ost-kategoriyalarni hisobga olgan holda tanlangan kategoriya bo\'yicha tovarlar ro\'yxatini filtrlash imkonini beradi. Filtr bir vaqtning o\'zida bir nechta tovar guruhlarini ko\'rsatish uchun ko\'p tanlovni qo\'llab-quvvatlaydi. Tanlangan kategoriya keyingi sessiyalar uchun foydalanuvchi sozlamalarida saqlanadi.'
  },

  { 
    order: 10, 
    ruDescription: 'Фильтр по складу показывает остатки товаров на конкретном складе или торговой точке. Это необходимо при работе в многозвенной сети для контроля запасов по местоположению.\n\nПри выборе склада система отображает только те товары, которые есть в наличии на этом объекте. Также показывается актуальное количество и статус наличия. Это помогает избежать ситуаций, когда товар заказывается с отсутствующего склада.\n\nФильтр особенно полезен для менеджеров складов, которые контролируют только свой объект. Можно настроить фильтр по умолчанию, чтобы при входе в раздел сразу видеть товары своего склада.',
    uzDescription: 'Ombor bo\'yicha filtr aniq ombor yoki savdo nuqtasidagi tovar qoldiqlarini ko\'rsatadi. Bu ko\'p bo\'g\'inli tarmoqda joylashuv bo\'yicha zaxiralarni nazorat qilish uchun zarur.\n\nOmbor tanlanganda tizim faqat ushbu ob\'ektda mavjud bo\'lgan tovarlarni ko\'rsatadi. Shuningdek dolzarb miqdor va mavjudlik holati ko\'rsatiladi. Bu tovar mavjud bo\'lmagan ombordan buyurtma qilinish holatlarining oldini oladi.\n\nFiltr ayniqsa faqat o\'z ob\'ektini nazorat qiluvchi ombor menejerlari uchun foydali. Kirish vaqtida o\'z omborining tovarlarini darhol ko\'rish uchun filtrni standart qilib sozlash mumkin.',
    ruFunctionality: 'Показывает товары конкретного склада или торговой точки с указанием точного количества и минимального остатка. При переключении склада автоматически обновляются все остатки и цены для выбранного объекта. Фильтр запоминает последний выбранный склад для текущего пользователя.',
    uzFunctionality: 'Aniq miqdor va minimal qoldiq ko\'rsatilgan holda ma\'lum ombor yoki savdo nuqtasining tovarlarini ko\'rsatadi. Ombor almashtirilganda tanlangan ob\'ekt uchun barcha qoldiqlar va narxlar avtomatik yangilanadi. Filtr joriy foydalanuvchi uchun oxirgi tanlangan omborni eslab qoladi.'
  },

  { 
    order: 11, 
    ruDescription: 'Кнопка редактирования товара открывает форму изменения параметров существующей позиции. Это позволяет актуализировать информацию о товаре при изменении условий работы.\n\nВ форме редактирования доступны все те же поля, что и при создании товара. Можно изменить наименование, цены, категорию, описание и другие характеристики. История изменений сохраняется, что позволяет отследить, кто и когда вносил корректировки.\n\nПри редактировании цен система может предложить обновить цены в связанных документах или пересчитать себестоимость. Это помогает поддерживать актуальность учётных данных.',
    uzDescription: 'Tovarni tahrirlash tugmasi mavjud pozitsiya parametrlarini o\'zgartirish formasini ochadi. Bu ish sharoitlari o\'zgarganda tovar haqidagi ma\'lumotlarni dolzarblashtirish imkonini beradi.\n\nTahrirlash formasida tovar yaratishdagidek barcha maydonlar mavjud. Nom, narxlar, kategoriya, tavsif va boshqa xususiyatlarni o\'zgartirish mumkin. O\'zgarishlar tarixi saqlanib qoladi, bu kim va qachon tuzatishlar kiritganini kuzatish imkonini beradi.\n\nNarlarni tahrirlashda tizim bog\'liq hujjatlarda narxlarni yangilashni yoki tannarxni qayta hisoblashni taklif qilishi mumkin. Bu hisob ma\'lumotlarining dolzarbligini saqlashga yordam beradi.',
    ruFunctionality: 'Открывает форму редактирования выбранного товара с возможностью изменения всех параметров: название, цены, категория, описание, изображение. Все изменения сохраняются в истории с указанием автора и времени редактирования. Система проверяет уникальность артикула и штрих-кода перед сохранением.',
    uzFunctionality: 'Barcha parametrlarni o\'zgartirish imkoniyati bilan tanlangan tovarni tahrirlash formasini ochadi: nom, narxlar, kategoriya, tavsif, tasvir. Barcha o\'zgarishlar muallif va tahrirlash vaqti ko\'rsatilgan holda tarixda saqlanadi. Tizim saqlashdan oldin artikul va shtrix-kod noyobligini tekshiradi.'
  },

  { 
    order: 12, 
    ruDescription: 'Кнопка удаления товара удаляет позицию из справочника товаров. Это действие требует подтверждения и имеет ограничения для защиты целостности данных.\n\nУдалить можно только тот товар, по которому нет движений в учёте. Если товар участвовал в приходах, реализациях или других операциях, система предложит пометить его как неактивный вместо удаления. Это позволяет сохранить историю операций.\n\nПеред удалением система показывает предупреждение о невозможности восстановления данных. Рекомендуется использовать эту функцию только для позиций, созданных по ошибке.',
    uzDescription: 'Tovarni o\'chirish tugmasi pozitsiyani tovarlar ma\'lumotnomasidan o\'chiradi. Bu harakat tasdiqlashni talab qiladi va ma\'lumotlar yaxlitligini himoya qilish uchun cheklovlarga ega.\n\nFaqat hisobda harakati bo\'lmagan tovarni o\'chirish mumkin. Agar tovar kirim, realizatsiya yoki boshqa operatsiyalarda qatnashgan bo\'lsa, tizim o\'chirish o\'rniga uni nofaol deb belgilashni taklif qiladi. Bu operatsiyalar tarixini saqlab qolish imkonini beradi.\n\nO\'chirishdan oldin tizim ma\'lumotlarni qayta tiklab bo\'lmasligi haqida ogohlantirish ko\'rsatadi. Bu funksiyadan faqat xato yaratilgan pozitsiyalar uchun foydalanish tavsiya etiladi.',
    ruFunctionality: 'Удаляет выбранный товар из базы после подтверждения, если по нему нет учётных движений. Для товаров с историей операций система предлагает архивирование вместо полного удаления. Операция удаления необратима и записывается в журнал действий пользователя.',
    uzFunctionality: 'Agar hisob harakatlari bo\'lmasa, tasdiqlangandan so\'ng tanlangan tovarni bazadan o\'chiradi. Operatsiyalar tarixi bo\'lgan tovarlar uchun tizim to\'liq o\'chirish o\'rniga arxivlashni taklif qiladi. O\'chirish operatsiyasi qaytarib bo\'lmaydi va foydalanuvchi harakatlari jurnaliga yoziladi.'
  },

  { 
    order: 13, 
    ruDescription: 'Функция экспорта товаров позволяет выгрузить список товаров в файл для работы во внешних программах или передачи контрагентам. Это востребованная функция для прайс-листов и инвентаризации.\n\nЭкспорт доступен в форматах Excel и CSV. При выгрузке можно выбрать конкретные колонки для экспорта, чтобы получить только нужную информацию. Также можно применить фильтры перед экспортом и выгрузить только отобранные товары.\n\nПолученный файл можно использовать для печати прайс-листа, загрузки на маркетплейсы или анализа в Excel. Это удобный способ обмена данными с внешними системами.',
    uzDescription: 'Tovarlarni eksport funksiyasi tovarlar ro\'yxatini tashqi dasturlarda ishlash yoki kontragentlarga uzatish uchun faylga yuklash imkonini beradi. Bu narx-listlar va inventarizatsiya uchun talab qilinadigan funksiya.\n\nEksport Excel va CSV formatlarida mavjud. Yuklashda faqat kerakli ma\'lumotni olish uchun eksport qilinadigan aniq ustunlarni tanlash mumkin. Shuningdek eksport oldidan filtrlarni qo\'llash va faqat tanlangan tovarlarni yuklash mumkin.\n\nOlingan faylni narx-listni chop etish, marketpleyslarga yuklash yoki Excel da tahlil qilish uchun ishlatish mumkin. Bu tashqi tizimlar bilan ma\'lumotlar almashinuvining qulay usuli.',
    ruFunctionality: 'Позволяет выгрузить список товаров в Excel или CSV с выбором колонок и применением текущих фильтров. Экспорт поддерживает до 100 000 товаров за одну операцию с сохранением форматирования. Файл автоматически скачивается в папку загрузок браузера.',
    uzFunctionality: 'Ustunlarni tanlash va joriy filtrlarni qo\'llash bilan tovarlar ro\'yxatini Excel yoki CSV ga yuklash imkonini beradi. Eksport bir operatsiyada formatni saqlab 100 000 gacha tovarlarni qo\'llab-quvvatlaydi. Fayl avtomatik ravishda brauzerni yuklab olish jildiga yuklanadi.'
  },

  { 
    order: 14, 
    ruDescription: 'Карточка товара содержит полную информацию о конкретной позиции: описание, характеристики, цены, остатки по складам и историю движения. Это детальное представление товара в системе.\n\nВ карточке товара можно увидеть текущие остатки на каждом складе, историю изменения цен, последние операции поступления и реализации. Эта информация помогает принимать решения о закупках и ценообразовании.\n\nИз карточки товара также доступны быстрые действия: создать приход, реализацию, напечатать ценник или штрих-код. Это ускоряет работу операторов складского учёта.',
    uzDescription: 'Tovar kartochkasi aniq pozitsiya haqida to\'liq ma\'lumotni o\'z ichiga oladi: tavsif, xususiyatlar, narxlar, omborlar bo\'yicha qoldiqlar va harakat tarixi. Bu tizimdagi tovarning batafsil ko\'rinishi.\n\nTovar kartochkasida har bir ombordagi joriy qoldiqlarni, narx o\'zgarishlari tarixini, oxirgi kirim va realizatsiya operatsiyalarini ko\'rish mumkin. Bu ma\'lumotlar xaridlar va narx belgilash bo\'yicha qarorlar qabul qilishga yordam beradi.\n\nTovar kartochkasidan shuningdek tezkor harakatlar mavjud: kirim, realizatsiya yaratish, narx yorlig\'i yoki shtrix-kod chop etish. Bu ombor hisobi operatorlarining ishini tezlashtiradi.',
    ruFunctionality: 'Показывает полную информацию о товаре: остатки, цены, движение, история изменений. В карточке доступны вкладки с разными разделами: основное, склады, цены, история, документы. Можно быстро перейти к редактированию товара или создать документ с этим товаром.',
    uzFunctionality: 'Tovar haqida to\'liq ma\'lumotni ko\'rsatadi: qoldiqlar, narxlar, harakat, o\'zgarishlar tarixi. Kartochkada turli bo\'limlar bilan varaqlar mavjud: asosiy, omborlar, narxlar, tarix, hujjatlar. Tovarni tahrirlashga tez o\'tish yoki bu tovar bilan hujjat yaratish mumkin.'
  },

  { 
    order: 15, 
    ruDescription: 'Функция добавления в избранное позволяет сохранить товар в персональном списке для быстрого доступа. Это удобно для товаров, которые часто используются в работе.\n\nИзбранные товары отображаются в отдельном разделе и на видном месте интерфейса. При создании чека или документа можно быстро добавить товар из избранного, не прибегая к поиску.\n\nСписок избранного индивидуален для каждого пользователя, что позволяет каждому сотруднику настроить быстрый доступ под свои потребности. Товар можно добавить или убрать из избранного одним кликом.',
    uzDescription: 'Sevimlilarga qo\'shish funksiyasi tovarni tez kirish uchun shaxsiy ro\'yxatda saqlash imkonini beradi. Bu ishda tez-tez ishlatiladigan tovarlar uchun qulay.\n\nSevimli tovarlar alohida bo\'limda va interfeysning ko\'zga tashlanadigan joyida ko\'rsatiladi. Chek yoki hujjat yaratishda qidirishga murojaat qilmasdan sevimlilardan tovarni tez qo\'shish mumkin.\n\nSevimlilar ro\'yxati har bir foydalanuvchi uchun individual bo\'lib, har bir xodimga o\'z ehtiyojlariga ko\'ra tez kirishni sozlash imkonini beradi. Tovarni bir marta bosish bilan sevimlilarga qo\'shish yoki olib tashlash mumkin.',
    ruFunctionality: 'Сохраняет товар в списке избранных для быстрого доступа из боковой панели или при создании документов. Список избранного синхронизируется между устройствами и сохраняется в профиле пользователя. Товар можно добавить в избранное кликом на иконку звезды в карточке или списке.',
    uzFunctionality: 'Tovarni yon paneldan yoki hujjatlar yaratishda tez kirish uchun sevimlilar ro\'yxatida saqlaydi. Sevimlilar ro\'yxati qurilmalar o\'rtasida sinxronlashtiriladi va foydalanuvchi profilida saqlanadi. Tovarni kartochka yoki ro\'yxatda yulduzcha ikonkasiga bosish orqali sevimlilarga qo\'shish mumkin.'
  },

  { 
    order: 16, 
    ruDescription: 'Массовое редактирование позволяет изменить параметры сразу для нескольких товаров за одну операцию. Это экономит время при необходимости обновить цены, категорию или другие атрибуты для группы товаров.\n\nДля массового редактирования нужно отметить товары с помощью чекбоксов и выбрать действие из меню. Доступные действия: изменение цены, перенос в категорию, изменение единицы измерения, установка статуса.\n\nСистема показывает превью изменений перед применением, чтобы избежать ошибок. После подтверждения все выбранные товары обновляются одновременно, и изменения отражаются в истории.',
    uzDescription: 'Ommaviy tahrirlash bir operatsiyada bir nechta tovar parametrlarini o\'zgartirish imkonini beradi. Bu tovarlar guruhi uchun narxlarni, kategoriyani yoki boshqa atributlarni yangilash kerak bo\'lganda vaqtni tejaydi.\n\nOmmaviy tahrirlash uchun tovarlarni checkbox lar yordamida belgilash va menyu dan harakatni tanlash kerak. Mavjud harakatlar: narxni o\'zgartirish, kategoriyaga ko\'chirish, o\'lchov birligini o\'zgartirish, holatni o\'rnatish.\n\nTizim xatolardan qochish uchun qo\'llashdan oldin o\'zgarishlarning oldindan ko\'rishini ko\'rsatadi. Tasdiqlangandan so\'ng barcha tanlangan tovarlar bir vaqtning o\'zida yangilanadi va o\'zgarishlar tarixda aks etadi.',
    ruFunctionality: 'Позволяет изменить цену или категорию для выбранных товаров через меню массовых действий. Система показывает превью изменений и требует подтверждения перед применением. Доступно до 500 товаров за одну операцию массового редактирования.',
    uzFunctionality: 'Ommaviy harakatlar menyusi orqali tanlangan tovarlar uchun narx yoki kategoriyani o\'zgartirish imkonini beradi. Tizim o\'zgarishlarning oldindan ko\'rishini ko\'rsatadi va qo\'llashdan oldin tasdiqlashni talab qiladi. Bir ommaviy tahrirlash operatsiyasida 500 gacha tovarlar mavjud.'
  },

  { 
    order: 17, 
    ruDescription: 'Функция печати ценника формирует печатную форму ценника для выбранного товара. Это необходимо для оформления торгового зала и соблюдения требований законодательства о защите прав потребителей.\n\nСистема предлагает несколько шаблонов ценников разных размеров и форматов. Можно выбрать шаблон для печати на обычной бумаге или на самоклеящейся этикетке. Доступна настройка шаблона с логотипом организации.\n\nПри печати ценника на него автоматически подставляется актуальная цена товара. Можно также распечатать ценники сразу для нескольких товаров, выбрав их в списке.',
    uzDescription: 'Narx yorlig\'ini chop etish funksiyasi tanlangan tovar uchun narx yorlig\'ining bosma shaklini yaratadi. Bu savdo zali ni bezash va iste\'molchilar huquqlarini himoya qilish to\'g\'risidagi qonun hujjatlariga rioya qilish uchun zarur.\n\nTizim turli o\'lcham va formatlardagi narx yorliqlarining bir nechta shablonlarini taklif qiladi. Oddiy qog\'ozga yoki o\'z-o\'zidan yopishqoq etiketkaga chop etish uchun shablonni tanlash mumkin. Tashkilot logotipi bilan shablonni sozlash mavjud.\n\nNarx yorlig\'ini chop etishda unga tovarning dolzarb narxi avtomatik qo\'yiladi. Shuningdek ro\'yxatda tanlab bir nechta tovarlar uchun darhol narx yorliqlarini chop etish mumkin.',
    ruFunctionality: 'Формирует и печатает ценник для выбранного товара с использованием настраиваемых шаблонов. Ценник включает наименование, цену, единицу измерения и optionally логотип компании. Поддерживается массовая печать ценников для группы товаров.',
    uzFunctionality: 'Sozlanadigan shablonlardan foydalanib tanlangan tovar uchun narx yorlig\'ini shakllantirib chop etadi. Narx yorlig\'i nom, narx, o\'lchov birligi va ixtiyoriy ravishda kompaniya logotipini o\'z ichiga oladi. Tovarlar guruhi uchun narx yorliqlarini ommaviy chop etish qo\'llab-quvvatlanadi.'
  },

  { 
    order: 18, 
    ruDescription: 'Функция копирования товара создаёт дубликат выбранной позиции со всеми её характеристиками. Это ускоряет добавление похожих товаров, когда новая позиция незначительно отличается от существующей.\n\nПри копировании создаётся новый товар с теми же значениями полей: категория, единица измерения, описание. Нужно только изменить наименование, артикул и скорректировать при необходимости цены.\n\nКопирование особенно полезно при вводе новых модификаций товара: другого цвета, размера или комплектации. Это экономит время на заполнение повторяющихся данных.',
    uzDescription: 'Tovarni nusxalash funksiyasi tanlangan pozitsiyaning barcha xususiyatlari bilan dublikatini yaratadi. Bu yangi pozitsiya mavjudidan oz farq qilganda o\'xshash tovarlarni qo\'shishni tezlashtiradi.\n\nNusxalashda bir xil maydon qiymatlari bilan yangi tovar yaratiladi: kategoriya, o\'lchov birligi, tavsif. Faqat nomni, artikulni o\'zgartirish va zarurat bo\'lganda narxlarni tuzatish kerak.\n\nNusxalash ayniqsa tovarning yangi modifikatsiyalarini kiritishda foydali: boshqa rang, o\'lcham yoki komplektatsiya. Bu takroriy ma\'lumotlarni to\'ldirish vaqtini tejaydi.',
    ruFunctionality: 'Создаёт дубликат товара с теми же характеристиками для быстрого добавления похожих позиций. Новый товар получает уникальный артикул и штрих-код, остальные поля копируются без изменений. После копирования открывается форма редактирования для корректировки данных.',
    uzFunctionality: 'O\'xshash pozitsiyalarni tez qo\'shish uchun bir xil xususiyatlar bilan tovar dublikatini yaratadi. Yangi tovar noyob artikul va shtrix-kod oladi, qolgan maydonlar o\'zgarishsiz nusxalanadi. Nusxalagandan so\'ng ma\'lumotlarni tuzatish uchun tahrirlash formasi ochiladi.'
  },

  { 
    order: 19, 
    ruDescription: 'История изменений товара показывает все изменения, которые производились с карточкой товара: изменение цен, описания, категории и других параметров. Это важный инструмент контроля и аудита.\n\nВ истории отображается дата и время изменения, пользователь, внёсший изменение, и сами изменённые значения — старое и новое. Это позволяет отследить причины и авторов всех корректировок.\n\nИстория хранится за весь период существования товара и не может быть удалена. Это обеспечивает прозрачность учётных данных и помогает при разборе спорных ситуаций.',
    uzDescription: 'Tovar o\'zgarishlari tarixi tovar kartochkasi bilan amalga oshirilgan barcha o\'zgarishlarni ko\'rsatadi: narxlar, tavsif, kategoriya va boshqa parametrlarning o\'zgarishi. Bu nazorat va auditoriyaning muhim vositasidir.\n\nTarixda o\'zgarish sanasi va vaqti, o\'zgarish kiritgan foydalanuvchi va o\'zgartirilgan qiymatlar — eski va yangi ko\'rsatiladi. Bu barcha tuzatishlarning sabablari va mualliflarini kuzatish imkonini beradi.\n\nTarix tovar mavjud bo\'lgan butun davrda saqlanadi va o\'chirib bo\'lmaydi. Bu hisob ma\'lumotlarining shaffofligini ta\'minlaydi va bahsli holatlarni hal qilishda yordam beradi.',
    ruFunctionality: 'Показывает все изменения цены, остатков и других данных товара с указанием автора и времени. История доступна в карточке товара на отдельной вкладке с возможностью фильтрации по типу изменений. Данные истории хранятся бессрочно и защищены от редактирования.',
    uzFunctionality: 'Muallif va vaqti ko\'rsatilgan holda tovar narxi, qoldiqlar va boshqa ma\'lumotlarning barcha o\'zgarishlarini ko\'rsatadi. Tarix tovar kartochkasida o\'zgarishlar turi bo\'yicha filtrlash imkoniyati bilan alohida varaqda mavjud. Tarix ma\'lumotlari cheksiz saqlanadi va tahrirlashdan himoyalangan.'
  },

  { 
    order: 20, 
    ruDescription: 'Функция просмотра и печати штрих-кода показывает графическое изображение штрих-кода товара для печати этикеток. Штрих-код используется для идентификации товара при сканировании.\n\nСистема генерирует штрих-код в формате EAN-13 или Code 128 в зависимости от типа кода товара. Изображение можно масштабировать для печати этикеток разного размера.\n\nРаспечатанный штрих-код можно наклеить на товар или упаковку для использования при приёмке, инвентаризации и продаже. Система также поддерживает печать QR-кодов с дополнительной информацией о товаре.',
    uzDescription: 'Shtrix-kodni ko\'rish va chop etish funksiyasi etiketkalarni chop etish uchun tovar shtrix-kodining grafik tasvirini ko\'rsatadi. Shtrix-kod skanerlashda tovarni identifikatsiya qilish uchun ishlatiladi.\n\nTizim tovar kodi turiga qarab EAN-13 yoki Code 128 formatida shtrix-kod yaratadi. Tasvirni turli o\'lchamdagi etiketkalarni chop etish uchun masshtablashtirish mumkin.\n\nChop etilgan shtrix-kodni qabul qilish, inventarizatsiya va sotishda foydalanish uchun tovar yoki qadoqqa yopishtirish mumkin. Tizim shuningdek tovar haqida qo\'shimcha ma\'lumot bilan QR-kodlarni chop etishni qo\'llab-quvvatlaydi.',
    ruFunctionality: 'Показывает штрих-код товара с возможностью печати для этикеток или наклеек. Генерирует изображение в формате EAN-13 или Code 128 с настраиваемым размером. Поддерживает массовую печать штрих-кодов для выбранных товаров.',
    uzFunctionality: 'Etiketkalar yoki yopishtiriqlar uchun chop etish imkoniyati bilan tovar shtrix-kodini ko\'rsatadi. Sozlanadigan o\'lcham bilan EAN-13 yoki Code 128 formatida tasvir yaratadi. Tanlangan tovarlar uchun shtrix-kodlarni ommaviy chop etishni qo\'llab-quvvatlaydi.'
  },

  // === СКЛАД: ПРИХОД (21-35) ===
  { 
    order: 21, 
    ruDescription: 'Раздел "Приход" предназначен для оформления поступления товаров от поставщиков. Это ключевой раздел складского учёта, где фиксируются все входящие поставки товаров.\n\nВ разделе отображается список документов поступления с информацией о поставщике, дате, сумме и статусе документа. Документы можно фильтровать по периоду, поставщику и статусу проведения.\n\nПравильное оформление прихода обеспечивает корректный учёт товаров и расчёт себестоимости. Все приходы сохраняются в истории и доступны для анализа и аудита.',
    uzDescription: '"Kirim" bo\'limi yetkazib beruvchilardan tovarlarning kelib tushishini rasmiylashtirish uchun mo\'ljallangan. Bu ombor hisobining asosiy bo\'limi bo\'lib, bu yerda barcha kiruvchi tovar yetkazib berishlar qayd etiladi.\n\nBo\'limda yetkazib beruvchi, sana, summa va hujjat holati haqida ma\'lumot bilan kelib tushish hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni davr, yetkazib beruvchi va o\'tkazish holati bo\'yicha filtrlash mumkin.\n\nKirimga to\'g\'ri rasmiylashtirish tovarlarning to\'g\'ri hisobini va tannarxni hisoblashni ta\'minlaydi. Barcha kirinishlar tarixda saqlanadi va tahlil va auditoriya uchun mavjud.',
    ruFunctionality: 'Открывает список документов поступления товаров от поставщиков с фильтрами по дате, контрагенту и статусу. Каждый документ содержит информацию о поставщике, складе получения, списке товаров и итоговой сумме. Документы можно создавать, редактировать, проводить и печатать.',
    uzFunctionality: 'Sana, kontragent va holat bo\'yicha filtrlar bilan yetkazib beruvchilardan tovar kelib tushish hujjatlari ro\'yxatini ochadi. Har bir hujjat yetkazib beruvchi, qabul qiluvchi ombor, tovarlar ro\'yxati va yakuniy summa haqida ma\'lumotni o\'z ichiga oladi. Hujjatlarni yaratish, tahrirlash, o\'tkazish va chop etish mumkin.'
  },

  { 
    order: 22, 
    ruDescription: 'Кнопка создания прихода открывает форму для оформления нового документа поступления товаров. Это первый шаг при приёмке товара от поставщика.\n\nВ форме необходимо указать поставщика, склад получения, дату документа и добавить список товаров с количеством и ценами. Система автоматически рассчитывает сумму документа и НДС.\n\nПосле заполнения документ можно сохранить как черновик или сразу провести, чтобы товары появились на остатках склада. Проведённый документ нельзя редактировать, можно только отменить.',
    uzDescription: 'Kirim yaratish tugmasi yangi tovar kelib tushish hujjatini rasmiylashtirish uchun formani ochadi. Bu yetkazib beruvchidan tovar qabul qilishdagi birinchi qadam.\n\nFormada yetkazib beruvchi, qabul qiluvchi ombor, hujjat sanasini ko\'rsatish va tovarlar ro\'yxatini miqdor va narxlar bilan qo\'shish kerak. Tizim avtomatik hujjat summasini va QQS ni hisoblaydi.\n\nTo\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki darhol o\'tkazish mumkin, shunda tovarlar ombor qoldiqlarida paydo bo\'ladi. O\'tkazilgan hujjatni tahrirlab bo\'lmaydi, faqat bekor qilish mumkin.',
    ruFunctionality: 'Открывает форму для создания нового документа поступления с выбором поставщика, склада и даты. В форме можно добавить товары вручную или сканированием штрих-кода с указанием количества и цены. После заполнения документ сохраняется как черновик или проводится сразу.',
    uzFunctionality: 'Yetkazib beruvchi, ombor va sana tanlash bilan yangi kelib tushish hujjati yaratish uchun formani ochadi. Formada tovarlarni qo\'lda yoki shtrix-kodni skanerlab miqdor va narx bilan qo\'shish mumkin. To\'ldirilgandan so\'ng hujjat qoralama sifatida saqlanadi yoki darhol o\'tkaziladi.'
  },

  { 
    order: 23, 
    ruDescription: 'Поле выбора поставщика позволяет указать контрагента, от которого поступает товар. Это обязательный реквизит документа прихода, влияющий на расчёты с поставщиками.\n\nПри вводе первых символов названия система предлагает варианты из справочника контрагентов. Можно также создать нового поставщика непосредственно из формы прихода.\n\nВыбранный поставщик автоматически подставляется в расчёты по дебиторской и кредиторской задолженности. История поставок от конкретного поставщика доступна в его карточке.',
    uzDescription: 'Yetkazib beruvchini tanlash maydoni tovar kelgan kontragentni ko\'rsatish imkonini beradi. Bu kirim hujjatining majburiy rekviziti bo\'lib, yetkazib beruvchilar bilan hisob-kitoblarga ta\'sir qiladi.\n\nNoming birinchi belgilari kiritilganda tizim kontragentlar ma\'lumotnomasidan variantlarni taklif qiladi. Shuningdek kirim formasidan to\'g\'ridan-to\'g\'ri yangi yetkazib beruvchi yaratish mumkin.\n\nTanlangan yetkazib beruvchi avtomatik debitorlik va kreditorlik qarzlari bo\'yicha hisob-kitoblarga qo\'yiladi. Aniq yetkazib beruvchidan yetkazib berishlar tarixi uning kartochkasida mavjud.',
    ruFunctionality: 'Позволяет выбрать поставщика из списка контрагентов с автоподсказками при вводе названия. При выборе поставщика автоматически подтягиваются его реквизиты и условия сотрудничества. Можно создать нового контрагента прямо из формы документа.',
    uzFunctionality: 'Nom kiritilganda avto-takliflar bilan kontragentlar ro\'yxatidan yetkazib beruvchini tanlash imkonini beradi. Yetkazib beruvchi tanlanganda uning rekvizitlari va hamkorlik shartlari avtomatik tortiladi. Hujjat formasidan to\'g\'ridan-to\'g\'ri yangi kontragent yaratish mumkin.'
  },

  { 
    order: 24, 
    ruDescription: 'Кнопка добавления товаров в приход открывает форму выбора позиций для включения в документ. Это основной этап формирования документа поступления.\n\nТовары можно добавлять по одному или выбирать сразу несколько позиций из списка. Для каждого товара указывается количество и цена закупки. Система проверяет корректность введённых данных.\n\nТакже доступно добавление товаров путём сканирования штрих-кода — это значительно ускоряет работу при приёмке больших партий товара.',
    uzDescription: 'Kirimga tovar qo\'shish tugmasi hujjatga kiritish uchun pozitsiyalarni tanlash formasini ochadi. Bu kelib tushish hujjatini shakllantirishning asosiy bosqichi.\n\nTovarlarni bittadan yoki ro\'yxatdan bir vaqtning o\'zida bir nechta pozitsiyani tanlash mumkin. Har bir tovar uchun miqdor va xarid narxi ko\'rsatiladi. Tizim kiritilgan ma\'lumotlarning to\'g\'riligini tekshiradi.\n\nShuningdek shtrix-kodni skanerlab tovar qo\'shish ham mavjud — bu katta tovar partiyalarini qabul qilishda ishni sezilarli darajada tezlashtiradi.',
    ruFunctionality: 'Открывает форму выбора товаров для добавления в документ с поиском и фильтрацией. Товары можно добавлять по одному или группой с указанием количества и закупочной цены. Поддерживается добавление через сканирование штрих-кода для ускорения работы.',
    uzFunctionality: 'Qidiruv va filtrlash bilan hujjatga qo\'shish uchun tovarlarni tanlash formasini ochadi. Tovarlarni bittadan yoki guruh bilan miqdor va xarid narxi ko\'rsatib qo\'shish mumkin. Ishni tezlashtirish uchun shtrix-kodni skanerlab qo\'shish qo\'llab-quvvatlanadi.'
  },

  { 
    order: 25, 
    ruDescription: 'Статус "Черновик" означает, что документ сохранён, но не проведён в учёте. В этом состоянии документ можно редактировать, но товары ещё не отражаются на остатках.\n\nЧерновики используются для предварительной подготовки документов, когда не все данные известны или требуются дополнительные согласования. Документ может находиться в статусе черновика неограниченное время.\n\nКогда все данные проверены и подтверждены, документ можно провести — товары зачислятся на склад, а документ перейдёт в статус "Оформлен".',
    uzDescription: '"Qoralama" holati hujjat saqlangan, lekin hisobda o\'tkazilmaganligini bildiradi. Bu holatda hujjatni tahrirlash mumkin, ammo tovarlar hali qoldiqlarda aks etmaydi.\n\nQoralamalar barcha ma\'lumotlar ma\'lum bo\'lmaganda yoki qo\'shimcha kelishuvlar talab qilinganda hujjatlarni oldindan tayyorlash uchun ishlatiladi. Hujjat cheksiz vaqt qoralama holatida bo\'lishi mumkin.\n\nBarcha ma\'lumotlar tekshirilib tasdiqlanganda, hujjatni o\'tkazish mumkin — tovarlar omborga qabul qilinadi va hujjat "Rasmiylashtirilgan" holatiga o\'tadi.',
    ruFunctionality: 'Документ сохраняется как черновик и доступен для редактирования без влияния на остатки товаров. В статусе черновика можно изменять все поля документа: поставщика, товары, цены. Документ остаётся в черновике пока не будет проведён или удалён.',
    uzFunctionality: 'Hujjat qoralama sifatida saqlanadi va tovar qoldiqlariga ta\'sir qilmasdan tahrirlash uchun mavjud. Qoralama holatida hujjatning barcha maydonlarini o\'zgartirish mumkin: yetkazib beruvchi, tovarlar, narxlar. Hujjat o\'tkazilmaguncha yoki o\'chirilmaguncha qoralamada qoladi.'
  },

  { 
    order: 26, 
    ruDescription: 'Статус "Оформлен" означает, что документ проведён в учёте и товары зачислены на склад. Это финальный статус документа прихода, подтверждающий факт поступления.\n\nПроведённый документ влияет на остатки товаров, расчёты с поставщиком и финансовую отчётность. Изменения, внесённые документом, отражаются во всех связанных отчётах и регистрах.\n\nПроведённый документ нельзя редактировать напрямую — для корректировки нужно отменить проведение или создать документ корректировки. Это обеспечивает целостность учётных данных.',
    uzDescription: '"Rasmiylashtirilgan" holati hujjat hisobda o\'tkazilgan va tovarlar omborga qabul qilinganligini bildiradi. Bu kelib tushishni tasdiqlovchi kirim hujjatining yakuniy holatidir.\n\nO\'tkazilgan hujjat tovar qoldiqlariga, yetkazib beruvchi bilan hisob-kitoblarga va moliyaviy hisobotga ta\'sir qiladi. Hujjat kiritgan o\'zgarishlar barcha bog\'liq hisobotlar va registrlarda aks etadi.\n\nO\'tkazilgan hujjatni to\'g\'ridan-to\'g\'ri tahrirlab bo\'lmaydi — tuzatish uchun o\'tkazishni bekor qilish yoki tuzatish hujjatini yaratish kerak. Bu hisob ma\'lumotlarining yaxlitligini ta\'minlaydi.',
    ruFunctionality: 'Документ проводится и товары зачисляются на склад с обновлением остатков в реальном времени. Проведённый документ создаёт задолженность перед поставщиком и увеличивает стоимость складских запасов. После проведения документ блокируется от редактирования для сохранения целостности данных.',
    uzFunctionality: 'Hujjat o\'tkaziladi va tovarlar real vaqtda qoldiqlarni yangilash bilan omborga qabul qilinadi. O\'tkazilgan hujjat yetkazib beruvchi oldidagi qarzni yaratadi va ombor zaxiralarining qiymatini oshiradi. O\'tkazilgandan so\'ng hujjat ma\'lumotlar yaxlitligini saqlash uchun tahrirlashdan bloklanadi.'
  },

  { 
    order: 27, 
    ruDescription: 'Функция печати прихода формирует печатную форму документа для архива и подписи. Это необходимо для документооборота с поставщиками и внутреннего контроля.\n\nСистема предлагает несколько шаблонов печатной формы: приходная накладная, приходный ордер, универсальный передаточный документ. Шаблоны соответствуют требованиям бухгалтерского учёта.\n\nРаспечатанный документ можно передать поставщику для подписи или хранить в архиве. Электронная версия документа также доступна для отправки по электронной почте.',
    uzDescription: 'Kirimni chop etish funksiyasi arxiv va imzo uchun hujjatning bosma shaklini yaratadi. Bu yetkazib beruvchilar bilan hujjat aylanishi va ichki nazorat uchun zarur.\n\nTizim bosma shaklning bir nechta shablonlarini taklif qiladi: kirim nakladnoysi, kirim orderi, universal uzatish hujjati. Shablonlar buxgalteriya hisobi talablariga mos keladi.\n\nChop etilgan hujjatni yetkazib beruvchiga imzolash uchun berish yoki arxivda saqlash mumkin. Hujjatning elektron versiyasi elektron pochta orqali yuborish uchun ham mavjud.',
    ruFunctionality: 'Формирует печатную форму документа для печати с возможностью выбора шаблона: приходная накладная, ТОРГ-12, УПД. Документ можно распечатать, сохранить в PDF или отправить по электронной почте. Печатная форма содержит все необходимые реквизиты и подписи.',
    uzFunctionality: 'Shablonni tanlash imkoniyati bilan chop etish uchun hujjatning bosma shaklini yaratadi: kirim nakladnoysi, TORG-12, UPD. Hujjatni chop etish, PDF ga saqlash yoki elektron pochta orqali yuborish mumkin. Bosma shakl barcha kerakli rekvizitlar va imzolarni o\'z ichiga oladi.'
  },

  { 
    order: 28, 
    ruDescription: 'Кнопка удаления прихода позволяет удалить документ из системы. Эта функция доступна только для документов в статусе черновика, чтобы защитить целостность учётных данных.\n\nЕсли документ уже проведён, система предложит сначала отменить проведение. После отмены проведения товары будут списаны со склада, и документ вернётся в статус черновика.\n\nУдаление требует подтверждения и логируется в системе. Рекомендуется использовать архивацию вместо удаления для сохранения истории операций.',
    uzDescription: 'Kirimni o\'chirish tugmasi hujjatni tizimdan o\'chirish imkonini beradi. Bu funksiya faqat qoralama holatidagi hujjatlar uchun mavjud, hisob ma\'lumotlari yaxlitligini himoya qilish uchun.\n\nAgar hujjat allaqachon o\'tkazilgan bo\'lsa, tizim avval o\'tkazishni bekor qilishni taklif qiladi. O\'tkazish bekor qilingandan so\'ng tovarlar ombordan yozib chiqariladi va hujjat qoralama holatiga qaytadi.\n\nO\'chirish tasdiqlashni talab qiladi va tizimda log qilinadi. Operatsiyalar tarixini saqlab qolish uchun o\'chirish o\'rniga arxivlashdan foydalanish tavsiya etiladi.',
    ruFunctionality: 'Удаляет документ прихода только в статусе черновика после подтверждения действия. Для проведённых документов сначала требуется отменить проведение, чтобы вернуть товары. Операция удаления записывается в журнал действий для аудита.',
    uzFunctionality: 'Harakatni tasdiqlagandan so\'ng faqat qoralama holatidagi kirim hujjatini o\'chiradi. O\'tkazilgan hujjatlar uchun avval tovarlarni qaytarish uchun o\'tkazishni bekor qilish talab qilinadi. O\'chirish operatsiyasi auditoriya uchun harakatlar jurnaliga yoziladi.'
  },

  { 
    order: 29, 
    ruDescription: 'Фильтр приходов по дате позволяет отобрать документы за определённый период времени. Это удобно для анализа поставок за неделю, месяц или произвольный интервал.\n\nФильтр поддерживает выбор предустановленных периодов: сегодня, вчера, эта неделя, этот месяц, этот квартал. Также можно указать произвольный диапазон дат с точностью до дня.\n\nПрименённый фильтр влияет на все расчёты и отчёты в разделе, показывая данные только за выбранный период. Это позволяет быстро получать нужную статистику.',
    uzDescription: 'Kirimlarni sana bo\'yicha filtr aniq davr uchun hujjatlarni tanlash imkonini beradi. Bu hafta, oy yoki ixtiyoriy oraliq uchun yetkazib berishlarni tahlil qilish uchun qulay.\n\nFiltr oldindan o\'rnatilgan davrlarni tanlashni qo\'llab-quvvatlaydi: bugun, kecha, bu hafta, bu oy, bu chorak. Shuningdek kunga aniqlik bilan ixtiyoriy sana oralig\'ini ko\'rsatish mumkin.\n\nQo\'llangan filtr bo\'limdagi barcha hisoblar va hisobotlarga ta\'sir qiladi, faqat tanlangan davr uchun ma\'lumotlarni ko\'rsatadi. Bu kerakli statistikani tez olish imkonini beradi.',
    ruFunctionality: 'Позволяет отфильтровать документы за выбранный период с предустановленными вариантами или произвольным диапазоном. Фильтр применяется мгновенно и сохраняется до конца сессии. Доступен экспорт отфильтрованных документов в Excel.',
    uzFunctionality: 'Oldindan o\'rnatilgan variantlar yoki ixtiyoriy diapazon bilan tanlangan davr uchun hujjatlarni filtrlash imkonini beradi. Filtr bir zumda qo\'llanadi va sessiya oxirigacha saqlanadi. Filtrlangan hujjatlarni Excel ga eksport qilish mavjud.'
  },

  { 
    order: 30, 
    ruDescription: 'Фильтр приходов по поставщику позволяет отобрать документы конкретного контрагента. Это полезно для анализа истории работы с определённым поставщиком.\n\nПри вводе названия поставщика система предлагает варианты из справочника контрагентов. Можно выбрать одного или нескольких поставщиков для отображения их документов.\n\nФильтр можно комбинировать с фильтром по дате для получения полной картины работы с поставщиком за определённый период.',
    uzDescription: 'Kirimlarni yetkazib beruvchi bo\'yichi filtr aniq kontragentning hujjatlarini tanlash imkonini beradi. Bu aniq yetkazib beruvchi bilan ish tarixini tahlil qilish uchun foydali.\n\nYetkazib beruvchi nomi kiritilganda tizim kontragentlar ma\'lumotnomasidan variantlarni taklif qiladi. Hujjatlarini ko\'rsatish uchun bitta yoki bir nechta yetkazib beruvchini tanlash mumkin.\n\nFiltrni aniq davr uchun yetkazib beruvchi bilan ishning to\'liq manzarasini olish uchun sana bo\'yicha filtr bilan birlashtirish mumkin.',
    ruFunctionality: 'Показывает документы выбранного поставщика из справочника контрагентов. Фильтр поддерживает множественный выбор для отображения документов нескольких поставщиков. Можно быстро перейти в карточку поставщика из фильтра.',
    uzFunctionality: 'Kontragentlar ma\'lumotnomasidan tanlangan yetkazib beruvchining hujjatlarini ko\'rsatadi. Filtr bir nechta yetkazib beruvchining hujjatlarini ko\'rsatish uchun ko\'p tanlovni qo\'llab-quvvatlaydi. Filtrdan yetkazib beruvchi kartochkasiga tez o\'tish mumkin.'
  },

  { 
    order: 31, 
    ruDescription: 'Функция копирования прихода создаёт новый документ на основе существующего. Это ускоряет оформление повторяющихся поставок от одного поставщика.\n\nПри копировании переносятся все данные документа: поставщик, склад, список товаров, цены и условия. Дата документа устанавливается текущей, а номер генерируется автоматически.\n\nНовый документ сохраняется как черновик и требует проверки актуальности цен и количества перед проведением. Это удобный способ быстро создать типовую поставку.',
    uzDescription: 'Kirimni nusxalash funksiyasi mavjud asosda yangi hujjat yaratadi. Bu bitta yetkazib beruvchidan takroriy yetkazib berishlarni rasmiylashtirishni tezlashtiradi.\n\nNusxalashda hujjatning barcha ma\'lumotlari ko\'chiriladi: yetkazib beruvchi, ombor, tovarlar ro\'yxati, narxlar va shartlar. Hujjat sanasi joriy o\'rnatiladi, raqam esa avtomatik yaratiladi.\n\nYangi hujjat qoralama sifatida saqlanadi va o\'tkazishdan oldin narxlar va miqdorning dolzarbligini tekshirishni talab qiladi. Bu tip yetkazib berishni tez yaratishning qulay usuli.',
    ruFunctionality: 'Создаёт новый документ на основе существующего с копированием всех позиций и реквизитов. Дата документа устанавливается текущей, а цены подтягиваются актуальные на момент копирования. Новый документ создаётся в статусе черновика.',
    uzFunctionality: 'Barcha pozitsiyalar va rekvizitlarni nusxalash bilan mavjud asosda yangi hujjat yaratadi. Hujjat sanasi joriy o\'rnatiladi, narxlar nusxalash vaqtida dolzarb tortiladi. Yangi hujjat qoralama holatida yaratiladi.'
  },

  { 
    order: 32, 
    ruDescription: 'Кнопка проведения прихода подтверждает документ и зачисляет товары на склад. Это ключевое действие, которое превращает черновик в полноценный учётный документ.\n\nПри проведении система проверяет корректность всех данных: наличие поставщика, заполнение обязательных полей, положительное количество товаров. При обнаружении ошибок выводятся предупреждения.\n\nПосле успешного проведения товары появляются на остатках склада, создаётся кредиторская задолженность перед поставщиком, и документ блокируется от редактирования.',
    uzDescription: 'Kirimga o\'tkazish tugmasi hujjatni tasdiqlaydi va tovarlarni omborga qabul qiladi. Bu qoralamani to\'liq hisob hujjatiga aylantiruvchi asosiy harakat.\n\nO\'tkazishda tizim barcha ma\'lumotlarning to\'g\'riligini tekshiradi: yetkazib beruvchining mavjudligi, majburiy maydonlarning to\'ldirilishi, tovarlar miqdorining musbatligi. Xatolar topilganda ogohlantirishlar chiqariladi.\n\nMuvaffaqiyatli o\'tkazilgandan so\'ng tovarlar ombor qoldiqlarida paydo bo\'ladi, yetkazib beruvchi oldidagi kreditorlik qarzi yaratiladi va hujjat tahrirlashdan bloklanadi.',
    ruFunctionality: 'Проводит документ и зачисляет товары на склад с обновлением остатков в реальном времени. Создаёт кредиторскую задолженность перед поставщиком на сумму документа. После проведения документ переходит в статус "Оформлен" и блокируется от редактирования.',
    uzFunctionality: 'Hujjatni o\'tkazadi va tovarlarni real vaqtda qoldiqlarni yangilash bilan omborga qabul qiladi. Hujjat summasi bo\'yicha yetkazib beruvchi oldidagi kreditorlik qarzini yaratadi. O\'tkazilgandan so\'ng hujjat "Rasmiylashtirilgan" holatiga o\'tadi va tahrirlashdan bloklanadi.'
  },

  { 
    order: 33, 
    ruDescription: 'Функция отмены проведения возвращает документ в статус черновика и отменяет все его учётные последствия. Это используется для корректировки ошибочно проведённого документа.\n\nПри отмене проведения товары списываются со склада, а кредиторская задолженность аннулируется. Все связанные документы и отчёты пересчитываются автоматически.\n\nПосле отмены документ снова доступен для редактирования. Можно внести исправления и провести документ заново или удалить его.',
    uzDescription: 'O\'tkazishni bekor qilish funksiyasi hujjatni qoralama holatiga qaytaradi va uning barcha hisob oqibatlarini bekor qiladi. Bu noto\'g\'ri o\'tkazilgan hujjatni tuzatish uchun ishlatiladi.\n\nO\'tkazish bekor qilinganda tovarlar ombordan yozib chiqariladi, kreditorlik qarzi bekor qilinadi. Barcha bog\'liq hujjatlar va hisobotlar avtomatik qayta hisoblanadi.\n\nBekor qilingandan so\'ng hujjat yana tahrirlash uchun mavjud bo\'ladi. Tuzatishlar kiritib hujjatni qayta o\'tkazish yoki o\'chirish mumkin.',
    ruFunctionality: 'Отменяет проведение и возвращает товары поставщику с корректировкой остатков. Аннулирует кредиторскую задолженность и пересчитывает связанные финансовые показатели. Документ возвращается в статус черновика для редактирования или удаления.',
    uzFunctionality: 'O\'tkazishni bekor qiladi va qoldiqlarni tuzatish bilan tovarlarni yetkazib beruvchiga qaytaradi. Kreditorlik qarzini bekor qiladi va bog\'liq moliyaviy ko\'rsatkichlarni qayta hisoblaydi. Hujjat tahrirlash yoki o\'chirish uchun qoralama holatiga qaytadi.'
  },

  { 
    order: 34, 
    ruDescription: 'Расширения прихода позволяют добавить дополнительную информацию к документу сверх стандартных полей. Это включает комментарии, номера накладных поставщика и другие данные.\n\nВ расширениях можно указать номер и дату накладной поставщика для сверки, добавить комментарий к документу, прикрепить файлы. Эта информация помогает при анализе и поиске документов.\n\nСистема также поддерживает добавление пользовательских полей для учёта специфической информации, необходимой конкретному бизнесу.',
    uzDescription: 'Kirim kengaytmalari hujjatga standart maydonlardan tashqari qo\'shimcha ma\'lumot qo\'shish imkonini beradi. Bu izohlar, yetkazib beruvchining nakladnaya raqamlari va boshqa ma\'lumotlarni o\'z ichiga oladi.\n\nKengaytmalarda solishtirish uchun yetkazib beruvchining nakladnaya raqami va sanasini ko\'rsatish, hujjatga izoh qo\'shish, fayllarni ilova qilish mumkin. Bu ma\'lumotlar tahlil va hujjatlarni qidirishda yordam beradi.\n\nTizim shuningdek aniq biznes uchun zarur bo\'lgan o\'ziga xos ma\'lumotlarni hisobga olish uchun foydalanuvchi maydonlarini qo\'shishni qo\'llab-quvvatlaydi.',
    ruFunctionality: 'Позволяет добавить комментарий, номер накладной и другие данные к документу поступления. Поддерживает прикрепление файлов: сканов накладных, сертификатов качества. Пользовательские поля можно настроить через интерфейс администратора.',
    uzFunctionality: 'Kirim hujjatiga izoh, nakladnaya raqami va boshqa ma\'lumotlarni qo\'shish imkonini beradi. Fayllarni ilova qilishni qo\'llab-quvvatlaydi: nakladnoylarning skanerlari, sifat sertifikatlari. Foydalanuvchi maydonlarini administrator interfeysi orqali sozlash mumkin.'
  },

  { 
    order: 35, 
    ruDescription: 'Функция сканирования штрих-кода позволяет добавлять товары в документ путём сканирования их штрих-кодов сканером или камерой. Это значительно ускоряет приёмку товаров.\n\nПри сканировании система автоматически находит товар в справочнике и добавляет его в документ. Если товара нет в базе, предлагается создать новую карточку с отсканированным штрих-кодом.\n\nФункция поддерживает различные форматы штрих-кодов: EAN-13, EAN-8, Code-128, QR-коды. Можно сканировать как ручным сканером, так и камерой мобильного устройства.',
    uzDescription: 'Shtrix-kodni skanerlash funksiyasi tovarlarni skaner yoki kamera bilan ularning shtrix-kodlarini skanerlab hujjatga qo\'shish imkonini beradi. Bu tovarlarni qabul qilishni sezilarli darajada tezlashtiradi.\n\nSkanerlashda tizim avtomatik tovarni ma\'lumotnomadan topadi va uni hujjatga qo\'shadi. Agar tovar bazada bo\'lmasa, skanerlangan shtrix-kod bilan yangi kartochka yaratish taklif etiladi.\n\nFunksiya turli shtrix-kod formatlarini qo\'llab-quvvatlaydi: EAN-13, EAN-8, Code-128, QR-kodlar. Qo\'l skaneri hamda mobil qurilma kamerasi bilan skanerlash mumkin.',
    ruFunctionality: 'Позволяет добавлять товары сканированием штрих-кода с использованием сканера или камеры устройства. Автоматически находит товар в справочнике или предлагает создать новый. Поддерживает форматы EAN-13, EAN-8, Code-128 и QR-коды.',
    uzFunctionality: 'Skaner yoki qurilma kamerasidan foydalanib shtrix-kodni skanerlab tovar qo\'shish imkonini beradi. Tovarni avtomatik ma\'lumotnomadan topadi yoki yangi yaratishni taklif qiladi. EAN-13, EAN-8, Code-128 va QR-kod formatlarini qo\'llab-quvvatlaydi.'
  },

  // === СКЛАД: ВОЗВРАТ ПРИХОДА (36-40) ===
  { 
    order: 36, 
    ruDescription: 'Раздел "Возврат прихода" предназначен для оформления возвратов товаров поставщикам. Это важный инструмент для работы с браком, пересортом и излишками.\n\nВ разделе отображается список документов возврата с информацией о поставщике, причине возврата, дате и сумме. Каждый возврат связан с конкретным документом поступления.\n\nПравильное оформление возврата обеспечивает корректный пересчёт остатков и задолженности перед поставщиком. Все возвраты сохраняются в истории и доступны для анализа.',
    uzDescription: '"Kirimni qaytarish" bo\'limi yetkazib beruvchilarga tovarlarni qaytarishni rasmiylashtirish uchun mo\'ljallangan. Bu brak, o\'tib ketgan va ortiqcha tovarlar bilan ishlash uchun muhim vosita.\n\nBo\'limda yetkazib beruvchi, qaytarish sababi, sana va summa haqida ma\'lumot bilan qaytarish hujjatlari ro\'yxati ko\'rsatiladi. Har bir qaytarish aniq kelib tushish hujjati bilan bog\'langan.\n\nQaytarishga to\'g\'ri rasmiylashtirish qoldiqlar va yetkazib beruvchi oldidagi qarzni to\'g\'ri qayta hisoblashni ta\'minlaydi. Barcha qaytarishlar tarixda saqlanadi va tahlil uchun mavjud.',
    ruFunctionality: 'Открывает список документов возврата товаров поставщикам с фильтрами по дате, контрагенту и причине. Документ возврата создаётся на основании прихода и автоматически формирует проводки. Возврат уменьшает кредиторскую задолженность и списывает товары со склада.',
    uzFunctionality: 'Sana, kontragent va sabab bo\'yicha filtrlar bilan yetkazib beruvchilarga tovar qaytarish hujjatlari ro\'yxatini ochadi. Qaytarish hujjati kirim asosida yaratiladi va avtomatik o\'tkazmalarni shakllantiradi. Qaytarish kreditorlik qarzini kamaytiradi va tovarlarni ombordan yozib chiqaradi.'
  },

  { 
    order: 37, 
    ruDescription: 'Кнопка создания возврата прихода открывает форму для оформления возврата товаров поставщику. Это первый шаг при обнаружении брака или пересорта.\n\nВ форме необходимо выбрать документ поступления, из которого возвращаются товары. Затем указать возвращаемые позиции, их количество и причину возврата. Система автоматически рассчитывает сумму возврата.\n\nДокумент можно сохранить как черновик или сразу провести. Проведённый возврат списывает товары со склада и уменьшает задолженность перед поставщиком.',
    uzDescription: 'Kirim qaytarish yaratish tugmasi yetkazib beruvchiga tovarlarni qaytarishni rasmiylashtirish uchun formani ochadi. Bu brak yoki o\'tib ketgan topilganda birinchi qadam.\n\nFormada tovarlar qaytarilayotgan kelib tushish hujjatini tanlash kerak. Keyin qaytariladigan pozitsiyalarni, ularning miqdorini va qaytarish sababini ko\'rsatish. Tizim avtomatik qaytarish summasini hisoblaydi.\n\nHujjatni qoralama sifatida saqlash yoki darhol o\'tkazish mumkin. O\'tkazilgan qaytarish tovarlarni ombordan yozib chiqaradi va yetkazib beruvchi oldidagi qarzni kamaytiradi.',
    ruFunctionality: 'Открывает форму для создания возврата поставщику на основании документа поступления. В форме выбираются товары для возврата с указанием количества и причины. После проведения формируется документ возврата с подписями и печатью.',
    uzFunctionability: 'Kelib tushish hujjati asosida yetkazib beruvchiga qaytarish yaratish uchun formani ochadi. Formada miqdor va sabab ko\'rsatilgan holda qaytarish uchun tovarlar tanlanadi. O\'tkazilgandan so\'ng imzolar va muhr bilan qaytarish hujjati shakllantiriladi.',
    uzFunctionality: 'Kelib tushish hujjati asosida yetkazib beruvchiga qaytarish yaratish uchun formani ochadi. Formada miqdor va sabab ko\'rsatilgan holda qaytarish uchun tovarlar tanlanadi. O\'tkazilgandan so\'ng imzolar va muhr bilan qaytarish hujjati shakllantiriladi.'
  },

  { 
    order: 38, 
    ruDescription: 'Поле выбора прихода для возврата позволяет указать документ поступления, из которого возвращаются товары. Это обеспечивает связь между приходом и возвратом.\n\nПри выборе система показывает список приходов от выбранного поставщика. Можно выбрать только проведённые документы поступления. После выбора система подтягивает список товаров из прихода.\n\nЭто упрощает оформление возврата: не нужно заново вводить все данные о товарах, достаточно выбрать позиции и указать возвращаемое количество.',
    uzDescription: 'Qaytarish uchun kirimni tanlash maydoni tovarlar qaytarilayotgan kelib tushish hujjatini ko\'rsatish imkonini beradi. Bu kirim va qaytarish o\'rtasidagi bog\'liqlikni ta\'minlaydi.\n\nTanlashda tizim tanlangan yetkazib beruvchidan kirishlar ro\'yxatini ko\'rsatadi. Faqat o\'tkazilgan kelib tushish hujjatlarini tanlash mumkin. Tanlangandan so\'ng tizim kirishdan tovarlar ro\'yxatini tortadi.\n\nBu qaytarishni rasmiylashtirishni soddalashtiradi: tovarlar haqidagi barcha ma\'lumotlarni qayta kiritish shart emas, faqat pozitsiyalarni tanlab qaytariladigan miqdorni ko\'rsatish kifoya.',
    ruFunctionality: 'Позволяет выбрать приход, из которого возвращаются товары с отображением списка доступных документов. После выбора прихода автоматически подтягивается список товаров с ценами и количеством. Система показывает только те товары, по которым есть остатки для возврата.',
    uzFunctionality: 'Mavjud hujjatlar ro\'yxati ko\'rsatilgan holda tovarlar qaytarilayotgan kirimni tanlash imkonini beradi. Kirim tanlangandan so\'ng narxlar va miqdor bilan tovarlar ro\'yxati avtomatik tortiladi. Tizim faqat qaytarish uchun qoldiqlari bo\'lgan tovarlarni ko\'rsatadi.'
  },

  { 
    order: 39, 
    ruDescription: 'Поле причины возврата позволяет указать основание для возврата товаров поставщику. Это важная информация для документооборота и анализа качества поставок.\n\nСистема предлагает предустановленные варианты причин: брак, пересорт, истечение срока годности, излишки, повреждение при транспортировке. Также можно указать произвольную причину.\n\nУказанная причина печатается в документе возврата и используется в отчётах по качеству работы с поставщиками.',
    uzDescription: 'Qaytarish sababi maydoni yetkazib beruvchiga tovarlarni qaytarish asosini ko\'rsatish imkonini beradi. Bu hujjat aylanishi va yetkazib berish sifati tahlili uchun muhim ma\'lumot.\n\nTizim oldindan o\'rnatilgan sabab variantlarini taklif qiladi: brak, o\'tib ketgan, yaroqlilik muddati tugashi, ortiqcha, tashishda shikastlanish. Shuningdek ixtiyoriy sababni ko\'rsatish mumkin.\n\nKo\'rsatilgan sabab qaytarish hujjatida chop etiladi va yetkazib beruvchilar bilan ish sifati bo\'yicha hisobotlarda ishlatiladi.',
    ruFunctionality: 'Позволяет указать причину возврата товара из предустановленного списка или ввести произвольную. Доступные причины: брак, пересорт, истечение срока годности, повреждение упаковки. Указанная причина фиксируется в документе и используется для аналитики.',
    uzFunctionality: 'Oldindan o\'rnatilgan ro\'yxatdan qaytarish sababini ko\'rsatish yoki ixtiyoriy kiritish imkonini beradi. Mavjud sabablar: brak, o\'tib ketgan, yaroqlilik muddati tugashi, qadoqlash shikastlanishi. Ko\'rsatilgan sabab hujjatda qayd etiladi va tahlil uchun ishlatiladi.'
  },

  { 
    order: 40, 
    ruDescription: 'Функция печати возврата формирует печатную форму документа для передачи поставщику и хранения в архиве. Это необходимо для документального подтверждения факта возврата.\n\nСистема генерирует документ по установленной форме с указанием всех реквизитов: поставщик, возвращаемые товары, количество, сумма, причина возврата. Документ содержит место для подписей обеих сторон.\n\nРаспечатанный документ передаётся поставщику вместе с возвращаемым товаром. Электронная копия сохраняется в системе и доступна для просмотра в любое время.',
    uzDescription: 'Qaytarishni chop etish funksiyasi yetkazib beruvchiga berish va arxivda saqlash uchun hujjatning bosma shaklini yaratadi. Bu qaytarish faktini hujjatli tasdiqlash uchun zarur.\n\nTizim barcha rekvizitlar ko\'rsatilgan holda o\'rnatilgan shaklda hujjat yaratadi: yetkazib beruvchi, qaytarilayotgan tovarlar, miqdor, summa, qaytarish sababi. Hujjat ikkala tomon imzolari uchun joy o\'z ichiga oladi.\n\nChop etilgan hujjat qaytarilayotgan tovar bilan birga yetkazib beruvchiga beriladi. Elektron nusxa tizimda saqlanadi va istalgan vaqtda ko\'rish uchun mavjud.',
    ruFunctionality: 'Формирует печатную форму документа возврата для печати, сохранения в PDF или отправки по email. Документ содержит все необходимые реквизиты и место для подписей сторон. Можно выбрать шаблон: накладная на возврат, ТОРГ-12, УПД.',
    uzFunctionality: 'Chop etish, PDF ga saqlash yoki email ga yuborish uchun qaytarish hujjatining bosma shaklini yaratadi. Hujjat barcha kerakli rekvizitlar va tomonlar imzolari uchun joy o\'z ichiga oladi. Shablonni tanlash mumkin: qaytarish nakladnoysi, TORG-12, UPD.'
  },
];

async function main() {
  console.log('Updating lessons 1-40 with expanded descriptions and functionality...');

  for (const lesson of lessonsData) {
    const result = await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
        ruFunctionality: lesson.ruFunctionality,
        uzFunctionality: lesson.uzFunctionality,
      },
    });
    console.log(`Updated lesson ${lesson.order} (${result.count} record(s))`);
  }

  console.log('Done! All 40 lessons have been updated.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
