// Update lessons 41-100 with detailed descriptions
// Run: npx ts-node scripts/update-lessons-part2.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const detailedLessons: { order: number; ruDescription: string; uzDescription: string }[] = [
  // === СКЛАД: ТРАНСФЕР (41-50) ===
  { order: 41, ruDescription: 'Раздел "Трансфер" предназначен для оформления перемещения товаров между складами организации. Это необходимая функция для многозвенных сетей с несколькими складами.\n\nВ разделе отображается список документов перемещения с информацией об отправителе, получателе, дате и статусе. Документы можно фильтровать по статусу: черновик, отправлен, получен, отменён.\n\nПравильное оформление трансфера обеспечивает корректный учёт товаров на каждом складе. Товары списываются с одного склада и зачисляются на другой без изменения общего количества.', uzDescription: '"Transfer" bo\'limi tashkilot omborlari orasida tovarlarni ko\'chirishni rasmiylashtirish uchun mo\'ljallangan. Bu bir nechta omborli ko\'p bo\'g\'inli tarmoqlar uchun zarur funksiya.\n\nBo\'limda yuboruvchi, qabul qiluvchi, sana va holat haqida ma\'lumot bilan ko\'chirish hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni holat bo\'yicha filtrlash mumkin: qoralama, yuborilgan, qabul qilingan, bekor qilingan.\n\nTransfega to\'g\'ri rasmiylashtirish har bir omborda tovarlarning to\'g\'ri hisobini ta\'minlaydi. Tovarlar bir ombordan yozib chiqarilib, boshqasiga umumiy miqdorni o\'zgartirmasdan qabul qilinadi.' },

  { order: 42, ruDescription: 'Кнопка создания трансфера открывает форму для оформления нового перемещения товаров. Это первый шаг при необходимости передать товары с одного склада на другой.\n\nВ форме необходимо указать склад-отправитель и склад-получатель, добавить список товаров с количеством. Система проверяет наличие достаточного количества товаров на складе-отправителе.\n\nПосле заполнения документ можно сохранить как черновик или отправить — товары будут списаны со склада-отправителя и перейдут в статус "в пути".', uzDescription: 'Transfer yaratish tugmasi yangi tovar ko\'chirishni rasmiylashtirish uchun formani ochadi. Bu tovarlarni bir ombordan boshqasiga o\'tkazish zarurati tug\'ilganda birinchi qadam.\n\nFormada yuboruvchi ombor va qabul qiluvchi omborni ko\'rsatish, tovarlar ro\'yxatini miqdor bilan qo\'shish kerak. Tizim yuboruvchi omborda yetarli miqdorda tovar borligini tekshiradi.\n\nTo\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki yuborish mumkin — tovarlar yuboruvchi ombordan yozib chiqarilib, "yo\'lda" holatiga o\'tadi.' },

  { order: 43, ruDescription: 'Поле выбора склада-отправителя позволяет указать склад, с которого будут отправлены товары. Это обязательный параметр документа трансфера.\n\nПри выборе склада система показывает актуальные остатки товаров на этом складе. Можно добавить только те товары, которые есть в наличии в достаточном количестве.\n\nПравильный выбор отправителя обеспечивает корректное списание товаров и предотвращает отрицательные остатки. Система блокирует отправку товаров, которых нет на складе.', uzDescription: 'Yuboruvchi omborni tanlash maydoni tovarlar yuboriladigan omborni ko\'rsatish imkonini beradi. Bu transfer hujjatining majburiy parametri.\n\nOmbor tanlanganda tizim ushbu ombordagi tovarlarning dolzarb qoldiqlarini ko\'rsatadi. Faqat yetarli miqdorda mavjud bo\'lgan tovarlarni qo\'shish mumkin.\n\nYuboruvchini to\'g\'ri tanlash tovarlarning to\'g\'ri yozib chiqarilishini ta\'minlaydi va manfiy qoldiqlarning oldini oladi. Tizim omborda yo\'q tovarlarni yuborishni bloklaydi.' },

  { order: 44, ruDescription: 'Поле выбора склада-получателя позволяет указать склад, на который поступят товары. Это обязательный параметр документа трансфера.\n\nПолучатель должен отличаться от отправителя — система не позволяет создать трансфер на тот же склад. Можно выбрать любой склад организации из справочника.\n\nПосле принятия трансфера товары зачисляются на склад-получатель и становятся доступными для продажи и других операций.', uzDescription: 'Qabul qiluvchi omborni tanlash maydoni tovarlar keladigan omborni ko\'rsatish imkonini beradi. Bu transfer hujjatining majburiy parametri.\n\nQabul qiluvchi yuboruvchidan farq qilishi kerak — tizim bir xil omborga transfer yaratishga yo\'l qo\'ymaydi. Tashkilotning ma\'lumotnomasidan istalgan omborni tanlash mumkin.\n\nTransfer qabul qilingandan so\'ng tovarlar qabul qiluvchi omborga qabul qilinadi va sotish va boshqa operatsiyalar uchun mavjud bo\'ladi.' },

  { order: 45, ruDescription: 'Статус "Отправлен" означает, что товары списаны со склада-отправителя и находятся в процессе перемещения. Это промежуточный статус документа трансфера.\n\nВ этом статусе товары числятся "в пути" — они уже не на складе-отправителе, но ещё не на складе-получателе. Это позволяет отследить товары во время логистического процесса.\n\nСотрудники склада-получателя видят входящие трансферы в специальном разделе и могут принять их, когда товары прибудут.', uzDescription: '"Yuborilgan" holati tovarlarning yuboruvchi ombordan yozib chiqarilganligini va ko\'chirish jarayonida ekanligini bildiradi. Bu transfer hujjatining oraliq holatidir.\n\nBu holatda tovarlar "yo\'lda" deb hisoblanadi — ular allaqachon yuboruvchi omborda emas, lekin hali qabul qiluvchi omborda ham emas. Bu logistik jarayon davomida tovarlarni kuzatish imkonini beradi.\n\nQabul qiluvchi ombor xodimlari kiruvchi transferlarni maxsus bo\'limda ko\'rishadi va tovarlar kelganda ularni qabul qilishlari mumkin.' },

  { order: 46, ruDescription: 'Статус "Получен" означает, что товары зачислены на склад-получатель и процесс перемещения завершён. Это финальный статус успешного трансфера.\n\nПосле получения товары появляются на остатках склада-получателя и становятся доступными для всех операций: продажи, инвентаризации, дальнейшего перемещения.\n\nИстория трансфера сохраняется, и можно отследить всю цепочку перемещения конкретной партии товара между складами.', uzDescription: '"Qabul qilingan" holati tovarlarning qabul qiluvchi omborga qabul qilinganligini va ko\'chirish jarayonining tugaganligini bildiradi. Bu muvaffaqiyatli transferning yakuniy holatidir.\n\nQabul qilingandan so\'ng tovarlar qabul qiluvchi omborning qoldiqlarida paydo bo\'ladi va barcha operatsiyalar uchun mavjud bo\'ladi: sotish, inventarizatsiya, keyingi ko\'chirish.\n\nTransfer tarixi saqlanib qoladi va aniq tovar partiyasining omborlar orasidagi ko\'chirish butun zanjirini kuzatish mumkin.' },

  { order: 47, ruDescription: 'Кнопка принятия трансфера подтверждает получение товаров на склад-получатель. Это действие выполняется сотрудниками принимающего склада.\n\nПри принятии можно скорректировать фактически полученное количество товаров, если оно отличается от указанного в документе. Расхождения фиксируются и могут быть основанием для претензий.\n\nПосле принятия товары зачисляются на остатки склада-получателя, а документ переходит в статус "Получен".', uzDescription: 'Transferni qabul qilish tugmasi tovarlarning qabul qiluvchi omborga kelishini tasdiqlaydi. Bu harakat qabul qiluvchi ombor xodimlari tomonidan amalga oshiriladi.\n\nQabul qilishda, agar hujjatda ko\'rsatilgandan farq qilsa, haqiqatda olingan tovar miqdorini tuzatish mumkin. Farqlar qayd etiladi va da\'volar uchun asos bo\'lishi mumkin.\n\nQabul qilingandan so\'ng tovarlar qabul qiluvchi omborning qoldiqlariga qabul qilinadi va hujjat "Qabul qilingan" holatiga o\'tadi.' },

  { order: 48, ruDescription: 'Фильтр трансферов по статусу позволяет отобрать документы по их текущему состоянию. Это упрощает работу с большим количеством документов перемещения.\n\nДоступные статусы для фильтрации: черновик, отправлен, получен, отменён. Можно выбрать несколько статусов одновременно для расширенного поиска.\n\nФильтр особенно полезен для менеджеров складов: отправители видят отправленные трансферы, а получатели — входящие для принятия.', uzDescription: 'Transferlarni holat bo\'yicha filtr hujjatlarni ularning joriy holati bo\'yicha tanlash imkonini beradi. Bu ko\'p miqdordagi ko\'chirish hujjatlari bilan ishlashni soddalashtiradi.\n\nFiltrlash uchun mavjud holatlar: qoralama, yuborilgan, qabul qilingan, bekor qilingan. Kengaytirilgan qidiruv uchun bir vaqtning o\'zida bir nechta holatni tanlash mumkin.\n\nFiltr ayniqsa ombor menejerlari uchun foydali: yuboruvchilar yuborilgan transferlarni, qabul qiluvchilar esa qabul qilish uchun kiruvchilarni ko\'rishadi.' },

  { order: 49, ruDescription: 'Кнопка отправки трансфера инициирует перемещение товаров со склада-отправителя. Это действие выполняется сотрудниками отправляющего склада.\n\nПри отправке система проверяет наличие товаров в нужном количестве и списывает их со склада. Товары переходят в статус "в пути" до момента принятия на складе-получателе.\n\nОтправку можно отменить, если товары ещё не приняты получателем. После принятия отмена невозможна.', uzDescription: 'Transferni yuborish tugmasi tovarlarning yuboruvchi ombordan ko\'chirilishini boshlaydi. Bu harakat yuboruvchi ombor xodimlari tomonidan amalga oshiriladi.\n\nYuborishda tizim kerakli miqdorda tovarlar mavjudligini tekshiradi va ularni ombordan yozib chiqaradi. Tovarlar qabul qiluvchi omborda qabul qilingunicha "yo\'lda" holatiga o\'tadi.\n\nAgar tovarlar hali qabul qiluvchi tomonidan qabul qilinmagan bo\'lsa, yuborishni bekor qilish mumkin. Qabul qilingandan so\'ng bekor qilish imkonsiz.' },

  { order: 50, ruDescription: 'Кнопка отмены трансфера прекращает процесс перемещения и возвращает товары на склад-отправитель. Это используется при невозможности доставки или изменении планов.\n\nОтменить можно только трансфер в статусе "Отправлен", но ещё не принятый получателем. При отмене товары возвращаются на остатки отправителя.\n\nОтмена трансфера требует указания причины и фиксируется в истории документа. Это помогает анализировать причины сбоев в логистике.', uzDescription: 'Transferni bekor qilish tugmasi ko\'chirish jarayonini to\'xtatadi va tovarlarni yuboruvchi omborga qaytaradi. Bu yetkazib berish imkonsizligida yoki rejalarning o\'zgarishida ishlatiladi.\n\nFaqat "Yuborilgan" holatida, lekin hali qabul qiluvchi tomonidan qabul qilinmagan transferni bekor qilish mumkin. Bekor qilishda tovarlar yuboruvchining qoldiqlariga qaytadi.\n\nTransferni bekor qilish sababni ko\'rsatishni talab qiladi va hujjat tarixida qayd etiladi. Bu logistikadagi uzilishlar sabablarini tahlil qilishga yordam beradi.' },

  // === СКЛАД: РЕАЛИЗАЦИЯ (51-55) ===
  { order: 51, ruDescription: 'Раздел "Реализация" предназначен для оформления отгрузки товаров контрагентам-покупателям. Это ключевой раздел для оптовых продаж и работы с корпоративными клиентами.\n\nВ разделе отображается список документов реализации с информацией о покупателе, дате, сумме и статусе отгрузки. Документы можно фильтровать по контрагенту, периоду и статусу.\n\nПравильное оформление реализации обеспечивает корректный списание товаров, начисление выручки и формирование дебиторской задолженности покупателя.', uzDescription: '"Realizatsiya" bo\'limi tovarlarni xaridor-kontragentlarga jo\'natishni rasmiylashtirish uchun mo\'ljallangan. Bu ulgurji sotuvlar va korporativ mijozlar bilan ishlash uchun asosiy bo\'lim.\n\nBo\'limda xaridor, sana, summa va jo\'natish holati haqida ma\'lumot bilan realizatsiya hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni kontragent, davr va holat bo\'yicha filtrlash mumkin.\n\nRealizatsiyaga to\'g\'ri rasmiylashtirish tovarlarning to\'g\'ri yozib chiqarilishini, tushumning hisoblanishini va xaridorning debitorlik qarzining shakllanishini ta\'minlaydi.' },

  { order: 52, ruDescription: 'Кнопка создания реализации открывает форму для оформления нового документа отгрузки товаров. Это первый шаг при продаже товаров контрагенту.\n\nВ форме необходимо указать покупателя, склад отпуска, добавить список товаров с количеством и ценами. Система проверяет наличие товаров на складе и рассчитывает сумму документа.\n\nПосле заполнения документ можно сохранить как черновик или оформить — товары будут списаны со склада, а документ станет основанием для расчётов с покупателем.', uzDescription: 'Realizatsiya yaratish tugmasi yangi tovar jo\'natish hujjatini rasmiylashtirish uchun formani ochadi. Bu tovarlarni kontragentga sotishda birinchi qadam.\n\nFormada xaridorni, jo\'natuvchi omborni ko\'rsatish, tovarlar ro\'yxatini miqdor va narxlar bilan qo\'shish kerak. Tizim omborda tovarlar mavjudligini tekshiradi va hujjat summasini hisoblaydi.\n\nTo\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki rasmiylashtirish mumkin — tovarlar ombordan yozib chiqariladi va hujjat xaridor bilan hisob-kitoblar uchun asos bo\'ladi.' },

  { order: 53, ruDescription: 'Поле выбора покупателя позволяет указать контрагента, которому отгружаются товары. Это обязательный реквизит документа реализации.\n\nПри вводе названия система предлагает варианты из справочника контрагентов. Можно также создать нового покупателя непосредственно из формы реализации.\n\nВыбранный покупатель автоматически подставляется в расчёты по дебиторской задолженности. История отгрузок конкретному покупателю доступна в его карточке.', uzDescription: 'Xaridorni tanlash maydoni tovarlar jo\'natiladigan kontragentni ko\'rsatish imkonini beradi. Bu realizatsiya hujjatining majburiy rekviziti.\n\nNom kiritilganda tizim kontragentlar ma\'lumotnomasidan variantlarni taklif qiladi. Shuningdek realizatsiya formasidan to\'g\'ridan-to\'g\'ri yangi xaridor yaratish mumkin.\n\nTanlangan xaridor avtomatik debitorlik qarzlari bo\'yicha hisob-kitoblarga qo\'yiladi. Aniq xaridorga jo\'natishlar tarixi uning kartochkasida mavjud.' },

  { order: 54, ruDescription: 'Функция печати реализации формирует печатную форму накладной для передачи покупателю. Это обязательный документ для оформления отгрузки.\n\nСистема предлагает несколько шаблонов: товарная накладная, расходная накладная, универсальный передаточный документ. Шаблоны соответствуют требованиям бухгалтерского и налогового учёта.\n\nПодписанная накладная является основанием для приёмки товаров покупателем и подтверждением перехода права собственности.', uzDescription: 'Realizatsiyani chop etish funksiyasi xaridorga uzatish uchun nakladnoyning bosma shaklini yaratadi. Bu jo\'natishni rasmiylashtirish uchun majburiy hujjat.\n\nTizim bir nechta shablonlarni taklif qiladi: tovar nakladnoysi, chiqim nakladnoysi, universal uzatish hujjati. Shablonlar buxgalteriya va soliq hisobi talablariga mos keladi.\n\nImzolangan nakladnaya xaridor tomonidan tovarlarni qabul qilish va mulk huquqining o\'tishini tasdiqlovchi asos hisoblanadi.' },

  { order: 55, ruDescription: 'Управление статусами реализации позволяет контролировать этапы отгрузки товаров. Статус показывает текущее состояние документа в цепочке продаж.\n\nДоступные статусы: черновик (документ готовится), оформлен (товары списаны со склада), отправлен (товары переданы покупателю). Каждый статус имеет свои ограничения на редактирование.\n\nИстория изменения статусов сохраняется и доступна для анализа. Это помогает отслеживать эффективность работы отдела продаж и логистики.', uzDescription: 'Realizatsiya holatlarini boshqarish tovarlarni jo\'natish bosqichlarini nazorat qilish imkonini beradi. Holat sotuvlar zanjiridagi hujjatning joriy holatini ko\'rsatadi.\n\nMavjud holatlar: qoralama (hujjat tayyorlanmoqda), rasmiylashtirilgan (tovarlar ombordan yozib chiqarilgan), yuborilgan (tovarlar xaridorga topshirilgan). Har bir holatning tahrirlash bo\'yicha o\'z cheklovlari bor.\n\nHolatlar o\'zgarish tarixi saqlanadi va tahlil uchun mavjud. Bu savdo va logistika bo\'limi ishining samaradorligini kuzatishga yordam beradi.' },

  // === СКЛАД: ПЕРЕОЦЕНКА (56-60) ===
  { order: 56, ruDescription: 'Раздел "Переоценка" предназначен для массового изменения цен товаров. Это необходимо при изменении закупочных цен, проведении акций или корректировке розничных цен.\n\nВ разделе отображается список документов переоценки с информацией о дате, количестве товаров и причине изменения цен. Каждый документ фиксирует изменение цен для определённой группы товаров.\n\nПереоценка позволяет одной операцией изменить цены для десятков и сотен товаров, что значительно экономит время по сравнению с построчным редактированием.', uzDescription: '"Qayta baholash" bo\'limi tovarlar narxlarini ommaviy o\'zgartirish uchun mo\'ljallangan. Bu xarid narxlarining o\'zgarishida, aksiyalar o\'tkazishda yoki chakana narxlarni tuzatishda zarur.\n\nBo\'limda sana, tovarlar soni va narxlar o\'zgarish sababi haqida ma\'lumot bilan qayta baholash hujjatlari ro\'yxati ko\'rsatiladi. Har bir hujjat aniq tovarlar guruhi uchun narxlar o\'zgarishini qayd etadi.\n\nQayta baholash bir operatsiyada o\'nlab va yuzlab tovarlar narxlarini o\'zgartirish imkonini beradi, bu satr bo\'yicha tahrirlash bilan solishtirganda vaqtni ancha tejaydi.' },

  { order: 57, ruDescription: 'Кнопка создания переоценки открывает форму для массового изменения цен товаров. Это первый шаг при необходимости обновить цены для группы товаров.\n\nВ форме нужно указать причину переоценки и добавить товары, цены которых нужно изменить. Товары можно добавить вручную, выбрать по категории или загрузить из файла.\n\nДля каждого товара указывается новая цена или процент изменения относительно текущей цены. Система показывает старую и новую цену для контроля.', uzDescription: 'Qayta baholash yaratish tugmasi tovarlar narxlarini ommaviy o\'zgartirish uchun formani ochadi. Bu tovarlar guruhi uchun narxlarni yangilash zarurati tug\'ilganda birinchi qadam.\n\nFormada qayta baholash sababini ko\'rsatish va narxlari o\'zgartirilishi kerak bo\'lgan tovarlarni qo\'shish kerak. Tovarlarni qo\'lda qo\'shish, kategoriya bo\'yicha tanlash yoki fayldan yuklash mumkin.\n\nHar bir tovar uchun yangi narx yoki joriy narxga nisbatan o\'zgarish foizi ko\'rsatiladi. Tizim nazorat uchun eski va yangi narxni ko\'rsatadi.' },

  { order: 58, ruDescription: 'Кнопка выбора товаров для переоценки открывает форму добавления товаров в документ. Это основной этап формирования документа переоценки.\n\nТовары можно добавлять несколькими способами: выбрать из списка с фильтрацией по категории, добавить по отдельности или импортировать список артикулов из файла.\n\nПри добавлении система показывает текущие цены товаров, что помогает определить направление и размер изменения. Можно предварительно просмотреть список выбранных товаров.', uzDescription: 'Qayta baholash uchun tovarlarni tanlash tugmasi hujjatga tovar qo\'shish formasini ochadi. Bu qayta baholash hujjatini shakllantirishning asosiy bosqichi.\n\nTovarlarni bir nechta usulda qo\'shish mumkin: kategoriya bo\'yicha filtrlash bilan ro\'yxatdan tanlash, alohida qo\'shish yoki fayldan artikullar ro\'yxatini import qilish.\n\nQo\'shishda tizim tovarlarning joriy narxlarini ko\'rsatadi, bu o\'zgarish yo\'nalishini va hajmini aniqlashga yordam beradi. Tanlangan tovarlar ro\'yxatini oldindan ko\'rish mumkin.' },

  { order: 59, ruDescription: 'Поле новой цены товара позволяет указать новое значение цены для каждого товара в документе переоценки. Это может быть конкретная сумма или процент от текущей цены.\n\nМожно указать фиксированную новую цену или задать формулу расчёта: увеличить на процент, уменьшить на сумму, округлить до определённого значения. Формулы применяются ко всем выбранным товарам.\n\nСистема автоматически рассчитывает новую цену и показывает разницу со старой ценой. Это помогает избежать ошибок при массовой переоценке.', uzDescription: 'Tovarning yangi narxi maydoni qayta baholash hujjatidagi har bir tovar uchun narxning yangi qiymatini ko\'rsatish imkonini beradi. Bu aniq summa yoki joriy narxning foizi bo\'lishi mumkin.\n\nBelgilangan yangi narxni ko\'rsatish yoki hisoblash formulasini berish mumkin: foizga oshirish, summani kamaytirish, aniq qiymatga yaxlitlash. Formulalar barcha tanlangan tovarlarga qo\'llaniladi.\n\nTizim avtomatik yangi narxni hisoblaydi va eski narx bilan farqni ko\'rsatadi. Bu ommaviy qayta baholashda xatolardan qochishga yordam beradi.' },

  { order: 60, ruDescription: 'Кнопка проведения переоценки применяет новые цены к выбранным товарам. Это финальное действие документа, после которого цены обновляются в системе.\n\nПри проведении система обновляет цены товаров в справочнике и фиксирует изменения в истории. Новые цены применяются к новым документам, а старые документы сохраняют цены на момент их создания.\n\nПроведённую переоценку можно отменить, если цены были изменены ошибочно. При отмене восстанавливаются предыдущие значения цен.', uzDescription: 'Qayta baholashni o\'tkazish tugmasi tanlangan tovarlarga yangi narxlarni qo\'llaydi. Bu hujjatning yakuniy harakati, undan so\'ng narxlar tizimda yangilanadi.\n\nO\'tkazishda tizim ma\'lumotnomada tovarlar narxlarini yangilaydi va o\'zgarishlarni tarixda qayd etadi. Yangi narxlar yangi hujjatlarga qo\'llaniladi, eski hujjatlar esa o\'z yaratilish vaqtidagi narxlarni saqlab qoladi.\n\nO\'tkazilgan qayta baholashni, agar narxlar xato o\'zgartirilgan bo\'lsa, bekor qilish mumkin. Bekor qilishda oldingi narx qiymatlari tiklanadi.' },

  // === СКЛАД: ИНВЕНТАРИЗАЦИЯ (61-65) ===
  { order: 61, ruDescription: 'Раздел "Инвентаризация" предназначен для проведения сверки фактических остатков товаров с учётными данными. Это важный инструмент контроля сохранности товарно-материальных ценностей.\n\nВ разделе отображается список документов инвентаризации с информацией о складе, дате проведения и статусе. Документы можно фильтровать по складу, периоду и результатам.\n\nРегулярное проведение инвентаризации помогает выявлять расхождения, анализировать их причины и принимать меры по предотвращению потерь.', uzDescription: '"Inventarizatsiya" bo\'limi faktik tovar qoldiqlarini hisob ma\'lumotlari bilan solishtirish uchun mo\'ljallangan. Bu tovar-moddaviy qadriyatlarning saqlanishini nazorat qilishning muhim vositasi.\n\nBo\'limda ombor, o\'tkazish sanasi va holat haqida ma\'lumot bilan inventarizatsiya hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni ombor, davr va natijalar bo\'yicha filtrlash mumkin.\n\nMuntazam inventarizatsiya o\'tkazish farqlarni aniqlash, ularning sabablarini tahlil qilish va yo\'qotishlarning oldini olish choralarni ko\'rishga yordam beradi.' },

  { order: 62, ruDescription: 'Кнопка создания инвентаризации открывает форму для проведения новой сверки остатков. Это первый шаг при планировании инвентаризации на складе.\n\nВ форме нужно указать склад, для которого проводится инвентаризация, и выбрать товары для проверки. Можно проверить все товары или только определённую категорию.\n\nСистема автоматически заполняет учётные остатки товаров. Остаётся ввести фактическое количество после пересчёта на складе.', uzDescription: 'Inventarizatsiya yaratish tugmasi yangi qoldiqlarni solishtirish uchun formani ochadi. Bu omborda inventarizatsiyani rejalashtirishda birinchi qadam.\n\nFormada inventarizatsiya o\'tkaziladigan omborni ko\'rsatish va tekshirish uchun tovarlarni tanlash kerak. Barcha tovarlarni yoki faqat aniq kategoriyani tekshirish mumkin.\n\nTizim avtomatik tovarlarning hisob qoldiqlarini to\'ldiradi. Omborda qayta hisoblangandan so\'ng haqiqiy miqdorni kiritish qoladi.' },

  { order: 63, ruDescription: 'Поле фактического остатка предназначено для ввода реального количества товаров, выявленного при пересчёте. Это ключевые данные инвентаризации.\n\nПосле ввода фактического количества система автоматически рассчитывает расхождение с учётным остатком. Положительное расхождение означает излишки, отрицательное — недостачу.\n\nВводить фактические остатки можно вручную или загружать из сканера штрих-кодов и терминала сбора данных. Это ускоряет процесс инвентаризации.', uzDescription: 'Haqiqiy qoldiq maydoni qayta hisoblashda aniqlangan tovarlarning haqiqiy miqdorini kiritish uchun mo\'ljallangan. Bu inventarizatsiyaning asosiy ma\'lumotlari.\n\nHaqiqiy miqdor kiritilgandan so\'ng tizim avtomatik hisob qoldig\'i bilan farqni hisoblaydi. Musbat farq ortiqchani, manfiy farq kamchilikni bildiradi.\n\nHaqiqiy qoldiqlarni qo\'lda kiritish yoki shtrix-kod skaneri va ma\'lumot yig\'ish terminalidan yuklash mumkin. Bu inventarizatsiya jarayonini tezlashtiradi.' },

  { order: 64, ruDescription: 'Вкладка расхождений инвентаризации показывает разницу между учётными и фактическими остатками. Это ключевой результат инвентаризации для анализа.\n\nРасхождения группируются по типу: излишки, недостачи, пересортица. Для каждого расхождения показывается товар, количество и возможная причина.\n\nНа основе расхождений можно автоматически создать документы оприходования излишков или списания недостач. Это упрощает оформление результатов инвентаризации.', uzDescription: 'Inventarizatsiya farqlari yorlig\'i hisob va haqiqiy qoldiqlar o\'rtasidagi farqni ko\'rsatadi. Bu tahlil uchun inventarizatsiyaning asosiy natijasi.\n\nFarqlar tur bo\'yicha guruhlanadi: ortiqcha, kamchilik, tartibsizlik. Har bir farq uchun tovar, miqdor va mumkin bo\'lgan sabab ko\'rsatiladi.\n\nFarqlar asosida avtomatik ortiqchalarni qabul qilish yoki kamchiliklarni yozib chiqarish hujjatlarini yaratish mumkin. Bu inventarizatsiya natijalarini rasmiylashtirishni soddalashtiradi.' },

  { order: 65, ruDescription: 'Кнопка принятия инвентаризации завершает процесс сверки и корректирует остатки в соответствии с фактическими данными. Это финальное действие документа инвентаризации.\n\nПри принятии система автоматически создаёт документы оприходования для излишков и списания для недостач. Эти документы проводятся и изменяют остатки товаров.\n\nРезультаты инвентаризации сохраняются в истории и доступны для аудита. Можно отследить, кто и когда проводил инвентаризацию и какие расхождения были выявлены.', uzDescription: 'Inventarizatsiyani qabul qilish tugmasi solishtirish jarayonini tugatadi va qoldiqlarni haqiqiy ma\'lumotlarga ko\'ra tuzatadi. Bu inventarizatsiya hujjatining yakuniy harakati.\n\nQabul qilishda tizim avtomatik ortiqchalar uchun qabul qilish va kamchiliklar uchun yozib chiqarish hujjatlarini yaratadi. Bu hujjatlar o\'tkaziladi va tovar qoldiqlarini o\'zgartiradi.\n\nInventarizatsiya natijalari tarixda saqlanadi va auditoriya uchun mavjud. Kim va qachon inventarizatsiya o\'tkazganini va qanday farqlar aniqlanganini kuzatish mumkin.' },

  // === СКЛАД: СПИСАНИЕ (66-70) ===
  { order: 66, ruDescription: 'Раздел "Списание" предназначен для оформления выбытия товаров по причинам, не связанным с продажей. Это необходимо для учёта потерь, порчи и других случаев уменьшения остатков.\n\nВ разделе отображается список документов списания с информацией о складе, причине, сумме и дате. Документы можно фильтровать по типу причины: порча, хищение, истечение срока годности.\n\nПравильное оформление списания обеспечивает корректный учёт себестоимости и помогает анализировать причины потерь для принятия мер по их снижению.', uzDescription: '"Yozib chiqarish" bo\'limi sotish bilan bog\'liq bo\'lmagan sabablarga ko\'ra tovarlarning chiqib ketishini rasmiylashtirish uchun mo\'ljallangan. Bu yo\'qotishlar, buzilish va qoldiqlarning kamayishining boshqa holatlarini hisobga olish uchun zarur.\n\nBo\'limda ombor, sabab, summa va sana haqida ma\'lumot bilan yozib chiqarish hujjatlari ro\'yxati ko\'rsatiladi. Hujjatlarni sabab turi bo\'yicha filtrlash mumkin: buzilish, o\'g\'irlik, yaroqlilik muddati tugash.\n\nYozib chiqarishga to\'g\'ri rasmiylashtirish tannarxning to\'g\'ri hisobini ta\'minlaydi va yo\'qotishlar sabablarini tahlil qilishga, ularni kamaytirish choralarni ko\'rishga yordam beradi.' },

  { order: 67, ruDescription: 'Кнопка создания списания открывает форму для оформления выбытия товаров. Это первый шаг при обнаружении товаров, которые нельзя продать или использовать.\n\nВ форме нужно указать склад, выбрать товары для списания и указать причину. Для каждого товара указывается количество, подлежащее списанию.\n\nСистема проверяет наличие достаточного количества товаров на складе и рассчитывает сумму списания по средней себестоимости.', uzDescription: 'Yozib chiqarish yaratish tugmasi tovarlarning chiqib ketishini rasmiylashtirish uchun formani ochadi. Bu sotib bo\'lmaydigan yoki foydalanib bo\'lmaydigan tovarlar aniqlanganda birinchi qadam.\n\nFormada omborni ko\'rsatish, yozib chiqarish uchun tovarlarni tanlash va sababni ko\'rsatish kerak. Har bir tovar uchun yozib chiqariladigan miqdor ko\'rsatiladi.\n\nTizim omborda yetarli miqdorda tovar borligini tekshiradi va yozib chiqarish summasini o\'rtacha tannarx bo\'yicha hisoblaydi.' },

  { order: 68, ruDescription: 'Поле причины списания позволяет выбрать основание для выбытия товаров. Это важная информация для анализа потерь и формирования отчётности.\n\nДоступные причины: порча при хранении, истечение срока годности, бой при транспортировке, хищение, моральный износ, потеря товарного вида. Выбор причины влияет на бухгалтерский учёт.\n\nСтатистика причин списания помогает выявить проблемные зоны в работе склада и принять меры по сокращению потерь.', uzDescription: 'Yozib chiqarish sababi maydoni tovarlarning chiqib ketishiga asosni tanlash imkonini beradi. Bu yo\'qotishlarni tahlil qilish va hisobotlarni shakllantirish uchun muhim ma\'lumot.\n\nMavjud sabablar: saqlashda buzilish, yaroqlilik muddati tugash, tashishda sinish, o\'g\'irlik, ma\'naviy eskirish, tovar ko\'rinishini yo\'qotish. Sabab tanlash buxgalteriya hisobiga ta\'sir qiladi.\n\nYozib chiqarish sabablari statistikasi ombor ishidagi muammoli joylarni aniqlashga va yo\'qotishlarni qisqartirish choralarni ko\'rishga yordam beradi.' },

  { order: 69, ruDescription: 'Поле ответственного за списание позволяет указать сотрудника, который несёт ответственность за списываемые товары. Это важно для контроля сохранности ценностей.\n\nОтветственный выбирается из справочника сотрудников. Обычно это материально ответственное лицо, за которым закреплён данный склад или товар.\n\nУказание ответственного помогает при разборе причин списания и определении степени вины конкретных сотрудников в случае потерь.', uzDescription: 'Yozib chiqarish bo\'yicha mas\'ul maydoni yozib chiqarilayotgan tovarlar uchun mas\'uliyatni oluvchi xodimni ko\'rsatish imkonini beradi. Bu qadriyatlarning saqlanishini nazorat qilish uchun muhim.\n\nMas\'ul xodimlar ma\'lumotnomasidan tanlanadi. Odatda bu ushbu ombor yoki tovar bilan bog\'langan moddiy mas\'ul shaxs.\n\nMas\'ulni ko\'rsatish yozib chiqarish sabablarini tahlil qilishda va yo\'qotishlar holatida aniq xodimlarning ayb darajasini aniqlashda yordam beradi.' },

  { order: 70, ruDescription: 'Кнопка проведения списания завершает оформление документа и списывает товары со склада. Это финальное действие, после которого товары перестают числиться в учёте.\n\nПри проведении система проверяет заполнение всех обязательных полей и наличие товаров на складе. Списанные товары исключаются из отчётов по остаткам и себестоимости.\n\nСумма списания отражается в затратах организации и влияет на финансовый результат. История списаний сохраняется для аудита и анализа.', uzDescription: 'Yozib chiqarishni o\'tkazish tugmasi hujjatni rasmiylashtirishni tugatadi va tovarlarni ombordan yozib chiqaradi. Bu yakuniy harakat, undan so\'ng tovarlar hisobda ko\'rsatilmaydi.\n\nO\'tkazishda tizim barcha majburiy maydonlarning to\'ldirilishini va omborda tovarlar mavjudligini tekshiradi. Yozib chiqarilgan tovarlar qoldiqlar va tannarx bo\'yicha hisobotlardan chiqariladi.\n\nYozib chiqarish summasi tashkilot xarajatlarida aks etadi va moliyaviy natijaga ta\'sir qiladi. Yozib chiqarishlar tarixi auditoriya va tahlil uchun saqlanadi.' },

  // === СКЛАД: ГРУППИРОВКА (71-73) ===
  { order: 71, ruDescription: 'Раздел "Группировка" предназначен для создания и управления группами товаров. Это позволяет структурировать ассортимент для удобства работы и отчётности.\n\nГруппы товаров образуют иерархическую структуру, отражающую логику организации бизнеса. Можно создавать группы по категориям, брендам, поставщикам или другим критериям.\n\nИспользование групп упрощает поиск товаров, формирование отчётов и управление ценами. К группе можно применить массовые действия: изменить категорию, установить наценку.', uzDescription: '"Guruhlash" bo\'limi tovar guruhlarini yaratish va boshqarish uchun mo\'ljallangan. Bu ishlash va hisobotlarni qulay qilish uchun assortimentni tuzilishini ta\'minlaydi.\n\nTovar guruhlari biznes tashkil etish mantiqini aks ettiruvchi ierarxik tuzilmani hosil qiladi. Guruhlarni kategoriyalar, brendlar, yetkazib beruvchilar yoki boshqa mezonlar bo\'yicha yaratish mumkin.\n\nGuruhlardan foydalanish tovarlarni qidirish, hisobotlarni shakllantirish va narxlarni boshqarishni soddalashtiradi. Guruhga ommaviy harakatlar qo\'llash mumkin: kategoriyani o\'zgartirish, chegirma o\'rnatish.' },

  { order: 72, ruDescription: 'Кнопка создания группы открывает форму для добавления новой группы товаров. Это первый шаг при структурировании ассортимента по новому признаку.\n\nВ форме нужно указать название группы и её родительскую группу, если создаётся подгруппа. Можно также добавить описание и настроить параметры группы.\n\nПосле создания группы в неё можно добавлять товары из справочника. Один товар может входить в несколько групп для разных целей.', uzDescription: 'Guruh yaratish tugmasi yangi tovar guruhi qo\'shish uchun formani ochadi. Bu assortimentni yangi belgi bo\'yicha tuzilishning birinchi qadami.\n\nFormada guruh nomini va, agar ost-guruh yaratilayotgan bo\'lsa, uning ota guruhini ko\'rsatish kerak. Shuningdek tavsif qo\'shish va guruh parametrlarini sozlash mumkin.\n\nGuruh yaratilgandan so\'ng unga ma\'lumotnomadan tovarlarni qo\'shish mumkin. Bitta tovar turli maqsadlar uchun bir nechta guruhga kiritilishi mumkin.' },

  { order: 73, ruDescription: 'Кнопка добавления товаров в группу открывает форму для включения товаров в выбранную группу. Это позволяет пополнять группу новыми позициями.\n\nТовары можно добавлять по одному или выбрать сразу несколько из справочника. Также доступен поиск по названию и фильтрация по категории для быстрого отбора.\n\nИз группы товары можно исключать, если они перестали соответствовать критериям. История изменений группы сохраняется для контроля.', uzDescription: 'Guruhga tovar qo\'shish tugmasi tanlangan guruhga tovarlarni kiritish uchun formani ochadi. Bu guruhni yangi pozitsiyalar bilan to\'ldirish imkonini beradi.\n\nTovarlarni bittadan yoki ma\'lumotnomadan bir vaqtning o\'zida bir nechtasini tanlab qo\'shish mumkin. Shuningdek tez tanlash uchun nom bo\'yicha qidiruv va kategoriya bo\'yicha filtrlash ham mavjud.\n\nAgar tovarlar mezonlarga mos kelmay qolsa, ularni guruhdan chiqarib tashlash mumkin. Guruh o\'zgarishlari tarixi nazorat uchun saqlanadi.' },

  // === СКЛАД: ВЕСОВЫЕ ТОВАРЫ (74-76) ===
  { order: 74, ruDescription: 'Раздел "Весовые товары" предназначен для управления товарами, которые продаются на вес. Это особая категория товаров, требующая специфического учёта.\n\nК весовым товарам относятся продукты питания: мясные изделия, сыры, кондитерские изделия, фрукты и овощи. Такие товары требуют точного взвешивания при каждой операции.\n\nСистема поддерживает работу с весовыми товарами: расчёт цены за единицу веса, учёт веса тары, интеграция с электронными весами. Это обеспечивает точность расчётов с покупателями.', uzDescription: '"Og\'irlikli tovarlar" bo\'limi og\'irlik bo\'yicha sotiladigan tovarlarni boshqarish uchun mo\'ljallangan. Bu o\'ziga xos hisobni talab qiluvchi tovarlarning alohida toifasi.\n\nOg\'irlikli tovarlarga oziq-ovqat mahsulotlari kiradi: go\'sht mahsulotlari, pishloqlar, konditer mahsulotlari, meva va sabzavotlar. Bunday tovarlar har bir operatsiyada aniq tortishni talab qiladi.\n\nTizim og\'irlikli tovarlar bilan ishlashni qo\'llab-quvvatlaydi: og\'irlik birligi uchun narxni hisoblash, tara og\'irligini hisobga olish, elektron tarozilar bilan integratsiya. Bu xaridorlar bilan hisob-kitoblarning aniqligini ta\'minlaydi.' },

  { order: 75, ruDescription: 'Настройка весового товара позволяет задать параметры для корректного учёта весовых позиций. Это специфические настройки, отличающиеся от штучных товаров.\n\nМожно указать единицу измерения: килограмм, грамм, фунт. Также настраивается точность взвешивания: до грамма, до 10 грамм, до 100 грамм в зависимости от типа товара.\n\nДля весовых товаров устанавливается цена за единицу веса, а не за штуку. При продаже система автоматически пересчитывает стоимость в зависимости от веса.', uzDescription: 'Og\'irlikli tovarni sozlash og\'irlikli pozitsiyalarni to\'g\'ri hisoblash uchun parametrlarni belgilash imkonini beradi. Bu donali tovarlardan farq qiluvchi o\'ziga xos sozlamalar.\n\nO\'lchov birligini ko\'rsatish mumkin: kilogramm, gramm, funt. Shuningdek tortish aniqligi ham sozlanadi: grammgacha, 10 grammgacha, 100 grammgacha, tovar turiga qarab.\n\nOg\'irlikli tovarlar uchun dona uchun emas, og\'irlik birligi uchun narx belgilanadi. Sotishda tizim avtomatik ravishda xarajatni og\'irlikka qarab qayta hisoblaydi.' },

  { order: 76, ruDescription: 'Поле тары весового товара позволяет учесть вес упаковки при взвешивании. Это необходимо для точного расчёта стоимости товара без упаковки.\n\nПри взвешивании товара с тарой система автоматически вычитает вес тары и показывает только чистый вес товара. Вес тары можно задать для каждого товара или группы товаров.\n\nКорректный учёт тары важен для честных расчётов с покупателями и соответствия требованиям законодательства о защите прав потребителей.', uzDescription: 'Og\'irlikli tovar tarasi maydoni tortishda qadoqlash og\'irligini hisobga olish imkonini beradi. Bu qadoqsiz tovar narxini aniq hisoblash uchun zarur.\n\nTara bilan tovar tortilganda tizim avtomatik tara og\'irligini ayirib, faqat tovarning toza og\'irligini ko\'rsatadi. Tara og\'irligini har bir tovar yoki tovar guruhi uchun berish mumkin.\n\nTaraning to\'g\'ri hisobi xaridorlar bilan adolatli hisob-kitoblar va iste\'molchilar huquqlarini himoya qilish to\'g\'risidagi qonun talablariga mos kelish uchun muhim.' },

  // === СКЛАД: ИМПОРТ (77-80) ===
  { order: 77, ruDescription: 'Раздел "Импорт товаров" предназначен для массовой загрузки товаров из внешних файлов. Это необходимо при первоначальном заполнении базы или обновлении ассортимента.\n\nИмпорт поддерживает форматы Excel и CSV. Можно загрузить как новые товары, так и обновить существующие по артикулу или штрих-коду.\n\nПроцесс импорта включает несколько этапов: загрузка файла, сопоставление полей, проверка данных и загрузка в базу. Каждый этап контролируется системой для предотвращения ошибок.', uzDescription: '"Tovarlarni import qilish" bo\'limi tashqi fayllardan tovarlarni ommaviy yuklash uchun mo\'ljallangan. Bu bazani dastlab to\'ldirishda yoki assortimentni yangilashda zarur.\n\nImport Excel va CSV formatlarini qo\'llab-quvvatlaydi. Yangi tovarlarni yuklash ham, artikul yoki shtrix-kod bo\'yicha mavjudlarni yangilash ham mumkin.\n\nImport jarayoni bir nechta bosqichni o\'z ichiga oladi: faylni yuklash, maydonlarni moslashtirish, ma\'lumotlarni tekshirish va bazaga yuklash. Har bir bosqich xatolarning oldini olish uchun tizim tomonidan nazorat qilinadi.' },

  { order: 78, ruDescription: 'Кнопка загрузки файла импорта открывает форму для выбора файла с данными о товарах. Это первый этап процесса импорта.\n\nФайл должен содержать колонки с данными о товарах: наименование, артикул, штрих-код, цена, категория. Рекомендуется использовать шаблон, который можно скачать в системе.\n\nПосле загрузки система анализирует структуру файла и показывает предпросмотр первых строк для проверки корректности данных.', uzDescription: 'Import faylini yuklash tugmasi tovarlar haqidagi ma\'lumotlar bilan faylni tanlash uchun formani ochadi. Bu import jarayonining birinchi bosqichi.\n\nFaylda tovarlar haqidagi ma\'lumotlar bilan ustunlar bo\'lishi kerak: nom, artikul, shtrix-kod, narx, kategoriya. Tizimda yuklab olinadigan shablondan foydalanish tavsiya etiladi.\n\nYuklangandan so\'ng tizim fayl tuzilmasini tahlil qiladi va ma\'lumotlar to\'g\'riligini tekshirish uchun birinchi qatorlarning oldindan ko\'rishini ko\'rsatadi.' },

  { order: 79, ruDescription: 'Этап сопоставления полей позволяет связать колонки файла с полями системы. Это необходимо для корректной интерпретации данных при импорте.\n\nСистема автоматически пытается определить соответствие по названиям колонок. Если автоматическое определение неверно, можно задать соответствие вручную для каждого поля.\n\nОбязательные поля должны быть обязательно сопоставлены, иначе импорт не будет возможен. Система показывает процент заполненности обязательных полей в файле.', uzDescription: 'Maydonlarni moslashtirish bosqichi fayl ustunlarini tizim maydonlari bilan bog\'lash imkonini beradi. Bu importda ma\'lumotlarni to\'g\'ri talqin qilish uchun zarur.\n\nTizim avtomatik ravishda ustun nomlari bo\'yicha moslikni aniqlashga harakat qiladi. Agar avtomatik aniqlash noto\'g\'ri bo\'lsa, har bir maydon uchun moslikni qo\'lda berish mumkin.\n\nMajburiy maydonlar albatta moslashtirilishi kerak, aks holda import imkonsiz bo\'ladi. Tizim faylda majburiy maydonlarning to\'ldirilish foizini ko\'rsatadi.' },

  { order: 80, ruDescription: 'Кнопка запуска импорта начинает загрузку товаров в базу данных. Это финальный этап процесса, после которого товары появляются в системе.\n\nПеред запуском система показывает сводку: сколько товаров будет добавлено, сколько обновлено и сколько строк с ошибками пропущено. Можно вернуться на предыдущие этапы для исправления.\n\nВо время загрузки отображается прогресс-бар. После завершения формируется отчёт об импорте с детализацией по каждому товару.', uzDescription: 'Importni boshlash tugmasi tovarlarni bazaga yuklashni boshlaydi. Bu jarayonning yakuniy bosqichi, undan so\'ng tovarlar tizimda paydo bo\'ladi.\n\nBoshlashdan oldin tizim hisobotni ko\'rsatadi: nechta tovar qo\'shiladi, nechtasi yangilanadi va nechta xatoli qatorlar o\'tkazib yuboriladi. Tuzatish uchun oldingi bosqichlarga qaytish mumkin.\n\nYuklash paytida progress-bar ko\'rsatiladi. Tugagandan so\'ng har bir tovar bo\'yicha batafsil import hisoboti shakllantiriladi.' },

  // === СКЛАД: ТЕХКАРТЫ (81-85) ===
  { order: 81, ruDescription: 'Раздел "Техкарты" предназначен для управления рецептурами и калькуляцией при производстве. Это ключевой раздел для предприятий общественного питания и производства.\n\nТехкарта описывает состав готового изделия: какие ингредиенты и в каком количестве используются. На основе техкарты автоматически рассчитывается себестоимость продукта.\n\nИспользование техкарт позволяет контролировать расход материалов, стандартизировать качество продукции и анализировать рентабельность производства.', uzDescription: '"Tex-kartalar" bo\'limi ishlab chiqarishda retseptura va kalkulyatsiyani boshqarish uchun mo\'ljallangan. Bu ommaviy ovqatlanish va ishlab chiqarish korxonalari uchun asosiy bo\'lim.\n\nTex-karta tayyor mahsulot tarkibini tasvirlaydi: qanday ingredientlar va qancha miqdorda ishlatiladi. Tex-karta asosida mahsulot tannarxi avtomatik hisoblanadi.\n\nTex-kartalardan foydalanish materiallar sarfini nazorat qilish, mahsulot sifatini standartlashtirish va ishlab chiqarish rentabelligini tahlil qilish imkonini beradi.' },

  { order: 82, ruDescription: 'Кнопка создания техкарты открывает форму для добавления новой рецептуры. Это первый шаг при разработке нового продукта или блюда.\n\nВ форме нужно указать наименование продукта, единицу измерения выхода и добавить ингредиенты с указанием количества. Ингредиенты выбираются из справочника товаров.\n\nТакже можно указать технологию приготовления, время подготовки и другие параметры, важные для производства. Это помогает стандартизировать процессы.', uzDescription: 'Tex-karta yaratish tugmasi yangi retseptura qo\'shish uchun formani ochadi. Bu yangi mahsulot yoki taom ishlab chiqishda birinchi qadam.\n\nFormada mahsulot nomini, chiqish o\'lchov birligini ko\'rsatish va miqdori bilan ingredientlarni qo\'shish kerak. Ingredientlar tovarlar ma\'lumotnomasidan tanlanadi.\n\nShuningdek tayyorlash texnologiyasi, tayyorgarlik vaqti va ishlab chiqarish uchun muhim boshqa parametrlarni ko\'rsatish mumkin. Bu jarayonlarni standartlashtirishga yordam beradi.' },

  { order: 83, ruDescription: 'Таблица ингредиентов техкарты содержит список материалов, необходимых для производства единицы продукции. Это основа расчёта себестоимости.\n\nДля каждого ингредиента указывается: наименование товара, количество на единицу продукции, единица измерения. Система автоматически подтягивает текущую цену ингредиента.\n\nПри изменении цен ингредиентов себестоимость продукции пересчитывается автоматически. Это позволяет отслеживать динамику затрат на производство.', uzDescription: 'Tex-karta ingredientlari jadvali mahsulot birligini ishlab chiqarish uchun kerakli materiallar ro\'yxatini o\'z ichiga oladi. Bu tannarxni hisoblashning asosi.\n\nHar bir ingredient uchun ko\'rsatiladi: tovar nomi, mahsulot birligiga miqdori, o\'lchov birligi. Tizim ingredientning joriy narxini avtomatik tortadi.\n\nIngredient narxlari o\'zgarganda mahsulot tannarxi avtomatik qayta hisoblanadi. Bu ishlab chiqarish xarajatlari dinamikasini kuzatish imkonini beradi.' },

  { order: 84, ruDescription: 'Поле себестоимости техкарты показывает расчётную стоимость производства единицы продукции. Это важнейший показатель для ценообразования.\n\nСебестоимость рассчитывается автоматически как сумма стоимостей всех ингредиентов. Учитываются текущие цены закупки материалов и их количество по рецептуре.\n\nНа основе себестоимости можно установить наценку и определить розничную цену. Система показывает рекомендуемую цену с учётом заданного уровня рентабельности.', uzDescription: 'Tex-karta tannarxi maydoni mahsulot birligini ishlab chiqarishning hisob-kitob qiymatini ko\'rsatadi. Bu narx belgilash uchun eng muhim ko\'rsatkich.\n\nTannarx barcha ingredientlar qiymatlari yig\'indisi sifatida avtomatik hisoblanadi. Materiallarning joriy xarid narxlari va retseptura bo\'yicha ularning miqdori hisobga olinadi.\n\nTannarx asosida chegirma o\'rnatish va chakana narxni aniqlash mumkin. Tizim belgilangan daromadlik darajasini hisobga olgan holda tavsiya etilgan narxni ko\'rsatadi.' },

  { order: 85, ruDescription: 'Поле готовой продукции техкарты позволяет указать, какой товар получается в результате производства. Это связывает техкарту с справочником товаров.\n\nГотовый продукт выбирается из справочника товаров или создаётся новый. При производстве через акт изготовления будет создаваться именно этот товар.\n\nЕсли готовый продукт является весовым, система учтёт вес выхода по техкарте. Это важно для корректного расчёта себестоимости единицы веса.', uzDescription: 'Tex-karta tayyor mahsuloti maydoni ishlab chiqarish natijasida qanday tovar olinishini ko\'rsatish imkonini beradi. Bu tex-kartani tovarlar ma\'lumotnomasi bilan bog\'laydi.\n\nTayyor mahsulot tovarlar ma\'lumotnomasidan tanlanadi yoki yangisi yaratiladi. Ishlab chiqarish akri orqali ishlab chiqarishda aynan shu tovar yaratiladi.\n\nAgar tayyor mahsulot og\'irlikli bo\'lsa, tizim tex-karta bo\'yicha chiqish og\'irligini hisobga oladi. Bu og\'irlik birligi tannarxini to\'g\'ri hisoblash uchun muhim.' },

  // === СКЛАД: АКТ ИЗГОТОВЛЕНИЯ (86-90) ===
  { order: 86, ruDescription: 'Раздел "Акт изготовления" предназначен для оформления выпуска готовой продукции. Это документ, который списывает материалы и приходует готовый продукт.\n\nВ разделе отображается список актов изготовления с информацией о продукте, количестве, дате и статусе. Каждый акт связан с техкартой, по которой производился продукт.\n\nПравильное оформление актов обеспечивает корректный учёт материалов и готовой продукции, а также расчёт фактической себестоимости производства.', uzDescription: '"Ishlab chiqarish akri" bo\'limi tayyor mahsulot chiqarishni rasmiylashtirish uchun mo\'ljallangan. Bu materiallarni yozib chiqarib, tayyor mahsulotni qabul qiluvchi hujjat.\n\nBo\'limda mahsulot, miqdor, sana va holat haqida ma\'lumot bilan ishlab chiqarish aktlari ro\'yxati ko\'rsatiladi. Har bir akt mahsulot ishlab chiqarilgan tex-karta bilan bog\'langan.\n\nAklarni to\'g\'ri rasmiylashtirish materiallar va tayyor mahsulotning to\'g\'ri hisobini, shuningdek ishlab chiqarishning faktik tannarxini hisoblashni ta\'minlaydi.' },

  { order: 87, ruDescription: 'Кнопка создания акта изготовления открывает форму для оформления нового производства продукции. Это первый шаг при выпуске партии готового продукта.\n\nВ форме нужно выбрать техкарту, указать количество производимого продукта и склад, на который поступит готовая продукция. Система автоматически определит необходимые материалы.\n\nПосле заполнения документ можно сохранить как черновик или провести — материалы будут списаны, а готовый продукт оприходован.', uzDescription: 'Ishlab chiqarish akri yaratish tugmasi yangi mahsulot ishlab chiqarishni rasmiylashtirish uchun formani ochadi. Bu tayyor mahsulot partiyasini chiqarishda birinchi qadam.\n\nFormada tex-kartani tanlash, ishlab chiqarilayotgan mahsulot miqdorini va tayyor mahsulot keladigan omborni ko\'rsatish kerak. Tizim kerakli materiallarni avtomatik aniqlaydi.\n\nTo\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki o\'tkazish mumkin — materiallar yozib chiqariladi va tayyor mahsulot qabul qilinadi.' },

  { order: 88, ruDescription: 'Поле выбора техкарты позволяет указать рецептуру для производства. Это ключевой параметр, определяющий состав и себестоимость продукции.\n\nПри выборе техкарты система автоматически заполняет список необходимых материалов и их количество для указанного объёма производства. Можно скорректировать количество при необходимости.\n\nТехкарту можно выбрать из списка или найти по названию. История использования техкарты показывает, когда и в каком объёме производился данный продукт.', uzDescription: 'Tex-kartani tanlash maydoni ishlab chiqarish uchun retsepturani ko\'rsatish imkonini beradi. Bu mahsulot tarkibi va tannarxini belgilovchi asosiy parametr.\n\nTex-karta tanlanganda tizim kerakli materiallar ro\'yxatini va ularning ko\'rsatilgan ishlab chiqarish hajmi uchun miqdorini avtomatik to\'ldiradi. Zarurat bo\'lganda miqdorni tuzatish mumkin.\n\nTex-kartani ro\'yxatdan tanlash yoki nom bo\'yicha qidirish mumkin. Tex-kartadan foydalanish tarixi ushbu mahsulot qachon va qanday hajmda ishlab chiqarilganini ko\'rsatadi.' },

  { order: 89, ruDescription: 'Поле количества продукции позволяет указать, сколько единиц продукта производится по данному акту. Это влияет на расчёт необходимых материалов.\n\nСистема автоматически пересчитывает количество ингредиентов на основании техкарты умноженное на указанное количество продукции. Также рассчитывается общая себестоимость партии.\n\nМожно указать фактическое количество готового продукта, если оно отличается от планового. Это важно для анализа эффективности производства.', uzDescription: 'Mahsulot miqdori maydoni ushbu akt bo\'yicha necha birlik mahsulot ishlab chiqarilayotganini ko\'rsatish imkonini beradi. Bu kerakli materiallarni hisoblashga ta\'sir qiladi.\n\nTizim tex-karta asosida ingredientlar miqdorini ko\'rsatilgan mahsulot miqdoriga ko\'paytirib avtomatik qayta hisoblaydi. Shuningdek partiyaning umumiy tannarxi ham hisoblanadi.\n\nAgar rejalashtirilgandan farq qilsa, tayyor mahsulotning haqiqiy miqdorini ko\'rsatish mumkin. Bu ishlab chiqarish samaradorligini tahlil qilish uchun muhim.' },

  { order: 90, ruDescription: 'Кнопка проведения акта изготовления завершает оформление и проводит документы списания материалов и оприходования продукции. Это финальное действие.\n\nПри проведении система проверяет наличие материалов на складе в нужном количестве. Если материалов недостаточно, система покажет предупреждение и предложит закупить недостающее.\n\nПосле проведения материалы списываются со склада, а готовый продукт поступает на остатки. Фактическая себестоимость фиксируется и может отличаться от плановой.', uzDescription: 'Ishlab chiqarish akriini o\'tkazish tugmasi rasmiylashtirishni tugatadi va materiallarni yozib chiqarish hamda mahsulotni qabul qilish hujjatlarini o\'tkazadi. Bu yakuniy harakat.\n\nO\'tkazishda tizim omborda kerakli miqdorda materiallar mavjudligini tekshiradi. Agar materiallar yetarli bo\'lmasa, tizim ogohlantirish ko\'rsatadi va yetishmayotganni sotib olishni taklif qiladi.\n\nO\'tkazilgandan so\'ng materiallar ombordan yozib chiqariladi va tayyor mahsulot qoldiqlarga keladi. Faktik tannarx belgilanadi va rejalashtirilgandan farq qilishi mumkin.' },

  // === СКЛАД: ИЗБРАННЫЕ (91-93) ===
  { order: 91, ruDescription: 'Раздел "Избранные товары" содержит список товаров, которые пользователь отметил как часто используемые. Это персональный список для быстрого доступа.\n\nИзбранные товары отображаются в верхней части интерфейса и в отдельном разделе. При создании документов можно быстро добавить товар из избранного, не прибегая к поиску по всему справочнику.\n\nСписок избранного индивидуален для каждого пользователя. Это позволяет каждому сотруднику настроить удобный доступ к нужным ему товарам.', uzDescription: '"Sevimli tovarlar" bo\'limi foydalanuvchi tez-tez ishlatiladigan deb belgilagan tovarlar ro\'yxatini o\'z ichiga oladi. Bu tez kirish uchun shaxsiy ro\'yxat.\n\nSevimli tovarlar interfeysning yuqori qismida va alohida bo\'limda ko\'rsatiladi. Hujjatlar yaratishda butun ma\'lumotnomada qidirishga murojaat qilmasdan sevimlilardan tovarni tez qo\'shish mumkin.\n\nSevimlilar ro\'yxati har bir foydalanuvchi uchun individual. Bu har bir xodimga o\'zi kerak bo\'lgan tovarlarga qulay kirishni sozlash imkonini beradi.' },

  { order: 92, ruDescription: 'Функция удаления из избранного убирает товар из персонального списка. Это используется, когда товар перестал быть актуальным для частого использования.\n\nУдалить из избранного можно одним кликом по иконке звезды. Товар остаётся в справочнике, но исчезает из списка избранного.\n\nСписок избранного можно полностью очистить или пересортировать. Рекомендуется периодически обновлять список для максимальной эффективности.', uzDescription: 'Sevimlilardan o\'chirish funksiyasi tovarni shaxsiy ro\'yxatdan olib tashlaydi. Bu tovar tez-tez ishlatilish uchun dolzarb bo\'lmay qolganda ishlatiladi.\n\nSevimlilardan yulduzcha ikonkasini bir marta bosish orqali o\'chirish mumkin. Tovar ma\'lumotnomada qoladi, lekin sevimlilar ro\'yxatidan yo\'qoladi.\n\nSevimlilar ro\'yxatini to\'liq tozalash yoki qayta saralash mumkin. Maksimal samaradorlik uchun ro\'yxatni vaqti-vaqti bilan yangilash tavsiya etiladi.' },

  { order: 93, ruDescription: 'Функция добавления всех в чек позволяет одним действием включить все избранные товары в документ продажи. Это ускоряет работу при типовых заказах.\n\nПри использовании функции система добавляет все товары из избранного в текущий чек или документ реализации. Количество каждого товара устанавливается по умолчанию и может быть скорректировано.\n\nЭта функция особенно полезна для менеджеров, работающих с постоянными клиентами, которые регулярно заказывают один и тот же набор товаров.', uzDescription: 'Hammasini chekka qo\'shish funksiyasi bitta harakat bilan barcha sevimli tovarlarni sotish hujjatiga kiritish imkonini beradi. Bu tipik buyurtmalar bilan ishlashni tezlashtiradi.\n\nFunksiyadan foydalanilganda tizim sevimlilardagi barcha tovarlarni joriy chekka yoki realizatsiya hujjatiga qo\'shadi. Har bir tovar miqdori standart bo\'yicha o\'rnatiladi va tuzatilishi mumkin.\n\nBu funksiya ayniqsa doimiy mijozlar bilan ishlaydigan, muntazam ravishda bir xil tovarlar to\'plamini buyurtma qiluvchi menejerlar uchun foydali.' },

  // === СПРАВОЧНИК: ПЕРСОНАЛ (94-100) ===
  { order: 94, ruDescription: 'Раздел "Персонал" предназначен для управления сотрудниками организации. Это центральное место для ведения кадрового учёта и настройки прав доступа.\n\nВ разделе отображается список всех сотрудников с информацией о должности, подразделении и статусе. Можно искать сотрудников по фамилии, фильтровать по подразделению.\n\nПравильное ведение справочника персонала обеспечивает корректный документооборот, расчёт заработной платы и разграничение прав доступа к системе.', uzDescription: '"Personal" bo\'limi tashkilot xodimlarini boshqarish uchun mo\'ljallangan. Bu kadrlar hisobini yuritish va kirish huquqlarini sozlash uchun markaziy joy.\n\nBo\'limda lavozim, bo\'linma va holat haqida ma\'lumot bilan barcha xodimlar ro\'yxati ko\'rsatiladi. Xodimlarni familiya bo\'yicha qidirish, bo\'linma bo\'yicha filtrlash mumkin.\n\nPersonal ma\'lumotnomasini to\'g\'ri yuritish hujjat aylanishini, ish haqini hisoblashni va tizimga kirish huquqlarini ajratishni ta\'minlaydi.' },

  { order: 95, ruDescription: 'Кнопка добавления сотрудника открывает форму для создания карточки нового работника. Это первый шаг при приёме сотрудника на работу.\n\nВ форме нужно указать фамилию, имя, отчество, должность, подразделение и контактные данные. Также настраивается учётная запись для входа в систему.\n\nПосле сохранения сотрудник появляется в справочнике и может быть назначен ответственным в документах. История изменений карточки сохраняется.', uzDescription: 'Xodim qo\'shish tugmasi yangi ishchi kartochkasini yaratish uchun formani ochadi. Bu xodimni ishga qabul qilishda birinchi qadam.\n\nFormada familiya, ism, sharif, lavozim, bo\'linma va aloqa ma\'lumotlarini ko\'rsatish kerak. Shuningdek tizimga kirish uchun hisob qaydnomasi sozlanadi.\n\nSaqlangandan so\'ng xodim ma\'lumotnomada paydo bo\'ladi va hujjatlarda mas\'ul etib tayinlanishi mumkin. Kartochka o\'zgarishlari tarixi saqlanadi.' },

  { order: 96, ruDescription: 'Карточка сотрудника содержит полную информацию о работнике: персональные данные, должность, права доступа, история работы. Это детальное представление сотрудника в системе.\n\nВ карточке можно изменить персональные данные, назначить роль и права доступа, просмотреть историю документов, созданных сотрудником. Это помогает администраторам управлять учётными записями.\n\nКарточка также содержит информацию о материальной ответственности сотрудника и закреплённых за ним складах.', uzDescription: 'Xodim kartochkasi ishchi haqida to\'liq ma\'lumotni o\'z ichiga oladi: shaxsiy ma\'lumotlar, lavozim, kirish huquqlari, ish tarixi. Bu tizimdagi xodimning batafsil ko\'rinishi.\n\nKartochkada shaxsiy ma\'lumotlarni o\'zgartirish, rol va kirish huquqlarini tayinlash, xodim yaratgan hujjatlar tarixini ko\'rish mumkin. Bu administratorlarga hisob qaydnomalarini boshqarishga yordam beradi.\n\nKartochka shuningdek xodimning moddiy mas\'uliyati va unga biriktirilgan omborlar haqida ma\'lumotni o\'z ichiga oladi.' },

  { order: 97, ruDescription: 'Поле роли сотрудника определяет набор прав доступа к функциям системы. Это ключевой элемент безопасности и разделения полномочий.\n\nДоступные роли: администратор, менеджер, кассир, кладовщик, бухгалтер. Каждая роль имеет свой предустановленный набор прав, который можно дополнительно настроить.\n\nПравильное назначение ролей предотвращает несанкционированный доступ к чувствительным функциям и данным. История изменений ролей сохраняется для аудита.', uzDescription: 'Xodim roli maydoni tizim funksiyalariga kirish huquqlari to\'plamini belgilaydi. Bu xavfsizlik va vakolatlarni bo\'lishning asosiy elementi.\n\nMavjud rollar: administrator, menejer, kassir, omborchi, buxgalter. Har bir rolning oldindan o\'rnatilgan huquqlar to\'plami bor, uni qo\'shimcha sozlash mumkin.\n\nRollarni to\'g\'ri tayinlash noqonuniy kirishdan sezgir funksiyalar va ma\'lumotlarni himoya qiladi. Rollar o\'zgarishlar tarixi auditoriya uchun saqlanadi.' },

  { order: 98, ruDescription: 'Настройка прав доступа позволяет детально настроить, какие функции доступны конкретному сотруднику. Это гибкий инструмент управления безопасностью.\n\nМожно ограничить доступ к конкретным разделам, складам, операциям. Например, кладовщик может видеть только свой склад, а бухгалтер — только финансовые документы.\n\nНастройки прав применяются немедленно и могут быть изменены в любой момент. Система ведёт лог всех действий сотрудников для контроля.', uzDescription: 'Kirish huquqlarini sozlash aniq xodimga qaysi funksiyalar mavjudligini batafsil sozlash imkonini beradi. Bu xavfsizlikni boshqarishning moslashuvchan vositasi.\n\nAniq bo\'limlar, omborlar, operatsiyalarga kirishni cheklash mumkin. Masalan, omborchi faqat o\'z omborini ko\'rishi, buxgalter esa faqat moliyaviy hujjatlarni ko\'rishi mumkin.\n\nHuquqlar sozlamalari darhol qo\'llaniladi va istalgan vaqtda o\'zgartirilishi mumkin. Tizim nazorat uchun barcha xodimlar harakatlarini yuritadi.' },

  { order: 99, ruDescription: 'История работы сотрудника показывает все действия, выполненные работником в системе. Это инструмент контроля и аудита.\n\nВ истории отображаются созданные и изменённые документы, время действий, использованные функции. Можно отфильтровать по периоду и типу действий.\n\nИстория работы помогает выявить ошибки, проанализировать производительность и разрешить спорные ситуации. Данные истории нельзя удалить или изменить.', uzDescription: 'Xodim ish tarixi ishchi tomonidan tizimda bajarilgan barcha harakatlarni ko\'rsatadi. Bu nazorat va auditoriya vositasi.\n\nTarixda yaratilgan va o\'zgartirilgan hujjatlar, harakatlar vaqti, ishlatilgan funksiyalar ko\'rsatiladi. Davr va harakat turi bo\'yicha filtrlash mumkin.\n\nIsh tarixi xatolarni aniqlash, samaradorlikni tahlil qilish va bahsli holatlarni hal qilishga yordam beradi. Tarix ma\'lumotlarini o\'chirib yoki o\'zgartirib bo\'lmaydi.' },

  { order: 100, ruDescription: 'Функция увольнения сотрудника оформляет прекращение трудовых отношений. Это важный процесс, который требует корректного закрытия всех обязательств.\n\nПри увольнении система блокирует учётную запись сотрудника, пересчитывает его задолженности и генерирует необходимые документы. Сотрудник исключается из справочника активных работников.\n\nИстория работы уволенного сотрудника сохраняется и доступна для аудита. Рекомендуется завершить все открытые документы перед оформлением увольнения.', uzDescription: 'Xodimni ishdan bo\'shatish funksiyasi mehnat munosabatlarining tugashini rasmiylashtiradi. Bu barcha majburiyatlarni to\'g\'ri yopishni talab qiluvchi muhim jarayon.\n\nBo\'shatishda tizim xodim hisob qaydnomasini bloklaydi, uning qarzini qayta hisoblaydi va kerakli hujjatlarni yaratadi. Xodim faol ishchilar ma\'lumotnomasidan chiqariladi.\n\nBo\'shatilgan xodim ish tarixi saqlanadi va auditoriya uchun mavjud. Bo\'shatishni rasmiylashtirishdan oldin barcha ochiq hujjatlarni tugatish tavsiya etiladi.' },
];

async function main() {
  console.log('Updating lessons 41-100 with detailed descriptions...');

  for (const lesson of detailedLessons) {
    await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
      },
    });
    console.log(`Updated lesson ${lesson.order}`);
  }

  console.log('Done!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
