// Update lessons 41-80 with detailed descriptions and functionality (3+ sentences each)
// Run: npx ts-node scripts/update-lessons-41-80.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const detailedLessons: {
  order: number;
  ruDescription: string;
  uzDescription: string;
  ruFunctionality: string;
  uzFunctionality: string;
}[] = [
  // === СКЛАД: ТРАНСФЕР (41-50) ===
  {
    order: 41,
    ruDescription: 'Раздел "Трансфер" предназначен для оформления перемещения товаров между складами организации. Это необходимая функция для многозвенных сетей с несколькими складами, торговыми точками или филиалами. В разделе отображается полный список документов перемещения с детальной информацией об отправителе, получателе, дате операции и текущем статусе документа. Правильное оформление трансфера обеспечивает корректный учёт товаров на каждом складе и позволяет отслеживать движение товаров в реальном времени.',
    uzDescription: '"Transfer" bo\'limi tashkilot omborlari orasida tovarlarni ko\'chirishni rasmiylashtirish uchun mo\'ljallangan. Bu bir nechta ombor, savdo nuqtalari yoki filiallari bo\'lgan ko\'p bo\'g\'inli tarmoqlar uchun zarur funksiya. Bo\'limda yuboruvchi, qabul qiluvchi, operatsiya sanasi va hujjatning joriy holati haqida batafsil ma\'lumot bilan ko\'chirish hujjatlari ro\'yxati ko\'rsatiladi. Transfega to\'g\'ri rasmiylashtirish har bir omborda tovarlarning to\'g\'ri hisobini ta\'minlaydi va tovarlar harakatini real vaqtda kuzatish imkonini beradi.',
    ruFunctionality: 'Функция открывает список всех документов перемещения товаров между складами с возможностью фильтрации по статусу, дате и участвующим складам. Пользователь может создавать новые документы трансфера, отслеживать статус отправленных товаров и принимать входящие перемещения. Система автоматически обновляет остатки на складах при изменении статуса документа и сохраняет полную историю всех операций перемещения.',
    uzFunctionality: 'Funksiya holat, sana va ishtirok etuvchi omborlar bo\'yicha filtrlash imkoniyati bilan omborlar orasida tovar ko\'chirish hujjatlari ro\'yxatini ochadi. Foydalanuvchi yangi transfer hujjatlarini yaratishi, yuborilgan tovarlar holatini kuzatishi va kiruvchi ko\'chirishlarni qabul qilishi mumkin. Tizim hujjat holati o\'zgarganda omborlardagi qoldiqlarni avtomatik yangilaydi va barcha ko\'chirish operatsiyalarining to\'liq tarixini saqlaydi.'
  },
  {
    order: 42,
    ruDescription: 'Кнопка создания трансфера открывает форму для оформления нового перемещения товаров между складами организации. Это первый шаг при необходимости передать товары с одного склада на другой для пополнения запасов или перераспределения ресурсов. Форма содержит все необходимые поля для указания отправителя, получателя и списка товаров с количеством. Система проверяет наличие достаточного количества товаров на складе-отправителе и блокирует создание документа при недостатке.',
    uzDescription: 'Transfer yaratish tugmasi tashkilot omborlari orasida yangi tovar ko\'chirishni rasmiylashtirish uchun formani ochadi. Bu zaxiralarni to\'ldirish yoki resurslarni qayta taqsimlash uchun tovarlarni bir ombordan boshqasiga o\'tkazish zarurati tug\'ilganda birinchi qadam. Forma yuboruvchi, qabul qiluvchi va miqdor bilan tovarlar ro\'yxatini ko\'rsatish uchun barcha kerakli maydonlarni o\'z ichiga oladi. Tizim yuboruvchi omborda yetarli miqdorda tovar borligini tekshiradi va yetishmovchilikda hujjat yaratishni bloklaydi.',
    ruFunctionality: 'При нажатии кнопки открывается модальное окно с формой создания документа трансфера, где необходимо указать склад-отправитель и склад-получатель. Пользователь может добавить товары в документ путём выбора из справочника или сканирования штрих-кодов, указав необходимое количество для каждого товара. После заполнения документ можно сохранить как черновик для дальнейшего редактирования или сразу отправить на исполнение.',
    uzFunctionality: 'Tugma bosilganda transfer hujjatini yaratish formasi bilan modal oyna ochiladi, bu yerda yuboruvchi ombor va qabul qiluvchi omborni ko\'rsatish kerak. Foydalanuvchi ma\'lumotnomadan tanlash yoki shtrix-kodlarni skanerlash orqali hujjatga tovarlar qo\'shishi, har bir tovar uchun kerakli miqdorni ko\'rsatishi mumkin. To\'ldirilgandan so\'ng hujjatni keyingi tahrirlash uchun qoralama sifatida saqlash yoki darhol ijroga yuborish mumkin.'
  },
  {
    order: 43,
    ruDescription: 'Поле выбора склада-отправителя позволяет указать склад, с которого будут отправлены товары в рамках документа трансфера. Это обязательный параметр, определяющий источник товаров для перемещения и место списания при отправке. При выборе склада система автоматически показывает актуальные остатки товаров на этом складе, что помогает пользователю определить доступное количество. Правильный выбор отправителя обеспечивает корректное списание товаров и предотвращает возникновение отрицательных остатков.',
    uzDescription: 'Yuboruvchi omborni tanlash maydoni transfer hujjati doirasida tovarlar yuboriladigan omborni ko\'rsatish imkonini beradi. Bu ko\'chirish uchun tovarlar manbasini va yuborish vaqtida yozib chiqarish joyini belgilovchi majburiy parametr. Ombor tanlanganda tizim ushbu ombordagi tovarlarning dolzarb qoldiqlarini avtomatik ko\'rsatadi, bu foydalanuvchiga mavjud miqdorni aniqlashga yordam beradi. Yuboruvchini to\'g\'ri tanlash tovarlarning to\'g\'ri yozib chiqarilishini ta\'minlaydi va manfiy qoldiqlarning yuzaga kelishining oldini oladi.',
    ruFunctionality: 'Поле представляет собой выпадающий список со всеми складами организации, доступными пользователю для отправки товаров. При вводе названия система предлагает варианты с возможностью быстрого поиска и фильтрации. После выбора отправителя система загружает актуальные остатки и блокирует добавление товаров, которых нет на складе в нужном количестве.',
    uzFunctionality: 'Maydon foydalanuvchi tovarlarni yuborish uchun mavjud bo\'lgan tashkilotning barcha omborlari bilan pastga tushuvchi ro\'yxatdir. Nom kiritilganda tizim tez qidiruv va filtrlash imkoniyati bilan variantlarni taklif qiladi. Yuboruvchi tanlangandan so\'ng tizim dolzarb qoldiqlarni yuklaydi va kerakli miqdorda mavjud bo\'lmagan tovarlarni qo\'shishni bloklaydi.'
  },
  {
    order: 44,
    ruDescription: 'Поле выбора склада-получателя позволяет указать склад, на который поступят товары после завершения трансфера. Это обязательный параметр, определяющий конечный пункт назначения и место зачисления товаров. Получатель должен отличаться от отправителя — система не позволяет создать трансфер на тот же склад во избежание бессмысленных операций. Можно выбрать любой склад организации из справочника, включая удалённые филиалы и торговые точки.',
    uzDescription: 'Qabul qiluvchi omborni tanlash maydoni transfer tugagandan so\'ng tovarlar keladigan omborni ko\'rsatish imkonini beradi. Bu oxirgi manzilni va tovarlarni qabul qilish joyini belgilovchi majburiy parametr. Qabul qiluvchi yuboruvchidan farq qilishi kerak — tizim ma\'nosiz operatsiyalarning oldini olish uchun bir xil omborga transfer yaratishga yo\'l qo\'ymaydi. Tashkilotning uzoq filiallari va savdo nuqtalari shu jumladan ma\'lumotnomadan istalgan omborni tanlash mumkin.',
    ruFunctionality: 'Выпадающий список содержит все склады организации за исключением склада-отправителя, который автоматически исключается из выбора. Пользователь может быстро найти нужный склад по названию или коду с помощью строки поиска. При выборе получателя система показывает расстояние и примерное время доставки, если эта информация настроена в справочнике складов.',
    uzFunctionality: 'Pastga tushuvchi ro\'yxat avtomatik tanlovdan chiqarilgan yuboruvchi ombordan tashqari tashkilotning barcha omborlarini o\'z ichiga oladi. Foydalanuvchi qidiruv satridan foydalangan holda nom yoki kod bo\'yicha kerakli omborni tez topishi mumkin. Qabul qiluvchi tanlanganda tizim masofa va taxminiy yetkazib berish vaqtini ko\'rsatadi, agar bu ma\'lumot omborlar ma\'lumotnomasida sozlangan bo\'lsa.'
  },
  {
    order: 45,
    ruDescription: 'Статус "Отправлен" означает, что товары списаны со склада-отправителя и находятся в процессе перемещения к складу-получателю. Это промежуточный статус документа трансфера, указывающий на то, что товары уже покинули отправителя, но ещё не прибыли на место назначения. В этом статусе товары числятся "в пути" — они уже не доступны на складе-отправителе, но ещё не доступны на складе-получателе. Сотрудники принимающего склада видят входящие трансферы с этим статусом и могут подготовиться к приёмке.',
    uzDescription: '"Yuborilgan" holati tovarlarning yuboruvchi ombordan yozib chiqarilganligini va qabul qiluvchi omborga ko\'chirilish jarayonida ekanligini bildiradi. Bu tovarlar allaqachon jo\'natuvchini tark etganini, lekin hali manzilga yetib bormaganligini ko\'rsatuvchi transfer hujjatining oraliq holatidir. Bu holatda tovarlar "yo\'lda" deb hisoblanadi — ular allaqachon yuboruvchi omborda mavjud emas, lekin hali qabul qiluvchi omborda ham mavjud emas. Qabul qiluvchi ombor xodimlari ushbu holatdagi kiruvchi transferlarni ko\'rishadi va qabul qilishga tayyorlanishlari mumkin.',
    ruFunctionality: 'Статус автоматически устанавливается при отправке трансфера и означает, что товары списаны с остатков склада-отправителя. Система резервирует эти товары как "в пути" и они недоступны для продажи или других операций до завершения перемещения. Пользователи могут отслеживать время нахождения товаров в пути и получать уведомления о задержках доставки.',
    uzFunctionality: 'Holat transfer yuborilganda avtomatik o\'rnatiladi va tovarlarning yuboruvchi ombor qoldiqlaridan yozib chiqarilganligini bildiradi. Tizim bu tovarlarni "yo\'lda" sifatida zaxiralaydi va ular ko\'chirish tugaguncha sotish yoki boshqa operatsiyalar uchun mavjud emas. Foydalanuvchilar tovarlarning yo\'lda bo\'lish vaqtini kuzatishlari va yetkazib berish kechikishlari haqida bildirishnomalar olishlari mumkin.'
  },
  {
    order: 46,
    ruDescription: 'Статус "Получен" означает, что товары успешно зачислены на склад-получатель и процесс перемещения полностью завершён. Это финальный статус успешного трансфера, после которого товары становятся доступными для всех складских операций на новом месте. После получения товары появляются в остатках склада-получателя и могут использоваться для продажи, инвентаризации или дальнейшего перемещения. История трансфера сохраняется в системе, что позволяет отследить всю цепочку перемещения конкретной партии товара.',
    uzDescription: '"Qabul qilingan" holati tovarlarning qabul qiluvchi omborga muvaffaqiyatli qabul qilinganligini va ko\'chirish jarayonining to\'liq tugaganligini bildiradi. Bu muvaffaqiyatli transferning yakuniy holati bo\'lib, undan keyin tovarlar yangi joyda barcha ombor operatsiyalari uchun mavjud bo\'ladi. Qabul qilingandan so\'ng tovarlar qabul qiluvchi omborning qoldiqlarida paydo bo\'ladi va sotish, inventarizatsiya yoki keyingi ko\'chirish uchun ishlatilishi mumkin. Transfer tarixi tizimda saqlanib qoladi, bu aniq tovar partiyasining ko\'chirish butun zanjirini kuzatish imkonini beradi.',
    ruFunctionality: 'Статус устанавливается при подтверждении приёмки товаров на складе-получателе и означает финал операции перемещения. Система автоматически зачисляет товары на остатки получателя с сохранением всех характеристик: цены, партии, сроков годности. После установки этого статуса документ становится доступным только для просмотра, редактирование невозможно.',
    uzFunctionality: 'Holat qabul qiluvchi omborda tovarlarni qabul qilish tasdiqlanganda o\'rnatiladi va ko\'chirish operatsiyasining tugashini bildiradi. Tizim tovarlarni barcha xususiyatlarini saqlagan holda avtomatik qabul qiluvchi qoldiqlariga qabul qiladi: narxlar, partiyalar, yaroqlilik muddatlari. Bu holat o\'rnatilgandan so\'ng hujjat faqat ko\'rish uchun mavjud bo\'ladi, tahrirlash mumkin emas.'
  },
  {
    order: 47,
    ruDescription: 'Кнопка принятия трансфера подтверждает получение товаров на склад-получатель и завершает процесс перемещения. Это действие выполняется сотрудниками принимающего склада после фактического прибытия товаров и их проверки. При принятии можно скорректировать фактически полученное количество товаров, если оно отличается от указанного в документе. Все расхождения фиксируются в системе и могут стать основанием для претензий к отправителю или транспортной компании.',
    uzDescription: 'Transferni qabul qilish tugmasi tovarlarning qabul qiluvchi omborga kelishini tasdiqlaydi va ko\'chirish jarayonini tugatadi. Bu harakat tovarlarning haqiqiy kelishi va ularning tekshirilishidan so\'ng qabul qiluvchi ombor xodimlari tomonidan amalga oshiriladi. Qabul qilishda, agar hujjatda ko\'rsatilgandan farq qilsa, haqiqatda olingan tovar miqdorini tuzatish mumkin. Barcha farqlar tizimda qayd etiladi va yuboruvchi yoki transport kompaniyasiga da\'volar uchun asos bo\'lishi mumkin.',
    ruFunctionality: 'Кнопка активна только для пользователей склада-получателя и только для документов в статусе "Отправлен". При нажатии открывается форма приёмки, где можно указать фактическое количество каждого товара и отметить повреждения при транспортировке. После подтверждения приёмки система автоматически зачисляет товары на остатки получателя и переводит документ в статус "Получен".',
    uzFunctionality: 'Tugma faqat qabul qiluvchi ombor foydalanuvchilari uchun va faqat "Yuborilgan" holatidagi hujjatlar uchun faol. Bosilganda qabul qilish formasi ochiladi, bu yerda har bir tovarning haqiqiy miqdorini ko\'rsatish va tashish paytidagi shikastlanishlarni belgilash mumkin. Qabul qilish tasdiqlangandan so\'ng tizim tovarlarni avtomatik qabul qiluvchi qoldiqlariga qabul qiladi va hujjatni "Qabul qilingan" holatiga o\'tkazadi.'
  },
  {
    order: 48,
    ruDescription: 'Фильтр трансферов по статусу позволяет отобрать документы перемещения по их текущему состоянию в системе. Это упрощает работу с большим количеством документов и помогает сосредоточиться на нужных операциях. Доступные статусы для фильтрации включают черновики, отправленные, полученные и отменённые трансферы. Фильтр особенно полезен для менеджеров складов: отправители видят свои отправленные трансферы, а получатели — входящие для принятия.',
    uzDescription: 'Transferlarni holat bo\'yicha filtr hujjatlarni ularning tizimdagi joriy holatiga ko\'ra tanlash imkonini beradi. Bu katta miqdordagi hujjatlar bilan ishlashni soddalashtiradi va kerakli operatsiyalarga e\'tiborni qaratishga yordam beradi. Filtrlash uchun mavjud holatlar qoralamalar, yuborilgan, qabul qilingan va bekor qilingan transferlarni o\'z ichiga oladi. Filtr ayniqsa ombor menejerlari uchun foydali: yuboruvchilar o\'zlarining yuborilgan transferlarini, qabul qiluvchilar esa qabul qilish uchun kiruvchilarni ko\'rishadi.',
    ruFunctionality: 'Выпадающий список фильтрации содержит все возможные статусы документов трансфера с возможностью множественного выбора. Пользователь может выбрать один или несколько статусов одновременно для отображения документов в разных состояниях. Выбранные параметры фильтрации сохраняются в настройках пользователя и применяются автоматически при следующем входе в раздел.',
    uzFunctionality: 'Filtrlashning pastga tushuvchi ro\'yxati ko\'p tanlov imkoniyati bilan transfer hujjatlarining barcha mumkin bo\'lgan holatlarini o\'z ichiga oladi. Foydalanuvchi har xil holatdagi hujjatlarni ko\'rsatish uchun bir vaqtning o\'zida bir yoki bir nechta holatni tanlashi mumkin. Tanlangan filtrlash parametrlari foydalanuvchi sozlamalarida saqlanadi va bo\'limga keyingi kirishda avtomatik qo\'llaniladi.'
  },
  {
    order: 49,
    ruDescription: 'Кнопка отправки трансфера инициирует перемещение товаров со склада-отправителя и переводит документ в статус "Отправлен". Это действие выполняется сотрудниками отправляющего склада после комплектации и подготовки товаров к отгрузке. При отправке система проверяет наличие товаров в нужном количестве и списывает их с остатков отправителя. Товары переходят в статус "в пути" до момента принятия на складе-получателе.',
    uzDescription: 'Transferni yuborish tugmasi tovarlarning yuboruvchi ombordan ko\'chirilishini boshlaydi va hujjatni "Yuborilgan" holatiga o\'tkazadi. Bu harakat tovarlarni komplektatsiya qilish va jo\'natishga tayyorlashdan so\'ng yuboruvchi ombor xodimlari tomonidan amalga oshiriladi. Yuborishda tizim kerakli miqdorda tovarlar mavjudligini tekshiradi va ularni yuboruvchining qoldiqlaridan yozib chiqaradi. Tovarlar qabul qiluvchi omborda qabul qilingunicha "yo\'lda" holatiga o\'tadi.',
    ruFunctionality: 'Кнопка доступна только для документов в статусе "Черновик" и только для пользователей склада-отправителя. При нажатии система проверяет заполнение всех обязательных полей и наличие товаров на складе. После успешной проверки товары списываются, документ блокируется для редактирования и переходит в статус "Отправлен".',
    uzFunctionality: 'Tugma faqat "Qoralama" holatidagi hujjatlar uchun va faqat yuboruvchi ombor foydalanuvchilari uchun mavjud. Bosilganda tizim barcha majburiy maydonlarning to\'ldirilishini va omborda tovarlar mavjudligini tekshiradi. Muvaffaqiyatli tekshiruvdan so\'ng tovarlar yozib chiqariladi, hujjat tahrirlash uchun bloklanadi va "Yuborilgan" holatiga o\'tadi.'
  },
  {
    order: 50,
    ruDescription: 'Кнопка отмены трансфера прекращает процесс перемещения и возвращает товары на склад-отправитель. Это используется при невозможности доставки, изменении планов или выявлении ошибок в документе. Отменить можно только трансфер в статусе "Отправлен", который ещё не принят получателем. При отмене товары возвращаются на остатки отправителя, а документ переходит в статус "Отменён". Отмена трансфера требует указания причины и фиксируется в истории документа.',
    uzDescription: 'Transferni bekor qilish tugmasi ko\'chirish jarayonini to\'xtatadi va tovarlarni yuboruvchi omborga qaytaradi. Bu yetkazib berish imkonsizligida, rejalarning o\'zgarishida yoki hujjatda xatolik aniqlanganda ishlatiladi. Faqat hali qabul qiluvchi tomonidan qabul qilinmagan "Yuborilgan" holatidagi transferni bekor qilish mumkin. Bekor qilishda tovarlar yuboruvchining qoldiqlariga qaytadi va hujjat "Bekor qilingan" holatiga o\'tadi. Transferni bekor qilish sababni ko\'rsatishni talab qiladi va hujjat tarixida qayd etiladi.',
    ruFunctionality: 'Функция доступна для документов в статусе "Отправлен" и требует подтверждения с указанием причины отмены. При отмене система автоматически возвращает товары на остатки отправителя и фиксирует операцию в истории. Документ переходит в статус "Отменён" и становится доступным только для просмотра.',
    uzFunctionality: 'Funksiya "Yuborilgan" holatidagi hujjatlar uchun mavjud va bekor qilish sababini ko\'rsatgan holda tasdiqlashni talab qiladi. Bekor qilishda tizim tovarlarni avtomatik yuboruvchining qoldiqlariga qaytaradi va operatsiyani tarixda qayd etadi. Hujjat "Bekor qilingan" holatiga o\'tadi va faqat ko\'rish uchun mavjud bo\'ladi.'
  },

  // === СКЛАД: РЕАЛИЗАЦИЯ (51-55) ===
  {
    order: 51,
    ruDescription: 'Раздел "Реализация" предназначен для оформления отгрузки товаров контрагентам-покупателям в рамках оптовых продаж. Это ключевой раздел для работы с корпоративными клиентами и документального оформления продаж. В разделе отображается список документов реализации с информацией о покупателе, дате, сумме и статусе отгрузки. Правильное оформление реализации обеспечивает корректное списание товаров, начисление выручки и формирование дебиторской задолженности покупателя.',
    uzDescription: '"Realizatsiya" bo\'limi ulgurji sotuvlar doirasida tovarlarni xaridor-kontragentlarga jo\'natishni rasmiylashtirish uchun mo\'ljallangan. Bu korporativ mijozlar bilan ishlash va sotuvlarni hujjatlashtirish uchun asosiy bo\'lim. Bo\'limda xaridor, sana, summa va jo\'natish holati haqida ma\'lumot bilan realizatsiya hujjatlari ro\'yxati ko\'rsatiladi. Realizatsiyaga to\'g\'ri rasmiylashtirish tovarlarning to\'g\'ri yozib chiqarilishini, tushumning hisoblanishini va xaridorning debitorlik qarzining shakllanishini ta\'minlaydi.',
    ruFunctionality: 'Функция открывает полный список документов реализации с возможностью фильтрации по контрагенту, периоду, статусу и сумме. Пользователь может создавать новые документы отгрузки, редактировать черновики, печатать накладные и отслеживать статус доставки. Система автоматически формирует проводки по списанию товаров и начислению дебиторской задолженности при проведении документа.',
    uzFunctionality: 'Funksiya kontragent, davr, holat va summa bo\'yicha filtrlash imkoniyati bilan realizatsiya hujjatlari ro\'yxatini ochadi. Foydalanuvchi yangi jo\'natish hujjatlari yaratishi, qoralamalarni tahrirlashi, nakladnoylarni chop etishi va yetkazib berish holatini kuzatishi mumkin. Tizim hujjat o\'tkazilganda tovarlarni yozib chiqarish va debitorlik qarzini hisoblash bo\'yicha o\'tkazmalarni avtomatik shakllantiradi.'
  },
  {
    order: 52,
    ruDescription: 'Кнопка создания реализации открывает форму для оформления нового документа отгрузки товаров покупателю. Это первый шаг при продаже товаров контрагенту в рамках оптовой торговли. В форме необходимо указать покупателя, склад отпуска, добавить список товаров с количеством и ценами для расчёта суммы документа. После заполнения документ можно сохранить как черновик или провести — товары будут списаны со склада, а документ станет основанием для расчётов с покупателем.',
    uzDescription: 'Realizatsiya yaratish tugmasi xaridorga tovar jo\'natishning yangi hujjatini rasmiylashtirish uchun formani ochadi. Bu ulgurji savdo doirasida tovarlarni kontragentga sotishda birinchi qadam. Formada xaridorni, jo\'natuvchi omborni ko\'rsatish, hujjat summasini hisoblash uchun tovarlar ro\'yxatini miqdor va narxlar bilan qo\'shish kerak. To\'ldirilgandan so\'ng hujjatni qoralama sifatida saqlash yoki o\'tkazish mumkin — tovarlar ombordan yozib chiqariladi va hujjat xaridor bilan hisob-kitoblar uchun asos bo\'ladi.',
    ruFunctionality: 'При нажатии открывается форма создания документа с полями для указания покупателя, склада, даты и примечаний. Пользователь может добавить товары из справочника с автоматическим заполнением цен из карточки товара или установить специальные цены для данной сделки. Система проверяет наличие товаров на складе и рассчитывает итоговую сумму документа с учётом скидок и НДС.',
    uzFunctionality: 'Bosilganda xaridor, ombor, sana va izohlar ko\'rsatish uchun maydonlar bilan hujjat yaratish formasi ochiladi. Foydalanuvchi tovar kartochkasidan narxlarni avtomatik to\'ldirish bilan ma\'lumotnomadan tovarlar qo\'shishi yoki ushbu bitim uchun maxsus narxlar o\'rnatishi mumkin. Tizim omborda tovarlar mavjudligini tekshiradi va chegirmalar va QQS hisobga olingan holda hujjatning yakuniy summasini hisoblaydi.'
  },
  {
    order: 53,
    ruDescription: 'Поле выбора покупателя позволяет указать контрагента, которому отгружаются товары в рамках документа реализации. Это обязательный реквизит документа, определяющий плательщика и получателя товаров. При вводе названия система предлагает варианты из справочника контрагентов с возможностью быстрого поиска. Выбранный покупатель автоматически подставляется в расчёты по дебиторской задолженности и становится получателем финансовых документов.',
    uzDescription: 'Xaridorni tanlash maydoni realizatsiya hujjati doirasida tovarlar jo\'natiladigan kontragentni ko\'rsatish imkonini beradi. Bu to\'lovchi va tovarlarni qabul qiluvchini belgilovchi hujjatning majburiy rekviziti. Nom kiritilganda tizim tez qidiruv imkoniyati bilan kontragentlar ma\'lumotnomasidan variantlarni taklif qiladi. Tanlangan xaridor avtomatik debitorlik qarzlari bo\'yicha hisob-kitoblarga qo\'yiladi va moliyaviy hujjatlarni qabul qiluvchiga aylanadi.',
    ruFunctionality: 'Поле представляет собой выпадающий список с поиском по наименованию, ИНН или коду контрагента. При выборе покупателя система автоматически заполняет его реквизиты: адрес доставки, контактное лицо, условия оплаты. Если контрагента нет в справочнике, его можно создать непосредственно из формы реализации без перехода в другие разделы.',
    uzFunctionality: 'Maydon nom, INN yoki kontragent kodi bo\'yicha qidiruv bilan pastga tushuvchi ro\'yxatdir. Xaridor tanlanganda tizim uning rekvizitlarini avtomatik to\'ldiradi: yetkazib berish manzili, kontakt shaxsi, to\'lov shartlari. Agar kontragent ma\'lumotnomada bo\'lmasa, uni boshqa bo\'limlarga o\'tmasdan to\'g\'ridan-to\'g\'ri realizatsiya formasidan yaratish mumkin.'
  },
  {
    order: 54,
    ruDescription: 'Функция печати реализации формирует печатную форму накладной для передачи покупателю вместе с товарами. Это обязательный документ для юридического оформления отгрузки и подтверждения перехода права собственности. Система предлагает несколько шаблонов: товарная накладная, расходная накладная, универсальный передаточный документ. Шаблоны соответствуют требованиям бухгалтерского и налогового учёта и могут быть настроены под нужды организации.',
    uzDescription: 'Realizatsiyani chop etish funksiyasi tovarlar bilan birga xaridorga uzatish uchun nakladnoyning bosma shaklini yaratadi. Bu jo\'natishni huquqiy rasmiylashtirish va mulk huquqining o\'tishini tasdiqlash uchun majburiy hujjat. Tizim bir nechta shablonlarni taklif qiladi: tovar nakladnoysi, chiqim nakladnoysi, universal uzatish hujjati. Shablonlar buxgalteriya va soliq hisobi talablariga mos keladi va tashkilot ehtiyojlariga ko\'ra sozlanishi mumkin.',
    ruFunctionality: 'При нажатии кнопки система формирует PDF-документ на основе выбранного шаблона с автоматическим заполнением всех реквизитов. Пользователь может предварительно просмотреть документ, выбрать количество копий и принтер для печати. Система сохраняет историю печати с указанием даты, времени и пользователя, распечатавшего документ.',
    uzFunctionality: 'Tugma bosilganda tizim barcha rekvizitlarni avtomatik to\'ldirib, tanlangan shablon asosida PDF-hujjatni shakllantiradi. Foydalanuvchi hujjatni oldindan ko\'rish, nusxalar sonini va chop etish uchun printerni tanlashi mumkin. Tizim hujjatni chop etgan sana, vaqt va foydalanuvchini ko\'rsatgan holda chop etish tarixini saqlaydi.'
  },
  {
    order: 55,
    ruDescription: 'Управление статусами реализации позволяет контролировать этапы отгрузки товаров от создания документа до передачи покупателю. Статус показывает текущее состояние документа в цепочке продаж и определяет доступные действия. Доступные статусы включают черновик, оформлен, отправлен и отменён. История изменения статусов сохраняется и доступна для анализа эффективности работы отдела продаж и логистики.',
    uzDescription: 'Realizatsiya holatlarini boshqarish hujjat yaratishdan boshlab xaridorga topshirishgacha tovar jo\'natish bosqichlarini nazorat qilish imkonini beradi. Holat sotuvlar zanjiridagi hujjatning joriy holatini ko\'rsatadi va mavjud harakatlarni belgilaydi. Mavjud holatlar qoralama, rasmiylashtirilgan, yuborilgan va bekor qilinganni o\'z ichiga oladi. Holatlar o\'zgarish tarixi saqlanadi va savdo va logistika bo\'limi ishining samaradorligini tahlil qilish uchun mavjud.',
    ruFunctionality: 'Система автоматически меняет статус документа при выполнении определённых действий: сохранение — черновик, проведение — оформлен, отправка — отправлен. Пользователь может вручную менять статус при наличии соответствующих прав. При изменении статуса система выполняет соответствующие операции: списание товаров, формирование проводок, отправку уведомлений.',
    uzFunctionality: 'Tizim aniq harakatlar bajarilganda hujjat holatini avtomatik o\'zgartiradi: saqlash — qoralama, o\'tkazish — rasmiylashtirilgan, yuborish — yuborilgan. Foydalanuvchi tegishli huquqlar mavjud bo\'lganda holatni qo\'lda o\'zgartirishi mumkin. Holat o\'zgarganda tizim mos operatsiyalarni bajaradi: tovarlarni yozib chiqarish, o\'tkazmalarni shakllantirish, bildirishnomalarni yuborish.'
  },

  // === СКЛАД: ПЕРЕОЦЕНКА (56-60) ===
  {
    order: 56,
    ruDescription: 'Раздел "Переоценка" предназначен для массового изменения цен товаров в системе. Это необходимая функция при изменении закупочных цен, проведении рекламных акций или корректировке розничных цен. В разделе отображается список документов переоценки с информацией о дате, количестве товаров и причине изменения цен. Каждый документ фиксирует изменение цен для определённой группы товаров и сохраняет историю предыдущих значений.',
    uzDescription: '"Qayta baholash" bo\'limi tizimda tovarlar narxlarini ommaviy o\'zgartirish uchun mo\'ljallangan. Bu xarid narxlarining o\'zgarishida, reklama aksiyalari o\'tkazishda yoki chakana narxlarni tuzatishda zarur funksiya. Bo\'limda sana, tovarlar soni va narxlar o\'zgarish sababi haqida ma\'lumot bilan qayta baholash hujjatlari ro\'yxati ko\'rsatiladi. Har bir hujjat aniq tovarlar guruhi uchun narxlar o\'zgarishini qayd etadi va oldingi qiymatlar tarixini saqlaydi.',
    ruFunctionality: 'Функция открывает список всех документов переоценки с возможностью фильтрации по дате, статусу и причине изменения. Пользователь может создавать новые документы переоценки, просматривать историю изменений цен и отменять ошибочные переоценки. Система автоматически обновляет цены товаров при проведении документа и сохраняет историю предыдущих значений для аудита.',
    uzFunctionality: 'Funksiya sana, holat va o\'zgarish sababi bo\'yicha filtrlash imkoniyati bilan barcha qayta baholash hujjatlari ro\'yxatini ochadi. Foydalanuvchi yangi qayta baholash hujjatlarini yaratishi, narxlar o\'zgarishlari tarixini ko\'rish va xato qayta baholashlarni bekor qilishi mumkin. Tizim hujjat o\'tkazilganda tovarlar narxlarini avtomatik yangilaydi va auditoriya uchun oldingi qiymatlar tarixini saqlaydi.'
  },
  {
    order: 57,
    ruDescription: 'Кнопка создания переоценки открывает форму для массового изменения цен товаров. Это первый шаг при необходимости обновить цены для группы товаров при изменении условий закупки или проведении акции. В форме нужно указать причину переоценки и добавить товары, цены которых нужно изменить. Для каждого товара указывается новая цена или процент изменения относительно текущей цены с возможностью округления.',
    uzDescription: 'Qayta baholash yaratish tugmasi tovarlar narxlarini ommaviy o\'zgartirish uchun formani ochadi. Bu xarid sharoitlari o\'zgarishida yoki aksiya o\'tkazishda tovarlar guruhi uchun narxlarni yangilash zarurati tug\'ilganda birinchi qadam. Formada qayta baholash sababini ko\'rsatish va narxlari o\'zgartirilishi kerak bo\'lgan tovarlarni qo\'shish kerak. Har bir tovar uchun yangi narx yoki joriy narxga nisbatan o\'zgarish foizi yaxlitlash imkoniyati bilan ko\'rsatiladi.',
    ruFunctionality: 'При нажатии открывается форма создания документа с полями для указания причины переоценки, даты вступления в силу и примечаний. Пользователь может добавить товары вручную, выбрать по категории или загрузить список из внешнего файла. Система показывает текущие цены товаров и позволяет задать новые значения или формулу расчёта для всех выбранных товаров.',
    uzFunctionality: 'Bosilganda qayta baholash sababi, kuchga kirish sanasi va izohlar ko\'rsatish uchun maydonlar bilan hujjat yaratish formasi ochiladi. Foydalanuvchi tovarlarni qo\'lda qo\'shishi, kategoriya bo\'yicha tanlashi yoki tashqi fayldan ro\'yxatni yuklashi mumkin. Tizim tovarlarning joriy narxlarini ko\'rsatadi va barcha tanlangan tovarlar uchun yangi qiymatlar yoki hisoblash formulasini belgilash imkonini beradi.'
  },
  {
    order: 58,
    ruDescription: 'Кнопка выбора товаров для переоценки открывает форму добавления товаров в документ массового изменения цен. Это основной этап формирования документа переоценки, определяющий список товаров для обновления. Товары можно добавлять несколькими способами: выбрать из списка с фильтрацией по категории, добавить по отдельности или импортировать список артикулов из файла. При добавлении система показывает текущие цены товаров для определения направления и размера изменения.',
    uzDescription: 'Qayta baholash uchun tovarlarni tanlash tugmasi narxlarni ommaviy o\'zgartirish hujjatiga tovar qo\'shish formasini ochadi. Bu yangilanishi kerak bo\'lgan tovarlar ro\'yxatini belgilovchi qayta baholash hujjatini shakllantirishning asosiy bosqichi. Tovarlarni bir nechta usulda qo\'shish mumkin: kategoriya bo\'yicha filtrlash bilan ro\'yxatdan tanlash, alohida qo\'shish yoki fayldan artikullar ro\'yxatini import qilish. Qo\'shishda tizim o\'zgarish yo\'nalishi va hajmini aniqlash uchun tovarlarning joriy narxlarini ko\'rsatadi.',
    ruFunctionality: 'Форма выбора товаров содержит справочник с фильтрами по категории, бренду, поставщику и другим параметрам. Пользователь может выбрать несколько товаров одновременно с помощью чекбоксов или воспользоваться функцией "Выбрать все" для категории. Система показывает превью списка выбранных товаров с их текущими ценами перед добавлением в документ.',
    uzFunctionality: 'Tovarlarni tanlash formasi kategoriya, brend, yetkazib beruvchi va boshqa parametrlar bo\'yicha filtrlar bilan ma\'lumotnomani o\'z ichiga oladi. Foydalanuvchi checkboxlar yordamida bir vaqtning o\'zida bir nechta tovarlarni tanlashi yoki kategoriya uchun "Barchasini tanlash" funksiyasidan foydalanishi mumkin. Tizim hujjatga qo\'shishdan oldin tanlangan tovarlar ro\'yxatining joriy narxlar bilan oldindan ko\'rishini ko\'rsatadi.'
  },
  {
    order: 59,
    ruDescription: 'Поле новой цены товара позволяет указать новое значение цены для каждого товара в документе переоценки. Это ключевой параметр документа, определяющий итоговую стоимость товара после переоценки. Можно указать фиксированную новую цену или задать формулу расчёта: увеличить на процент, уменьшить на сумму, округлить до определённого значения. Система автоматически рассчитывает новую цену и показывает разницу со старой ценой.',
    uzDescription: 'Tovarning yangi narxi maydoni qayta baholash hujjatidagi har bir tovar uchun narxning yangi qiymatini ko\'rsatish imkonini beradi. Bu qayta baholashdan keyin tovarning yakuniy qiymatini belgilovchi hujjatning asosiy parametri. Belgilangan yangi narxni ko\'rsatish yoki hisoblash formulasini berish mumkin: foizga oshirish, summani kamaytirish, aniq qiymatga yaxlitlash. Tizim yangi narxni avtomatik hisoblaydi va eski narx bilan farqni ko\'rsatadi.',
    ruFunctionality: 'Поле поддерживает несколько режимов ввода: прямое указание суммы, процентное изменение от текущей цены или формула с округлением. При изменении значения система мгновенно пересчитывает итоговую цену и показывает процент изменения. Можно применить одинаковое изменение ко всем выбранным товарам с помощью функции массового редактирования.',
    uzFunctionality: 'Maydon kiritishning bir nechta rejimlarini qo\'llab-quvvatlaydi: summani to\'g\'ridan-to\'g\'ri ko\'rsatish, joriy narxdan foizli o\'zgartirish yoki yaxlitlash bilan formula. Qiymat o\'zgarganda tizim yakuniy narxni bir zumda qayta hisoblaydi va o\'zgarish foizini ko\'rsatadi. Ommaviy tahrirlash funksiyasi yordamida barcha tanlangan tovarlarga bir xil o\'zgartirishni qo\'llash mumkin.'
  },
  {
    order: 60,
    ruDescription: 'Кнопка проведения переоценки применяет новые цены к выбранным товарам и завершает оформление документа. Это финальное действие, после которого цены обновляются в системе и становятся действующими. При проведении система обновляет цены товаров в справочнике и фиксирует изменения в истории для аудита. Новые цены применяются к новым документам, а старые документы сохраняют цены на момент их создания.',
    uzDescription: 'Qayta baholashni o\'tkazish tugmasi tanlangan tovarlarga yangi narxlarni qo\'llaydi va hujjatni rasmiylashtirishni tugatadi. Bu narxlar tizimda yangilanib, amalda bo\'ladigan yakuniy harakat. O\'tkazishda tizim ma\'lumotnomada tovarlar narxlarini yangilaydi va auditoriya uchun o\'zgarishlarni tarixda qayd etadi. Yangi narxlar yangi hujjatlarga qo\'llaniladi, eski hujjatlar esa o\'z yaratilish vaqtidagi narxlarni saqlab qoladi.',
    ruFunctionality: 'При нажатии система проверяет корректность заполнения документа и показывает превью изменений перед применением. После подтверждения цены обновляются в карточках товаров, и документ переходит в статус "Проведён". Система сохраняет предыдущие значения цен, что позволяет отменить переоценку при необходимости и восстановить старые цены.',
    uzFunctionality: 'Bosilganda tizim hujjat to\'g\'ri to\'ldirilganligini tekshiradi va qo\'llashdan oldin o\'zgarishlarning oldindan ko\'rishini ko\'rsatadi. Tasdiqlangandan so\'ng narxlar tovar kartochkalarida yangilanadi va hujjat "O\'tkazilgan" holatiga o\'tadi. Tizim oldingi narx qiymatlarini saqlaydi, bu zarurat bo\'lganda qayta baholashni bekor qilish va eski narxlarni tiklash imkonini beradi.'
  },

  // === СКЛАД: ИНВЕНТАРИЗАЦИЯ (61-65) ===
  {
    order: 61,
    ruDescription: 'Раздел "Инвентаризация" предназначен для проведения сверки фактических остатков товаров с учётными данными. Это важный инструмент контроля сохранности товарно-материальных ценностей и выявления расхождений. В разделе отображается список документов инвентаризации с информацией о складе, дате проведения и результатах. Регулярное проведение инвентаризации помогает выявлять недостачи и излишки, анализировать их причины и принимать меры по предотвращению потерь.',
    uzDescription: '"Inventarizatsiya" bo\'limi faktik tovar qoldiqlarini hisob ma\'lumotlari bilan solishtirish uchun mo\'ljallangan. Bu tovar-moddaviy qadriyatlarning saqlanishini nazorat qilish va farqlarni aniqlashning muhim vositasi. Bo\'limda ombor, o\'tkazish sanasi va natijalar haqida ma\'lumot bilan inventarizatsiya hujjatlari ro\'yxati ko\'rsatiladi. Muntazam inventarizatsiya o\'tkazish kamchilik va ortiqchalarni aniqlash, ularning sabablarini tahlil qilish va yo\'qotishlarning oldini olish choralarni ko\'rishga yordam beradi.',
    ruFunctionality: 'Функция открывает список всех документов инвентаризации с возможностью фильтрации по складу, периоду и статусу. Пользователь может создавать новые документы инвентаризации, просматривать результаты проведённых проверок и формировать отчёты по расхождениям. Система автоматически рассчитывает расхождения между учётными и фактическими остатками и предлагает варианты их оформления.',
    uzFunctionality: 'Funksiya ombor, davr va holat bo\'yicha filtrlash imkoniyati bilan barcha inventarizatsiya hujjatlari ro\'yxatini ochadi. Foydalanuvchi yangi inventarizatsiya hujjatlarini yaratishi, o\'tkazilgan tekshiruvlar natijalarini ko\'rish va farqlar bo\'yicha hisobotlarni shakllantirishi mumkin. Tizim hisob va haqiqiy qoldiqlar o\'rtasidagi farqlarni avtomatik hisoblaydi va ularni rasmiylashtirish variantlarini taklif qiladi.'
  },
  {
    order: 62,
    ruDescription: 'Кнопка создания инвентаризации открывает форму для проведения новой сверки остатков товаров на складе. Это первый шаг при планировании инвентаризации и формировании документа проверки. В форме нужно указать склад, для которого проводится инвентаризация, и выбрать товары для проверки. Система автоматически заполняет учётные остатки товаров, остаётся ввести фактическое количество после пересчёта на складе.',
    uzDescription: 'Inventarizatsiya yaratish tugmasi omborda tovar qoldiqlarini yangi solishtirish o\'tkazish uchun formani ochadi. Bu inventarizatsiyani rejalashtirish va tekshirish hujjatini shakllantirishda birinchi qadam. Formada inventarizatsiya o\'tkaziladigan omborni ko\'rsatish va tekshirish uchun tovarlarni tanlash kerak. Tizim tovarlarning hisob qoldiqlarini avtomatik to\'ldiradi, omborda qayta hisoblangandan so\'ng haqiqiy miqdorni kiritish qoladi.',
    ruFunctionality: 'При нажатии открывается форма создания документа с выбором склада, даты проведения и ответственных лиц. Пользователь может выбрать все товары склада или конкретную категорию для выборочной инвентаризации. Система формирует документ с учётными остатками, готовый для ввода фактических данных после пересчёта.',
    uzFunctionality: 'Bosilganda ombor, o\'tkazish sanasi va mas\'ul shaxslarni tanlash bilan hujjat yaratish formasi ochiladi. Foydalanuvchi omborning barcha tovarlarini yoki tanlab inventarizatsiya uchun aniq kategoriyani tanlashi mumkin. Tizim qayta hisoblashdan so\'ng haqiqiy ma\'lumotlarni kiritishga tayyor, hisob qoldiqlari bilan hujjatni shakllantiradi.'
  },
  {
    order: 63,
    ruDescription: 'Поле фактического остатка предназначено для ввода реального количества товаров, выявленного при пересчёте на складе. Это ключевые данные инвентаризации, на основании которых определяются расхождения. После ввода фактического количества система автоматически рассчитывает расхождение с учётным остатком и определяет излишки или недостачу. Вводить фактические остатки можно вручную или загружать из сканера штрих-кодов и терминала сбора данных.',
    uzDescription: 'Haqiqiy qoldiq maydoni omborda qayta hisoblashda aniqlangan tovarlarning haqiqiy miqdorini kiritish uchun mo\'ljallangan. Bu farqlar aniqlanadigan asosda inventarizatsiyaning asosiy ma\'lumotlari. Haqiqiy miqdor kiritilgandan so\'ng tizim hisob qoldig\'i bilan farqni avtomatik hisoblaydi va ortiqcha yoki kamchilikni aniqlaydi. Haqiqiy qoldiqlarni qo\'lda kiritish yoki shtrix-kod skaneri va ma\'lumot yig\'ish terminalidan yuklash mumkin.',
    ruFunctionality: 'Поле принимает числовые значения с возможностью ввода дробных чисел для весовых товаров. При вводе значения система мгновенно показывает расхождение с учётным остатком и подсвечивает проблемные позиции. Поддерживается массовый ввод данных через импорт из файла или интеграцию с оборудованием для автоматического подсчёта.',
    uzFunctionality: 'Maydon og\'irlikli tovarlar uchun kasr sonlarni kiritish imkoniyati bilan son qiymatlarni qabul qiladi. Qiymat kiritilganda tizim hisob qoldig\'i bilan farqni bir zumda ko\'rsatadi va muammoli pozitsiyalarni ajratib ko\'rsatadi. Fayldan import orqali yoki avtomatik hisoblash uchun uskunalar bilan integratsiya orqali ma\'lumotlarni ommaviy kiritish qo\'llab-quvvatlanadi.'
  },
  {
    order: 64,
    ruDescription: 'Вкладка расхождений инвентаризации показывает разницу между учётными и фактическими остатками товаров. Это ключевой результат инвентаризации для анализа и принятия решений. Расхождения группируются по типу: излишки, недостачи, пересортица, и для каждого показывается товар, количество и возможная причина. На основе расхождений можно автоматически создать документы оприходования излишков или списания недостач.',
    uzDescription: 'Inventarizatsiya farqlari yorlig\'i tovarlarning hisob va haqiqiy qoldiqlar o\'rtasidagi farqni ko\'rsatadi. Bu tahlil va qaror qabul qilish uchun inventarizatsiyaning asosiy natijasi. Farqlar tur bo\'yicha guruhlanadi: ortiqcha, kamchilik, tartibsizlik va har biri uchun tovar, miqdor va mumkin bo\'lgan sabab ko\'rsatiladi. Farqlar asosida ortiqchalarni qabul qilish yoki kamchiliklarni yozib chiqarish hujjatlarini avtomatik yaratish mumkin.',
    ruFunctionality: 'Вкладка отображает сводную таблицу расхождений с возможностью сортировки по типу, количеству и сумме. Пользователь может фильтровать расхождения по значимости, скрывать незначительные отклонения и фокусироваться на существенных. Система предлагает автоматическое создание документов корректировки на основе выявленных расхождений.',
    uzFunctionality: 'Yorliq tur, miqdor va summa bo\'yicha saralash imkoniyati bilan farqlarning umumlashtirilgan jadvalini ko\'rsatadi. Foydalanuvchi farqlarni ahamiyati bo\'yicha filtrlashi, ahamiyatsiz og\'ishlarni yashirishi va muhimlariga e\'tibor qaratishi mumkin. Tizim aniqlangan farqlar asosida tuzatish hujjatlarini avtomatik yaratishni taklif qiladi.'
  },
  {
    order: 65,
    ruDescription: 'Кнопка принятия инвентаризации завершает процесс сверки и корректирует остатки товаров в соответствии с фактическими данными. Это финальное действие документа инвентаризации, после которого изменения вступают в силу. При принятии система автоматически создаёт документы оприходования для излишков и списания для недостач. Результаты инвентаризации сохраняются в истории и доступны для аудита и анализа.',
    uzDescription: 'Inventarizatsiyani qabul qilish tugmasi solishtirish jarayonini tugatadi va qoldiqlarni haqiqiy ma\'lumotlarga ko\'ra tuzatadi. Bu o\'zgarishlar kuchga kiradigan inventarizatsiya hujjatining yakuniy harakati. Qabul qilishda tizim ortiqchalar uchun qabul qilish va kamchiliklar uchun yozib chiqarish hujjatlarini avtomatik yaratadi. Inventarizatsiya natijalari tarixda saqlanadi va auditoriya va tahlil uchun mavjud.',
    ruFunctionality: 'При нажатии система показывает итоговую сводку расхождений и требует подтверждения ответственного лица. После подтверждения автоматически создаются и проводятся документы корректировки остатков. Документ инвентаризации переходит в статус "Завершён» и становится доступным только для просмотра.',
    uzFunctionality: 'Bosilganda tizim farqlarning yakuniy hisobotini ko\'rsatadi va mas\'ul shaxsning tasdiqlashini talab qiladi. Tasdiqlangandan so\'ng qoldiqlarni tuzatish hujjatlari avtomatik yaratiladi va o\'tkaziladi. Inventarizatsiya hujjati "Tugallangan" holatiga o\'tadi va faqat ko\'rish uchun mavjud bo\'ladi.'
  },

  // === СКЛАД: СПИСАНИЕ (66-70) ===
  {
    order: 66,
    ruDescription: 'Раздел "Списание" предназначен для оформления выбытия товаров по причинам, не связанным с продажей. Это необходимо для учёта потерь, порчи, хищений и других случаев уменьшения остатков. В разделе отображается список документов списания с информацией о складе, причине, сумме и дате операции. Правильное оформление списания обеспечивает корректный учёт себестоимости и помогает анализировать причины потерь для принятия мер по их снижению.',
    uzDescription: '"Yozib chiqarish" bo\'limi sotish bilan bog\'liq bo\'lmagan sabablarga ko\'ra tovarlarning chiqib ketishini rasmiylashtirish uchun mo\'ljallangan. Bu yo\'qotishlar, buzilish, o\'g\'irlik va qoldiqlarning kamayishining boshqa holatlarini hisobga olish uchun zarur. Bo\'limda ombor, sabab, summa va operatsiya sanasi haqida ma\'lumot bilan yozib chiqarish hujjatlari ro\'yxati ko\'rsatiladi. Yozib chiqarishga to\'g\'ri rasmiylashtirish tannarxning to\'g\'ri hisobini ta\'minlaydi va yo\'qotishlar sabablarini tahlil qilishga, ularni kamaytirish choralarni ko\'rishga yordam beradi.',
    ruFunctionality: 'Функция открывает список всех документов списания с возможностью фильтрации по складу, причине, периоду и сумме. Пользователь может создавать новые документы списания, просматривать историю операций и формировать аналитические отчёты по причинам потерь. Система автоматически формирует проводки по списанию себестоимости товаров на затраты организации.',
    uzFunctionality: 'Funksiya ombor, sabab, davr va summa bo\'yicha filtrlash imkoniyati bilan barcha yozib chiqarish hujjatlari ro\'yxatini ochadi. Foydalanuvchi yangi yozib chiqarish hujjatlarini yaratishi, operatsiyalar tarixini ko\'rish va yo\'qotishlar sabablari bo\'yicha tahliliy hisobotlarni shakllantirishi mumkin. Tizim tovarlar tannarxini tashkilot xarajatlariga yozib chiqarish bo\'yicha o\'tkazmalarni avtomatik shakllantiradi.'
  },
  {
    order: 67,
    ruDescription: 'Кнопка создания списания открывает форму для оформления выбытия товаров со склада. Это первый шаг при обнаружении товаров, которые нельзя продать или использовать по назначению. В форме нужно указать склад, выбрать товары для списания и указать причину выбытия. Система проверяет наличие достаточного количества товаров на складе и рассчитывает сумму списания по средней себестоимости.',
    uzDescription: 'Yozib chiqarish yaratish tugmasi ombordan tovarlarning chiqib ketishini rasmiylashtirish uchun formani ochadi. Bu sotib bo\'lmaydigan yoki maqsadga muvofiq ishlatib bo\'lmaydigan tovarlar aniqlanganda birinchi qadam. Formada omborni ko\'rsatish, yozib chiqarish uchun tovarlarni tanlash va chiqib ketish sababini ko\'rsatish kerak. Tizim omborda yetarli miqdorda tovar borligini tekshiradi va o\'rtacha tannarx bo\'yicha yozib chiqarish summasini hisoblaydi.',
    ruFunctionality: 'При нажатии открывается форма создания документа с выбором склада, даты и ответственного лица. Пользователь может добавить товары из справочника с указанием количества и причины списания для каждого. Система автоматически рассчитывает сумму списания по методу средней себестоимости и показывает итоговую сумму документа.',
    uzFunctionality: 'Bosilganda ombor, sana va mas\'ul shaxsni tanlash bilan hujjat yaratish formasi ochiladi. Foydalanuvchi ma\'lumotnomadan har biri uchun miqdor va yozib chiqarish sababini ko\'rsatgan holda tovarlar qo\'shishi mumkin. Tizim o\'rtacha tannarx usuli bo\'yicha yozib chiqarish summasini avtomatik hisoblaydi va hujjatning yakuniy summasini ko\'rsatadi.'
  },
  {
    order: 68,
    ruDescription: 'Поле причины списания позволяет выбрать основание для выбытия товаров со склада. Это важная информация для анализа потерь, формирования отчётности и принятия управленческих решений. Доступные причины включают порчу при хранении, истечение срока годности, бой при транспортировке, хищение, моральный износ и потерю товарного вида. Выбор причины влияет на бухгалтерский учёт и может требовать различных форм подтверждения.',
    uzDescription: 'Yozib chiqarish sababi maydoni ombordan tovarlarning chiqib ketishiga asosni tanlash imkonini beradi. Bu yo\'qotishlarni tahlil qilish, hisobotlarni shakllantirish va boshqaruv qarorlarini qabul qilish uchun muhim ma\'lumot. Mavjud sabablar saqlashda buzilish, yaroqlilik muddati tugash, tashishda sinish, o\'g\'irlik, ma\'naviy eskirish va tovar ko\'rinishini yo\'qotishni o\'z ichiga oladi. Sabab tanlash buxgalteriya hisobiga ta\'sir qilishi va turli tasdiq shakllarini talab qilishi mumkin.',
    ruFunctionality: 'Поле представляет собой выпадающий список с предустановленными причинами списания и возможностью добавления собственных. При выборе причины система может требовать заполнения дополнительных полей: объяснительная записка, акт комиссии, ссылка на инвентаризацию. Статистика причин списания доступна в аналитических отчётах для выявления проблемных зон.',
    uzFunctionality: 'Maydon oldindan o\'rnatilgan yozib chiqarish sabablari va o\'zlarinikini qo\'shish imkoniyati bilan pastga tushuvchi ro\'yxatdir. Sabab tanlanganda tizim qo\'shimcha maydonlarni to\'ldirishni talab qilishi mumkin: tushuntirish yozuvi, komissiya akti, inventarizatsiyaga havola. Yozib chiqarish sabablari statistikasi muammoli joylarni aniqlash uchun tahliliy hisobotlarda mavjud.'
  },
  {
    order: 69,
    ruDescription: 'Поле ответственного за списание позволяет указать сотрудника, который несёт ответственность за списываемые товары. Это важно для контроля сохранности ценностей и определения степени вины при потерях. Ответственный выбирается из справочника сотрудников и обычно является материально ответственным лицом, за которым закреплён данный склад или товар. Указание ответственного помогает при разборе причин списания и формировании претензий.',
    uzDescription: 'Yozib chiqarish bo\'yicha mas\'ul maydoni yozib chiqarilayotgan tovarlar uchun mas\'uliyatni oluvchi xodimni ko\'rsatish imkonini beradi. Bu qadriyatlarning saqlanishini nazorat qilish va yo\'qotishlarda ayb darajasini aniqlash uchun muhim. Mas\'ul xodimlar ma\'lumotnomasidan tanlanadi va odatda ushbu ombor yoki tovar bilan bog\'langan moddiy mas\'ul shaxsdir. Mas\'ulni ko\'rsatish yozib chiqarish sabablarini tahlil qilishda va da\'volarni shakllantirishda yordam beradi.',
    ruFunctionality: 'Выпадающий список содержит всех сотрудников организации с возможностью поиска по имени или табельному номеру. При выборе ответственного система может показать его историю списаний для оценки дисциплины. Поле является обязательным для документов списания по причинам, связанным с виной сотрудника.',
    uzFunctionality: 'Pastga tushuvchi ro\'yxat ism yoki tabel raqami bo\'yicha qidiruv imkoniyati bilan tashkilotning barcha xodimlarini o\'z ichiga oladi. Mas\'ul tanlanganda tizim intizomni baholash uchun uning yozib chiqarishlar tarixini ko\'rsatishi mumkin. Maydon xodim aybi bilan bog\'liq sabablarga ko\'ra yozib chiqarish hujjatlari uchun majburiy hisoblanadi.'
  },
  {
    order: 70,
    ruDescription: 'Кнопка проведения списания завершает оформление документа и списывает товары со склада организации. Это финальное действие, после которого товары перестают числиться в учёте и их стоимость относится на затраты. При проведении система проверяет заполнение всех обязательных полей и наличие товаров на складе. Сумма списания отражается в затратах организации и влияет на финансовый результат периода.',
    uzDescription: 'Yozib chiqarishni o\'tkazish tugmasi hujjatni rasmiylashtirishni tugatadi va tovarlarni tashkilot omboridan yozib chiqaradi. Bu tovarlar hisobda ko\'rsatilmaydigan va ularning qiymati xarajatlarga o\'tkaziladigan yakuniy harakat. O\'tkazishda tizim barcha majburiy maydonlarning to\'ldirilishini va omborda tovarlar mavjudligini tekshiradi. Yozib chiqarish summasi tashkilot xarajatlarida aks etadi va davrning moliyaviy natijasiga ta\'sir qiladi.',
    ruFunctionality: 'При нажатии система проверяет корректность документа и показывает итоговую сумму списания для подтверждения. После подтверждения товары списываются с остатков, формируются бухгалтерские проводки и документ переходит в статус "Проведён». История списаний сохраняется для аудита и доступна в аналитических отчётах.',
    uzFunctionality: 'Bosilganda tizim hujjat to\'g\'riligini tekshiradi va tasdiqlash uchun yozib chiqarishning yakuniy summasini ko\'rsatadi. Tasdiqlangandan so\'ng tovarlar qoldiqlardan yozib chiqariladi, buxgalteriya o\'tkazmalari shakllantiriladi va hujjat "O\'tkazilgan" holatiga o\'tadi. Yozib chiqarishlar tarixi auditoriya uchun saqlanadi va tahliliy hisobotlarda mavjud.'
  },

  // === СКЛАД: ГРУППИРОВКА (71-73) ===
  {
    order: 71,
    ruDescription: 'Раздел "Группировка" предназначен для создания и управления группами товаров в системе. Это позволяет структурировать большой ассортимент для удобства работы, отчётности и анализа. Группы товаров образуют иерархическую структуру, отражающую логику организации бизнеса: по категориям, брендам, поставщикам или другим критериям. Использование групп упрощает поиск товаров, формирование отчётов и применение массовых операций к категории товаров.',
    uzDescription: '"Guruhlash" bo\'limi tizimda tovar guruhlarini yaratish va boshqarish uchun mo\'ljallangan. Bu ishlash, hisobotlarni shakllantirish va tahlilni qulaylashtirish uchun katta assortimentni tuzilishini ta\'minlaydi. Tovar guruhlari biznes tashkil etish mantiqini aks ettiruvchi ierarxik tuzilmani hosil qiladi: kategoriyalar, brendlar, yetkazib beruvchilar yoki boshqa mezonlar bo\'yicha. Guruhlardan foydalanish tovarlarni qidirish, hisobotlarni shakllantirish va tovarlar toifasiga ommaviy operatsiyalarni qo\'llashni soddalashtiradi.',
    ruFunctionality: 'Функция открывает древовидную структуру групп товаров с возможностью сворачивания и разворачивания уровней. Пользователь может создавать новые группы, редактировать существующие, перемещать товары между группами. Система поддерживает перетаскивание товаров и групп для удобной реорганизации структуры классификатора.',
    uzFunctionality: 'Funksiya daraxtsimon tuzilmani yig\'ish va yoyish imkoniyati bilan tovar guruhlarini ochadi. Foydalanuvchi yangi guruhlarni yaratishi, mavjudlarni tahrirlashi, tovarlarni guruhlar o\'rtasida ko\'chirishi mumkin. Tizim klassifikator tuzilishini qulay qayta tashkil qilish uchun tovarlar va guruhlarni sudirib o\'tkazishni qo\'llab-quvvatlaydi.'
  },
  {
    order: 72,
    ruDescription: 'Кнопка создания группы открывает форму для добавления новой группы товаров в классификатор. Это первый шаг при структурировании ассортимента по новому признаку или расширении существующей иерархии. В форме нужно указать название группы и её родительскую группу, если создаётся подгруппа в существующей структуре. После создания группы в неё можно добавлять товары из справочника для организации удобной навигации.',
    uzDescription: 'Guruh yaratish tugmasi klassifikatorga yangi tovar guruhi qo\'shish uchun formani ochadi. Bu assortimentni yangi belgi bo\'yicha tuzish yoki mavjud ierarxiyani kengaytirishda birinchi qadam. Formada guruh nomini va, agar mavjud tuzilmada ost-guruh yaratilayotgan bo\'lsa, uning ota guruhini ko\'rsatish kerak. Guruh yaratilgandan so\'ng unga qulay navigatsiyani tashkil etish uchun ma\'lumotnomadan tovarlar qo\'shish mumkin.',
    ruFunctionality: 'Форма создания группы содержит поля для наименования, родительской группы, описания и настроек видимости. Пользователь может сразу добавить изображение для группы, которое будет отображаться в каталоге. Система проверяет уникальность имени группы на одном уровне иерархии и не допускает дублирование.',
    uzFunctionality: 'Guruh yaratish formasi nom, ota guruh, tavsif va ko\'rinuvchanlik sozlamalari uchun maydonlarni o\'z ichiga oladi. Foydalanuvchi katalogda ko\'rsatiladigan guruh uchun tasvirni darhol qo\'shishi mumkin. Tizim ierarxiyaning bir darajasida guruh nomining noyobligini tekshiradi va takrorlanishga yo\'l qo\'ymaydi.'
  },
  {
    order: 73,
    ruDescription: 'Кнопка добавления товаров в группу открывает форму для включения товаров в выбранную группу классификатора. Это позволяет пополнять группу новыми позициями и поддерживать актуальную структуру ассортимента. Товары можно добавлять по одному или выбрать сразу несколько из справочника с помощью чекбоксов. Также доступен поиск по названию и фильтрация по категории для быстрого отбора нужных товаров.',
    uzDescription: 'Guruhga tovar qo\'shish tugmasi klassifikatorning tanlangan guruhiga tovarlarni kiritish uchun formani ochadi. Bu guruhni yangi pozitsiyalar bilan to\'ldirish va assortimentning dolzarb tuzilishini qo\'llab-quvvatlash imkonini beradi. Tovarlarni bittadan yoki checkboxlar yordamida ma\'lumotnomadan bir vaqtning o\'zida bir nechtasini tanlab qo\'shish mumkin. Shuningdek kerakli tovarlarni tez tanlash uchun nom bo\'yicha qidiruv va kategoriya bo\'yicha filtrlash ham mavjud.',
    ruFunctionality: 'Форма выбора товаров содержит справочник с фильтрами и возможностью множественного выбора. Пользователь может использовать поиск по названию, артикулу или штрих-коду для быстрого нахождения нужных позиций. После выбора товаров система показывает их количество и предлагает подтвердить добавление в группу.',
    uzFunctionality: 'Tovarlarni tanlash formasi filtrlar va ko\'p tanlov imkoniyati bilan ma\'lumotnomani o\'z ichiga oladi. Foydalanuvchi kerakli pozitsiyalarni tez topish uchun nom, artikul yoki shtrix-kod bo\'yicha qidiruvdan foydalanishi mumkin. Tovarlar tanlangandan so\'ng tizim ularning sonini ko\'rsatadi va guruhga qo\'shishni tasdiqlashni taklif qiladi.'
  },

  // === СКЛАД: ВЕСОВЫЕ ТОВАРЫ (74-76) ===
  {
    order: 74,
    ruDescription: 'Раздел "Весовые товары" предназначен для управления товарами, которые продаются на вес и требуют особого учёта. Это специфическая категория товаров, включающая продукты питания: мясные изделия, сыры, кондитерские изделия, фрукты и овощи. Такие товары требуют точного взвешивания при каждой операции и учёта веса тары. Система поддерживает работу с весовыми товарами: расчёт цены за единицу веса, учёт веса тары, интеграция с электронными весами.',
    uzDescription: '"Og\'irlikli tovarlar" bo\'limi og\'irlik bo\'yicha sotiladigan va o\'ziga xos hisobni talab qiluvchi tovarlarni boshqarish uchun mo\'ljallangan. Bu go\'sht mahsulotlari, pishloqlar, konditer mahsulotlari, meva va sabzavotlarni o\'z ichiga oluvchi oziq-ovqat mahsulotlari bo\'lgan tovarlarning o\'ziga xos toifasi. Bunday tovarlar har bir operatsiyada aniq tortishni va tara og\'irligini hisobga olishni talab qiladi. Tizim og\'irlikli tovarlar bilan ishlashni qo\'llab-quvvatlaydi: og\'irlik birligi uchun narxni hisoblash, tara og\'irligini hisobga olish, elektron tarozilar bilan integratsiya.',
    ruFunctionality: 'Функция открывает список весовых товаров с указанием единицы измерения, цены за вес и настроек тары. Пользователь может настраивать параметры весовых товаров: точность взвешивания, единицы измерения, вес тары. Система поддерживает интеграцию с электронными весами для автоматического получения веса при продаже.',
    uzFunctionality: 'Funksiya o\'lchov birligi, og\'irlik uchun narx va tara sozlamalarini ko\'rsatgan holda og\'irlikli tovarlar ro\'yxatini ochadi. Foydalanuvchi og\'irlikli tovarlar parametrlarini sozlashi mumkin: tortish aniqligi, o\'lchov birliklari, tara og\'irligi. Tizim sotishda og\'irlikni avtomatik olish uchun elektron tarozilar bilan integratsiyani qo\'llab-quvvatlaydi.'
  },
  {
    order: 75,
    ruDescription: 'Настройка весового товара позволяет задать специфические параметры для товаров, продаваемых на вес. Это включает единицы измерения, точность взвешивания, вес тары и правила округления цены. Правильная настройка обеспечивает корректный расчёт стоимости при продаже и исключает ошибки при взвешивании. Система поддерживает различные единицы измерения: килограммы, граммы, фунты в зависимости от региона использования.',
    uzDescription: 'Og\'irlikli tovarni sozlash og\'irlik bo\'yicha sotiladigan tovarlar uchun o\'ziga xos parametrlarni belgilash imkonini beradi. Bu o\'lchov birliklari, tortish aniqligi, tara og\'irligi va narxni yaxlitlash qoidalarini o\'z ichiga oladi. To\'g\'ri sozlash sotishda qiymatni to\'g\'ri hisoblashni ta\'minlaydi va tortishda xatolarni istisno qiladi. Tizim foydalanish mintaqasiga qarab turli o\'lchov birliklarini qo\'llab-quvvatlaydi: kilogrammlar, grammalar, funtlar.',
    ruFunctionality: 'Форма настройки содержит поля для выбора единицы измерения, точности взвешивания и диапазона допустимых значений веса. Пользователь может указать минимальный и максимальный вес для товара, что помогает выявлять ошибки при взвешивании. Система сохраняет настройки и применяет их при всех операциях с данным товаром.',
    uzFunctionality: 'Sozlash formasi o\'lchov birligini, tortish aniqligini va og\'irlikning ruxsat etilgan qiymatlar diapazonini tanlash uchun maydonlarni o\'z ichiga oladi. Foydalanuvchi tovar uchun minimal va maksimal og\'irlikni ko\'rsatishi mumkin, bu tortishda xatolarni aniqlashga yordam beradi. Tizim sozlamalarni saqlaydi va ushbu tovar bilan barcha operatsiyalarda ularni qo\'llaydi.'
  },
  {
    order: 76,
    ruDescription: 'Поле тары весового товара позволяет указать вес упаковки или тары для вычета при взвешивании. Это необходимо для точного определения веса чистого товара без учёта упаковки. Вес тары автоматически вычитается из общего веса при расчёте стоимости, что обеспечивает честную цену для покупателя. Система поддерживает различные типы тары с фиксированным весом и позволяет настраивать вес тары для каждого товара индивидуально.',
    uzDescription: 'Og\'irlikli tovar tarasi maydoni tortishda ayirish uchun qadoq yoki tara og\'irligini ko\'rsatish imkonini beradi. Bu qadoqlashni hisobga olmaganda toza tovar og\'irligini aniq aniqlash uchun zarur. Tara og\'irligi qiymatni hisoblashda umumiy og\'irlikdan avtomatik ayiriladi, bu xaridor uchun adolatli narzni ta\'minlaydi. Tizim belgilangan og\'irlik bilan turli tara turlarini qo\'llab-quvvatlaydi va har bir tovar uchun tara og\'irligini individual sozlash imkonini beradi.',
    ruFunctionality: 'Поле принимает числовое значение веса тары в выбранных единицах измерения. При продаже весового товара система автоматически вычитает вес тары из показаний весов. Пользователь может выбрать тип тары из предустановленного списка или указать произвольное значение веса упаковки.',
    uzFunctionality: 'Maydon tanlangan o\'lchov birliklarida tara og\'irligining son qiymatini qabul qiladi. Og\'irlikli tovar sotilganda tizim tarozilar ko\'rsatkichlaridan tara og\'irligini avtomatik ayiradi. Foydalanuvchi oldindan o\'rnatilgan ro\'yxatdan tara turini tanlashi yoki qadoqlash og\'irligining ixtiyoriy qiymatini ko\'rsatishi mumkin.'
  },

  // === СКЛАД: ИМПОРТ (77-80) ===
  {
    order: 77,
    ruDescription: 'Раздел "Импорт товаров" предназначен для массовой загрузки товаров в систему из внешних файлов. Это необходимая функция при первоначальном заполнении базы данных или регулярном обновлении прайс-листов от поставщиков. Раздел поддерживает загрузку файлов в форматах Excel и CSV с возможностью настройки соответствия полей. Правильное использование импорта экономит время при вводе большого количества товаров и минимизирует ошибки ручного ввода.',
    uzDescription: '"Tovarlarni import qilish" bo\'limi tashqi fayllardan tizimga tovarlarni ommaviy yuklash uchun mo\'ljallangan. Bu ma\'lumotlar bazasini dastlabki to\'ldirishda yoki yetkazib beruvchilardan muntazam narx-listlarni yangilashda zarur funksiya. Bo\'lim maydonlar mosligini sozlash imkoniyati bilan Excel va CSV formatlaridagi fayllarni yuklashni qo\'llab-quvvatlaydi. Importdan to\'g\'ri foydalanish katta miqdordagi tovarlarni kiritishda vaqtni tejaydi va qo\'lda kiritish xatolarini minimallashtiradi.',
    ruFunctionality: 'Функция открывает мастер импорта с пошаговым процессом загрузки товаров из файла. Пользователь может загрузить файл, настроить соответствие полей файла полям системы и запустить процесс импорта. Система проверяет данные на ошибки, показывает превью результатов и позволяет исправить проблемы перед загрузкой.',
    uzFunctionality: 'Funksiya fayldan tovarlarni yuklashning bosqichma-bosqich jarayoni bilan import ustasini ochadi. Foydalanuvchi faylni yuklashi, fayl maydonlarini tizim maydonlariga mosligini sozlash va import jarayonini boshlashi mumkin. Tizim ma\'lumotlarni xatolarga tekshiradi, natijalarning oldindan ko\'rishini ko\'rsatadi va yuklashdan oldin muammolarni tuzatish imkonini beradi.'
  },
  {
    order: 78,
    ruDescription: 'Кнопка загрузки файла импорта открывает диалог для выбора файла с данными товаров на компьютере пользователя. Это первый шаг процесса импорта, определяющий источник данных для загрузки. Система поддерживает файлы в форматах Excel (.xlsx, .xls) и CSV с различными разделителями. После выбора файла система автоматически анализирует его структуру и предлагает варианты соответствия полей.',
    uzDescription: 'Import faylini yuklash tugmasi foydalanuvchi kompyuterida tovar ma\'lumotlari bo\'lgan faylni tanlash uchun dialogni ochadi. Bu yuklash uchun ma\'lumotlar manbasini belgilovchi import jarayonining birinchi qadami. Tizim turli ajratuvchilar bilan Excel (.xlsx, .xls) va CSV formatlaridagi fayllarni qo\'llab-quvvatlaydi. Fayl tanlangandan so\'ng tizim uning tuzilishini avtomatik tahlil qiladi va maydonlar mosligi variantlarini taklif qiladi.',
    ruFunctionality: 'При нажатии открывается стандартный диалог выбора файла с фильтрацией по поддерживаемым форматам. Система проверяет размер файла, его структуру и наличие данных. Если файл содержит ошибки формата, система показывает подробное сообщение о проблеме и предлагает варианты исправления.',
    uzFunctionality: 'Bosilganda qo\'llab-quvvatlanadigan formatlar bo\'yicha filtrlash bilan standart fayl tanlash dialogi ochiladi. Tizim fayl hajmini, uning tuzilishini va ma\'lumotlar mavjudligini tekshiradi. Agar fayl format xatolarini o\'z ichiga olsa, tizim muammo haqida batafsil xabarni ko\'rsatadi va tuzatish variantlarini taklif qiladi.'
  },
  {
    order: 79,
    ruDescription: 'Функция сопоставления полей позволяет настроить связь между колонками загружаемого файла и полями в системе. Это ключевой этап импорта, определяющий куда попадут данные из каждой колонки файла. Система автоматически предлагает варианты сопоставления на основе названий колонок и поддерживает ручную корректировку. Правильное сопоставление полей обеспечивает корректную загрузку всех данных без потерь и искажений.',
    uzDescription: 'Maydonlarni moslashtirish funksiyasi yuklanayotgan fayl ustunlari va tizimdagi maydonlar o\'rtasida bog\'lanishni sozlash imkonini beradi. Bu har bir ustundan ma\'lumotlar qayerga tushishini belgilovchi importning asosiy bosqichi. Tizim ustun nomlari asosida moslashtirish variantlarini avtomatik taklif qiladi va qo\'lla tuzatishni qo\'llab-quvvatlaydi. Maydonlarning to\'g\'ri moslashtirilishi barcha ma\'lumotlarni yo\'qotish va buzilishlarsiz to\'g\'ri yuklashni ta\'minlaydi.',
    ruFunctionality: 'Интерфейс сопоставления показывает список колонок файла и соответствующие поля системы в виде таблицы. Пользователь может выбрать поле для каждой колонки из выпадающего списка или оставить колонку без сопоставления. Система подсвечивает обязательные поля, которые должны быть заполнены для успешного импорта.',
    uzFunctionality: 'Moslashtirish interfeysi fayl ustunlari ro\'yxatini va mos keluvchi tizim maydonlarini jadval shaklida ko\'rsatadi. Foydalanuvchi har bir ustun uchun maydonni pastga tushuvchi ro\'yxatdan tanlashi yoki ustunni moslashtirmasdan qoldirishi mumkin. Tizim muvaffaqiyatli import uchun to\'ldirilishi kerak bo\'lgan majburiy maydonlarni ajratib ko\'rsatadi.'
  },
  {
    order: 80,
    ruDescription: 'Кнопка запуска импорта начинает процесс загрузки товаров из файла в базу данных системы. Это финальный этап импорта, после которого данные из файла становятся частью справочника товаров. Перед запуском система показывает превью первых записей и количество товаров для загрузки. В процессе импорта система отслеживает ошибки и по завершении показывает детальный отчёт о результатах: успешно загруженные записи и ошибки.',
    uzDescription: 'Importni boshlash tugmasi fayldan tizim ma\'lumotlar bazasiga tovarlarni yuklash jarayonini boshlaydi. Bu fayldan ma\'lumotlar tovarlar ma\'lumotnomasining bir qismiga aylanadigan importning yakuniy bosqichi. Boshlashdan oldin tizim birinchi yozuvlarning oldindan ko\'rishini va yuklash uchun tovarlar sonini ko\'rsatadi. Import jarayonida tizim xatolarni kuzatib boradi va tugagandan so\'ng natijalar haqida batafsil hisobotni ko\'rsatadi: muvaffaqiyatli yuklangan yozuvlar va xatolar.',
    ruFunctionality: 'При нажатии система начинает обработку файла с отображением прогресс-бара и количества обработанных записей. Пользователь может выбрать режим импорта: только новые товары, обновление существующих или полная замена. По завершении система формирует протокол импорта с детальной информацией о результатах и возможных ошибках.',
    uzFunctionality: 'Bosilganda tizim progress-bar va ishlov berilgan yozuvlar soni ko\'rsatilgan holda faylni qayta ishlashni boshlaydi. Foydalanuvchi import rejimini tanlashi mumkin: faqat yangi tovarlar, mavjudlarni yangilash yoki to\'liq almashtirish. Tugagandan so\'ng tizim natijalar va mumkin bo\'lgan xatolar haqida batafsil ma\'lumot bilan import protokolini shakllantiradi.'
  }
];

async function main() {
  console.log('Updating lessons 41-80 with detailed descriptions and functionality...');

  for (const lesson of detailedLessons) {
    await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
        ruFunctionality: lesson.ruFunctionality,
        uzFunctionality: lesson.uzFunctionality,
      },
    });
    console.log(`Updated lesson ${lesson.order}`);
  }

  console.log('Done! Updated 40 lessons (41-80).');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
