// Update all lessons with detailed descriptions (3+ paragraphs)
// Run: npx ts-node scripts/update-lessons-detailed.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const detailedLessons = [
  // === ГЛАВНАЯ (1-5) ===
  { order: 1, ruDescription: 'Главная страница системы Lume Admin является центральной точкой доступа ко всем функциям и возможностям программы. Здесь пользователь видит актуальную информацию о состоянии бизнеса, включая статистику продаж, остатки на складах и важные уведомления. Интерфейс главной страницы интуитивно понятен и позволяет быстро ориентироваться в системе.\n\nДашборд главной страницы содержит виджеты с ключевыми показателями эффективности: выручка за день, количество продаж, средний чек и другие метрики. Эти данные обновляются в реальном времени, что позволяет оперативно реагировать на изменения в работе.\n\nС главной страницы также доступен быстрый переход к часто используемым функциям: создание чека, добавление товара, просмотр отчётов. Это значительно ускоряет работу и повышает эффективность сотрудников.', uzDescription: 'Lume Admin tizimining bosh sahifasi dasturning barcha funksiyalari va imkoniyatlariga markaziy kirish nuqtasidir. Bu yerda foydalanuvchi biznes holati haqida dolzarb ma\'lumotlarni ko\'radi, shu jumladan sotuv statistikasi, omborlardagi qoldiqlar va muhim bildirishnomalar. Bosh sahifa interfeysi intuitiv tushunarli bo\'lib, tizimda tez yo\'nalinga imkon beradi.\n\nBosh sahifa dashbordi samaradorlikning asosiy ko\'rsatkichlari bilan vidjetlarni o\'z ichiga oladi: kunlik tushum, sotuvlar soni, o\'rtacha chek va boshqa ko\'rsatkichlar. Bu ma\'lumotlar real vaqtda yangilanib, ish jarayonidagi o\'zgarishlarga o\'z vaqtida munosabat bildirishga imkon beradi.\n\nBosh sahifadan shuningdek tez-tez ishlatiladigan funksiyalarga tez o\'tish mumkin: chek yaratish, tovar qo\'shish, hisobotlarni ko\'rish. Bu ishni sezilarli darajada tezlashtiradi va xodimlarning samaradorligini oshiradi.' },

  { order: 2, ruDescription: 'Баланс счёта отображается в верхней части интерфейса и показывает текущее состояние расчётного счёта организации. Это ключевой показатель, который позволяет оперативно контролировать финансовое состояние компании и планировать расходы.\n\nПри клике на баланс открывается детальная информация о движении средств: входящие и исходящие платежи, даты операций и контрагенты. Это позволяет быстро найти нужную операцию и проверить её корректность.\n\nБаланс обновляется автоматически при проведении финансовых операций: оплата от покупателя увеличивает баланс, а оплата поставщику — уменьшает. Система также учитывает курсовые разницы при работе с валютными счетами.', uzDescription: 'Hisob balansi interfeysning yuqori qismida ko\'rsatiladi va tashkilotning hisob-raqamining joriy holatini aks ettiradi. Bu kompaniyaning moliyaviy holatini operativ nazorat qilish va xarajatlarni rejalashtirishga imkon beruvchi asosiy ko\'rsatkichdir.\n\nBalans bosilganda mablag\'lar harakati haqida batafsil ma\'lumot ochiladi: kiruvchi va chiquvchi to\'lovlar, operatsiyalar sanalari va kontragentlar. Bu kerakli operatsiyani tez topish va uning to\'g\'riligini tekshirish imkonini beradi.\n\nBalans moliyaviy operatsiyalar o\'tkazilganda avtomatik yangilanadi: xaridordan to\'lov balansni oshiradi, yetkazib beruvchiga to\'lov esa kamaytiradi. Tizim shuningdek valyutaviy hisoblar bilan ishlashda valyuta farqlarini hisobga oladi.' },

  { order: 3, ruDescription: 'Кнопка пополнения баланса находится в верхней панели и предоставляет быстрый доступ к функционалу пополнения расчётного счёта. Это важная функция для поддержания достаточного уровня средств на счету для бесперебойной работы бизнеса.\n\nПри нажатии открывается форма выбора способа пополнения: банковский перевод, платёжная карта или электронный кошелёк. Система поддерживает интеграцию с большинством популярных платёжных систем и банков.\n\nПосле выбора способа система формирует платёжное поручение или переводит на страницу платёжного шлюза. Все операции пополнения сохраняются в истории с указанием даты, времени и способа оплаты.', uzDescription: 'Balansni to\'ldirish tugmasi yuqori panelda joylashgan bo\'lib, hisob-raqamni to\'ldirish funktsiyasiga tez kirishni ta\'minlaydi. Bu biznesning uzluksiz ishlashi uchun hisobda yetarli mablag\' darajasini saqlab qolish uchun muhim funksiya.\n\nBosilganda to\'ldirish usulini tanlash formasi ochiladi: bank o\'tkazmasi, to\'lov kartasi yoki elektron hamyon. Tizim ko\'pchilik mashhur to\'lov tizimlari va banklar bilan integratsiyani qo\'llab-quvvatlaydi.\n\nUsul tanlangandan so\'ng tizim to\'lov topshiriqlarini shakllantiradi yoki to\'lov shlyuzi sahifasiga o\'tkazadi. Barcha to\'ldirish operatsiyalari sana, vaqt va to\'lov usuli ko\'rsatilgan holda tarixda saqlanadi.' },

  { order: 4, ruDescription: 'Профиль пользователя содержит персональные данные сотрудника и настройки его работы в системе. Это центральное место для управления личной информацией, паролем и предпочтениями интерфейса.\n\nВ профиле можно изменить пароль, настроить уведомления, выбрать язык интерфейса и тему оформления. Каждый пользователь может адаптировать систему под свои потребности и привычный стиль работы.\n\nДля администраторов профиль также показывает информацию о правах доступа и роли пользователя. Это помогает контролировать безопасность системы и при необходимости корректировать уровень доступа сотрудника.', uzDescription: 'Foydalanuvchi profili xodimning shaxsiy ma\'lumotlarini va tizimdagi ish sozlamalarini o\'z ichiga oladi. Bu shaxsiy ma\'lumotlar, parol va interfeys afzalliklarini boshqarish uchun markaziy joy hisoblanadi.\n\nProfil ichida parolni o\'zgartirish, bildirishnomalarni sozlash, interfeys tilini va mavzuni tanlash mumkin. Har bir foydalanuvchi tizimni o\'z ehtiyojlariga va o\'rganish uslubiga moslashtirishi mumkin.\n\nAdministratorlar uchun profil shuningdek foydalanuvchi huquqlari va roli haqida ma\'lumotni ko\'rsatadi. Bu tizim xavfsizligini nazorat qilishga va zarurat bo\'lganda xodimning kirish darajasini tuzatishga yordam beradi.' },

  { order: 5, ruDescription: 'Кнопка выхода из системы обеспечивает безопасное завершение работы с программой. Это важный элемент безопасности, который предотвращает несанкционированный доступ к системе в отсутствие пользователя.\n\nПри нажатии на кнопку система запрашивает подтверждение выхода, чтобы исключить случайное действие. После подтверждения сессия завершается, и все несохранённые данные могут быть потеряны.\n\nРекомендуется всегда использовать кнопку выхода при завершении работы, особенно на общих или публичных компьютерах. Это гарантирует сохранность коммерческой информации и персональных данных.', uzDescription: 'Tizimdan chiqish tugmasi dastur bilan ishlashni xavfsiz tugatishni ta\'minlaydi. Bu foydalanuvchi yo\'qligida tizimga ruxsatsiz kirishning oldini oluvchi muhim xavfsizlik elementidir.\n\nTugma bosilganda tizim chiqishni tasdiqlashni so\'raydi, bu tasodifiy harakatni istisno qiladi. Tasdiqlangandan so\'ng sessiya tugatiladi va barcha saqlanmagan ma\'lumotlar yo\'qolishi mumkin.\n\nIsh tugatilganda, ayniqsa umumiy yoki ommaviy kompyuterlarda chiqish tugmasidan foydalanish tavsiya etiladi. Bu tijorat ma\'lumotlari va shaxsiy ma\'lumotlarning xavfsizligini kafolatlaydi.' },

  // === СКЛАД: ТОВАРЫ (6-20) ===
  { order: 6, ruDescription: 'Раздел "Товары" является основой складского учёта и содержит полный список всех товаров организации. Здесь хранится информация о наименованиях, ценах, остатках, единицах измерения и других характеристиках продукции.\n\nИнтерфейс раздела включает таблицу с возможностью сортировки и фильтрации по различным параметрам: категория, бренд, склад, наличие. Поиск работает по названию, артикулу и штрих-коду, что позволяет мгновенно находить нужную позицию.\n\nВ этом разделе можно выполнять все основные операции с товарами: добавление новых позиций, редактирование существующих, удаление неактуальных товаров. Также доступны функции массового редактирования и экспорта данных.', uzDescription: '"Tovarlar" bo\'limi ombor hisobining asosi hisoblanadi va tashkilotning barcha tovarlari ro\'yxatini o\'z ichiga oladi. Bu yerda nomlar, narxlar, qoldiqlar, o\'lchov birliklari va mahsulotning boshqa xususiyatlari haqida ma\'lumotlar saqlanadi.\n\nBo\'lim interfeysi turli parametrlar bo\'yicha saralash va filtrlash imkoniyati bilan jadvalni o\'z ichiga oladi: kategoriya, brend, ombor, mavjudlik. Qidiruv nom, artikul va shtrix-kod bo\'yicha ishlaydi, bu kerakli pozitsiyani bir zumda topishga imkon beradi.\n\nBu bo\'limda tovarlar bilan barcha asosiy operatsiyalarni bajarish mumkin: yangi pozitsiyalar qo\'shish, mavjudlarni tahrirlash, dolzarb bo\'lmagan tovarlarni o\'chirish. Shuningdek ommaviy tahrirlash va ma\'lumotlarni eksport qilish funksiyalari mavjud.' },

  { order: 7, ruDescription: 'Кнопка добавления товара открывает форму создания новой позиции в справочнике товаров. Это первый шаг при появлении нового товара в ассортименте организации.\n\nФорма содержит все необходимые поля: наименование на разных языках, артикул, штрих-код, категорию, единицу измерения, цены закупки и продажи. Обязательные поля отмечены специальным образом, и система не позволит сохранить товар без их заполнения.\n\nПосле заполнения формы и сохранения товар появляется в общем списке и становится доступен для всех складских операций: прихода, реализации, инвентаризации. Можно также загрузить изображение товара для удобства идентификации.', uzDescription: 'Tovar qo\'shish tugmasi tovarlar ma\'lumotnomasida yangi pozitsiya yaratish formasini ochadi. Bu tashkilot assortimentida yangi tovar paydo bo\'lganda birinchi qadam hisoblanadi.\n\nForma barcha kerakli maydonlarni o\'z ichiga oladi: turli tillarda nom, artikul, shtrix-kod, kategoriya, o\'lchov birligi, xarid va sotuv narxlari. Majburiy maydonlar maxsus belgi bilan belgilanadi va tizim ularsiz tovarni saqlashga yo\'l qo\'ymaydi.\n\nForma to\'ldirilib saqlangandan so\'ng, tovar umumiy ro\'yxatda paydo bo\'ladi va barcha ombor operatsiyalari uchun mavjud bo\'ladi: kirim, realizatsiya, inventarizatsiya. Tovarni identifikatsiya qilish qulayligi uchun uning tasvirini yuklash ham mumkin.' },

  { order: 8, ruDescription: 'Поле поиска товаров позволяет быстро найти нужную позицию в базе данных без необходимости пролистывать весь список. Это значительно ускоряет работу, особенно при большом ассортименте.\n\nПоиск работает в реальном времени: результаты появляются уже при вводе первых символов. Система ищет по названию товара, артикулу, штрих-коду и другим идентификаторам. Результаты сортируются по релевантности.\n\nДля более точного поиска можно использовать специальные операторы: кавычки для точного совпадения фразы, минус для исключения слов. Это помогает найти товар даже при неполном знании его названия.', uzDescription: 'Tovarlarni qidirish maydoni butun ro\'yxatni aylantirish zaruriyatisiz bazadan kerakli pozitsiyani tez topish imkonini beradi. Bu ishni sezilarli darajada tezlashtiradi, ayniqsa katta assortimentda.\n\nQidiruv real vaqtda ishlaydi: natijalar birinchi belgilarni kiritishda paydo bo\'ladi. Tizim tovar nomi, artikul, shtrix-kod va boshqa identifikatorlar bo\'yicha qidiradi. Natijalar dolzarblik bo\'yicha saralanadi.\n\nAniqroq qidirish uchun maxsus operatorlardan foydalanish mumkin: iboraning to\'liq mos kelishi uchun tirnoqlar, so\'zlarni istisno qilish uchun minus. Bu tovar nomini to\'liq bilmasa ham topishga yordam beradi.' },

  { order: 9, ruDescription: 'Фильтр по категории позволяет ограничить список товаров определённой группой, что упрощает работу с ассортиментом. Категории образуют иерархическую структуру, отражающую логику организации товаров.\n\nПри выборе категории система показывает только товары, относящиеся к ней и её подкатегориям. Это особенно полезно при работе с большими справочниками, когда нужно сосредоточиться на конкретной группе продукции.\n\nФильтр можно комбинировать с другими фильтрами и поиском для максимально точного отбора товаров. Также доступен множественный выбор категорий для одновременного просмотра нескольких групп.', uzDescription: 'Kategoriya bo\'yicha filtr tovarlar ro\'yxatini ma\'lum guruh bilan cheklash imkonini beradi, bu assortiment bilan ishlashni soddalashtiradi. Kategoriyalar tovarlarning mantiqiy tuzilishini aks ettiruvchi ierarxik tuzilmani hosil qiladi.\n\nKategoriya tanlanganda tizim faqat unga va uning ost-kategoriyalariga tegishli tovarlarni ko\'rsatadi. Bu katta ma\'lumotnomalar bilan ishlashda, aniq mahsulot guruhi ustida ishlash kerak bo\'lganda ayniqsa foydali.\n\nFiltrni boshqa filtrlar va qidiruv bilan birlashtirish mumkin, tovarlarni maksimal aniq tanlash uchun. Shuningdek bir vaqtning o\'zida bir nechta kategoriyani ko\'rish uchun ko\'p tanlov ham mavjud.' },

  { order: 10, ruDescription: 'Фильтр по складу показывает остатки товаров на конкретном складе или торговой точке. Это необходимо при работе в многозвенной сети для контроля запасов по местоположению.\n\nПри выборе склада система отображает только те товары, которые есть в наличии на этом объекте. Также показывается актуальное количество и статус наличия. Это помогает избежать ситуаций, когда товар заказывается с отсутствующего склада.\n\nФильтр особенно полезен для менеджеров складов, которые контролируют только свой объект. Можно настроить фильтр по умолчанию, чтобы при входе в раздел сразу видеть товары своего склада.', uzDescription: 'Ombor bo\'yicha filtr aniq ombor yoki savdo nuqtasidagi tovar qoldiqlarini ko\'rsatadi. Bu ko\'p bo\'g\'inli tarmoqda joylashuv bo\'yicha zaxiralarni nazorat qilish uchun zarur.\n\nOmbor tanlanganda tizim faqat ushbu ob\'ektda mavjud bo\'lgan tovarlarni ko\'rsatadi. Shuningdek dolzarb miqdor va mavjudlik holati ko\'rsatiladi. Bu tovar mavjud bo\'lmagan ombordan buyurtma qilinish holatlarining oldini oladi.\n\nFiltr ayniqsa faqat o\'z ob\'ektini nazorat qiluvchi ombor menejerlari uchun foydali. Kirish vaqtida o\'z omborining tovarlarini darhol ko\'rish uchun filtrni standart qilib sozlash mumkin.' },

  { order: 11, ruDescription: 'Кнопка редактирования товара открывает форму изменения параметров существующей позиции. Это позволяет актуализировать информацию о товаре при изменении условий работы.\n\nВ форме редактирования доступны все те же поля, что и при создании товара. Можно изменить наименование, цены, категорию, описание и другие характеристики. История изменений сохраняется, что позволяет отследить, кто и когда вносил корректировки.\n\nПри редактировании цен система может предложить обновить цены в связанных документах или пересчитать себестоимость. Это помогает поддерживать актуальность учётных данных.', uzDescription: 'Tovarni tahrirlash tugmasi mavjud pozitsiya parametrlarini o\'zgartirish formasini ochadi. Bu ish sharoitlari o\'zgarganda tovar haqidagi ma\'lumotlarni dolzarblashtirish imkonini beradi.\n\nTahrirlash formasida tovar yaratishdagidek barcha maydonlar mavjud. Nom, narxlar, kategoriya, tavsif va boshqa xususiyatlarni o\'zgartirish mumkin. O\'zgarishlar tarixi saqlanib qoladi, bu kim va qachon tuzatishlar kiritganini kuzatish imkonini beradi.\n\nNarlarni tahrirlashda tizim bog\'liq hujjatlarda narxlarni yangilashni yoki tannarxni qayta hisoblashni taklif qilishi mumkin. Bu hisob ma\'lumotlarining dolzarbligini saqlashga yordam beradi.' },

  { order: 12, ruDescription: 'Кнопка удаления товара удаляет позицию из справочника товаров. Это действие требует подтверждения и имеет ограничения для защиты целостности данных.\n\nУдалить можно только тот товар, по которому нет движений в учёте. Если товар участвовал в приходах, реализациях или других операциях, система предложит пометить его как неактивный вместо удаления. Это позволяет сохранить историю операций.\n\nПеред удалением система показывает предупреждение о невозможности восстановления данных. Рекомендуется использовать эту функцию только для позиций, созданных по ошибке.', uzDescription: 'Tovarni o\'chirish tugmasi pozitsiyani tovarlar ma\'lumotnomasidan o\'chiradi. Bu harakat tasdiqlashni talab qiladi va ma\'lumotlar yaxlitligini himoya qilish uchun cheklovlarga ega.\n\nFaqat hisobda harakati bo\'lmagan tovarni o\'chirish mumkin. Agar tovar kirim, realizatsiya yoki boshqa operatsiyalarda qatnashgan bo\'lsa, tizim o\'chirish o\'rniga uni nofaol deb belgilashni taklif qiladi. Bu operatsiyalar tarixini saqlab qolish imkonini beradi.\n\nO\'chirishdan oldin tizim ma\'lumotlarni qayta tiklab bo\'lmasligi haqida ogohlantirish ko\'rsatadi. Bu funksiyadan faqat xato yaratilgan pozitsiyalar uchun foydalanish tavsiya etiladi.' },

  { order: 13, ruDescription: 'Функция экспорта товаров позволяет выгрузить список товаров в файл для работы во внешних программах или передачи контрагентам. Это востребованная функция для прайс-листов и инвентаризации.\n\nЭкспорт доступен в форматах Excel и CSV. При выгрузке можно выбрать конкретные колонки для экспорта, чтобы получить только нужную информацию. Также можно применить фильтры перед экспортом и выгрузить только отобранные товары.\n\nПолученный файл можно использовать для печати прайс-листа, загрузки на маркетплейсы или анализа в Excel. Это удобный способ обмена данными с внешними системами.', uzDescription: 'Tovarlarni eksport funksiyasi tovarlar ro\'yxatini tashqi dasturlarda ishlash yoki kontragentlarga uzatish uchun faylga yuklash imkonini beradi. Bu narx-listlar va inventarizatsiya uchun talab qilinadigan funksiya.\n\nEksport Excel va CSV formatlarida mavjud. Yuklashda faqat kerakli ma\'lumotni olish uchun eksport qilinadigan aniq ustunlarni tanlash mumkin. Shuningdek eksport oldidan filtrlarni qo\'llash va faqat tanlangan tovarlarni yuklash mumkin.\n\nOlingan faylni narx-listni chop etish, marketpleyslarga yuklash yoki Excel da tahlil qilish uchun ishlatish mumkin. Bu tashqi tizimlar bilan ma\'lumotlar almashinuvining qulay usuli.' },

  { order: 14, ruDescription: 'Карточка товара содержит полную информацию о конкретной позиции: описание, характеристики, цены, остатки по складам и историю движения. Это детальное представление товара в системе.\n\nВ карточке товара можно увидеть текущие остатки на каждом складе, историю изменения цен, последние операции поступления и реализации. Эта информация помогает принимать решения о закупках и ценообразовании.\n\nИз карточки товара также доступны быстрые действия: создать приход, реализацию, напечатать ценник или штрих-код. Это ускоряет работу операторов складского учёта.', uzDescription: 'Tovar kartochkasi aniq pozitsiya haqida to\'liq ma\'lumotni o\'z ichiga oladi: tavsif, xususiyatlar, narxlar, omborlar bo\'yicha qoldiqlar va harakat tarixi. Bu tizimdagi tovarning batafsil ko\'rinishi.\n\nTovar kartochkasida har bir ombordagi joriy qoldiqlarni, narx o\'zgarishlari tarixini, oxirgi kirim va realizatsiya operatsiyalarini ko\'rish mumkin. Bu ma\'lumotlar xaridlar va narx belgilash bo\'yicha qarorlar qabul qilishga yordam beradi.\n\nTovar kartochkasidan shuningdek tezkor harakatlar mavjud: kirim, realizatsiya yaratish, narx yorlig\'i yoki shtrix-kod chop etish. Bu ombor hisobi operatorlarining ishini tezlashtiradi.' },

  { order: 15, ruDescription: 'Функция добавления в избранное позволяет сохранить товар в персональном списке для быстрого доступа. Это удобно для товаров, которые часто используются в работе.\n\nИзбранные товары отображаются в отдельном разделе и на видном месте интерфейса. При создании чека или документа можно быстро добавить товар из избранного, не прибегая к поиску.\n\nСписок избранного индивидуален для каждого пользователя, что позволяет каждому сотруднику настроить быстрый доступ под свои потребности. Товар можно добавить или убрать из избранного одним кликом.', uzDescription: 'Sevimlilarga qo\'shish funksiyasi tovarni tez kirish uchun shaxsiy ro\'yxatda saqlash imkonini beradi. Bu ishda tez-tez ishlatiladigan tovarlar uchun qulay.\n\nSevimli tovarlar alohida bo\'limda va interfeysning ko\'zga tashlanadigan joyida ko\'rsatiladi. Chek yoki hujjat yaratishda qidirishga murojaat qilmasdan sevimlilardan tovarni tez qo\'shish mumkin.\n\nSevimlilar ro\'yxati har bir foydalanuvchi uchun individual bo\'lib, har bir xodimga o\'z ehtiyojlariga ko\'ra tez kirishni sozlash imkonini beradi. Tovarni bir marta bosish bilan sevimlilarga qo\'shish yoki olib tashlash mumkin.' },

  { order: 16, ruDescription: 'Массовое редактирование позволяет изменить параметры сразу для нескольких товаров за одну операцию. Это экономит время при необходимости обновить цены, категорию или другие атрибуты для группы товаров.\n\nДля массового редактирования нужно отметить товары с помощью чекбоксов и выбрать действие из меню. Доступные действия: изменение цены, перенос в категорию, изменение единицы измерения, установка статуса.\n\nСистема показывает превью изменений перед применением, чтобы избежать ошибок. После подтверждения все выбранные товары обновляются одновременно, и изменения отражаются в истории.', uzDescription: 'Ommaviy tahrirlash bir operatsiyada bir nechta tovar parametrlarini o\'zgartirish imkonini beradi. Bu tovarlar guruhi uchun narxlarni, kategoriyani yoki boshqa atributlarni yangilash kerak bo\'lganda vaqtni tejaydi.\n\nOmmaviy tahrirlash uchun tovarlarni checkbox lar yordamida belgilash va menyu dan harakatni tanlash kerak. Mavjud harakatlar: narxni o\'zgartirish, kategoriyaga ko\'chirish, o\'lchov birligini o\'zgartirish, holatni o\'rnatish.\n\nTizim xatolardan qochish uchun qo\'llashdan oldin o\'zgarishlarning oldindan ko\'rishini ko\'rsatadi. Tasdiqlangandan so\'ng barcha tanlangan tovarlar bir vaqtning o\'zida yangilanadi va o\'zgarishlar tarixda aks etadi.' },

  { order: 17, ruDescription: 'Функция печати ценника формирует печатную форму ценника для выбранного товара. Это необходимо для оформления торгового зала и соблюдения требований законодательства о защите прав потребителей.\n\nСистема предлагает несколько шаблонов ценников разных размеров и форматов. Можно выбрать шаблон для печати на обычной бумаге или на самоклеящейся этикетке. Доступна настройка шаблона с логотипом организации.\n\nПри печати ценника на него автоматически подставляется актуальная цена товара. Можно также распечатать ценники сразу для нескольких товаров, выбрав их в списке.', uzDescription: 'Narx yorlig\'ini chop etish funksiyasi tanlangan tovar uchun narx yorlig\'ining bosma shaklini yaratadi. Bu savdo zali ni bezash va iste\'molchilar huquqlarini himoya qilish to\'g\'risidagi qonun hujjatlariga rioya qilish uchun zarur.\n\nTizim turli o\'lcham va formatlardagi narx yorliqlarining bir nechta shablonlarini taklif qiladi. Oddiy qog\'ozga yoki o\'z-o\'zidan yopishqoq etiketkaga chop etish uchun shablonni tanlash mumkin. Tashkilot logotipi bilan shablonni sozlash mavjud.\n\nNarx yorlig\'ini chop etishda unga tovarning dolzarb narxi avtomatik qo\'yiladi. Shuningdek ro\'yxatda tanlab bir nechta tovarlar uchun darhol narx yorliqlarini chop etish mumkin.' },

  { order: 18, ruDescription: 'Функция копирования товара создаёт дубликат выбранной позиции со всеми её характеристиками. Это ускоряет добавление похожих товаров, когда новая позиция незначительно отличается от существующей.\n\nПри копировании создаётся новый товар с теми же значениями полей: категория, единица измерения, описание. Нужно только изменить наименование, артикул и скорректировать при необходимости цены.\n\nКопирование особенно полезно при вводе новых модификаций товара: другого цвета, размера или комплектации. Это экономит время на заполнение повторяющихся данных.', uzDescription: 'Tovarni nusxalash funksiyasi tanlangan pozitsiyaning barcha xususiyatlari bilan dublikatini yaratadi. Bu yangi pozitsiya mavjudidan oz farq qilganda o\'xshash tovarlarni qo\'shishni tezlashtiradi.\n\nNusxalashda bir xil maydon qiymatlari bilan yangi tovar yaratiladi: kategoriya, o\'lchov birligi, tavsif. Faqat nomni, artikulni o\'zgartirish va zarurat bo\'lganda narxlarni tuzatish kerak.\n\nNusxalash ayniqsa tovarning yangi modifikatsiyalarini kiritishda foydali: boshqa rang, o\'lcham yoki komplektatsiya. Bu takroriy ma\'lumotlarni to\'ldirish vaqtini tejaydi.' },

  { order: 19, ruDescription: 'История изменений товара показывает все изменения, которые производились с карточкой товара: изменение цен, описания, категории и других параметров. Это важный инструмент контроля и аудита.\n\nВ истории отображается дата и время изменения, пользователь, внёсший изменение, и сами изменённые значения — старое и новое. Это позволяет отследить причины и авторов всех корректировок.\n\nИстория хранится за весь период существования товара и не может быть удалена. Это обеспечивает прозрачность учётных данных и помогает при разборе спорных ситуаций.', uzDescription: 'Tovar o\'zgarishlari tarixi tovar kartochkasi bilan amalga oshirilgan barcha o\'zgarishlarni ko\'rsatadi: narxlar, tavsif, kategoriya va boshqa parametrlarning o\'zgarishi. Bu nazorat va auditoriyaning muhim vositasidir.\n\nTarixda o\'zgarish sanasi va vaqti, o\'zgarish kiritgan foydalanuvchi va o\'zgartirilgan qiymatlar — eski va yangi ko\'rsatiladi. Bu barcha tuzatishlarning sabablari va mualliflarini kuzatish imkonini beradi.\n\nTarix tovar mavjud bo\'lgan butun davrda saqlanadi va o\'chirib bo\'lmaydi. Bu hisob ma\'lumotlarining shaffofligini ta\'minlaydi va bahsli holatlarni hal qilishda yordam beradi.' },

  { order: 20, ruDescription: 'Функция просмотра и печати штрих-кода показывает графическое изображение штрих-кода товара для печати этикеток. Штрих-код используется для идентификации товара при сканировании.\n\nСистема генерирует штрих-код в формате EAN-13 или Code 128 в зависимости от типа кода товара. Изображение можно масштабировать для печати этикеток разного размера.\n\nРаспечатанный штрих-код можно наклеить на товар или упаковку для использования при приёмке, инвентаризации и продаже. Система также поддерживает печать QR-кодов с дополнительной информацией о товаре.', uzDescription: 'Shtrix-kodni ko\'rish va chop etish funksiyasi etiketkalarni chop etish uchun tovar shtrix-kodining grafik tasvirini ko\'rsatadi. Shtrix-kod skanerlashda tovarni identifikatsiya qilish uchun ishlatiladi.\n\nTizim tovar kodi turiga qarab EAN-13 yoki Code 128 formatida shtrix-kod yaratadi. Tasvirni turli o\'lchamdagi etiketkalarni chop etish uchun masshtablashtirish mumkin.\n\nChop etilgan shtrix-kodni qabul qilish, inventarizatsiya va sotishda foydalanish uchun tovar yoki qadoqqa yopishtirish mumkin. Tizim shuningdek tovar haqida qo\'shimcha ma\'lumot bilan QR-kodlarni chop etishni qo\'llab-quvvatlaydi.' },
];

async function main() {
  console.log('Updating lessons with detailed descriptions...');

  for (const lesson of detailedLessons) {
    await prisma.lesson.updateMany({
      where: { order: lesson.order },
      data: {
        ruDescription: lesson.ruDescription,
        uzDescription: lesson.uzDescription,
      },
    });
    console.log(`Updated lesson ${lesson.order}`);
  }

  console.log('Done!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
